### ISSUE TITLE
Capybara.reset_session! doesn't reset HTML5 session storage

### ISSUE THREAD

**Issue by deepj** [teamcapybara/capybara#1001]
I'm testing our heavy AJAX and Java enterprise SaaS application through RSpec, Capybara and Selenium/Poltergeist and it saves some data in HTML5 session storage. Unfortunately, Capybara doesn't reset them during reseting session what affects some my scenarios. I can make "signing out from the application" but it takes some additional time and sometimes it fails. If it fails, so it affects some other scenarios.

It'd be nice when Capybara resets HTML5 session storage too. Thanks

**Comment by eterry1388** [comment]
This needs to be supported.  New web applications prefer local storage over cookies or sessions.  We have an angularJS web app that uses local storage for all session data and is not getting reset when using capybara with rspec.

**Comment by Nakilon** [comment]
:+1: for reseting localStorage

**Comment by nertzy** [comment]
Nowadays, localStorage and sessionStorage are in common use and are supported by all major browsers except Opera Mini.

http://caniuse.com/#feat=namevalue-storage

Would be great to revisit this idea. Even if it were off by default and could be turned on via something like:

```ruby
Capybara.clear_web_storage_when_clearing_session = true
```
