### ISSUE TITLE
Issues with matching values in forms, and hidden fields

### ISSUE THREAD

**Issue by kaspergrubbe** [teamcapybara/capybara#1017]
Hello, I am currently using rspec for testing our application. This is the HTML that we are testing against:

``` html
<form accept-charset="UTF-8" action="/en/newsletters/signup" data-remote="true" method="post">
<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
<div class='actionform'>
<input class="email" id="email" name="email" type="text" value="Your e-mail address" />
<div class='clear'></div>
<input id="mailinglist" name="mailinglist" type="hidden" value="1" />
<input class="btn btn-warning subscribe" name="commit" type="submit" value="Subscribe" />
<div class='clear'></div>
</div>
</form>
```
## Issues with have_field on hidden fields

This works fine:

``` ruby
response.should have_field("email", :type => "text")
```

This doesn't work:

``` ruby
response.should have_field("mailinglist", :type => "text", :visible => false)
```

This also fails:

``` ruby
response.should have_field("mailinglist", :type => "hidden")
```

Why can't I select a hidden field with the `have_field` method?

Instead I have to do it like this:

``` ruby
response.should have_selector("input#mailinglist", :visible => false)
```
## Issues with matching values of a hidden form-field

How can I test the value of a hidden field?

I want to do something like this:

``` ruby
response.should have_selector("input#mailinglist", 
:visible => false, 
:value => @mailinglist.id)
```

But the `:value`-property isn't available in the `have_selector` method. 

**Update**

I figured out that I could use the following syntax for testing values:

``` ruby
response.should have_selector("input#mailinglist[value=\"#{@mailinglist.id}\"]")
```

Is it really correct to use xpath like this?

**Comment by nosretep** [comment]
So on a form that spans multiple pages, carrying values from start to finish by way of hidden fields, the developer cannot sanity check whether a given page has the hidden fields set to an expected value?
