### ISSUE TITLE
Consecutive specs using selenium hangs

### ISSUE THREAD

**Issue by wakiki** [teamcapybara/capybara#1035]
Another strange issue - running consecutive specs using selenium driver hangs (as in the browser window remains open, but it does not load the page). Changing to webkit driver works fine, and running individual specs using selenium works fine. Something is stopping consecutive specs running in selenium - has anyone come across this?

**Comment by jdelStrother** [comment]
FWIW, the chromedriver bug appears to be fixed now - https://code.google.com/p/chromedriver/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&groupby=&sort=&id=502.   Not sure if we want to revert back to just using `about:blank` anytime soon?
