### ISSUE TITLE
Meta tags matchers

### ISSUE THREAD

**Issue by alfius** [teamcapybara/capybara#1059]
I can't find a way to match meta tags on my tests. I'm using Capybara 2.1.0:

``` bash
(rdb:1) p page.source
"<!doctype html>\n<html>\n<head>\n<title>MyTitle</title>\n<meta charset='utf-8'>\n<meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>\n<meta content='width=device-width, initial-scale=1' name='viewport'>\n<meta name='description'>\n\n..."

(rdb:1) p page.find 'meta'
*** Capybara::ElementNotFound Exception: Unable to find css "meta"

(rdb:1) p page.find :xpath, '//html'
#<Capybara::Element tag="html" path="/html">

(rdb:1) p page.find :xpath, '//html/head'
*** Capybara::ElementNotFound Exception: Unable to find xpath "//html/head"
```

Seems like the whole `head` element is ignored by Capybara. Are there any special matchers for meta tags?

**Comment by EddieOne** [comment]
page.find bla bla, it seems to break with capital letters. Trying to find the following is impossible. Anyone able to recreate?

    <meta content="http://sample.net" itemProp="target" />

With something like this

    expect(find('meta[itemProp="target"]', visible: false)).to be_truthy

**Comment by twalpole** [comment]
@EddieOne Works fine using the selenium driver for me, fails using rack_test.  Nokogiri lowercases the attribute name so you'd need to find 'meta[itemprop="target"` .  I'm guessing it might be a bug in Nokogiri, but it would require more research.  Also, the way you're writing your expectations is really awkward and won't provide you iwith decent errors. It should be written as

    expect(page).to have_css('meta[itemProp="target"]', visible: false)

**Comment by EddieOne** [comment]
That would fit my use case. Thanks for the info @twalpole . It's better to use lowercase, so let's leave it.
