### ISSUE TITLE
Find input element by its value doesn't work when the value is changed by JS

### ISSUE THREAD

**Issue by ohcibi** [teamcapybara/capybara#1061]
I have this example: https://github.com/ohcibi/capybara-xpath-example which is called xpath, but I just noticed that it also applies for css selectors.

There is a simple index.html that has an input of type range with value 0

``` html
<input id="input" type="range" value="0" step="1" min="0" max="1" step="1">
```

The value then gets changed by JS

``` javascript
document.getElementById("input").value = 1;
```

I now want to assert that the input field has this value of 1 like this

``` ruby
expect(page).to have_xpath %Q{//input[@value="1"]}
```

But this won't work. If I replace `1` by `0` the element would be found (as if it is found by its initial value).

The reason why I'm doing this is because I want to utilize capybaras behaviour of waiting a certain amount of time before an element is considered as "not found"; to check if the value of the input has changed, which happens async in my application (as the example shows: its not even necessary to be async to trigger this bug).

If I would do a normal find and then assert for the value it'll work but then I would have to wait manually as the element is already on the page but has its old value as long as the async-process is not finished.

By the way I checked that the value of the `input` is actually 1 with pry and when using selenium it is even visible in the spawned firefox session, which stays open a few secs because capybara cant find the input with value 1.

**Update**
The example uses capybara-2.0.3 as there is a bug with capybara-webkit and capybara-2.1.0, but I just verified that this bug also happens when using capybara-2.1.0 with selenium

**Comment by daino3** [comment]
I just want to bring attention to this again. Because of this, I needed to write my own data table parser and execute javascript to ascertain the text field in an updated input. Consequently, each row of the datatable now takes 6 seconds to parse. There might, and probably is a better way to parse this, but this "issue" lends itself to slow, ugly code workarounds. 

```cucumber
 # feature file
  Scenario: As a User, I can change High/Low price 
    Given I am logged in as "Awesome" User
    And I change low price limit for "FUT" to "250"
    Then I should see "Successfully updated FUT"
    And I change high price limit for "FUT" to "450"
    Then I should see "Successfully updated FUT"
    And I should see the following instruments:
     | <Some table to validate against> |
```

```ruby
# step definition
Then(/^I should see the following instruments:$/) do |table|
  rows = find('#instruments-datatable').all('tr').to_a
  header_row = rows.shift
  headers = header_row.all('th').map { |header| header.text.strip }

  actual_table =
    rows.map do |row|
      # gotta do this because value property of inputs
      # doesn't change after page load vs. what is visible on the screen
      # see: https://github.com/jnicklas/capybara/issues/1061
      state_finder = "##{row[:id]} #instrumentState option:selected"
      state = page.evaluate_script("$('#{state_finder}').val()").strip

      high_limit_finder = "##{row[:id]} input.high-price-limit"
      high_limit = page.evaluate_script("$('#{high_limit_finder}').val()").strip

      low_limit_finder = "##{row[:id]} input.low-price-limit"
      low_limit = page.evaluate_script("$('#{low_limit_finder}').val()").strip

      # THIS PART IS EXTREMELY INEFFICIENT; like 6 seconds to map each row
      row_data = []
      row.all('td').each do |col|
        data = col.text.strip
        # must assert against negative presence for performance reasons
        col_data =
          case
          when !col.has_no_css?('#instrumentState') then state
          when data.present? then data
          when !col.has_no_css?('input.high-price-limit') then high_limit
          when !col.has_no_css?('input.low-price-limit') then low_limit
          else data
          end
        row_data << col_data
      end
      row_data
    end

  actual_table.unshift(headers)
  actual_table.pop if actual_table.last.empty?
  table.dup.diff!(actual_table)
end
```

**Comment by twalpole** [comment]
@daino3 if you know the page isn't dynamically changing then pass wait: 0 as an option to all your has_no_css? calls and the method will be almost instantaneous - the default has_no_css? will wait for Capybara.default_max_wait_time seconds to make sure the page isn't being loaded by an ajax call - if you know you don't have to worry about that passing wait: 0 will make it check and continue without a retry

**Comment by daino3** [comment]
Thanks @twalpole! The `wait: 0` option made it got from 6 sec to 0.1! Gonna have to put that in the ol' tool kit. 

 I'm going to guess though, there's no "nice" way of getting around extracting a change in input value without executing some javascript... is that correct?

**Comment by twalpole** [comment]
In the future please ask howto question in the mailing list as requested in the README -  I'm locking this conversation for now  - but to answer your question

element['value'] should give you the value property (as opposed to attribute) in selenium and poltergeist, not sure with capybara-webkit off the top of my head.  If you're just looking to validate the selected value then you should be looking at the `with` option for the field selector or the `selected` option for the select selector

    expect(page).to have_field('id/name/etc of field', with: 'value') # verifies that an input/select/textarea exists with the specified value
    expect(page).to have_select('id/name/etc of select', selected: 'The selected option') # verifies a select exists with the given text being the selected option
