### ISSUE TITLE
find_button seems to cannot detect disabled button

### ISSUE THREAD

**Issue by dot** [teamcapybara/capybara#1095]
`page.should have_selector("input[value='Click']:disabled")`
was pass, but
`page.find_button('Click')[:disabled].should eq 'disabled'`
was 

> Capybara::ElementNotFound: 
> Unable to find button "Click"

occurred at same page, in Capybara 2.1.0.

Is this expected behavior?

**Comment by indiesquidge** [comment]
This worked for me as well. Thank you.
