### ISSUE TITLE
expect(page).to have_content behaves inconsistently with case sensitivity

### ISSUE THREAD

**Issue by thatandyrose** [teamcapybara/capybara#1165]
**this is for non javascript tests**

If you run

```
expect(page).to have_content
```

with a headless browser, the underlying html gets read.

However, if you run the same expectation with say :selenium then the CCS styles text gets read, which may have a different case depending on the CCS style.

So, is there are way to have_content be case insensitive?

**Comment by frnco** [comment]
@jnicklas (And anyone else this may concern), this has bitten me too, and although it was pretty easy to find an answer and fix it, it is a bit hacky to use a RegEx, and it means we can't test for the right text neither on CSS or on the code.

I image this kind of inconsistency would be pretty easy to fix, or at least to define a "standard" and explain which drivers are the exception (Either Selenium and you test code, and have to be hacky when using headless, or you test the CSS-ed version and Selenium is flagged).

I'm also Ok with suggesting using RegEx from the start and documenting it, or whichever other solution is decided on, I just think we shouldn't let any inconsistencies "slide", especially considering pretty much everything is working really smoothly. :D

**Comment by twalpole** [comment]
@frnco Which headless driver are you referring to?

**Comment by momolog** [comment]
I was bitten by that behaviour using capybara-webkit. 

The page in question contains the string "Thanks" in an element that is styled using `text-transform: uppercase`. This results in `expect(page).to have_content 'Thanks'` to fail, which is very unexpected and imho a bug.
The same expectation does pass when not using capybara-webkit.

So is this a capybara-webkit issue?

**Comment by abotalov** [comment]
`text` and similar methods try to return text that is `roughly what a text-only browser would display`.

For example Webdriver specification explicitly says that `text-transform` should be respected. See
https://www.w3.org/TR/webdriver/#getelementtext

**Comment by momolog** [comment]
@abotalov So `has_content?` is **not** meant to check for content of the page body?
Checking for the raw content therefore should be done via `page.find('body').text`?

**Comment by twalpole** [comment]
@momolog This is as designed - Capybara is designed to emulate user behavior and therefore any driver which processes CSS should "see" the text as a user sees it. In your case you are applying a text-transform of uppercase so the user would see "THANKS".  Why would you not want to test for the text as the user sees it, that's the whole point of feature tests?  If you really need case insensitivity use a regex.  The exception to this is the rack-test driver which doesn't process CSS (or JS, ...) so is really only useful for very simple testing nowadays
