### ISSUE TITLE
date_select with capybara

### ISSUE THREAD

**Issue by thiagocifani** [teamcapybara/capybara#117]
Hello people,

I was testing my application with capybara and rspec, but when I try to setup my form with a date field I get a error message! I tried to put select( 'option', :from => 'date_field'), but it didn't work sucessfully!

If anyone here knows how to setup it I would thank you if you help me!

I am a rookie and need some information!

I´ve tried google it, but I didn't find anything!

best regards!

**Comment by obie** [comment]
I know this is an old issue but I just ran into it and cannot find any solution or workaround. For what it's worth, there are situations where `date_helper` is exactly what is needed and superior to JS datepickers... for example, selection of a birthday.

**Comment by twalpole** [comment]
@obie As mentioned above, depending on the actual HTML you have you may need to write your own CSS selectors to find and then set the value of each input. Anyway, tacking on to an issue closed 7 years ago is not the right way to get help
