### ISSUE TITLE
Node#drag_by(right_by, down_by)

### ISSUE THREAD

**Issue by runeb** [teamcapybara/capybara#119]
In Selenium Capybara supports dragging one DOM element onto another with `Node#drag_to(element)`. After calculating positional differences, that method delegates to `Selenium::WebDriver::Element#drag_and_drop_by(right_by, down_by)`

I've implemented `Node#drag_by(right_by, down_by)` for the capybara selenium driver which delegates to `#drag_and_drop_by` directly since there are instances where you don't have a specific DOM element to drop something on, for example moving a draggable marker in Google Maps.

Passing test included at runeb/capybara@ce9eaaa0cf

**Comment by mltsy** [comment]
Wait... closed without an implementation?  This would be really useful!  Particularly with the new HTML 5 range input type.  Should I put in a new request for this?  Or can we re-open this?

In case anybody else is looking, here's a monkey-patch you can use to get a drag_by function for now: https://stackoverflow.com/questions/10866960/how-do-i-drag-a-jquery-slider-handle-from-within-capybara-and-chromedriver

**Comment by twalpole** [comment]
@mitsy It was closed because no one ever submitted a PR that matched the requirements discussed above.  If you want to submit a PR that does meet the requirements it will be considered.
