### ISSUE TITLE
No support for Rails restful :method magic

### ISSUE THREAD

**Issue by robholland** [teamcapybara/capybara#12]
Hard to know how to handle this. Webrat does some magic to check if a link has javascript to send "_method=delete" and sends a different HTTP verb based on that. In capybara context that feels a little "dishonest" to me. If something doesn't work without javascript it shouldn't work in the plain rack driver so people know that javascript is actually required for the thing to function (in my opinion). The question is, is that going to frustrate a lot of people? I presume most Rails users are now doing restful routes and using "link_to 'Delete', :method => :delete" in their views. That won't work as expected under the capybara rack driver. Thoughts?

Should we just leave things as they are and suggest that people tag deletion scenarios as @javascript so it's clear there is a requirement there? I think that is my preference.

**Comment by thelucid** [comment]
Just stumbled on this issue. Can't believe it's still a thing in 2017. I wrote an article way back in 2006 on how this could be solved: http://thelucid.com/2006/07/26/simply-restful-the-missing-action/

**Comment by twalpole** [comment]
@thlucid Entitled much?  and with a link to an article where the server is down too.  Also this has been supported for years so not really sure what your problem is - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rails.rb#L18 - Locking this thread
