### ISSUE TITLE
Clicking elements that are not links or buttons.

### ISSUE THREAD

**Issue by jarl-dk** [teamcapybara/capybara#1200]
I have a situation where I must click a `span` elements, which makes parts of the DOM vissible (that I must verify). A javascript click eventhandler makes the part of the DOM vissble. But when using capybaras `click_on` it seems that it only searches through `a` and `button` elements. So triggering this javascript click eventhandler seems impossible.

**Comment by verma-rajatk** [comment]
page.find_all(:xpath, "//*[normalize-space(text())='#{link_text}']").first.click
