### ISSUE TITLE
page.execute_script works, click doesn't

### ISSUE THREAD

**Issue by justin808** [teamcapybara/capybara#1211]
In the following script, button.click fails, but I can call page.execute_script per what I'd evaluate in the console, and that works.

On this page, there's a lot of dynamic javascript manipulating the DOM. Nevertheless, it's an absolute mystery why button.click did not work. I'd expect it to be doing the same same thing as calling click() in javascript. What's really strange is that if I called button.click twice, sometimes it would fire once, but not reliably.

```
button = find(".add-to-cart > .action-btn")
expect(button).to have_content("ADD TO CART")
page.execute_script('$(".add-to-cart > .action-btn").click()')
#button.click
```

I'm happy to try to provide more information to resolve this.

Some things I did:
1. I went into debugger mode for poltergeist. Everything looks normal, and the jquery script showed above worked fine in the console.
2. The button runs an ajax request. I'm quite sure that the button is just not getting clicked, so ajax is not part of the issue.

Here is a shot of the DOM for this issue.

![developer_tools_-_file____users_justin_j_blink_bpos_tmp_capybara_screenshot_2013-12-13-20-15-35 761 html](https://f.cloud.github.com/assets/1118459/1747957/e5bd45e4-6489-11e3-91f3-987efd5cc33b.jpg)

**Comment by gerrywastaken** [comment]
For anybody searching this issue using Chromedriver and mobil emulation:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2144&desc=2#c50

A workaround for this bug would be something along the lines of:
`page.execute_script("arguments[0].click()", find(selector))`
