### ISSUE TITLE
Proposal: refactor Capybara::RSpecMatchers to use public RSpec Expectations API

### ISSUE THREAD

**Issue by abotalov** [teamcapybara/capybara#1238]
I propose to refactor it to something like:

``` ruby
module Capybara::RSpecMatchers
  extend RSpec::Matchers::DSL

  module Helpers
    def wrapped
      if @actual.respond_to?("has_selector?")
        @actual
      else
        Capybara.string(@actual.to_s)
      end
    end
  end

  module HaveSelectorHelpers
    include Helpers

    def matches?(actual)
      @actual = actual
      wrapped.assert_selector(*@expected)
    end
  end

  matcher :have_selector do |*args|
    include HaveSelectorHelpers
  end
end
```

It would allow us to use features provided by Matchers DSL like default implementation of `failure_message`, `failure_message_when_negated`, `description`, composable matchers, chainable matchers. In some cases default implementations of failure messages look good enough, e.g. in `become_closed` matcher proposed here - https://github.com/jnicklas/capybara/pull/1235.

This can be done only in Capybara 3.0 as I believe `Capybara::RSpecMatchers::HaveSelector` is part of public API.

If you approve this suggestion I'll work on it myself.

**Comment by abotalov** [comment]
I wrote this issue when I didn't know it's valid to write custom matchers in this way (I think RSpec didn't have good enough documentation for this case).

Now it has (http://www.rubydoc.info/gems/rspec-expectations/RSpec/Matchers/MatcherProtocol) so it doesn't probably make sense to refactor it fully. But it looks to me there is still some stuff to cleanup there so I leave this open.

**Comment by twalpole** [comment]
Closing since these are pretty DRY now.
