### ISSUE TITLE
Capybara isn't finding select options

### ISSUE THREAD

**Issue by kiddrew** [teamcapybara/capybara#1242]
I'm using Capybara 2.2.1 with Rspec.

I have this code on my page:

```
<label for="question_category_id">Category</label>
<select id="question_category_id" name="question[category_id]">
  <option value="1">General</option>
</select>
```

And I've tried each of these:

```
select "General", from: "question_category_id"
select "General", from: "question[category_id]"
select "General", from: "Category"
page.select "General", from: "Category"
```

I get the same error every time:

```
Failure/Error: select "General", from: "Category"
Capybara::ElementNotFound:
  Unable to find option "General"
```

Everything I've read says that all of these should work.  Am I doing something wrong?

**Comment by alexdesi** [comment]
That also happens when using Materializecss, in that case is enough to pass the  visible: false option (thanks @twalpole)

**Comment by wadson-qwiklabs** [comment]
I just spent an afternoon on this issue, when doing a bit of debugging noticed that some of the fields were empty on the form, which led me to clone the development DB. 

Rake db:test:prepare

**Comment by AngeloRwanda** [comment]
I was facing the same issue. I ended up discovering that my factories were causing the issue. They weren't being created. This code helped troubleshoot them (placed in the spec files): 
```
FactoryBot.factories.map(&:name).each do |factory_name|
	describe "The #{factory_name} factory" do
		it "is valid" do 
			factory_thing = build(factory_name)
			expect(factory_thing).to be_valid
		end
	end
end 
```

**Comment by AngeloRwanda** [comment]
I was facing the same issue. It turned out my factories were the problem. They weren't being created at all, hence the lack of the data to populate the `<option> </option>`. The following code helped troubleshoot them factories (placed in the spec files): 
```
FactoryBot.factories.map(&:name).each do |factory_name|
	describe "The #{factory_name} factory" do
		it "is valid" do 
			factory_thing = build(factory_name)
			expect(factory_thing).to be_valid
		end
	end
end 
```

**Comment by twalpole** [comment]
@AngeloRwanda FYI -- You don't need to write that code yourself, FactoryBot provides it via the `lint` method - https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#linting-factories
