### ISSUE TITLE
Capybara switches to iframe context after executing js

### ISSUE THREAD

**Issue by maximderbin** [teamcapybara/capybara#1244]
Hi, guys!

I've just got issue with testing `CKEditor` using `capybara-webkit` driver

after executing client side code such as

``` coffeescript
CKEDITOR.instances['instanseId'].insertHtml('<p>some html</p>')
```

capybara switches to context of this ckeditor's `iframe` and cann't go back.

Is there way to switch capybara back to default (document) context?

**Comment by Hirurg103** [comment]
I found another way to fill in ckeditor. See [this comment](https://github.com/thoughtbot/capybara-webkit/issues/620#issuecomment-330810446)
