### ISSUE TITLE
Proposal: provide a nice way to do synchronized full text/title matching

### ISSUE THREAD

**Issue by abotalov** [teamcapybara/capybara#1256]
Currently `have_selector`, `have_text` and `have_title` do substring matching when string is passed to them.

But if element's text is not too long it's often more useful to do full string matching.

Currently synchronized full text matching can be done only using regexps:

``` ruby
have_selector('#id', text: /\A#{Regexp.escape('some text.')}\Z/)
have_text(/\A#{Regexp.escape('some text.')}\Z/)
have_title(/\A#{Regexp.escape('some text.')}\Z/)
```

But IMO it looks awful. I think Capybara should do a better job here and provide a way to do a full text matching more nicely.

I'd like to propose some ways how API may look like and I would like to hear your opinion on this.

Here is what I can propose:

``` ruby
#1
have_selector('#id', full_text: 'some text.')

#2a
have_full_title('some text.')
#2b
have_title(:full, 'some text.')
#2c
have_title(full: 'some text.')

#3a
have_full_text(:all, 'some text.')
#3b
have_text(:all, :full, 'some text.')
#3c
have_text(:all, full: 'some text.'))
```
#1 + #2a + #3a looks quiet good. But in that case we will have to add methods 10 methods:

`has_full_text?`, `has_no_full_text?`, `have_full_text`, `assert_full_text`, `assert_no_full_text`, `has_full_title?`, `has_no_full_title?`, `have_full_title`, `assert_full_title`, `assert_no_full_title`. IMO it's too much given that there are other ways.

IMO #3b doesn't look good.

I like #1 + #2c + #3c the most. The only issue with this is that it doesn't fit into the general idea of locator that carries out the main role in searching + options that clarify it.

**Comment by twalpole** [comment]
Closing this for PR #1813

**Comment by jvaron** [comment]
hello I'm building a test and I get this error Failure / Error: expect (page) .to have_content? ("From the control panel of your account you can see your")
                                                                                                                                              
      ArgumentError:
        The expect syntax does not support operator matchers, so you must pass to matcher to `# to`.

can someone help me, thanks

**Comment by twalpole** [comment]
@jvaron You've posted on the end of a closed thread with a question that really isn't about the thread.  If you have an actual issue with Capybara please create a new one, if you just have a howto question then please use the mailing list, gitter, or stackoverflow as requested in the README
