### ISSUE TITLE
Should Capybara API be more modularized?

### ISSUE THREAD

**Issue by abotalov** [teamcapybara/capybara#1294]
Capybara provides most of its methods as part of `Session` class. Then those methods are included to `Capybara::DSL`. It makes sense to add other methods to Capybara' `Session` like:
- resize current window / get size of current window / close current window / maximize current window
- wrappers for [action builder](https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#actions)
- wrappers for [touch gestures builder](https://dvcs.w3.org/hg/webdriver/raw-file/tip/webdriver-spec.html#touch-gestures)
- `switch_to_frame`
- `scroll_to(left,top)` / `current_scroll_position` (implemented via `execute_script`)
- methods for manipulations with cookies (`add_cookie`, `delete_cookie`, etc.)

Usually such methods are added as instance methods of `Session` class and are included to `Capybara::DSL`. But it bothers me that such approach adds too many methods into end user code that may start to interfere with methods provided by other libraries. Thus I don't especially like such design. Thus I'm curious if you see a better way out of this. But I don't see this way myself :worried:

**Comment by twalpole** [comment]
Closing this because I think it would be too big a breaking change, not to mention annoying to have to scope all user interactions to some other object all the time.
