### ISSUE TITLE
Net::ReadTimeout on first test using selenium

### ISSUE THREAD

**Issue by bdarfler** [teamcapybara/capybara#1305]
I've been trying to figure out a fix or work around for an intermittent Net::ReadTimeout on the first test in the test suite to run using Selenium.

I have two stacktraces, one from cucumber, one from rspec.

https://gist.github.com/bdarfler/4ff9710b9b8b222ffc54

I have enabled screenshots and when I look at them the page is clearly there as is the html. I have increased the selenium timeout to 2 minutes but that has not helped.

If it helps I am not able to replicate this locally. Only when the suite runs in CircleCi.

I'm out of ideas both for what the issue might be or how I might gain more information to help diagnose. Any help or suggestions would be greatly appreciated.

**Comment by dwbutler** [comment]
When the server is first starting up, it can take a while for the assets to be compiled during the first request. I suspect that this is why Selenium times out - the server simply takes too long to respond to the very first request. This is why only the first test in the suite times out, and why it can be intermittent.

It looks like `selenium-webdriver` has an internal HTTP timeout of 60 seconds. Here's the [documentation](https://code.google.com/p/selenium/wiki/RubyBindings#Internal_timeouts) explaining how to configure the timeout.

Unfortunately, it looks like [Capybara::Selenium::Driver](https://github.com/jnicklas/capybara/blob/e5c5991bd356eff4bd6c2cdf9ff85d3aa05cf569/lib/capybara/selenium/driver.rb#L13) does not expose this option.

I am using rspec-retry to work around the issue for now. Works like a charm. You don't have to change anything in the tests. Here is my configuration:

```ruby
require 'rspec/retry'

RSpec.configure do |config|
  # show retry status in spec process
  config.verbose_retry = true
  # Try twice (retry once)
  config.default_retry_count = 2
  # Only retry when Selenium raises Net::ReadTimeout
  config.exceptions_to_retry = [Net::ReadTimeout]
end
```

**Comment by afomi** [comment]
I also ran into the first feature spec timing out in an `ember-cli-rails` app.  Here's what I did to workaround assets taking more than 60 seconds to compile:

```
Capybara.register_driver :selenium do |app|
  profile = Selenium::WebDriver::Firefox::Profile.new
  client = Selenium::WebDriver::Remote::Http::Default.new
  client.timeout = 90 # instead of the default 60
  Capybara::Selenium::Driver.new(app, browser: :firefox, profile: profile, http_client: client)
end
```

**Comment by dylanlive** [comment]
Wanted to chime in that I also see Net::ReadTimeout issues pop up frequently. This seemed to be limited to the first test. Any other tests that hit our front page would pass without issue.

I resolved using rspec-rerun, with a max rerun of 5 times. Unfortunately, this "solution" still adds a significant amount of time to test duration.

**Comment by bhgames** [comment]
I also see this issue, and found rspec/retry, but we actually found after a year of rspec/retry that it was an anti-pattern for us. It allowed us to get sloppy on our tests, and eventually we had to go and skip tests that where chronically bad and slowly come back to them over time, so that we had green runs again. 

I wish there were a better work-around!

**Comment by rstormsf** [comment]
Here is another solution:
```ruby
RSpec.configure do |config|
  config.example_status_persistence_file_path = "./tmp/rspec_examples_status.txt"
...
end
```

then in your circleci.yml
```
dependencies:
  pre:
    - rm -rf ./tmp/rspec_examples_status.txt

test:
   override:
    - bundle exec rspec --failure-exit-code 0:
    - bundle exec rspec --only-failures:
```

**Comment by prashanth-sams** [comment]
@bdarfler do we have any retry gem for cucumber to handle timeout error?

**Comment by bdarfler** [comment]
@prashanth-sams I'm no longer working at the company where we had this issue and I don't recall the answer to your question. Sorry.

**Comment by ericboehs** [comment]
Another option for me was to just precompile the assets before the page loaded. I'm using CircleCI and followed [this article](https://jtway.co/4-lines-to-speed-up-your-rails-test-suite-on-ci-744e4326e8a3) on adding precompiling with inter-build caching.
