### ISSUE TITLE
current_url not correct when redirected to unreachable domain

### ISSUE THREAD

**Issue by tekknolagi** [teamcapybara/capybara#1313]
I am testing a URL shortener (http://github.com/palyvoice/paly.io), and have a test for redirects.

The test uses a randomly generated url with `Faker::Internet.http_url`, and so sometimes does not exist at all.

When I get dumped there, the `current_url` is `data:text/html,chromewebdata` instead of whatever url I was supposed to be redirected to.

Why is this? How can I fix it or otherwise assert that I have been redirected?

I am using Sinatra+Rspec+Capybara.

**Comment by bradparks** [comment]
For those interested, the page url seems to be available from javascript [as detailed here](http://stackoverflow.com/a/29945213/26510), and [usable in Capbara by calling evalute_script](http://stackoverflow.com/a/24965161/26510)

**Comment by prpetten** [comment]
Following @bradparks 
It ended up being this for me:
`page.driver.browser.title`

**Comment by kenorb** [comment]
Related: [ChromeDriver bug #1272](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1272)
