### ISSUE TITLE
Capybara::DSL within method overridden when including RSpec::Matchers

### ISSUE THREAD

**Issue by jwarykowski** [teamcapybara/capybara#1361]
Hi All,

Quick question as I'm unable to solve this:

``` ruby
require 'capybara'
require 'capybara/dsl'
require 'capybara/rspec/matchers'
require 'rspec'

class Page
  include Capybara::DSL
  include Capybara::RSpecMatchers
  include RSpec::Matchers

  def initialize
  end
end

page = Page.new
```

If you view the methods available to the Test object instance, as I have included the `RSpec::Matchers` the `Capybara::DSL` method 'within' is overridden by the method in the `RSpec::Matchers` module.

Is there anyway to get around this? I basically want to be able to use `expect` within my Test object.  e.g.

``` ruby
 def test
   expect(true).to eql true
 end
```

Please note that if I don't include the `RSpec::Matchers` module then I'm unable to use the expect method. I have the following versions of the gems installed:

capybara (2.4.1)
rspec (3.0.0)
rspec-core (~> 3.0.0)
rspec-expectations (~> 3.0.0)
rspec-mocks (~> 3.0.0) 

Any feedback would be greatly appreciated.

Regards,
Jon

**Comment by twalpole** [comment]
635671904345299bf6e351cc3e71c3fdfc836518 Should prevent this from the next release on.
