### ISSUE TITLE
Capybara with rspec and rails throw No route matches error on facebook dialog window

### ISSUE THREAD

**Issue by borisaka** [teamcapybara/capybara#1375]
Every time, when i try to find elements with wrong selector. 
Here is my code:

``` ruby
describe "Facebook login from dialog" do
  visit "/"
  click_link("sign_in")
    within_window (windows.last) do
    fill_in 'email:', with: "myemail@gmail.com"
  end
end
```

Selector 'email:' is wrong, but it's not see in stacktrace:
/Users/boris/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call': No route matches [GET] "/images/favicon.ico" (ActionController::RoutingError)
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/railties-4.1.4/lib/rails/rack/logger.rb:38:in `call_app'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in`block in call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:26:in`tagged'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/activesupport-4.1.4/lib/active_support/tagged_logging.rb:68:in `tagged'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/railties-4.1.4/lib/rails/rack/logger.rb:20:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/activesupport-4.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/actionpack-4.1.4/lib/action_dispatch/middleware/static.rb:64:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/railties-4.1.4/lib/rails/engine.rb:514:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/railties-4.1.4/lib/rails/application.rb:144:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in`block in call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in`call'
    from /Users/boris/.rvm/gems/ruby-2.1.1@global/gems/capybara-2.4.1/lib/capybara/server.rb:19:in `call'
    from /Users/boris/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in`service'
    from /Users/boris/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
    from /Users/boris/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in`run'
    from /Users/boris/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by anujaware** [comment]
I am also getting same error.

**Comment by chalmagean** [comment]
+1

**Comment by twalpole** [comment]
@chalmagean  This issue is CLOSED  -- its not a Capybara issue. If you want help with an error you're getting, go to the Capybara mailing list as requested in the README and post details of your problem there

**Comment by mikeantonelli** [comment]
My setup includes a Rails Engine, using Combustion and Capybara to run functional tests. I also ran into this issue, and placed a favicon in `spec/internal/public/favicon.ico` to resolve. Hope this helps fellow googlers.
