### ISSUE TITLE
has_text? ignores visible key

### ISSUE THREAD

**Issue by rbu** [teamcapybara/capybara#1453]
This is on 2.4.1. Other keys work just fine. Providing :visible to other functions works fine as well.

``` ruby
(byebug) has_text?('all', :visible => true)
invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
true
(byebug) has_text?('all', :visible => false)
invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
true
(byebug) has_text?('all', :count => 3)
false
(byebug) has_css?('.all', :visible => true)
false
```

**Comment by dwt** [comment]
Ping! Any closure on this? I just stumbled about this again.

**Comment by dwt** [comment]
I've just gotten bitten by this again. Is there a specific reason that you want to accept `has_text?('foo', visible: false)` just like you do with all other `has*?()` APIs? AFAIK it really stands out as being the only one of the bunch that doesn't follow this convention.

**Comment by twalpole** [comment]
@dwt The `visible` option everywhere else has 5 valid values - 
true/:visible, false/:all, and :hidden -  The :hidden value cannot be implemented for has_text? so it uses a different API -- Any recent version of Capybara should warn you if you try to use a `visible` option so I'm not really sure how you could get bitten by this again.  This may be changing when v3 releases but as of now it's the way it is.
