### ISSUE TITLE
Capybara throws away URL fragment under rack-test (and others?)

### ISSUE THREAD

**Issue by glenjamin** [teamcapybara/capybara#155]
I have a page which sends a redirect to a URL that contains a URL fragment eg. /studies/1/#users

When capybara makes a request to rack-test, it sends the fragment correctly
When Rack/Rack-test forms the environment hash from the URI, it discards the URL fragment. This is probably correct too.

When I request the current_url from the driver, it uses request.url - which has no knowledge of the URL fragment.

We've currently monkeypatched a low-level request method in MockSession to record the URL before it was parsed, and changed current_url to return this.

Obviously this isn't particularly nice.

**Comment by aminariana** [comment]
Wow, this is a nasty bug!
+1 for including the hash fragment of the URL in current_url

**Comment by twalpole** [comment]
@aminariana You just commented on an issue closed in 2011 - If you're having an issue that you think is actually a bug in capybara please create a new issue with enough information to reproduce it rather than commenting on things closed 6 years ago.
