### ISSUE TITLE
Net::ReadTimeout when within_frame iframe suddenly closes

### ISSUE THREAD

**Issue by samgavinio** [teamcapybara/capybara#1793]
I'm writing a capybara/rspec test for a web app that opens a popup window containing a form that needs to be submitted. Immediately upon submission of the form, the javascript logic in the popup window would automatically close the popup window. 

Now I would intermittently get `Net::ReadTimeout` errors because of this, I'm assuming because the selenium webdriver cant recover when the popup closes too quickly and is left in a weird state.

```
          popup_window = window_opened_by do
              some_button.click
          end

          within_window popup_window do
            within_frame 0 do
              some_form_submit_button.click #this would close the popup
            end
          end
     
          # carry on with other stuff in the parent window
```

I'm using `within_frame` here because the form I need to submit is actually within an iframe in the pop-up window. I have no control over the page I am testing and would only really be able to work around it in the test.

Is there any way to reliable handle the popup window and the iframe within it closing too quickly?

### Versions

capybara (2.7.1)
selenium-webdriver (2.51.0)

**Comment by twalpole** [comment]
This sounds driver specific. What driver/versions are you using?

**Comment by samgavinio** [comment]
Versions are:

capybara (2.7.1)
selenium-webdriver (2.51.0)

**Comment by twalpole** [comment]
Upgrade to the latest version of capybara and selenium-webdriver

**Comment by samgavinio** [comment]
Experiencing this still in capybara (2.10.1)  and selenium-webdriver 2.53.4. Here's some older related selenium issues for reference:

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3291
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7534

Since it seems to be a selenium driver issue it's probably a good idea to keep this closed.
