### ISSUE TITLE
be_readonly as in addition to be_disabled

### ISSUE THREAD

**Issue by ain** [teamcapybara/capybara#1794]
I'd like to propose a feature: `be_readonly` as in addition to `be_disabled` so a spec can be written to check against HTML 5 elements that have the `readonly` attribute, e.g.: 
```ruby
expect(find('#field_id')).to be_readonly
```

**Comment by twalpole** [comment]
The be_xxxx matchers are provided by RSpec for all boolean (name ends in ?) methods on the element, so if you're using a version new enough to have Element#readonly? (2.8 iirc) this should already be provided.  That being said, those marchers don't provide any waiting/retrying behavior, and a much better way to test for this is the have_field matcher

    expect(page).to have_field('field_id', readonly: true)

**Comment by ain** [comment]
Thanks for prompt feedback!
