### ISSUE TITLE
`fill_in` Not Rendering Following save_and_open_page

### ISSUE THREAD

**Issue by Schwad** [teamcapybara/capybara#1796]
## Meta
Capybara Version:
2.7.1
Driver Information (and browser if relevant):
Firefox Versoin:
47.0.1
Selenium-Webdriver Verstion:
2.53.4

Nothing else custom configured such as Poltergeist, etc.

## Expected Behavior

Following save_and_open_page with fields filled in the codebase (*and* working behind the scenes if I enable `click_button 'Log in'`), I should see the user email and the user password entered.

## Actual Behavior

Page renders unfilled. 

Screenshot:
<img width="340" alt="screen shot 2016-11-20 at 9 02 32 pm" src="https://cloud.githubusercontent.com/assets/7865030/20466116/b0ff3bd6-af64-11e6-9f5f-6059e5576fc5.png">

Code:

```
scenario 'logs in user' do
    visit root_path
    click_link "Sign In"
    fill_in "Email", with: user.email
    fill_in "Password", with: user.password
    save_and_open_page
    click_button("Log in")
    expect(page).to have_content('Queries')
  end
```
## Steps to reproduce

Fork my codebase: https://github.com/Schwad/PorkCasts-Montana

`rake db:migrate`
`bundle install`
(Currently on ruby 2.2.1, upgrading to Rails five and Ruby 2.3.1 following full test suite).

Would appreciate any thoughts here, I started seeing this behavior on a production app in my day job and have used my side-project public repo to replicate the issue for you to be able to dig in. 

I've ensured Firefox is 47.0.1 and disabled updates so it hasn't snuck around to 50 behind my back!

Would sincerely appreciate any thoughts, comments or questions you can offer.

Best,

Schwad

**Comment by twalpole** [comment]
save_and_open_page saves the current HTML and attributes.  Filling in a field only changes the value property (not attribute) so it won't be shown in the saved page.  If you need to see the current state, use save_screenshot instead.

**Comment by Schwad** [comment]
Thanks for this @twalpole .

For those who may visit this issue in the future having a similar problem, be sure to:

* Set default_driver as selenium
* If you want to replicate the functionality of save_and_open_page with `save_screenshot`, I found `save_and_open_image` from the [capybara-screenshot](https://github.com/mattheworiordan/capybara-screenshot) gem helpful.

**Comment by twalpole** [comment]
@Schwad There is also `save_and_open_screenshot` which doesn't need the capybara-screenshot gem.
