### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by 8vius** [teamcapybara/capybara#1800]
Hello I'm just upgrading to rails 5, specifically 5.0.0.1 and I'm getting a lot of deprecation warnings that look like the following:
`
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from process at /Users/LuisMiguelDelgado/.rvm/gems/ruby-2.3.1/bundler/gems/capybara-6234d2d20b63/lib/capybara/rack_test/browser.rb:61)`

I was getting varied deprecation warnings with the same message, thought Capybara might be the source so I pulled the gem straight from the github master branch and now I'm getting these. Any thoughts?

**Comment by twalpole** [comment]
Since that line (and no where else in Capybara) mentions `original_exception` it's not a Capybara issue.
