### ISSUE TITLE
Using set() on contenteditable does not fire JavaScript events

### ISSUE THREAD

**Issue by mrjlynch** [teamcapybara/capybara#1802]
## Meta
**Capybara Version:** 2.7.1
**Driver Information:** capybara-webkit 1.11.1

## The problem
Using `.set()` works well, but neglects to fire JavaScript events. This creates an issue when javascript events must be fired when a user types into a `contenteditable` field (eg. when using redactor, Froala). This was mentioned in #310.

One solution is to set the field using javascript: (froala example)
```ruby
page.execute_script("$('#element').froalaEditor('html.set','Zenn')")
```

This solution is messy however, is there an alternative approach or could `.set()` be changed to allow these js methods to fire?

**Comment by twalpole** [comment]
This is driver specific behavior - you need to file this issue over on the capybara-webkit project
