### ISSUE TITLE
select drop down

### ISSUE THREAD

**Issue by LamhotJM** [teamcapybara/capybara#1806]
## Meta
'capybara', '~> 2.10', '>= 2.10.1'

Driver Information (and browser if relevant):
45.5.0 firefox ESR

## Expected Behavior
should able to select  hapus 
select 'hapus', :from => :toggle_action

I also have been try to use 

find('#toggle_action').click
sleep 2
find('#toggle_action').find(:xpath, 'option[2]').select_option
select('hapus')
find(:xpath, './/*[@id="toggle_action"]/option[@value="delete"]').click
select "hapus", :from => "toggle_action"
sleep 1
within '#toggle_action' do
find('#toggle_action>option', :text => 'hapus').click
end
find('#toggle_action').click
select('hapus', :from => 'toggle_action')
select("delete")

find(item_id).select('hapus')

## Actual Behavior
Can't select 'hapus',  but step green 

## Steps to reproduce

![screenshot from 2016-12-16 09-18-43](https://cloud.githubusercontent.com/assets/19463315/21249466/ca69eba0-c370-11e6-9a72-3bb616c8a5db.png)

**Comment by twalpole** [comment]
What version of selenium-webdriver are you using?

If your step is green, what makes you believe the item is not selected?

**Comment by twalpole** [comment]
The following code works fine for me - closing until enough information is provided to replicate the issue
```
require "selenium/webdriver"
require "capybara/dsl"

html = DATA.read
app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

# Disable marionetter on selenium-webdriver 3.x
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(
    app,
    browser: :firefox,
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.firefox(marionette: false)
  )
end

sess = Capybara::Session.new(:selenium, app)
sess.visit("/")

sess.assert_selector(:select, 'toggle_action', selected: 'set dibaca')
sess.select('hapus', from: 'toggle_action')
sess.assert_selector(:select, 'toggle_action', selected: 'hapus')

__END__

<!doctype html>
<html>
<head>
<title>Some title</title>
</head>
<body>
<select id="toggle_action" class="c-inp c-inp--smal" name="toggle_action">
  <option value="read">set dibaca</option>
  <option value="delete">hapus</option>
</select>
</body>
</html>
```
