### ISSUE TITLE
Non-empty about:blank prevents Capybara from resetting session

### ISSUE THREAD

**Issue by wildlyinaccurate** [teamcapybara/capybara#1809]
## Meta
Capybara Version: 2.2.1, 2.11.0
Driver Information (and browser if relevant): selenium-webdriver 3.0.3 using ChromeDriver 2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6) to drive Chrome 55
Other: Tests are running with Cucumber 2.4.0

## Expected Behavior

Capybara should reset the session after each scenario with no issues.

## Actual Behavior

When JavaScript is disabled, ChromeDriver appends an iframe to the about:blank page's body, which causes Capybara's [empty page check](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L136) to fail:

```html
<html><head></head><body><iframe name="chromedriver dummy frame" src="about:blank"></iframe></body></html>
```

**2.11.0** Chrome navigates to about:blank, and after 10 seconds Capybara raises `Timed out waiting for Selenium session reset (Capybara::ExpectationNotMet)`

**2.2.1** as soon as Chrome navigates to about:blank, Capybara raises `expected not to find xpath "/html/body/*", found 1 match: "" (Capybara::ExpectationNotMet)`

**2.2.0** works fine because it uses an empty HTML file instead of about:blank

## Steps to reproduce

With the following files, run `bundle install && bundle exec cucumber`

```ruby
# Gemfile
source 'http://rubygems.org'

gem 'cucumber', '~> 2.4.0'
gem 'capybara', '~> 2.11.0'
gem 'selenium-webdriver',  '~> 3.0.0'
```

```ruby
# features/support/env.rb
require 'capybara/cucumber'

Capybara.default_driver = :chrome_no_js
Capybara.register_driver :chrome_no_js do |app|
  Capybara::Selenium::Driver.new(
    app,
    :browser => :chrome,
    :prefs => {
      :profile => {
        :default_content_setting_values => { :javascript => 2 }
      }
    }
  )
end

When('I open BBC News') { visit 'http://www.bbc.com/news' }
```

```cucumber
# features/test.feature
Feature: iframe shenanigans

Scenario: the test
  When I open BBC News
```

## Screenshot

![screen shot 2016-12-18 at 22 13 13](https://cloud.githubusercontent.com/assets/794263/21292819/00c7fbae-c576-11e6-98de-b07db1e3ad42.png)

**Comment by twalpole** [comment]
This sounds like a Chrome bug -- have you reported it to that project?

**Comment by wildlyinaccurate** [comment]
I haven't reported it to ChromeDriver because I assume it's a "feature" rather than a bug. I was wondering whether Capybara would solve this by going back to using an empty HTML document rather than navigating to about:blank? Is there a reason that about:blank is preferred?

**Comment by twalpole** [comment]
@wildlyinaccurate about:blank is preferred because the empty HTML document caused all sorts of issues with other browsers in selenium, and isn't necessarily available when Capybara is set to not run its own server.  Not sure how having an extra iframe in the about:blank page could be considered a "feature", it's completely against the idea of about:blank.  

Anyway, try the extra_dummy_frame branch and see if that works for you, there's no guarantee all the other features of Capybara will work correctly when JS is disabled either, since things like returning non-visible text depend on execute_script, which used to not work when JS was disabled in the browser.  It's possible JS is now allowed to be executed from chromedriver even when JS is disabled, but it's not tested)

**Comment by wildlyinaccurate** [comment]
Thanks, I'll give that branch a go. I'll also have a play around with ChromeDriver and see if I can comfirm whether execute_script still functions correctly.

**Comment by twalpole** [comment]
@wildlyinaccurate Any feedback on the branch?

**Comment by wildlyinaccurate** [comment]
Nope, I'm sans computer at the moment. I'll check back in after the holidays.

**Comment by twalpole** [comment]
@wildlyinaccurate Any update on this?

**Comment by twalpole** [comment]
Closing due to lack of response - we can reopen if/when feedback is provided
