### ISSUE TITLE
Capybara 2.12 Release

### ISSUE THREAD

**Issue by twalpole** [teamcapybara/capybara#1821]
@jferris @mhoran @jonleighton @route FYI: I plan to do a Capybara 2.12.0 within the next week or two. Two changes that affect drivers are 

1. Optional driver support for simple argument passing to execute_script/evaluate_script (including page elements).
2. Session#switch_to_frame - requires the driver to support the Driver#switch_to_frame API

There were also some tests added around #disabled? behavior when field elements are inside disabled fieldsets.

**Comment by route** [comment]
@twalpole Do we have both in poltergeist?

**Comment by twalpole** [comment]
@route - Yes, I implemented bath in Polyergeist (not released yet though), it should be passing all the capybara master branch tests.

**Comment by coding-bunny** [comment]
*question:*  Is it possible to support a higher nokogiri version? Because right my dependencies are flagged as:

```
    capybara (~> 2.11.0) was resolved to 2.11.0, which depends on
      xpath (~> 2.0) was resolved to 2.0.0, which depends on
        nokogiri (~> 1.3)
```

And I cannot upgrade Nokogiri because of it  (and due a few other gems)
Unless I misinterpreted this bundle errror, then please ignore this comment.

**Comment by twalpole** [comment]
@coding-bunny The specification `nokogiri (~> 1.3}'  means   >= 1.3.0 and  < 2.0.0 so it's not capybara or path limiting your nokogiri version

**Comment by coding-bunny** [comment]
Then the error makes no sense....
Will dive deeper, thanks for the explanation.
Looking forward to the new release as well :)

**Comment by twalpole** [comment]
@coding-bunny -- just add a  `gem 'nokogiri', '= 1.7.0.1' to your own projects Gemfile and then update, it'll make it clear what is actually stopping it.  (maybe ruby version - Nokogiri 1.7 requires ruby 2.1+)

**Comment by twalpole** [comment]
Released
