### ISSUE TITLE
Occasional failure when using rack_test driver on Ruby 2.4

### ISSUE THREAD

**Issue by twalpole** [teamcapybara/capybara#1825]
When running Capybaras tests we are getting occasional failures on the rack_test tests

    Failure/Error: process(:get, last_response["Location"], {}, env) if last_response.redirect?
    
     TypeError:
       wrong argument type Integer (expected Proc)
     # ./lib/capybara/rack_test/browser.rb:39:in `block in process_and_follow_redirects'

These errors (when they occur) are in random tests, and I think are probably a bug in Ruby 2.4s forwardable implementation but haven't been able to prove that yet.

**Comment by twalpole** [comment]
@abotalov Have you come across this or do you have any ideas about the cause?

**Comment by abotalov** [comment]
I have found out that it also happens in `html` method where `last_response` is used:
* ./lib/capybara/rack_test/browser.rb:94:in `html' (https://travis-ci.org/teamcapybara/capybara/jobs/188745458)

Also it sometimes happens more than one time per build - https://travis-ci.org/teamcapybara/capybara/jobs/188644698

It happens in different specs all the time.

**Comment by twalpole** [comment]
Yeah, last_response is forwarded with def_delegator.  I'm leaning towards believing this is a bug in ruby 2.5

**Comment by abotalov** [comment]
It might be given there were many changes in Forwardable, but it has to be proven.

**Comment by twalpole** [comment]
Agreed - short term I may monkey patch rack_test and see if the issue goes away

**Comment by twalpole** [comment]
I'm running a test set with the last_response method monkey patched to just call rather than use the implementation of def_delegator - will see how that goes  https://travis-ci.org/teamcapybara/capybara/builds/189108461

**Comment by twalpole** [comment]
So after monkey patching around the def_delegator I've run the full build 3 times on travis and the error has not occurred -- I think this pretty conclusively proves it's an issue in the ruby 2.4 delegator code.

**Comment by twalpole** [comment]
This is indeed a bug in the MRI ruby optimizer, it has been fixed in trunk so will be fixed ruby 2.4.1

**Comment by twalpole** [comment]
Closing since it's a Ruby 2.4.0 bug.
