### ISSUE TITLE
Capybara is starting Puma 3.7.0 with wrong host and port settings

### ISSUE THREAD

**Issue by ditch0** [teamcapybara/capybara#1831]
## Meta
Capybara Version: 2.12.0

## Expected Behavior
Capybara starts Puma server with host and port settings defined in config.

## Actual Behavior
When using Puma 3.7.0 server is started on tcp://0.0.0.0:3000. Capybara.server_port and Capybara.server_host are ignored.

My config:
> Capybara.javascript_driver = :poltergeist
> Capybara.server = :puma
> Capybara.server_host = '127.0.0.1'
> Capybara.server_port = 3030

rspec output:
> Puma starting in single mode...
> * Version 3.7.0 (ruby 2.4.0-p0), codename: Snowy Sagebrush
> * Min threads: 5, max threads: 5
> * Environment: test
> * Listening on tcp://0.0.0.0:3000

With Puma 3.6.2 it works as expected.

## Steps to reproduce
* Install Puma 3.7.0
* Set non-default Capybara.server_port and Capybara.server_host
* Run tests using javascript driver

**Comment by twalpole** [comment]
I can't reproduce this behavior, do you have your own `Capybara.register_server(:puma)` block defined?

**Comment by twalpole** [comment]
I have replicated this, but have no clue why --I think it's a bug in puma

**Comment by twalpole** [comment]
Puma is now automatically loading `config/puma.rb` - Not sure why though

**Comment by twalpole** [comment]
Until a new Capybara release is made you can workaround this issue by putting

    Capybara.register_server :puma do |app, port, host|
      require 'rack/handler/puma'
      Rack::Handler::Puma.run(app, Host: host, Port: port, Threads: "0:4", config_files: ['-'])
    end

in your code before specifying `Capybara.server = :puma`  which will prevent puma from loading config/puma.rb and use the passed in options.

**Comment by nateberkopec** [comment]
We'll fix this in 3.7.1, should push it out soon.

**Comment by twalpole** [comment]
@nateberkopec Any update on a puma 3.7.1 release?

**Comment by twalpole** [comment]
Fixed in puma 3.7.1
