### ISSUE TITLE
Capybara working with Angular Directives

### ISSUE THREAD

**Issue by giovanicosta** [teamcapybara/capybara#1832]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

Driver Information (and browser if relevant): Implement support to AngularJS implementations. Would it be possible for the Capybara to implements support to all AngularJS directives? For example: https://docs.angularjs.org/api/ng/directive

## Expected Behavior
For example, to command <fill_in ‘ng-directive’, :with => “value”>, we have a success result.

## Actual Behavior
For example, to command <fill_in ‘ng-directive’, :with => “value”>, we have a not found result.

**Comment by twalpole** [comment]
Capybara focuses on adding interaction for standard HTML elements, and is not currently interested in adding methods to handle the JS framework du jour elements/widgets.  If you wanted to create a separate gem that provides selectors for angular elements (using Capybara.add_selector) on top of Capybara feel free.
