### ISSUE TITLE
Spurious Error in IDE; Only for Capybara

### ISSUE THREAD

**Issue by jeffnyman** [teamcapybara/capybara#1840]
This is more of an issue with Capybara and IDE integration. As such, I wasn't sure of the best place to post this. I'm finding that if you use the following structure in RubyMine (or IntelliJ IDE with the Ruby plugin), you get an error indicated for the code. Although the code still works.

Here is the code:

```ruby
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
```

The second line is the one that leads to a contextual error in RubyMine. Specifically:

    Found 2 extra arguments. Required 0.

I bring this up because it happens with literally no other Ruby library that I have found, only Capybara. As far as version specifics:

Capybara version is 2.12.1. I'm using RubyMine 2016.3.2. Current build is RM-163.10154.57. This, however, happens on the last three builds of RubyMine for me. I've also tried this on the IDE on different machines just in case I was getting some weird artifact.

I'm not sure if there's anything that can even be done for this but I just wanted to bring it up in case it was either a known issue or an emerging issue, particularly since, so far, Capybara is the only library I've seen this happen with.

**Comment by twalpole** [comment]
I don't use an RubyMine or IntelliJ so I have no way to replicate this however the code called by `Capybara::Selenium::Driver.new` is https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L35 .  From that we can see it defined as `def initialize(app, options={})`, so it takes 1 or 2 parameters and the code you show is calling it with 2 so the error doesn't really make a lot of sense to be coming from that line.  Maybe you should report it to RubyMine for an explanation?

**Comment by jeffnyman** [comment]
Agreed. I am in process of doing just that with JetBrains and will report back when I get a response. The code assist in RubyMine ("jump to declaration") is pointing to these two locations:

    Driver (Capybara in capybara.rb)
    Driver (Capybara in capybara/driver/node.rb)

I note that in the first of those, the following lines are being jumped to:

```ruby
module Driver; end
module Selenium; end
```

I don't know if that's what is throwing RubyMine off. I was hesitant to bring this up here because clearly the code works so it's not an issue with Capybara; but if others use this IDE they might come across this issue.

**Comment by twalpole** [comment]
Ok - closing this for now then, we can reopen if JetBrains gets back to you and it does turn out to be a Capybara issue.
