### ISSUE TITLE
Add support for proxied requests including X-FORWARDED-FOR

### ISSUE THREAD

**Issue by rschellhorn** [teamcapybara/capybara#1842]
## Meta
Capybara Version: 2.12.1
Driver Information (and browser if relevant): Poltergeist
Rails: 5.0.2
Rack: 2.0.1

## Expected
Capybara should start a Rack server able to handle X-FORWARDED-FOR headers.

## Actual case
The way Capybara fires up the rack server is similar to: https://github.com/rack/rack/issues/990 . Therefore browser requests going through a proxy  won't reach the actual Rails server.

## Possible fix
As suggested in the Rack-issue, is adding the full uri to the `map` command. See https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rails.rb#L5

**Comment by twalpole** [comment]
Since we don't necessarily know what the full uri is going to be (the user can change Capybara.app_host, /etc/hosts, local DNS routing, etc) and I would guess a config using  X-FORWARDED-FOR when testing is pretty rare, this is probably up to the user to just set their own Capybara.app

**Comment by twalpole** [comment]
Also, what have you set Capybara.server to?  If you haven't set it, try `Capybara.server = :puma`

**Comment by rschellhorn** [comment]
Thanks for the last reply. Puma works like a charm!

Some background:
We use Capybara to test a React (through create-react-app) front-end with a Rails backend. Create-react-app just enabled X-FORWARD headers for their built in proxy capabilities.

**Comment by twalpole** [comment]
Closing this since it sounds like it's just a limitation of Webrick, which will not be the default whenever 3.0 launches and Capybara is easily switched to puma (which with rails 5+ you really want to do anyway otherwise ActionCable in process testing won't work)
