### ISSUE TITLE
Capybara::ElementNotFound when within Bootstrap .collapse div

### ISSUE THREAD

**Issue by dxypher** [teamcapybara/capybara#1848]
## Meta
Capybara Version:
2.8.1
Driver Information (and browser if relevant):
Poltergeist, Chrome

## Expected Behavior
    within '.main-navigation' do
      click_link 'Blog'
    end

should find the link 'Blog'
## Actual Behavior
     Failure/Error: click_link 'Blog'
     
     Capybara::ElementNotFound:
       Unable to find link "Blog"

## Steps to reproduce
```
<nav class="navbar navbar-toggleable-lg navbar-inverse main-navigation" id="scroll-top">
  <button class="navbar-toggler navbar-toggler-right" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link mr-4" href="#">Blog</a>
    </div>
  </div>
</nav>
```
If I move the Blog link outside of the .collapse div test passes
Inside of .collapse Capybara doesn't find the link even though save_and_open_page displays Blog link.

**Comment by twalpole** [comment]
The .collapse would by default be non-visible on the page -- save_and_open_page just saves the HTML without the CSS - a better test for you would be `save_and_open_screenshot` which will actually show what is visible and non-visible on the page.  If you haven't clicked on the button to toggle the menu before attempting to click the link then it definitely won't work.  If you have then show your full test code that you expect to work.
