### ISSUE TITLE
All method for RSpec not playing nice with Capybara

### ISSUE THREAD

**Issue by luke-hill** [teamcapybara/capybara#1849]
Copied from selenium-webdriver https://github.com/SeleniumHQ/selenium/issues/3724

## Meta
Capybara Version: 2.12.0
Driver Information (and browser if relevant):
Selenium webdriver 2.53.4

## Meta -
OS:  

Selenium Version:  2.53.4

Browser:  Irrespective (I used Chrome)

Browser Version:  Irrespective (I used latest Chrome)

## Expected Behavior -
When asking RSpec to perform `all` matching tests. They run and pass/fail accordingly
## Actual Behavior -
The following the error is thrown
```
Selenium::WebDriver::Error::InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.1.7601 SP1 x86_64)
```
## Steps to reproduce -
Try and perform one of the following inline tests
`expect(['23 apr 2017','23 apr 2017','23 apr 2017','23 apr 2017']).to all eq('23 apr 2017')`
`expect(['23 apr 2017','23 apr 2017','23 apr 2017','23 apr 2017']).to all include('23 apr 2017')`
`expect([1, 3, 5]).to all( be < 10 )`
`expect([1, 3, 5]).to all( be_odd.and be < 10 )`

Have been told by Selenium it's likely to be Capybara

**Comment by luke-hill** [comment]
I'll close this as I've just realised that this is a duplicate of: https://github.com/teamcapybara/capybara/issues/1396. I've tried namespacing the RSpec test by doing something like this.

`expect(@app.stage2.outbound_flight_dates).to RSpec::Matchers.all eq( @selected_date.downcase )` But sadly to no avail.

**Comment by abotalov** [comment]
Please also see https://github.com/teamcapybara/capybara/pull/1814

**Comment by luke-hill** [comment]
Thanks for that. I'm guessing there's something in the pipeline from both communities and I just need to wait until those are done before trying to do my code?

**Comment by twalpole** [comment]
Nothing is coming to "fix" this, at most it would be a warning when RSpec shadows Capybara.  What you probably need to do to access RSpecs `all` matcher is

    ... .to RSpec::BuiltIn::All.new(eq(...))

**Comment by luke-hill** [comment]
Cheers for that, I had actually tried something "similar" to that, but never thought to try re-create the object. Managed to get it working with a slightly tweaked version of your snippet :) Props!

**Comment by twalpole** [comment]
Something did come along to fix this :) 635671904345299bf6e351cc3e71c3fdfc836518 should fix it in the next release

**Comment by luke-hill** [comment]
We've got a custom module which currently creates an `all_match` method. So we have this kinda example in our step definition cucumber code.

`expect(@app.stage2.array_of_flights). to all_match include "Manchester")`

So hopefully this should work as 
`expect(@app.stage2.array_of_flights). to all include "Manchester")` - If I'm right?

**Comment by twalpole** [comment]
If you're using the master branch it should
