### ISSUE TITLE
Capybara will not choose radio elements generated by simple_form

### ISSUE THREAD

**Issue by orenyk** [teamcapybara/capybara#1851]
## Meta
Capybara Version: 2.13.0
Driver Information (and browser if relevant): Rack::Test

## Expected Behavior
Choosing a radio button input should a) actually change the form input and b) be permitted by Capybara.

## Actual Behavior
Choosing a radio button input generates a warning about changing readonly elements and does not change the form inputs.

## Steps to reproduce
I've recently upgraded from 2.7.1 to 2.13.0 and this has broken tests using radio button inputs generated by [`simple_form`](https://github.com/plataformatec/simple_form). The failing test is [here](https://github.com/YaleSTC/vesta/blob/eac7de690dcfc391fc7a82986228c69909b69d17/spec/features/draws/draw_student_assignment_spec.rb#L34), and the relevant view / form is [here](https://github.com/YaleSTC/vesta/blob/eac7de690dcfc391fc7a82986228c69909b69d17/app/views/draws/student_summary.html.erb#L17). The test now generates the warning about attempting to set readonly elements, which I believe causes the actual choosing to be ignored. I suspect that this has to do with the hidden form generated by simple_form as part of the input; the generated html is:

```html
<div class="input radio_buttons required draw_student_assignment_form_adding">
  <label class="radio_buttons required"><abbr title="required">*</abbr> Action</label>
  <input type="hidden" name="draw_student_assignment_form[adding]" value="">
  <div class="radio">
    <label for="draw_student_assignment_form_adding_true"><input class="radio_buttons required" required="required" aria-required="true" type="radio" value="true" checked="checked" name="draw_student_assignment_form[adding]" id="draw_student_assignment_form_adding_true">Add</label>
  </div>
  <div class="radio">
    <label for="draw_student_assignment_form_adding_false"><input class="radio_buttons required" required="required" aria-required="true" readonly="readonly" type="radio" value="false" name="draw_student_assignment_form[adding]" id="draw_student_assignment_form_adding_false">Remove</label>
  </div>
</div>
```

Choosing a radio option changes the value of the hidden element, causing the Capybara warning behavior. I suspect that this was caused by b2af3d45c4c20765c75b799b2798c88c7316d323.

**Comment by twalpole** [comment]
Since the rack_test driver doesn't support JS there is no way the value of the hidden element is being changed, and the error being reported is correct - since the radio button you're attempting to choose has the `readonly="readonly"` attribute, which prevents it from being selected.  Why your view is outputting it as readonly I have no clue since it doesn't appear to be in the view code.

**Comment by orenyk** [comment]
Oh you're totally right, I missed the `readonly` setting on the radio elements themselves. I'll take this up with the simple_form team, thanks!
