### ISSUE TITLE
Capybara clicks on different element than what it was instructed to click on

### ISSUE THREAD

**Issue by dwt** [teamcapybara/capybara#1857]
## Meta
Capybara Version: capybara (2.10.1)
Driver Information (and browser if relevant):
Firefox 53.0 (64-Bit), (venv:yeepa), geckodriver 0.16.1

## Expected Behavior

Capybara should click on the requested elements, then click on the targeted elements, not just somewhere on the page where it might have been at some point during the animation that shows it.

## Actual Behavior

It just clicks on something.

## Steps to reproduce
```
require 'capybara'

Capybara.run_server = false
Capybara.default_max_wait_time = 20
Capybara.ignore_hidden_elements = true
Capybara.exact = false
Capybara.match = :prefer_exact


Capybara.register_driver(:firefox) do |app|
  Capybara::Selenium::Driver.new(app, browser: :remote, 
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.firefox)
end

Capybara.default_driver = :firefox

page = Capybara::Session.new(:selenium)
page.visit('https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71')

10.times do
  page.find('.side-menu').click_link('Play')
  page.find('.side-menu').click_link("Measure")
  page.click_link("My results")
  sleep 3
end
```

**Comment by dwt** [comment]
This is actually quite funny to watch and you get to almost all the pages in the top part of the menu.

What is not so funny is that because of this my ac server is deep red. :/

**Comment by twalpole** [comment]
This is caused by the same issues with selenium-webdriver/geckodriver mentioned in Issue #1856
