### ISSUE TITLE
Which filters did it not match?

### ISSUE THREAD

**Issue by jjb** [teamcapybara/capybara#1858]
## Meta
* Capybara 2.13.0
* selenium-webdriver 3.4.0
* ChromeDriver 2.27
* rails 5.1

## Expected Behavior

this to work:

```ruby
visit page_path("foo")
assert_selector "h1", text: "Foo Bar"
```

## Actual Behavior

> expected to find css "h1" with text "Foo Bar" but there were no matches. Also found "Foo Bar", which matched the selector but not all filters.

I've tried adding `visible: true, count: 1` just in case it was accidentally invisible or the count default was something else. same behavior.

1. how do i find out which filters are being expected?
1. I've been dealing with this error message for years. Couldn't it print out which filters weren't satisfied? Or at least, print out all the filters being expected? If this is possible and desirable, I can maybe put together a PR.

**Comment by twalpole** [comment]
`visible: true` is the default, so adding that would make no difference.  You could add `visible: false` or `visible: :all` if you want it to match visible and hidden elements.  

The filters available on a given selector are specified when the selector type is defined - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb#L37 - Assuming you're using the default `:css` selector there are no extra filters defined beyond the 2 filters available on every selector type - text and visible (the count options aren't filters on a per element basis).  Since the text looks like it matches in the error message it would imply the element is not visible for some reason. 

Sure it would be possible to return the failing filter (failure is short-circuited for performance reasons so not every filter is necessarily applied).  It would require modifying the way Capybara::Result and  Capybara::Queries::SelectorQuery#matches_filters? work.  It may get complicated because the results are lazily evaluated for performance reasons, and we wouldn't give that up for a better error message.   If you want to give a PR a go we will definitely consider it.

**Comment by jjb** [comment]
@twalpole Thanks for your thorough reply. In my bare-bones setup, the test failure fails in the same way with `visible: false` and `visible: :all`. What should I do next to debug?

>It may get complicated because the results are lazily evaluated for performance reasons

right but at the point of failure, surely the filter which fails is easy to access?

**Comment by twalpole** [comment]
@jjb The filter which fails isn't saved though.  You need to remember that it might run through 20 elements applying filters that fail before finding an element that passes all the filters which can be returned, and then it may run through the next 20 elements to make sure there are no other elements that match all the filters so there is a unique result. 

As far as next steps, I just notice you say you're using chromedriver 2.27 - 2.29 is the current version so you probably want to update that if using the latest version of chrome.  Beyond that what does the relevant HTML actually look like?  Is CSS being applied to change the case of the text?

**Comment by jjb** [comment]
🤦‍♂️ 💩 🤦‍♂️ 💩 🤦‍♂️ 💩 

my source file was a sentence with two spaces after a period (e.g. `Foo.  Bar.`), but browsers collapse whitespace into a single space, so it was comparing it to `Foo. Bar.`.

The way the error message was structured, I thought it was telling me "we did find the text you were looking for" -- but really it was telling me "we did find an h1 node, and btw here's the text". So I was going crazy thinking that it matched the text but missed something else.

**Comment by twalpole** [comment]
@jjb  Sorry about the delay, I missed your response.  I'm not sure it's worth outputting the diff since the case you're having isn't really that common, and usually the found text in an error like that would be drastically different from the original.

**Comment by joelparkerhenderson** [comment]
Same error: two spaces in a row doesn't work. I agree with @jjb that an improvement to the error message could be a big help.

**Comment by twalpole** [comment]
@joelparkerhenderson PRs are all considered

**Comment by twalpole** [comment]
@joelparkerhenderson My personal view is that I don't think it's going to be worth the time/effort to create a useful error message for this that doesn't also just produce a bunch of spam output for other cases.  If you can come up with something and submit a PR, great -  but the current team isn't going to be working on it.

**Comment by joelparkerhenderson** [comment]
How much time/effort are you guessing?

I'm imagining something easy to start such as this pseudocode:

    def css_text_has_successive_spaces?(str)
      !!(str =~ /  /)
    end

    def css_text_has_successive_spaces!(str)
      !!(str =~ /  /) and warn(t(:css_text_has_successive_spaces))
    end

If you can give me any kind of approximate ballpark estimate for how long it would take you personally to write something that is a quality level you'll be happy to accept, then I can do a pro-bono request. Thanks for the info and discussion.

**Comment by twalpole** [comment]
I’m not willing to work on it.  I have never run into an issue in my own apps where I couldn’t tell why a text match failed with the current error messages and therefore don’t consider it a priority.  Someone who considers it a priority for them will need to implement a PR that doesn’t just end up creating more useless error output than useful.

**Comment by joelparkerhenderson** [comment]
Yes I understand. I'm asking you for a quick one-minute estimate of how long it could take an existing expert to implement the PR. The estimate enables me to ask for my own pro bono time i.e. I need to know a tiny bit about what's ahead to be able to allocate my pro bono time. Thanks again!
