### ISSUE TITLE
Capybara::Session.driver.switch_to_window(handle) results in UnknownError

### ISSUE THREAD

**Issue by ibaralf** [teamcapybara/capybara#1861]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

Driver Information (and browser if relevant):

## Expected Behavior
Returns object

## Actual Behavior
Error
Selenium::WebDriver::Error::UnknownError:
       unknown error: 'name' must be a string
         (Session info: chrome=57.0.2987.133)
         (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)

## Steps to reproduce

@cap_session = Capybara::Selenium::Driver.new(app, :browser => :chrome)
@webdriver = @cap_session.driver
@main_window = @webdriver.current_window_handle
Do some click to popup a window and get that window's handle
@webdriver.switch_to_window(new_popup_handle)

NOTE: It seems to have been reported a while back - https://github.com/Codeception/Codeception/issues/407

**Comment by twalpole** [comment]
I'm unclear as to what you're actually doing here.  The link you posted has nothing to do with Capybara, you're creating Capybara::Selenium::Driver instance and assigning it to variable named @cap_session (which one would assume would normally be an instance of Capybara::Session), and then calling all Selenium specific methods thereby completely bypassing Capybara.  If you have an issue with Selenium you should report it over there.

If you want to use Capybara instead you should be doing something like

    session = Capybara::Session.new(:selenium_chrome, rack_app) # rack_app can be nil if you're visiting an external url
    session.visit(...)
    new_window  = session.window_opened_by do
      session.click_link ...    #whatever action opens the new window
    end

    session.within_window(new_window) do
       #do whatever you want in the new window
    end

**Comment by ibaralf** [comment]
Thanks. That's what I ended up using. Before I was using just the ruby selenium gem and I thought this the Capybara::Session.driver would be returning me the same class as Selenium::WebDriver. No matter, the solution above works great.
