### ISSUE TITLE
Better feedback on near identical string matches

### ISSUE THREAD

**Issue by olivierlacan** [teamcapybara/capybara#1862]
This is a general issue I've encountered several times and has been a major source of frustration with myself (first) and Capybara (second).

If I ask Capybara to do the following:

```ruby
click_on "Let's get started"
```

It will fail with:

```
Capybara::ElementNotFound:
       Unable to find link or button "Let's get started"
```

Because:

```ruby
= link_to "Let’s get started", get_started_path
```

Did you catch it? If so good job: `’` vs `'`

Straight quote vs. proper typographical curly apostrophe. Using the handy levenshtein gem, you can easily see that the two strings (expect vs. actual) are as close as they can possibly be without being identical: 

```ruby
require "levenshtein"
=> false
Levenshtein.distance "Let’s get started", "Let's get started"
=> 1
``` 

Interestingly, `click_on "get started"` for `link_to "Let’s get started", get_started_path` works with `Capybara.match` set to `:smart`, but `click_on "Let's get started"` doesn't.

Unlike the case of multiple potential matches though, Capybara's smart matching seems to break down in this situation simply because of the `’` vs `'`. It feels like this is a missing or partially incomplete feature. I understand it's not an easy fix since it would involve messing with the matching algorithm.

**Comment by twalpole** [comment]
:smart matching is defined in the README - https://github.com/teamcapybara/capybara#strategy - and basically means  it will prefer a unique exact match to a unique partially matching element.   It has nothing to do with Capybara trying to decide when what the user has told it to do isn't exactly what it should do.  If the user wrote `click_on "user1"` but there's only a link/button with "user2", should Capybara click on the user2 ?  Of course not, but the Levenshtein distance is the same as your example. 

If you want to work on a PR that "fixes" your issue cleanly and works across all types of error conditions feel free, but I think it's going to be a lot of work for very small gain.

**Comment by olivierlacan** [comment]
I think you misunderstood me. I'm not talking about Capybara matching trying to infer what you mean when the expectation is close to the actual matcher.  

I'm talking about error feedback on matchers and finders.  

Right now there's virtually no difference between a 500 error causing a no match result and a one character difference that resulted in an imperfect match. This is very different from RSpec which does a lot of useful work to compare expectations to actual results.  

Of course with Capybara it's different, the whole page has to be scanned, not just the object under test, but in effect the whole page **is** the object under test, at least it's surface layer. I don't think it's a small gain to receive feedback from Capybara that would help identify mismatches. It would quite literally have save me and my entire team at Code School several months (in total) of wasted work due to bewildering failures.  

I've been a Capybara user for years and I believe I understand its philosophy with regards to feature testing yet I'm still regularly bitten by it's poor feedback mechanisms. Now that Capybara ships with Rails this will likely cause a lot of friction.  

This a very verbose attempt on my part to convince you of how important this is. I'll definitely take a crack at it, but I just wanted to make my point clearer since I don't want to push a feature if you don't believe in it.

**Comment by twalpole** [comment]
@olivierlacan If you can come up with better error messages that don't produce a massive amount of useless spam output, don't have race conditions (due to the retrying/waiting behavior) that end up saying `did you mean button "exactly what I initially specified"`, take into account that the text of elements isn't the only reason they might not match (there are lots of other potential filters) and don't add a ton of technical debt that will have to be dealt with going forward - I'm all for it

**Comment by olivierlacan** [comment]
That's fair. I don't expect it to be easy at all. Just adding 500 error detection (to report them instead of match/finder errors) was one of the nastiest hack I've ever done.

**Comment by twalpole** [comment]
Server errors should already be shown as long as you don't have any gems producing informative error pages installed in the test environment (web-console, better_errors, etc).  Rails used to include web-console in both development and test by default, but now only installs it in development, because it ends up hiding errors when installed in test.
