### ISSUE TITLE
has_select?() should support with_selected argument for symmetry with with_options

### ISSUE THREAD

**Issue by dwt** [teamcapybara/capybara#1865]
## Meta
Capybara Version: 2.10.1

## Expected Behavior
It should be easy to query wether a multi-select <select>-box has a specific selection as part of it's multi select.

## Actual Behavior
Actually that's surprisingly difficult.

## Steps to reproduce
Try to find out wether a particular <select> has a specific selection as part of it's selection. Then nearly despair once you find out that `with_options:` is actually supported, but `with_selected:` or something similar is not.

**Comment by twalpole** [comment]
Valid point, do you want to submit.a PR?  Also note that in your own code you can always add a new filter to any of the built-in sectors using `Capybara.modify_selector`

**Comment by dwt** [comment]
@twalpole I'd rather not submit a pr, as my ruby is not quite at production strength.

Oh, and thanks for the heads up with the modify_selector, I didn't know about that!

**Comment by twalpole** [comment]
@dwt Should be a relatively easy to thing to implement based off the current implementation of :select ed and :with_options.  If you have a chance it would be a good PR for a beginner rubyist to start with, If not I'll probably get around to it in a week or two.

**Comment by zatapathique** [comment]
Hey @twalpole, we are having the same issue in one of our projects so I'm willing to implement this feature :)

**Comment by twalpole** [comment]
@zatapathique Great

**Comment by twalpole** [comment]
@zatapathique Any update on this?

**Comment by zatapathique** [comment]
@twalpole I'm planning to implement this at the weekend.

**Comment by twalpole** [comment]
Closed via PR #1873
