### ISSUE TITLE
page.has_content? issue with regex

### ISSUE THREAD

**Issue by artemv** [teamcapybara/capybara#1869]
## Meta
Capybara Version:
2.8.1, 2.14.1

Driver Information (and browser if relevant):
selenium-webdriver 2.53.4

## Expected Behavior
page.has_content? with given regex (see below) should return true

## Actual Behavior
page.has_content? returns false

## Steps to reproduce
```
[1] pry> page.body
=> "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head></head><body><a href=\"\\&quot;/tests/1-test-yourself-2-705814/conversations/1\\&quot;\">\n  <b>Ivan Petroff</b>\n  concerning your participation in\n  <i>My Awesome Test</i>\n</a>\n</body></html>"
[2] pry> r = /concerning your participation in[\n|\s]+\<i\>My Awesome Test/m
=> /concerning your participation in[\n|\s]+\<i\>My Awesome Test/m
[3] pry> page.has_content? r
=> false
# wrong
[4] pry> page.body =~ r
=> 159
# allright
```

**Comment by twalpole** [comment]
has_content? Is an alias for has_text? and looks at the text of the page, it does not include element tags. This is behaving as expected
