### ISSUE TITLE
Stale element reference

### ISSUE THREAD

**Issue by davidmoseler** [teamcapybara/capybara#1871]
Hello. My problem is, in essence, that i have to choose between receiving a "stale element reference" error or receiving an "element not found" error because, if I do not use "syncronize", I get a stale element reference error, and, if I use syncronize, capybara does not wait for the element to load.

I am amazed by the confidence of capybara developers to just remove the wait_until method, guaranteeing that it was not needed because "find" already waits for the element to appear... Being it the fact that the find method waits sometimes, and sometimes don't. My code is as simples as it can get:

@@session.find("*.uiButtonConfirm").click
@@session.document.synchronize do
    @@session.should have_content("Messenger")
    a = @@session.find('span', text: 'Messenger')
end

If I do not use the synchronize method, I get an stale reference error. If I do use it, after clicking the button, capybara immediately stops, saying that no element with content "Messenger" was found; in other words, it does not wait one second for the page to load.

This makes it impossible to do even the simplest things using capybara without having a 50% chance 
failure. Documentation is also scarse and way-too-confident.

I'm using the latest version of capybara/rspec gem, with ruby 2.3.1 and firefox through selenium-webdriver.

The error when I do not use synchronize:

".rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': The element reference of <span> stale: either the element is no longer attached to the DOM or the page has been refreshed (Selenium::WebDriver::Error::StaleElementReferenceError)"

**Comment by davidmoseler** [comment]
Now I changed the code a little bit, to:

    @@session.all('div', text: 'Messenger', visible: false).should have_content("Messenger")
    a = @@session.all('div', text: 'Messenger', visible: false)

And I get

".rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>': expected #<Capybara::Result:0x0056266c10f548> to respond to `has_content?` (RSpec::Expectations::ExpectationNotMetError)"

After no waiting.

My opinion: capybara NEEDS to have the wait_until method back, because users should be able to decide when they want to wait for an element, and capybara just does not do it by itself.

**Comment by twalpole** [comment]
@davidmoseler You don't need `wait_until` if you use Capybara correctly, no matter how much you think/shout you do.  

1.  What is @@session ?
2.  What do you have `Capybara.default_max_wait_time` set to?
3.  Why are you doing have_content, and then finding the same element?  Just finding the element would also assure it's there
4.  Does the page already have the text "Messenger" on it before you click the confirm button?
3. Why are you calling the have_content matcher on the result of `all`?
4. What makes you think `all` should wait when the docs specifically say the only way to have all wait is by specifying a count ? - http://www.rubydoc.info/gems/capybara/Capybara/Node/Finders#all-instance_method 
5.   ...

**Comment by twalpole** [comment]
Also, if you actually want help with whatever issues you're having, post enough of the stacktraces that they actually show locations in Capybara, and indicate which line is actually raising the error.

**Comment by davidmoseler** [comment]
"1. What is @@session ?"
@@session = Capybara::Session.new(:selenium)
"2. What do you have Capybara.default_max_wait_time set to?"
Capybara.default_max_wait_time = 30
"3. Why are you doing have_content, and then finding the same element? Just finding the element would also assure it's there"
Yeah, but find wasn't waiting inside of a synchronize block, so I have tried adding an expectation. As the error code suggested, the expectation was not met.
"4. Does the page already have the text "Messenger" on it before you click the confirm button?"
No. But it exists right after. It is the "Messenger" button on facebook homepage.
"5. Why are you calling the have_content matcher on the result of all"
Sounds like I shouln't. Ok, I am honesty confused by the api, after so many random and inconsistent behaviours from different methods. The error I wrote here is only the tip of the iceberg.

I actually made it work, with the following code:

    @@session.document.synchronize do
      a = @@session.all('div', text: 'Messenger', visible: false, minimum: 1)
      a.last.click
    end

But I still get an ocasional "element reference is stale". Yeah, inside of synchronize! That is, this exact same code works sometimes, and sometimes don't.

Also, you commented on the second code I wrote, but the first didn't work also. After posting here, I replaced 'span' with 'div' in the first code, but nothing changed. If you pay attention, the only difference between it and the code I am running now is the "visible: false" clause. But the "Messenger" text is visible on facebook's home page. Why should I add a visible: false? Maybe I am missing something.

Well, but choosing a single conclusion: isn't the fact that I run the above code and get an ocasional "Stale element reference error" a bug in capybara?

**Comment by twalpole** [comment]
You shouldn't add `visible: false` unless you are looking for non-visible elements.  You also shouldn't be using synchronize since it disables waiting/retrying on everything inside it, and then retries it's own block multiple times - hence why you should only be using `synchronize` for complicated things.  Basically for your level of understanding of Capybara you should never be using synchronize manually.

The problem you're having is that there are many nested divs that all contain the text 'Messenger' and the results of all/first are non-reloadable so always prefer find.  There are many ways to scope the find to find a unique item -

1. scope it to a containing element

    find('.sideNavItem div', text: 'Messenger').click

2. Use a regex to find exact text

    find('div', text: /^Messenger$/).click

3.  Use the exact_text option to find exact text

    find('div', exact_text: 'Messenger').click
    find('div', text: 'Messenger', exact_text: true).click  # same as the previous just more verbose

**Comment by davidmoseler** [comment]
twalpole, thank you very much for your patience.

You are right about the nested divs. But I think the results I had when following your solutions maybe serve the purpose of showing how uncertain capybara can be.

-When I used both the "exact text" solutions, I received:

'"invalid keys :exact_text, should be one of :count, :minimum, :maximum, :between, :text, :visible, :exact, :match, :wait"'

-When I used the regex solution, I received a stale element reference error.

-The find('.sideNavItem div', text: 'Messenger') solution worked.

-On the other hand, my own solution that I mentioned above is working, and it does use a synchronize block and the "all" method waits nonetheless:

  def synchronize_and_try block
    begin
      @@session.document.synchronize do
        block.call
      end
    rescue => e
      p e.message
      puts "Retrying"
      retry
    end
  end

      find_messenger = lambda do
        a = @@session.all('div', text: 'Messenger', visible: false, minimum: 1)
        return a
      end
      a = synchronize_and_try find_messenger

That is, it does not disable waiting as you expected it to.

-Finally, the code above works 'if visible: false' is set, and does not find anything otherwise. And it is indeed not looking for something that is hidden in the html.

All of this makes me question even further if capybara's behaviour is what people expect it to be. I have found by means of actual testing that, given 5 beliefs that you've expressed concerning it's behaviour, only one was true!

**Comment by twalpole** [comment]
1. Since it's telling you `exact_text` is an invalid key, you're either not actually using the latest version of Capybara, or there's a bug - I'm inclined to lean towards the former, since it works in Capybaras tests and in the small test I just did, but am not ruling out the possibility of a bug.  

2.  regex solution giving stale element reference - It's caught by the synchronize internals and retried so without a reproducible example I have no idea what you're doing.

3. I don't know what that code block is trying to show me -  all waiting/retrying behavior on methods called inside the the block passed to synchronize is disabled,   however the whole block itself will be retried -  You can see that from the code - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/base.rb#L77 - if already inside a synchronize loop individual methods called do not have execptions caught - they all get caught at the outer synchronize level and the whole block is rerun

4.  visible: false   ---  Visibility is reported by selenium -- Without a reproducible example I have no way of confirming this or what you're actually doing

As far as only one of the things being right, I think if you check the version of Capybara you're actually using you'll probably find everything I told you is correct.

**Comment by davidmoseler** [comment]
twalpole,

Concerning the point 3 you've made, I got it now. It does make sense.

Concerning 1... I originally used only capybara, but then I had this problem and was told to start using expectations, and had to replace it for a "capybara/rspec" gem... In some part of this process I mixed up versions. My fault.

Concerning the other points, I am pasting the code for future reference and clarification.

    @@session = Capybara::Session.new(:selenium)
    Capybara.default_max_wait_time = 30
    @@session.visit("https://facebook.com")
    @@session.fill_in 'email', :with =>
    @@session.fill_in 'pass', :with =>
    @@session.find("*.uiButtonConfirm").click
    find_messenger = lambda do
      a = @@session.all('div', text: 'Messenger', visible: false, minimum: 1)
      return a
    end
    a = synchronize_and_try find_messenger
    a = @@session.find('.sideNavItem div', text: 'Messenger')

**Comment by twalpole** [comment]
One other thing I've noticed is the error that you posted 
".rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in block in <module:Support>': expected #<Capybara::Result:0x0056266c10f548> to respond tohas_content?` (RSpec::Expectations::ExpectationNotMetError)"

is actually coming from the RSpec have_xxxx built-in matcher, which would tend you indicate you probably havent actually followed the documentation and included the rspec matchers by requiring 'capybara/rspec' - https://github.com/teamcapybara/capybara#using-capybara-with-rspec   

I'm now 90% convinced at least 90% of your issues are user caused.

**Comment by davidmoseler** [comment]
I am actually requiring capybara/rspec!

    require 'capybara/rspec'

**Comment by twalpole** [comment]
Where are you requiring it, because they're not being loaded

**Comment by twalpole** [comment]
So I just took your code example - made it as simple as it should be, and ran it -  works just fine

```
require "capybara/dsl"
require "selenium-webdriver"

session = Capybara::Session.new(:selenium)
Capybara.default_max_wait_time = 30
session.visit("https://facebook.com")
session.fill_in 'email', :with => #put email here
session.fill_in 'pass', :with => #put password here
session.find("*.uiButtonConfirm").click
session.find('.sideNavItem div', text: 'Messenger').click
```

For any more help you're going to need to produce a reproducible example because I have zero clue what you're doing

**Comment by twalpole** [comment]
Ah - I know why you're not using the provided matchers, you're not actually writing tests, you're using Capybara as part of your app aren't you ?  The matchers are by default only included into feature tests -- you will need to include Capybara::RSpecMatchers  into whatever class you're running your Capybara code in for them to be used.

**Comment by davidmoseler** [comment]
Yes, I had to include the matchers:

  include RSpec::Matchers

But I think maybe I got it now. I was requiring capybara twice:

require 'capybara/rspec'
require 'rspec/expectations'
require 'capybara'
require 'unobservable'
require 'json'

I will see if the problems stop ocurring.

My original problem was that "find" was not waiting even a second for page loading, and, trying to solve this, I ran through tutorials and installed rspec to try to enforce waiting. But things got more and more confusing, probably in part because of this double capybara requiring. I regret not having the code of the original problem anymore, since it was something like one month ago. But I have really tried many different settings, and "find", in a specific situation was for some reason not waiting anything, even with default_max_time setting to 30 seconds. It was odd, because, changing the text from "Messenger" to something else, it did work, but with the text "Messenger" it returned an "element not found" kind of error the same instant the button was clicked, that is, before the page even started working. 

Ah, and most importantly: the code worked perfectly fine with the inclusion of a "sleep". It was sleep followed by find. And if I took the sleep off, it broke. I've lost this sample code though.

But, in essence, the thing with the old wait_until method is that I think some redundancy is good sometimes. Because, if things do not work as expected, that is, if for some reason a method does not wait when it should, then the user has this resource at his disposition.

**Comment by davidmoseler** [comment]
About the code working fine, it does work fine with session.find('.sideNavItem div', text: 'Messenger').click. It also works fine the way I wrote it above, with the "synchronize_and_try" method. These are the two solutions that actually worked for me.

**Comment by twalpole** [comment]
It works fine with the `exact_text` options too if you're using the latest version of Capybara.
You should never require 'capybara' (hence why it's not mentioned in the readme to require it), you may sometimes need to require 'capybara/dsl' , although in your case requiring 'capybara/rspec' requires the rest of them

**Comment by davidmoseler** [comment]
I was just having problems with another old script. I changed from "capybara" to "capybara/dsl" and it worked instantly. Thank you very much. I think many problems I had actually came from this "require 'capybara'"
