### ISSUE TITLE
Feature request: Preserve caller when server error occurs

### ISSUE THREAD

**Issue by Fjan** [teamcapybara/capybara#1872]
When a test encounters a server error Capybara re-raises the error (assuming raise_server_errors is true) to pass it to the test frame work. However, in doing so the line number of the test that triggered the error gets lost along the way and this is interesting information to display to the user.

It would be a very simple addition to store the caller in an instance variable just before re-raising, so that the error reporter can then get it from ```Capybara.current_session.error_caller```

Please let me know if you agree and if you would like me to create a PR.

**Comment by twalpole** [comment]
I don't think this is as simple as you believe.  Server errors can occur asynchronously, and Capybara checks for them before each visit, before waiting/retrying on any method which triggers a wait/retry, and when `reset!` is called (usually at the end of each test).  This means the actual test line being executed may not actually be the one that triggered the server error (and in the case of tests using multiple sessions with a shared app server may not actually be from the test that raises it).  This could lead to reporting completely incorrect lines and misdirecting the user which would be worse than the current state.

**Comment by Fjan** [comment]
Thanks for the quick reply. I agree that care needs to be taken on how the information is presented because of the issues you mention.

I actually have this running monkey patched into Capybara for several months now, together with a patched minitest reporter, and while it is true that the line number is off by a little bit if an error occurs during an Ajax request, that is still quite useful information to have. Previously we had to put a bunch of log statements in the test to zoom in on the problem. Also, an inaccurate line number is good enough to show a "replay" command in the test reporter, because it will need to start at the top of the method anyway. (Almost all of our tests are single session so I haven't encountered it being in the wrong file, thanks for alerting me to that possibility).

Anyway, I can live with this being a monkey path for us, so if you feel the provisos about the accuracy make sharing this more trouble than it's worth then I'll close this for now.

**Comment by twalpole** [comment]
@Fjan Thanks for understanding. As it is we have a lot of beginner developers who don't read the docs before insisting something isn't working correctly (when it is), I think adding a line number that is possibly not correct cound make that issue even worse.

**Comment by Fjan** [comment]
Ok, as you wish. As least one dev I know was puzzled about "why is there no line number on some errors?", so those have to be weighed against the ones who are confused by having an estimate. Perhaps we could address it by naming the accessor "approximate_error_caller" or something.
