### ISSUE TITLE
StaleElementReferenceError when using matcher with `visible: false`

### ISSUE THREAD

**Issue by aaronjensen** [teamcapybara/capybara#1874]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 2.14.0

Driver Information (and browser if relevant): selenium-webdriver 3.4.0 with Chrome Canary

## Expected Behavior

```
    expect(page).to have_css('div.list', text: /#{list.name}.*#{card_regex(card)}/, visible: false)
```

Would not ever throw `Selenium::WebDriver::Error::StaleElementReferenceError`

```
Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: headless chrome=60.0.3100.0)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-108-generic x86_64)
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:678:in `raw_execute'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:656:in `execute'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/bridge.rb:604:in `element_displayed?'
./bundle/ruby/2.4.0/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/element.rb:201:in `displayed?'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/selenium/node.rb:143:in `visible?'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/node/element.rb:269:in `block in visible?'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/node/base.rb:85:in `synchronize'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/node/element.rb:269:in `visible?'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/queries/selector_query.rb:80:in `matches_filters?'
./bundle/ruby/2.4.0/gems/capybara-2.14.0/lib/capybara/result.rb:29:in `block in initialize'
```

## Actual Behavior

It throws if the `div.list` is removed from the dom in between the time that the element is captured and its visibility is checked.

## Steps to reproduce

No easy repro yet, if necessary I can probably put one together, but it'll take some time.

**Comment by twalpole** [comment]
Please try the master branch

**Comment by twalpole** [comment]
@aaronjensen  Also, do you have any more length on that stack trace, I'd like to see it back to the `have_css` call if possible.

**Comment by aaronjensen** [comment]
Unfortunately that's all I have. Is there a limit imposed by something?

**Comment by twalpole** [comment]
@aaronjensen I don't know where what the config for that is, probably an IRB config - but it's probably easier to just rescue the exception and then have access to the full trace.  

One last thing, are you sure the expectation you posted above is the one that generated that stack trace because, off the top of my head, I don't think it should be calling `visible?` with the `visible: false` set (it would probably still raise the same error on the text check though)

**Comment by aaronjensen** [comment]
> One last thing, are you sure the expectation you posted above is the one that generated that stack trace because, off the top of my head, I don't think it should be calling visible? with the visible: false set (it would probably still raise the same error on the text check though)

I can't say I'm 100% sure as it is hard for me to repro w/ my test suite locally. It only happens on CI and only occasionally. It is the only place that we're checking visibility afaict in this test.

**Comment by twalpole** [comment]
@aaronjensen - All Capybara finds check visibility by default, when  `visible: false` is specified it shouldn't test visibility at all since that means visible or not.  If you're trying to verify that the element is present but non-visible then you want `visible: :hidden`

**Comment by aaronjensen** [comment]
ah. In that case it could be anything in my test. Are there fixes in master for scenarios like this? I can try running with that for a while and see if it helps.

**Comment by twalpole** [comment]
@aaronjensen There is a change in master that catches invalid element errors during the filtering by matches_filters -- It would affect this if this was actually coming from iterating the results returned from an `all` call -- I don't think it would affect this if your error was actually from a `have_css` call because it should already be catching that error.

**Comment by aaronjensen** [comment]
This test does have:

```
      list_cards = page.all('.list-card-title').map{|card| card.text}
```

**Comment by aaronjensen** [comment]
(and that is within a `within`)

I remember from long ago there was a setting that controlled out `within` worked, whether or not it requeried on each wait loop. Is there still such an option?

**Comment by twalpole** [comment]
@aaronjensen If that's where your error is coming from, it could affect it -- The error should tell you what line it was on.

**Comment by twalpole** [comment]
There is no setting that affects `within` specifically.  There is the `allow_reload` setting on elements, but you really shouldn't need to be playing with that, it's more for internal record keeping based on how the element was located.

**Comment by twalpole** [comment]
@aaronjensen Did master fix your issue?

**Comment by aaronjensen** [comment]
I ran the tests several times and got no failures, so that's a good sign. I'll run w/ master for now and if it crops up again I'll debug further. Thank you for your help.
