### ISSUE TITLE
missing exception message causes TypeError

### ISSUE THREAD

**Issue by staugaard** [teamcapybara/capybara#1879]
Missing error messages cause internal exception.

```
TypeError:         TypeError: exception class/object expected
            vendor/bundle/ruby/2.3.0/gems/capybara-2.14.2/lib/capybara/minitest.rb:91:in `raise'
            vendor/bundle/ruby/2.3.0/gems/capybara-2.14.2/lib/capybara/minitest.rb:91:in `rescue in assert_no_selector'
            vendor/bundle/ruby/2.3.0/gems/capybara-2.14.2/lib/capybara/minitest.rb:87:in `assert_no_selector'
            vendor/bundle/ruby/2.3.0/gems/capybara-2.14.2/lib/capybara/minitest/spec.rb:26:in `wont_have_selector'
            vendor/bundle/ruby/2.3.0/gems/capybara-2.14.2/lib/capybara/minitest/spec.rb:20:in `wont_have_selector'
            test/integration/ticket_part_2_test.rb:70:in `block (2 levels) in <class:TicketIntegrationTest>'
```

## Meta
Capybara Version:
2.14.2
Driver Information (and browser if relevant):
selenium-webdriver 3.4.0 with chromedriver 2.30 on Chrome 59.0.3071 on Travis CI

## Expected Behavior
I expect a Minitest::Assertions to raise

## Actual Behavior

The call to `raise ::Minitest::Assertions, e.message` passes nil as the message, and we get a `TypeError`

## Steps to reproduce
I wish I knew. I have not been able to reproduce this locally on OSX, but it happens almost every time in this specific test on travis CI

**Comment by twalpole** [comment]
What are you passing to `wont_have_selector`?   I'm not clear on how it's even possible for `e.message` to be nil

**Comment by twalpole** [comment]
Ummm, actually -- shouldn't that be raising a Minitest::Assertion  not (s) -- how the hell have my tests been passing

**Comment by staugaard** [comment]
the call I'm making is:
```ruby
page.wont_have_selector '.label.solved', text: 'Done'
```

**Comment by twalpole** [comment]
@staugaard   Could you please try the `minitest_assertions` branch and see if that fixes the issue for you.  It didn't have anything to do with the message, it was raising `::Minitest::Assertions` (which is a module) rather than `::Minitest::Assertion`.  Unfortunately I wasn't actually testing failures in the minitest tests previously, I'm amazed this hasn't been reported before.

**Comment by staugaard** [comment]
Wow yeah that is crazy. I've made a PR switching to your branch, but travis is having issues for private repos right now. I'll update you when it runs.

**Comment by twalpole** [comment]
@staugaard No problem, it's definitely wrong the way it was so I'm going to merge it into master as soon as Capybara's tests pass on that branch, and will go into 2.14.3 as soon as selenium-webdriver 2.4.2 releases so the tests for that fix can be run too.

**Comment by twalpole** [comment]
Should be fixed via 21844c783c46febff0a6bc14f440f1cc8d3d7fab

**Comment by sebroeder** [comment]
Thank you for this fix. It took me one day to find out why the new System Tests in Rails 5.1.x (using the default stack of Minitest + Capybara) swallow the Capybara error messages when test fail.

For example this is the output of a failed System Test with Rails 5.1.1 and Capybara 2.14.1:

```
Error:
UserViewsPublicationsList#test_it_shows_the_correct_heading:
TypeError: exception class/object expected
    test/system/user_views_publications_list_test.rb:14:in `block in <class:UserViewsPublicationsList>'
```

After updating to Capybara 2.14.3 the failure output makes sense again:

```
Failure:
UserViewsPublicationsList#test_it_shows_the_correct_heading [/Users/sebroeder/Developer/public/sebroeder/kerndatensatz-forschung-rails/test/system/user_views_publications_list_test.rb:14]:
expected to find css "h1" with text "This heading is not on the page" but there were no matches.
```

**Comment by twalpole** [comment]
@sebroeder  You're welcome, as I stated above I was a little shocked it hadn't been reported as an issue sooner.
