### ISSUE TITLE
Rails 5.1.2 breaks headless Chrome mode

### ISSUE THREAD

**Issue by mrreynolds** [teamcapybara/capybara#1887]
## Meta
Capybara Version:
2.14.4
Driver Information (and browser if relevant):
selenium-webdriver 3.4.3 with Chrome 59 headless, chromedriver 2.30.477690 (via homebrew)

## Expected Behavior
System tests run normally.

## Actual Behavior
System tests fail with an error. Downgrading to Rails 5.1.1 helps.

```
rails test:system
Run options: --seed 41398

# Running:

E

Error:
FooTest#test_visiting_root:
NoMethodError: undefined method `needs_server?' for nil:NilClass
    test/system/foo_test.rb:5:in `block in <class:FooTest>'

Error:
FooTest#test_visiting_root:
NoMethodError: undefined method `needs_server?' for nil:NilClass
```

## Steps to reproduce
    git clone git@github.com:innoq/rails-headless-chrome-capybara.git
    bundle
    rails db:setup db:migrate
    rails test:system

**Comment by twalpole** [comment]
It's a Rails issue - https://github.com/rails/rails/issues/29688 - that they've already fixed -- not sure when it will be released, not much Capybara can do about it.
