### ISSUE TITLE
Error for filling_in disabled field is misleading

### ISSUE THREAD

**Issue by gerrywastaken** [teamcapybara/capybara#1891]
It tells you it can't find the field, when really the field is there, but it just happened to be disabled at the time. Debugging this is tricky when when dealing with a react component where the disabled state is so brief that you didn't even know it existed. I'm sure there are many other cases of this. It would be great if capybara told me what the real issue was.

## Meta
Capybara Version:
2.14.0

## Expected Behavior

"Field <selector_used> was disabled so could not be filled in"

OR (less ideal but still a LOT better)

"Unable to find field <selector_used>. It could be disabled or hidden."

## Actual Behavior

"Unable to find field <selector_used>"

## Steps to reproduce

```html
<input type="input" id="foo" disabled />
```

```ruby
fill_in('foo', with: 123)
```

Thank you for all your work btw. I love Capybara. :)

**Comment by twalpole** [comment]
PRs are gladly considered - although it gets really tricky to generate a comprehensive error message when custom filters can be added to any selector (just a warning before you attempt a PR)

**Comment by twalpole** [comment]
@gerrywastaken One relatively easy thing that can be done is to ensure selector filters that have default options are considered in the error description.  Please try the WIP f`filter_error_messages` branch and see if that's better for you.

**Comment by gerrywastaken** [comment]
@twalpole sorry that I have not come back to this issue till now. Thank you so much for this:
https://github.com/teamcapybara/capybara/pull/1892/files

I'm sure it will not just help me but also many others. You are awesome. :)
