### ISSUE TITLE
Capybara + Chromedriver, different behavior with headless tag

### ISSUE THREAD

**Issue by Maxxillo** [teamcapybara/capybara#1893]
hello, 

I found out a different behavior using capybara + chromedriver in headless mode is behaving differently than capybara + chromedriver without headless mode

## Meta
Capybara Version:
capybara 2.14.x
selenium-webdriver 3.4.4
chrome 59 (with tag '--headless')

## Expected Behavior
The recaptcha checkbox is found and clicked

## Actual Behavior
The recaptcha checkbox is not found

## Steps to reproduce
```
page.visit('https://www.google.com/recaptcha/api2/demo')
page.within_frame(page.find('#recaptcha-demo iframe')) do
  page.find('.recaptcha-checkbox-checkmark').click
end
```

Hope that are enough details of the issue (maybe related to: [https://github.com/teamcapybara/capybara/issues/1860](url) )

**Comment by twalpole** [comment]
If you take a look at the visible text of the frame  (`puts page.text` inside the frame) when running in headless mode you'll see

    Please upgrade to a supported browser to get a reCAPTCHA challenge. Alternatively if you think you are getting this page in error, please check your internet connection and reload.

It's not Capybara + chrome driver behaving differently, it's the reCAPTCHA code detecting that Chrome is running in headless mode and not supporting it.

**Comment by Maxxillo** [comment]
I did not saw that !! thank you 👍
