### ISSUE TITLE
browser: :remote with headless chrome options ArgumentError - configuration parity issue?

### ISSUE THREAD

**Issue by rosskevin** [teamcapybara/capybara#1909]
## Context
Following @twalpole's reference to the spec in https://github.com/teamcapybara/capybara/issues/1860#issuecomment-305347221, I tried setting up a remote execution and it failed with invalid options.

Locally, I have it working with the spec configuration:

```ruby
Capybara.register_driver :selenium do |app|
  options = ::Selenium::WebDriver::Chrome::Options.new()
  options.args << 'headless'
  Capybara::Selenium::Driver.new(
    app,
    {
      options: options,
      browser: :chrome,
    }
  )
end
```

## Meta
Capybara Version: 2.15.1
Driver Information (and browser if relevant):
- selenium/standalone-chrome-debug:3.5.2 
- chrome 60.0.3112.113 (Official Build) (64-bit)
- selenium-webdriver 3.5.1

## Expected Behavior
Options used in chrome local may be use in chrome remote

## Actual Behavior
```
ArgumentError: unknown option: {:options=>#<Selenium::WebDriver::Chrome::Options:0x007fc84be1ebd0 @args=["headless"], @binary=nil, @prefs={}, @extensions=[], @options={}, @emulation={}, @encoded_extensions=[]>}
```

## Steps to reproduce

```ruby
Capybara.register_driver :selenium do |app|
  options = ::Selenium::WebDriver::Chrome::Options.new()
  options.args << 'headless'
  Capybara::Selenium::Driver.new(
    app,
    {
      options: options,
      browser: :remote,
      url: 'http://127.0.0.1:4444/wd/hub'
    }
  )
end
```

## Rationale
I'm trying to get `selenium/standalone-chrome-debug` to work in headless mode, which I have failed miserably.  I wanted to fallback to a known-good configuration, then work forward.  Here I am with a known good configuration locally but that is rejected for remote use.

**Comment by twalpole** [comment]
This really is a Selenium issue - Capybara basically just passes the options through to Selenium, and it defines what are and are not acceptable configuration options for itself.

**Comment by twalpole** [comment]
Note: the one thing here that may be an issue in Capybara, is needing to detect when Chrome is being used remotely in headless mode.  If you come up with a Selenium allowed Chrome headless remote config that isn't being detected as headless by Capybara (alert/confirm/prompt don't work) please post that config in a separate issue and we'll try and updated Capybaras headless detection to match it.
