### ISSUE TITLE
[Feature Request] Make Capybara::Queries::CurrentPathQuery More Robust

### ISSUE THREAD

**Issue by mvastola** [teamcapybara/capybara#1919]
So I have a request for a feature (which I am happy to make a PR for) but I thought I would make an issue for it first because I'm not sure which would be the preferred way to implement it. This is because it would seem the simplest and most intuitive implementation would require a breaking change.

Basically, (and I can go into my specific use case if necessary) rather than simply choosing between `:url` (all URI components), `:only_path` and the implied default (the path *and* querystring components of the URI), I think it should be possible to specify exactly which URI components one does (or does not) wish to compare using `Capybara::Queries::CurrentPathQuery`.

If I were to implement this cleanly, I would probably ditch the currentl `:url` and `:only_path` options and just have two options for `:only` and `:except` which each can take an array of components. From there, the comparison is as simple as:

```ruby
actual_uri = Addressable::URI.parse(actual_url)
expected_uri = Addressable::URI.parse(expected_url)
expected_uri.omit(@skipped_components) == actual_uri.omit(@skipped_components)
```

.. however this obviously constitutes a breaking change. What would be the best way to implement this in a PR?

**Comment by twalpole** [comment]
Breaking change on this is a big issue.  See https://github.com/teamcapybara/capybara/pull/1881 which is the direction it's currently planned to go towards, but hasn't yet been merged due to backwards breaking issues.  What is your use case for needing to deal with more than just url, path, and query options ?

**Comment by mvastola** [comment]
D'oh. Figures it's one of the 7 PRs already open. :-p
Yeah, I just need to be able to ignore the querystring, but I have a multi-subdomain site so I want to check I'm at the subdomain corresponding to my single-sign on portal, but the query will never match because it contains encrypted/hashed session info.

**Comment by mvastola** [comment]
If you'd like to close this and count me as a second for that PR, I'd be happy with that.

**Comment by twalpole** [comment]
@mvastola Yeah - I think that will do what you want, also note that you can get that behavior today using a regex too   `expect(page).to have_current_path(url: true, regex_to_match_beginning_url)`

**Comment by mvastola** [comment]
Yup. That regex is exactly what I'm doing now. Thanks!

**Comment by twalpole** [comment]
@mvastola The PR mentioned here is now in master (will most likely be part of 2.16) if you want to give it a try

**Comment by mvastola** [comment]
Oh. Great. Thanks for the heads up!
