### ISSUE TITLE
Checkbox clickable only via JS in :selenium_chrome_headless

### ISSUE THREAD

**Issue by texpert** [teamcapybara/capybara#1930]
Capybara Version: 2.15.4

Driver Information and browser: 

selenium-webdriver 3.6.0 with Chrome 62.0.3202.62, Chrome driver 2.33

## Expected Behavior
Checkbox should be checkable either by 
`check 'confirmation_terms_agreement'`
, or by 
`find(:label, for: 'confirmation_terms_agreement').click`

## Actual Behavior
I could click it in :selenium_chrome_headless only by:
`page.execute_script("document.getElementById('confirmation_terms_agreement').click()")`

## Steps to reproduce

The actual HTML (generated by Rails) is:
```
<fieldset>
    # some fields
    <div class="form-group boolean optional confirmation_terms_agreement">
        <div class="checkbox">
            <input name="confirmation[terms_agreement]" type="hidden" value="0" />
            <input class="boolean optional" type="checkbox" value="1" name="confirmation[terms_agreement]"
                   id="confirmation_terms_agreement" />
            <label class="boolean optional" for="confirmation_terms_agreement">
                "Some text "<a class="js-new-window" href="/somedatalink">Data</a>
                ". Some text "
                <a class="js-new-window" href="/agreementrules">
                    Some text</a>.
            </label>
        </div>
    </div>
    # some fileds
</fieldset>
```

**Comment by twalpole** [comment]
What error do you get with `check 'confirmation_terms_agreement'` ?

**Comment by texpert** [comment]
The checkbox is visible and no error is returned. As a result of the checkbox being clicked, a `Continue` button should be enabled, but it isn't.

Both usual methods are working OK in full-head :selenium_chrome.

**Comment by twalpole** [comment]
So you don't get an error, just clicking it doesn't do what you expect?

**Comment by texpert** [comment]
Exactly, but the JS click works as expected.

**Comment by twalpole** [comment]
Sounds like an issue with the chrome/chromedriver combo you're using and/or a timing issue of when the behaviors are bound to the checkboxes.  After the `check` command is run is the checkbox checked? `expect(page).to have_checked_field('confirmation_terms_agreement')` if using RSpec.

**Comment by texpert** [comment]
No timing issue - I have tried some sleeps in between with no luck. Will double-check it tomorrow, though, as well as I'll check the RSpec expectation.

Thanks for great product and prompt replies!

**Comment by twalpole** [comment]
@texpert Note -- we do have a test suite that tests checking of checkboxes, and is run with headless chrome and passes on Travis.  So if it's not a timing issue, then it could very well be a bug in headless chrome/chromedriver  dependent on which event you are triggering on.

**Comment by texpert** [comment]
@twalpole , not a timing issue - just have checked it once more.

Also, `expect(page).to have_checked_field('confirmation_terms_agreement')` is giving the error, both on headless and full-head :selenium_chrome:

```
js_driver: selenium_chrome_headless: expected to find visible field "confirmation_terms_agreement" that is checked and not disabled but there were no matches. Also found "", which matched the selector but not all filters.
```

**Comment by twalpole** [comment]
@texpert then you’ll need to provide a way to replicate since it works fine in the tests and I can’t replicate this issue.

**Comment by texpert** [comment]
Used JS to finish the specs.

Unfortunately, couldn't clone the page - NDA and too much work to impersonate it with random data. So, closing the issue.

Thanks for help, @twalpole !

**Comment by twalpole** [comment]
Ok, as long as you realize you aren’t actually testing the page since calling the click handler directly is not the same as using the page. You might as well just mark the test as `skip`.
