### ISSUE TITLE
ArgumentError: unknown option: for :binary

### ISSUE THREAD

**Issue by iamdriz** [teamcapybara/capybara#1931]
Apologies if this the wrong place to raise this!

Capybara version: 2.15.4
Selenium WebDriver version: 3.6.0

In short I am trying to change the location of the binary used by the driver as I have IT restrictions in place that prevent me from updating or installing applications in the default `~/Applications` folder. I am using Mac OS if that wasn't apparent.

So I have installed the latest version of Chrome (Version 62.0.3202.62 (Official Build) (64-bit)) and the ChromeDriver (2.33) and I want to make Capybara use this version of Chrome. That is installed at `~/Applications (local)/Google Chrome.app`

I have the following code in the `application_system_test_case.rb` file in my Rails app:
~~~
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome, screen_size: [800, 600], options: {
      :binary => '~/Applications (local)/Google Chrome.app/Contents/MacOS/Google Chrome'
  }
end
~~~

And I get the error:

`ArgumentError: unknown option: {:binary=>"~/Applications (local)/Google Chrome.app/Contents/MacOS/Google Chrome"}`

Why am I getting this error? And what's the correct way to specify the binary location for the driver if I can't use the default location.

**Comment by twalpole** [comment]
What makes you think there should be a `:binary` option?  You need to pass valid for Selenium options, or configure Selenium separately.

**Comment by iamdriz** [comment]
I was told that when you specify chrome as the driver that options works the same as chromeOptions which takes a binary parameter.

In any case how do I specify the binary location for the driver?

Thanks
