### ISSUE TITLE
Can't call `respond_to?` on `ConfigDeprecator`/`Capybara::Config`

### ISSUE THREAD

**Issue by betterment-ash** [teamcapybara/capybara#1935]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
2.15.4
Driver Information (and browser if relevant):
N/A

We have some configuration shared between different applications that may use different version of Capybara, so we sometimes ask the `config` yielded to the `Capybara.configure` block what it `responds_to?`. We recently upgraded and this behavior has stopped working.

## Expected Behavior
Should be able to call `respond_to?`
## Actual Behavior
Cannot call `respond_to?`
## Steps to reproduce

```
irb(main):001:0> require 'capybara'
=> true
irb(main):002:0> Capybara::VERSION
=> "2.15.4"
irb(main):003:0> Capybara.configure {|c| c.respond_to?(:anything?) }
NoMethodError: private method `respond_to_missing?' called for #<Capybara::Config:0x00007f95d48c5ef8>
Did you mean?  respond_to?
	from /.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/capybara-2.15.4/lib/capybara/config.rb:128:in `respond_to_missing?'
	from (irb):3:in `respond_to?'
	from (irb):3:in `block in irb_binding'
	from /.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/capybara-2.15.4/lib/capybara.rb:97:in `configure'
	from (irb):3
	from /.rbenv/versions/2.4.2/bin/irb:11:in `<main>'
```

######
From a brief investigation, I think the solution is to not use `respond_to_missing?` directly in `ConfigDeprecator#respond_to_missing?`, but not sure.

`capybara-2.15.4/lib/capybara/config.rb:127`
```
def respond_to_missing?(m, include_private = false)
  @config.respond_to_missing?(m, include_private) || Capybara.respond_to_missing?(m, include_private)
end
```

**Comment by twalpole** [comment]
Yeah -- this should be calling `respond_to?` rather than `respond_to_missing?`- Fixed via 52e2619111b99006a4ef8326c338675addfd092f . 

Thanks
