### ISSUE TITLE
Errors/problems generating docs with YARD (Markdown)

### ISSUE THREAD

**Issue by rlue** [teamcapybara/capybara#1936]
## Meta

* Capybara Version: 2.14.1 & 2.15.1 (haven't tried any others)
* YARD Version: 0.9.9 (latest)

## Expected Behavior

1. Run `yard server -g`
2. Visit http://localhost:8808/docs/capybara
3. See docs identical to those at http://www.rubydoc.info/github/teamcapybara/capybara

## Actual Behavior

1. Code samples are not rendered accurately:

   **on rubydoc.info**

   ![screen shot 2017-11-15 at 5 50 31 pm](https://user-images.githubusercontent.com/12194123/32829643-a07d6b18-ca2d-11e7-8265-4f3d17e75ad3.png)

   **on localhost**

   ![screen shot 2017-11-15 at 5 50 18 pm](https://user-images.githubusercontent.com/12194123/32829664-af1ceaea-ca2d-11e7-8dc9-537b4d3f789f.png)

2. YARD throws errors related to parsing `README.md` as docs are being generated:

   ```
   $ yard server -g
   >> YARD 0.9.9 documentation server at http://localhost:8808
   Puma starting in single mode...
   * Version 3.10.0 (ruby 2.4.0-p0), codename: Russell's Teapot
   * Min threads: 0, max threads: 16
   * Environment: development
   * Listening on tcp://0.0.0.0:8808
   Use Ctrl-C to stop
   [warn]: in YARD::Handlers::Ruby::AttributeHandler: Undocumentable OPTIONS
           in file 'lib/capybara/session/config.rb':11:
   
           11: attr_accessor(*OPTIONS)
   
   [warn]: In file `/Users/rlue/.gem/ruby/2.4.0/gems/capybara-2.14.4/README.md':964: Cannot resolve link to num from text:
           ...{num}...
   [warn]: In file `/Users/rlue/.gem/ruby/2.4.0/gems/capybara-2.14.4/README.md':968: Cannot resolve link to type from text:
           ...{type}...
   [warn]: In file `/Users/rlue/.gem/ruby/2.4.0/gems/capybara-2.14.4/README.md':964: Cannot resolve link to num from text:
           ...{num}...
   [warn]: In file `/Users/rlue/.gem/ruby/2.4.0/gems/capybara-2.14.4/README.md':968: Cannot resolve link to type from text:
           ...{type}...
   ```

**Comment by twalpole** [comment]
Please try the latest release - https://github.com/teamcapybara/capybara/pull/1933/commits/07af41f7cb9578deb87ddc338771293f79f9fb8e was merged into that which may affect this.

**Comment by rlue** [comment]
Embarrassingly enough, it appears that something may have been wrong with my capybara installations altogether — uninstalling and reinstalling did the trick, for previous releases and for 2.16.0.
