### ISSUE TITLE
Can not input string '3' with fill_in, sen

### ISSUE THREAD

**Issue by mappuj1** [teamcapybara/capybara#1938]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
**Capybara Version:**
2.10.1
**Driver Information (and browser if relevant):**
selenium-webdriver 3.0.4 with Chrome 62.0.3202.94

## Expected Behavior
Try 
```
fill_in 'phone_number', with: '0987654321'
```

Got
```
0987654321
```

Try
```
find_field('phone_number').send_keys '0987654321'
```

Got
```
0987654321
```

Try
```
find_field('phone_number').set '0987654321'
```

Got
```
0987654321
```

## Actual Behavior
Try 
```
fill_in 'phone_number', with: '0987654321'
```

Got
```
098765421
```

Try
```
find_field('phone_number').send_keys '0987654321'
```

Got
```
098765421
```

Try
```
find_field('phone_number').set '0987654321'
```

Got
```
098765421
```

## Steps to reproduce
Try to do above experiment with capybara version, and chrome version above.

## Workaround

I tried to downgrade the Chrome version to version 61 and it works. I think Google try to filter string '3' somehow.

**Comment by twalpole** [comment]
Odds are you haven't updated to the latest`chromedriver` when updating Chrome, however either way this is a `chromedriver` issue not a Capybara issue.

**Comment by mappuji** [comment]
Thank you

**Comment by mappuj1** [comment]
updating the chromedriver to latest 2.33 not soling the problem 😭

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/2b9852cbbe01dc6b14916283398fceb2   That code runs fine for me.  I just read the actual versions of things you are using.  Capybara 2.10.1 is over a year old, and selenium-webdriver is nearly a year old.  Expecting them to work with modern browser versions is unrealistic.  Keep your testing tools up to date.

**Comment by mappuji** [comment]
Just updated to 2.16.1 and nothing happens. No change in result for that case.

BTW, thank you for reminding me to update the tools.

**Comment by FLemon** [comment]
had the same problem, when fill_in with string contains `@`, the browser opens a new tab to `chrome:://settings`

**Comment by twalpole** [comment]
@FLemon A reproducible example would be needed to troubleshoot that.  If you take the gist posted above and change the text being sent to include an '@' it works fine, so there is something other than just having '@' in the `fill_in` string.  If you can provide a reproducible example please open a new issue with instructions on how to replicate.
