### ISSUE TITLE
Provide error message upon clicking link that contains invalid HTML

### ISSUE THREAD

**Issue by nwshane** [teamcapybara/capybara#1939]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 2.16.0

## Actual Behavior

Clicking on a link that contains block styled elements fails silently. 

## Expected Behavior

It'd be nice if the click methods (`click_link`, `click_on`, etc.) would provide a useful error message when the link they are targeting contains invalid HTML.

## To reproduce:

Capybara:
```ruby
click_on("link")
```

HTML:
```html
<a id="link" href="https://example.com">
  <h3>Invalid heading within link</h3>
</a>

OR

<a style="display: block;" id="link" href="https://example.com">
  invalid display: block; style
</a>
```

**Comment by twalpole** [comment]
Capybara does not (and is not going to start) validate HTML.  On top of that neither of the examples you've given are actually invalid - `<a>` elements may contain 'flow content' (which `<h3>` is) or 'phrasing content', and it's never invalid to put any legitimate CSS display style on any element.

**Comment by nwshane** [comment]
@twalpole Okay, thanks for the explanation - and sorry for the bad examples. I had some trouble with these two links earlier, so I assumed (wrongly) that the trouble I was having was because they were invalid. If I have time I'll take a look at them and try to figure out the real reason they were failing.

I love capybara by the way, thanks for all your good work on it!

**Comment by twalpole** [comment]
@nwshane You're welcome. If you do find the failure are actual issues with Capybara, please try and provide a small reproducible example and we'll get it fixed ASAP.
