### ISSUE TITLE
Chrome is always opening the "about chrome" tab

### ISSUE THREAD

**Issue by herkyl** [teamcapybara/capybara#1942]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

Driver Information (and browser if relevant): 2.16.1 / Chromedriver

## Expected Behavior
I expect to see the tab that is running the test.

## Actual Behavior
A few days ago Chrome started opening an "About Chrome" tab as soon as I run a test. This is the screen I see:
![screen shot 2017-11-23 at 09 16 42](https://user-images.githubusercontent.com/714950/33162428-246b29c4-d032-11e7-863a-932487def2f2.png)

## Steps to reproduce
```ruby
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

Capybara.default_driver = :chrome
```
Then run any test.

**Comment by twalpole** [comment]
Make sure you're running the latest version of chromedriver  that is compatible with Chrome 62

**Comment by herkyl** [comment]
@twalpole you are right! I got it working like so:
```
rm -rf $HOME/.chromedriver-helper
bundle update chromedriver-helper
```
