### ISSUE TITLE
Different exceptions for invisible vs missing elements

### ISSUE THREAD

**Issue by taw** [teamcapybara/capybara#1943]
So this request comes from experience of fixing tons of flakey acceptance tests in multiple codebases.

The most common case for flakey test is randomly getting hard to reproduce `Capybara::ElementNotFound` on CI. This exception can mean two things - either that element is actually not present, or that element is present but capybara considers it invisible.

Just figuring out which is it is usually quite hard, and with selectors being buried deep inside code there's no easy way to patch this (except by forking capybara and its drivers and patching it there).

If feel that capybara could be more helpful here, and raise a different exception. `Capybara::ElementNotVisible` (or `Capybara::VisibleElementNotFound` or some such) subclassing `Capybara::ElementNotFound` could be raised if selected element is present, but is not actually visible, with appropriate error message.

This shouldn't affect normal API, only failure reporting, and should be generally backwards compatible, both for use cases where element is expected, and where it's not.

Alternatively, for an even less intrusive change, message could simply be changed from `Unable to find css "#foo"` to something like `Unable to find css "#foo" - all matching elements invisible` without creating any extra exception type.

Capybara already does something similar with `Capybara::Ambiguous`  and `Capybara::ExpectationNotMet` subclassing `Capybara::ElementNotFound`

**Comment by twalpole** [comment]
PRs are welcome
