### ISSUE TITLE
Special Characters Not Testable

### ISSUE THREAD

**Issue by cdrp68** [teamcapybara/capybara#1944]
## Meta
Capybara Version:
2.16.1

## Expected Behavior
It appears that there is an issue when writing tests to match or find strings/elements with special characters and/or html tags.

For example, I am currently working on supporting multiple languages in our capybara tests and a test that might have been the following in English:
`find('span', text: 'Unverified', count: 1)`

should be as straightforward/equivalent as the following for Portuguese:
`find('span', text: "Não verificado", count: 1)`

## Actual Behavior
What is happening when printing out the html body when running the test, the following is returned:
`<span class="text-bold text-negative"> (NÃ£o verificado)</span>`
ã is being "replaced"/displayed as Ã£, so that span is "unable to be found" by Capybara.

The issue is not replicated when running the source code directly so it definitely seems there is an issue with the special characters through Capybara directly.

Other pertinent meta data that might be helpful:
`<meta charset="UTF-8" content="text/html" http-equiv="content-type">`

**Comment by twalpole** [comment]
What driver are you using?

**Comment by cdrp68** [comment]
Poltergeist

**Comment by twalpole** [comment]
@cdrp68 With what version of PhantomJS?

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/a6bf26a7fc2814730b80654c51ff09a5  is a gist showing it working correctly with rack_test, selenium with chrome, and poltergeist (with PhantomJS 2.1.1) - What is the effective difference in your setup?  If you can modify that gist to show the issue then we can look into it.

**Comment by cdrp68** [comment]
Thank you for the response and example. It appears to be an issue with how we are rendering our page and not with Capybara as I first thought.

**Comment by twalpole** [comment]
@cdrp68 You're welcome
