### ISSUE TITLE
[FEATURE REQUEST] could have_link display a list of all the links in the page when there isn't a match?

### ISSUE THREAD

**Issue by tansaku** [teamcapybara/capybara#1945]
Was just reflecting on how time consuming it can be to track down slight differences in expected links.

Was imagining `have_link` failures could also include info on all the links that are in a page, in order to make it easier to debug mismatches ...?

Example; we just spent a while with the debugger to realise that we needed to use CGI.escape to match a link that we had in one of our projects ...

**Comment by twalpole** [comment]
PRs are welcome - although needing to use CGI.escape shouldn't ever be necessary so if you can provide a failing example and details of the driver/versions I can look into that.

**Comment by tansaku** [comment]
we needed CGI.escape as we were doing something special with link redirection - it's not a failure on the part of capybara - was just thinking about providing more informative error messages.

Interesting - would need to be a change to `have_selector` under the hood then - could generalise to any mismatch where something isn't found - but links is a good starting point ...

**Comment by twalpole** [comment]
Closing due to lack of followup, will consider PRs if submitted.
