### ISSUE TITLE
How to send user and password for browser alert out of the application? Chrome - Authentication

### ISSUE THREAD

**Issue by labittencourt** [teamcapybara/capybara#1951]
Hello. I am new to automation with capybara and also learning ruby, ruby ​​being my first programming language. So I do not have much experience with both. Until then I was doing manual tests. At the moment I am starting an implementation of automated tests and I found my first challenge. And I need help. I have to authenticate via "Chrome" browser with username and password. But these fields do not belong to the application, but to the browser, so I can not inspect it.
I have found the following solution: http: // user: password@127.0.0.1: 3239 ". In a way, it works because I have to send user and password, but I can not return to the initial page of my system to continue the steps. screen stops showing user and id.
If I call my url again I come back again to the initial screen requesting again user and password.

In practice or manually doing this authentication are the following steps:
1 - Enter the url
2 - The authentication box is displayed on the screen
3 - Enter username and password
4 - Press button ok
5 - Opens new screen viewed user and id
6 - return to the tab of step 1 and press F5
7 - System loads again with authenticated user.
8 - End of the process

**Comment by twalpole** [comment]
Please ask howto questions on the mailing list or stackoverlow as requested in the README.
