### ISSUE TITLE
Option to make SelectorQuery raise instead of warn if there are unused parameters

### ISSUE THREAD

**Issue by rmacklin** [teamcapybara/capybara#1955]
I'm going to copy the examples from this blog post: http://millo.me/capybara-unused-parameters

Say you have this test:
```rb
example 'show user page' do
  user = FactoryGirl.create(:user)

  visit user_path(user)

  expect(page).to have_content user.name
  expect(page).to have_content user.email_address
  expect(page).to have_link 'Edit', edit_user_path(user)
end
```

It can pass, even if the `Edit` link does not link to the `edit_user_path(user)`. That's because the last line is supposed to be:
```rb
expect(page).to have_link 'Edit', href: edit_user_path(user)
```

Capybara happily proceeds, though, just ignoring the `edit_user_path(user)` argument and logging a warning: https://github.com/teamcapybara/capybara/blob/5b31ac10315bfc42c4220098a12cc9ea7425f49f/lib/capybara/queries/selector_query.rb#L21

But this warning can be easy for developers to miss, which can lead to developers writing tests that they think are asserting more properties about the page content than what is actually being asserted. (In this example, the test only asserts that there's a link with the text "Edit", not that it has the correct `href`, which means that if someone breaks the `href` by accident, the test would still pass even though it shouldn't based on the test author's intentions.)

The linked blog post provides a monkey patch that can be used to make this `raise` instead of `warn`, but I'm opening this issue to ask if the maintainers would be open to either changing the `warn` to `raise` outright, or making whether it should `raise` or `warn` depend on some Capybara configuration.

Thanks for your work on Capybara!

**Comment by rmacklin** [comment]
Also, if this _is_ something the maintainers think is a good idea, I would be willing to submit a PR when I have some free time.

**Comment by twalpole** [comment]
@rmacklin Sure - submit a PR that changes the warning to raising an ArgumentError for Capybara 3 (master branch)

**Comment by twalpole** [comment]
6ef251e72881b3d869ce85e203126d95adfd5e8b

**Comment by rmacklin** [comment]
Thanks @twalpole!
