### ISSUE TITLE
Capybara 2.17.0 appends '/' to Capybara.app_host after visit '/'

### ISSUE THREAD

**Issue by h-parekh** [teamcapybara/capybara#1957]
## Meta
Capybara Version: 2.10.0
Driver Information (and browser if relevant): Poltergeist with Phantomjs

## Expected Behavior
When `Capybara.app_host` is set to a URL which doesn't have any redirects, 
after visit '/', `current_url` should be equal to `Capybara.app_host`

## Actual Behavior
after visit '/', `current_url` has an additional '/' and isn't equal to `Capybara.app_host`

## Steps to reproduce
1. Clone @mhallwac's [curate_test repository](https://github.com/mhallwac/curate_test)
2. Run `bundle install`
3. Run test: `bundle exec rspec curate.rb`
4. Evaluate value for `current_url` and `Capybara.app_host` at the byebug command line

## Additional information
This issue was initially [reported](https://github.com/ndlib/QA_tests/issues/268) in our QA_tests repository. My colleague @mhallwac created the dummy [curate_test repository](https://github.com/mhallwac/curate_test) to make sure the issue isn't due to any monkey patching of code on our end.

**Comment by twalpole** [comment]
This is as expected - What makes you think current_url should be equal to Capybara.app_host?

**Comment by h-parekh** [comment]
@twalpole With version 2.14.3 of Capybara, visit '/' wasn't appending a '/'.

**Comment by twalpole** [comment]
@h-parekh  Ok - but `https://curate.nd.edu` and `https://curate.nd.edu/` are equivalent, and would only cause an issue if you were doing string assertions of current_url which you should never be doing.  You should be using `assert_path`, `have_current_path`, `has_current_path?`, etc.
