### ISSUE TITLE
In README, links to the DSL documentation are broken

### ISSUE THREAD

**Issue by benel** [teamcapybara/capybara#1959]
Example: 

http://rubydoc.info/github/teamcapybara/capybara/master/Capybara/Session#visit-instance_method

**Comment by twalpole** [comment]
Works fine if you click on the visit link in the README shown on rubydoc.info.  Seems maybe `rubydoc` is stripping fragments on first request?  Not sure there's much we can do about that.

**Comment by benel** [comment]
Earlier in the day (Western Europe), I got no response at all. I think rubydoc was down. It works again like a charm.
