### ISSUE TITLE
NoMethodError when accept_alert is first call to capybara using selenium chrome 

### ISSUE THREAD

**Issue by tmertens** [teamcapybara/capybara#1961]
## Meta
Capybara Version: 2.17.0
Driver Information (and browser if relevant):
- selenium-webdriver (3.9.0)
- chromedriver-helper (1.2.0)
- ChromeDriver 2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e)
- Chrome 63.0.3239.132 (Official Build) (64-bit)

## Expected Behavior

The test should accept the alert on page load and test should pass

## Actual Behavior

`*** NoMethodError Exception: undefined method `[]' for nil:NilClass` is raised and causes the test to fail.  Relevant lines of stack trace are below:

```
# ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/selenium/driver.rb:439:in `rescue in find_modal'
# ~/.rvm/gems/ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/selenium/driver.rb:432:in `find_modal'
# ~/.rvm/gems/ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/selenium/driver.rb:242:in `accept_modal'
# ~/.rvm/gems/ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/session.rb:872:in `accept_modal'
# ~/.rvm/gems/ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/session.rb:683:in `accept_alert'
# ~/.rvm/gems/ruby-2.3.4@foo/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
```

## Root Cause

This defect affects the `accept_modal` and `dismiss_modal` methods.  It is caused by the call to `headless_chrome?` [here](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L218) (and the similar line in `dismiss_modal`).

`headless_chrome?` in turn [references the instance variable ](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L298)`@processed_options` directly, which at this point is unset because [the browser has not yet been started](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L23).

`processed_options` should be moved to an attr_reader method that can be evaluated outside of the `browser` method, and the mutations to the `options` hash [here](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L18-L23) should be moved somewhere else as well since it has a material impact on the options hash referenced by `processed_options`.

## Steps to reproduce

Run a test by itself using chromedriver, which calls `accept_alert` as the first step when visiting a page.  It will fail with the stack trace posted above:

```ruby
it 'should accept the alert and pass' do
    accept_alert do
      visit "some/page/with/alert"
    end
end
```

NOTE: This defect affects both chrome and headless chrome.  I have not tested firefox or other drivers but would expect them to be affected as well.

```ruby
# chromedriver configuration
Capybara.register_driver :chrome do |app|
  chrome_options = { browser: :chrome, options: ::Selenium::WebDriver::Chrome::Options.new }
  # https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239
  chrome_options[:options].args << 'disable-browser-side-navigation'
  Capybara::Selenium::Driver.new(app, chrome_options)
end
```

**Comment by twalpole** [comment]
The mutations to the `processed_options` hash that we care about occur in Selenium when the browser is started  (Selenium::WebDriver.for has side effects on it), so we can't really move them elsewhere.  The issue here is that the browser hasn't actually been started at the time `accept_alert` /`headless_chrome?` is called which can be solved by changing the first line of `headless_chrome?` to `if chrome? && browser`.    Unfortunately this issue isn't really solvable for headless chrome since that requires us to inject JS into the page which has the alert, and we can't really do that if the page is changing inside the call to `accept_alert`.  However, I believe headless mode should just work without calling `accept_alert` at all in this case since it's default behavior (before we insert the JS) is to just ignore/not show the system modals.  I'll work on a fixwith this change for the 2.17_stable branch later today/tomorrow if no one else submits one first.

**Comment by twalpole** [comment]
Looks like chrome headless actually supports modals now (at least with chromedriver 2.35 and chrome  65) so we may be able to just remove the checking for headless mode and JS injection.

**Comment by tmertens** [comment]
@twalpole I would just note here that chrome v65 has not yet hit the stable channels yet so it will not be in wide use until it does.  I am trying it to see if it resolves a different issue I had with chrome v64 https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239 so I'd be happy to try out changes to `accept_alert` on a branch if desired.

**Comment by twalpole** [comment]
@tmertens Please try the `chrome_modals` branch which is master but with the modal JS injection removed and passes the travis test suite with Chrome 64

**Comment by twalpole** [comment]
The master and 2.18_dev branches both now have the JS injection removed

**Comment by tmertens** [comment]
I will try to find time to test this today, thanks!

**Comment by tmertens** [comment]
@twalpole I ran our build with headless_chrome on the 2.18_dev branch and didn't run into any issues.  I did __not__ retry the "disable-browser-side-navigation" option however and have been using the chrome 65 beta instead, as that option caused all sorts of other problems.
