### ISSUE TITLE
Failing tests since update to 2.18.0 (passing again when pinned to < 2.18.0)

### ISSUE THREAD

**Issue by jenlindner** [teamcapybara/capybara#1964]
We have a repo that uses Capybara in our tests, and just starting seeing fails in the last three unrelated PRs since the update. Here's a link to one of our failing builds:

https://travis-ci.org/samvera/hyrax/jobs/341043963

And our PRs: https://travis-ci.org/samvera/hyrax/jobs/341043963

## Meta
Capybara Version: 2.18.0

Driver Information (and browser if relevant):

**Comment by jenlindner** [comment]
See https://github.com/samvera/hyrax/issues/2642

**Comment by twalpole** [comment]
Version 2.8.1 was released in august of 2016 and is obsolete.

**Comment by jenlindner** [comment]
Sorry, meant 2.18.0

**Comment by jenlindner** [comment]
https://github.com/teamcapybara/capybara/releases/tag/2.18.0

**Comment by twalpole** [comment]
Ok -- the only real change in 2.18.0 that should really have any effect on anyone would be the removal of the JS modal injection if someone isn't running the latest chrome and chromedriver.   Do any of your failing tests involve JS system modals (alert, confirm, prompt), and if not are you 100% sure the only thing that's changed is the version of Capybara?

**Comment by twalpole** [comment]
@jenlindner Then make sure you're running the latest chromedriver

**Comment by jenlindner** [comment]
It's failing in travis, which installs latest stable by default https://github.com/samvera/hyrax/blob/master/.travis.yml

**Comment by jenlindner** [comment]
Yeah those are good points about how the test is written and I'll try to verify the chromedriver version, but our gemspec only has chromedriver-helper w/o a pin so it should be getting latest.

**Comment by twalpole** [comment]
Looking at all 3 of your failures, they appear to be of the same structure -- `accept_confirm`, immediately access something in the DB without a visual change synchronization.  You have another instance of `accept_confirm` which does a visual waiting/retrying expectation (`have_content`) - https://github.com/samvera/hyrax/blob/4fd8d9ad3c32db7deffc3b5246af5d1459a4b046/spec/features/ownership_transfer_spec.rb#L51 which doesn't fail, so I would say this is definitely about how the tests are written.  Closing for now, we can reopen if it proves to be a Capybara issue.

**Comment by twalpole** [comment]
https://github.com/samvera/hyrax/pull/2644
