### ISSUE TITLE
strange capybara-code only crash when unable to locate button;  wrong number of arguments (given 1, expected 2) in capybara/session.rb:128

### ISSUE THREAD

**Issue by jasonfb** [teamcapybara/capybara#1967]
## Meta
Ruby 2.3.0 on Rails 4.1

jason@Jasons-MB-Air-3:beezwax.net (43257/why-are-you-unsubscribing/jfb)$ chromedriver -v
ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)

Capybara Version:

it is setup in `rauls_heper.rb` using
```
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end
```

## Expected Behavior
a crash that makes more sense to me

## Actual Behavior
this crash, which has a stacktrace through capybara's code only but not my code
```
jason@Jasons-MB-Air-3:$ be rspec spec/features/subscription_management_spec.rb
.F

Failures:

  1) subscription management allows me to click 'undo' and re-subscribe
     Failure/Error:
       def initialize(template, original_exception)
         super(original_exception.message)
         @template, @original_exception = template, original_exception
         @sub_templates = nil
         set_backtrace(original_exception.backtrace)
       end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 2)
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:128:in `exception'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:128:in `raise'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:128:in `rescue in raise_server_error!'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:125:in `raise_server_error!'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:113:in `reset!'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara.rb:334:in `block in reset_sessions!'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara.rb:334:in `reverse_each'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara.rb:334:in `reset_sessions!'
     # /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/rspec.rb:21:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   /Users/jason/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.1/lib/capybara/session.rb:126:in `raise_server_error!'

Finished in 5 seconds (files took 8.86 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/features/subscription_management_spec.rb:13 # subscription management allows me to click 'undo' and re-subscribe

```

## Steps to reproduce

Can't show client app, but here is the spec:

```
require 'rails_helper'

describe "subscription management", :js => true, :type => :feature  do
  before :each do

  end

  it "allows me to unsubscribe" do
    visit '/users/subscription-management?name=John&md_email=info%40beezwax.net&md_id=95773ba4786c44e4a03a5b62fb1ee446'
    expect(page).to have_content('John, so sorry to see you')
  end

  it "allows me to click 'undo' and re-subscribe" do
    visit '/users/subscription-management?name=John&md_email=info%40beezwax.net&md_id=95773ba4786c44e4a03a5b62fb1ee446'
    expect(page).to have_content('John, so sorry to see you')


    click_button 'UNDO'
  end

  it "asks me why I am opting out at this time" do
    pending
  end


  it "asks whether or not I want to truly opt-out" do
    pending
  end
end
```

should be straightforward… I'd be expecting either it to find my button "UNDO" or tell me it can't locate the button

**Comment by jasonfb** [comment]
Unless I'm missing something on this early morning.

**Comment by jasonfb** [comment]
Then I tested it with
`click_button('jellyfish')` which I know not to be on the page and got the expected result

```
  1) subscription management allows me to click 'undo' and re-subscribe
     Failure/Error: click_button('jellyfish')
     
     Capybara::ElementNotFound:
       Unable to find button "jellyfish"
```

**Comment by jasonfb** [comment]
I have confirmed that on my server side, I am receiving this and see this in the logs. so it is finding the button, and then there's a crash on the server-side action that happens after the button is clicked

```
Completed 500 Internal Server Error in 59ms (ActiveRecord: 9.9ms)
** [Airbrake] Notice was not sent due to configuration:         
  Environment Monitored? false         
  API key set? true
   (0.2ms)  ROLLBACK
```

**Comment by jasonfb** [comment]
I did some refactoring to namespce better and this appears to have gone away. Will follow-up later today to confirm.

**Comment by twalpole** [comment]
This was fixed in 2.10.2 - App exceptions with multiple parameter initializers now re-raised correctly - Issue #1785 [Michael Lutsiuk] .

Additionally Capybara 2.10.1 (the version you're using) was released well over a year ago.  You really need to keep your testing gems up to date.

**Comment by jasonfb** [comment]
At yes thank you. 

Many Rails app do not even have any testing frameworks, and as such, in this particular case this is the very first installation of the gem. 

Generally speaking I do not recommend willy-nilly updating of everything all the time— but of course— in many cases (such as this one), later advancements in gem code (like capybara's!) produce better code and have fixed bugs.

interestingly, 2.10.1 is what came out as *default* (bundle install) on my Rails 4.1.16 app — _I did not specify it directly_.

I used Bunder's version lock mechanism to lock capybara to 2.10.2 for my app. 

Thank you for the feedback!

I think this serves as good documentation. will cross-post to Stack-overflow

Jason

**Comment by jasonfb** [comment]
I did literally install capybara in this Rails 4.1 app _yesterday_, so you might want to consider why bundler is pull `2.10.1` as default when it should be pulling `2.10.2` down. Obviously as I said above I know how to version lock in the Gemfile which is an easy solution.

**Comment by twalpole** [comment]
@jasonfb It shouldn't be pulling 2.10.2 - it should be pulling the latest - 2.18.0 if there are no restrictions put on it (and it's not already in the Gemfile.lock).  I would guess 2.10.1 was the version that was already specified in the Gemfile.lock of the app you checked out, so then `bundle install` would just install that version.  If you did `bundle update capybara` then it would have updated to the latest Capybara.
