### ISSUE TITLE
Cannot test modals using `Session#refresh`

### ISSUE THREAD

**Issue by joefiorini** [teamcapybara/capybara#1969]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

2.18.0

Driver Information (and browser if relevant):

selenium-webdriver 3.7.0

## Expected Behavior

With this code in a spec:

```ruby
page.dismiss_confirm do
  page.refresh
end
```

I'd expect the `dismiss_confirm` call to cancel the refresh and remain on the page.

## Actual Behavior

Spec fails with `Capybara::ModalNotFound` error since the underlying code is wrapped in an `accept_confirm`. Is this a good assumption?

**Comment by twalpole** [comment]
`refresh` is for the test writer to refresh the page - why would you ever want to have that not happen? If you don't want the page to refresh, don't call refresh.

**Comment by twalpole** [comment]
Reopening, thinking about this more - The reason for the `accept_confirm` is because when refreshing pages that were the result of a POST the browser asks whether or not you're sure you want to repost.  However the same question stands, if you don't want the page to refresh, why are you calling `refresh` ?

**Comment by elliterate** [comment]
If someone were testing a form, I could imagine them wanting to test that the user was asked whether they wanted to discard their changes.

**Comment by twalpole** [comment]
So the horrendous onbeforeunload popups that just lead to terrible UX.  Not sure we should be changing things to make using them easier.

**Comment by joefiorini** [comment]
So in my specific use case I am refactoring a bunch of specs (that I did not write) to use headless chrome instead of poltergeist. One of them is testing that the pop up comes up before reloading. If this is an automatic browser feature, then I guess you could argue that there's no need to test the browser behavior, since that should be tested already. Then again, a failing spec here could be really useful should Chrome ever remove this feature (or change how it is triggered).

And I'm not sure I'd assume this is terrible UX. We are dealing with forms (filled out by internal users) that could have a lot of data and are very sensitive to our business. If someone accidentally refreshed (perhaps forgetting which tab they are in), they could lose a lot of time reentering all that data. Not so horrendous in that case.

**Comment by twalpole** [comment]
Save the data to sessionStorage/localStorage and reload it when the page is visited again

**Comment by twalpole** [comment]
Anyway , if you want to test them with selenium for now you'll need to do

    page.dismiss_confirm do
      page.driver.browser.navigate.refresh
    end

**Comment by twalpole** [comment]
6458ed55ed53d6abdf45cf814b56360976136d3b
