### ISSUE TITLE
Finders#first returns nil rather than raising exception

### ISSUE THREAD

**Issue by ms-ati** [teamcapybara/capybara#1971]
## Meta
Capybara Version:
2.17.0 (latest release), also 2.15.4 

Driver Information (and browser if relevant):
ChromeDriver 2.33 with Chrome 62.0.3202.94-1 on Linux

## Expected Behavior
Per [the API documentation](http://www.rubydoc.info/github/teamcapybara/capybara/master/Capybara/Node/Finders#first-instance_method) for `Finder#first`: we would expect that, if no matching element can be found before the `Capybara.default_max_wait_time`, that capybara would raise `Capybara::ElementNotFound`.

## Actual Behavior
In practice, it appears that `#first` will return `nil` instead of raising the error. It's not clear if this was previously the *intended* behavior and the intent changed between versions, because while the code docs definitely document the expected error, they also still say "The found element or nil" at https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/finders.rb#L274 -- so there's some ambiguity about the expected behavior even with in the documented API?

## Steps to reproduce

```ruby
element = first("td", text: "WontBeFound")
#=> nil
```

**Comment by ms-ati** [comment]
Digging deeper, am I correct in my reading that, apart from ambiguity in the doc comment, this was actually fixed in https://github.com/teamcapybara/capybara/commit/d873b83b2aeba0c479bc589a8542072c7b5d69eb#diff-e0a7e0b5db6bbb0355a03b1e6ee1e3b0 on Nov 14 2017?

**Comment by ms-ati** [comment]
...and am I also correct that this fix is now awaiting an actual release version, as [2.18.0](https://github.com/teamcapybara/capybara/blob/2.18.0/lib/capybara/node/finders.rb) doesn't have this fix no the spec driving it?

**Comment by twalpole** [comment]
You're linking to the docs for the master branch, which is the for the upcoming v3 --  If you look at the documentation for the 2.x release versions you'll see the current behavior is as documented - http://www.rubydoc.info/gems/capybara/Capybara/Node/Finders#first-instance_method.  This is one of the things changing for 3.0 and is mentioned in the https://github.com/teamcapybara/capybara/blob/master/History.md for v3.0

**Comment by ms-ati** [comment]
Ah cool, thanks! Well looking forwards to 3.0 then. @twalpole before closing this, are you sure you don't want to fix the ambiguous doc comment that still exists in master ("...or nil")?

**Comment by twalpole** [comment]
@ms-ati Quick reaction would be that I think it's probably still possible for it to return `nil` if the user chooses to pass in `minimum: 0` although I'd have to try it or refresh my reading of that code path to confirm.

**Comment by ms-ati** [comment]
@twalpole Yep, that's the ambiguity isn't it? Anything we could do to reduce the ambiguity / truly clarify for next version would be awesome

**Comment by twalpole** [comment]
@ms-ati I don't think I agree that's an ambiguity -- If the user tells it to find a minimum of 0 elements then nil is a valid return.  If they don't then a minimum of 1 is assumed and Capybara::ElementNotFound would be returned if there are no matching elements.
