### ISSUE TITLE
`session#reset!` should reset all sessions windows

### ISSUE THREAD

**Issue by cyrilchampier** [teamcapybara/capybara#1984]
## Real life problem
In a rails test, I open 2 pages. 
On each page, there is some javascript executing. 
This javascript make an ajax request every seconds to our server.
On teardown, I use `Capybara.reset!`, then clear database.
`Capybara.reset!` will stop javascript executing on current_page, but not on second page
If an ajax request comes during database clear, the test will fail.

## Meta
Capybara Version:
2.17
Driver Information (and browser if relevant):
selenium-webdriver 3.7.0 with Chrome

## Expected Behavior
All opened window should be cleared
The test below only test for html because thats what cause me troubles, but it should also test for storage to be cleared.

## Actual Behavior
Only the current window is cleared

## Steps to reproduce
capybara tests:
```rb
  it "reset multiple windows", requires: [:windows] do
    windows = [@session.current_window, @session.open_new_window]

    windows.each do |window|
      @session.within_window(window) do
        @session.visit('/with_html')
        expect(@session).to have_content('This is a test')
        expect(@session.find('.//h1').text).to include('This is a test')
      end
    end

    @session.reset_session!

    windows.each do |window|
      @session.within_window(window) do
        expect(@session.body).not_to include('This is a test')
        expect(@session).to have_no_selector('.//h1')
      end
    end
  end
```

## Possible solutions
* Modify the `Session#reset!`: but we dont know if underlying driver supports windows
* Add a  `Session#reset_windows!` ?

**Comment by twalpole** [comment]
Currently it's the users responsibility to close extra windows opened during a test when done with them.  If we want to change this behavior it would need to be implemented in each drivers #reset! method.

**Comment by cyrilchampier** [comment]
I would be ok to submit a PR for that, but appart from this one '/lib/capybara/selenium/driver.rb',
where would the other drivers be ?

**Comment by twalpole** [comment]
in their own repos - poltergeist, capybara-WebKit, etc

**Comment by cyrilchampier** [comment]
you seems to contribute to these 3 repositories,
would you approve if I submit one pr on each with this windows loop in their respective implementation of `reset!` ?

**Comment by twalpole** [comment]
@cyrilchampier The more I think about it, the more I think we should just be closing extra windows before we reset the one remaining window.  What are your thoughts on doing that rather than resetting them?

**Comment by cyrilchampier** [comment]
This is something I did not yet completely investigated: whether a simple close would work, or if we need to visit `about:blank` first.
But in both case, it should be the responsibility of the driver to end up with a pristine state after `reset!`, dont you think ?

**Comment by twalpole** [comment]
Closed via 590793d0042e21317fd1d4c7669279d67d2bded8

**Comment by cyrilchampier** [comment]
@twalpole I added a comment on your pr: you should always come back to first window, or the javascript will have a different behavior.

**Comment by twalpole** [comment]
@cyrilchampier Where does the quote "Scripts may close only the windows that were opened by it." come from, and since the window gets reset to about:blank then there is no JS existing that created the window anymore.  Can you provide an example to prove your assertion ?

**Comment by cyrilchampier** [comment]
in lib/capybara/spec/test_app.rb:
```
  get '/with_javascript_close' do
    "<script>window.close()</script>"
  end
``
`

then in a test:
```
    first_window = @session.current_window
    second_window = @session.open_new_window

    @session.within_window(first_window) { @session.visit('/with_javascript_close') }
    # @session.windows.count == 2
    @session.within_window(second_window) { @session.visit('/with_javascript_close') }
    # @session.windows.count == 1
```

on chrome, the first window refuses to close with the javascript console warning "Scripts may close only the windows that were opened by it."

**Comment by twalpole** [comment]
@cyrilchampier I'm not clear on how that actually relates to this issue -  We don't close windows by calling the JS `window.close()` --  If you can produce a PR for a test that shows how reset not leaving the original first window open causes an issue it would help.  The test can start exactly the same as https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/reset_session_spec.rb#L75 and then show what behavior in the remaining window doesn't work that should/would if that window was the one initially open.

**Comment by cyrilchampier** [comment]
The case we had was a window closed by our javascript.
Depending if it runs on the "main" capybara window or not, it will have a different behavior:
Assuming it's the first to run, the window wont be closed.
If it's the second after a test that closed the "main" window and let another one opened by `open_new_window`, the script will successfully close the window.

Imagine that these 2 runs are this same test that runs 2 times, it will show the two different behavior:

```
  it "closes extra windows when not on the first window", :focus_, requires: [:windows] do
    # FIRST RUN
    first_window = @session.current_window
    second_window = @session.open_new_window
    @session.visit('/with_javascript_close')
    # The first window is the master window, it cannot be closed by javascript, since it was opened by cvapybara
    expect(@session.windows.size).to eq 2 # main window and the other opened by open_new_window
    @session.switch_to_window(second_window)
    @session.reset_session!
    expect(@session.windows.size).to eq 1

    # SECOND RUN
    first_window = @session.current_window
    second_window = @session.open_new_window
    @session.visit('/with_javascript_close')
    # The first window is NOT the master window anymore, it can be closed by javascript
    expect(@session.windows.size).to eq 2 # This will fail: the first_window has been closed
    @session.switch_to_window(second_window)
    @session.reset_session!
    expect(@session.windows.size).to eq 1
  end
```

got it ?

**Comment by twalpole** [comment]
@cyrilchampier Ok -- That seems more like a user issue with the way the tests are written.  From a user perspective I would consider it surprising that the initial window doesn't actually close when `with_javascript_close` is visited, and brings up whether or not the driver should be preventing users from ever calling `close` on the initial window.  I also see no mention of treating the initial window as special in the WebDriver spec.

**Comment by cyrilchampier** [comment]
So you mean capybara should allow closing window, even if it's the first/main ?
That would mean opening a new window at the start of the suite, and close the original one.
This way, all test would run on a closable window.
But this behavior seems complicated just for this special edge case.
I dont think of any satisfying behavior :(

**Comment by twalpole** [comment]
@cyrilchampier I mean selenium allows closing the window (with no way to reopen it that I see), and your test example is depending on completely undocumented behavior of selenium (that the initial window can't be closed by JS)

**Comment by cyrilchampier** [comment]
k, let's ignore this very bordeline behavior.
Do you want me to open PRs on [poltergeist](https://github.com/teampoltergeist/poltergeist) and (webkit)[https://github.com/thoughtbot/capybara-webkit] to mimick the behavior you implemented on the [selenium one](https://github.com/teamcapybara/capybara/pull/1986) ?

**Comment by twalpole** [comment]
From a quick test Poltergeist doesn't need any changes since it already closes all windows on reset and creates a new one - I haven't checked capybara-webkit yet.

**Comment by cyrilchampier** [comment]
ok, thanks for you reactivity, let me know if you need any help. Great job on Capybara by the way!
