### ISSUE TITLE
Page object pattern support

### ISSUE THREAD

**Issue by abotalov** [teamcapybara/capybara#1988]
Not having "good" support for page objects is quiet a disadvantage of Capybara IMO.

Watir provides an abstraction around `Element` so page objects can be implemented very easily there:
```ruby
class SomePage
  def some_el
    browser.element(id: "id")
  end
end
el = SomePage.new.some_el
el.exists?
el.click
```

It can't be done as simply using Capybara.

It can be done via some metaprogramming like SitePrism does but the main disadvantage (to me) is the inability to use IDE's "Go to Definition" ability to check element definition. Also SitePrism has some other disadvantages:
1. By including `Capybara::DSL` into `BasePage` too many methods are exposed as object methods (e.g. `some_page.within_window`, etc.)
2. Some decisions made by such libraries may be inconsistent with decisions made in Capybara (e.g. not using Capybara waits by default, etc.)
3. Some difficulties when implementing such library (e.g. https://github.com/natritmeyer/site_prism/issues/83)

I've been thinking a lot about the proper way of writing page objects when using Capybara. But Watir idea (of having abstraction around element) seemed better than my ideas.

For reasons above I think it would be better to maintain page object implementation inside Capybara.

As a note, I can't work on a PR for adding support of page objects. I haven't even used Capybara since 2014.

**Comment by twalpole** [comment]
Implementing the `to_capybara_node` method in any page object should allow them to work with Capybaras matchers, what else do you think should be necessary?

**Comment by twalpole** [comment]
@abotalov Take a look at https://github.com/twalpole/capybara_page which is an experimental fork of SitePrism that doesn't include Capybara/DSL into every object, uses Capybaras defaults of implicit waits, etc and uses `to_capybara_node` for matcher/assertion support.  It requires the current master branch of Capybara and hasn't really be tested for anything other than passing the 99% of the SitePrism test suite that makes sense for it to pass.

**Comment by abotalov** [comment]
Well, I made a quick look at this and have found the following bits surprising:
* I think usual Capybara methods shouldn't be exposed as Page's/Section's methods at all. One may think that `Section#execute_script`/`evaluate_script` execute script strictly inside this section. Another one may think that SomePage.new.text will return text of SomePage but it returns just the text of currently opened page. As users can access these methods directly through Capybara, they should do so without raising confusion.
* Methods like `wait_for_*`, `wait_until_*_visible`, `wait_until_*_invisible` are not in line with Capybara naming conventions. I think `SomePage.new.assert_search_field` would be enough as these methods could accept `visible: true`/`visible: :hidden`

**Comment by twalpole** [comment]
@abotalov Yes -- it was an experiment to show that SitePrism could be implemented without including Capybara/DSL everywhere, it was not intended to be a perfect implementation of the page object model.
