### ISSUE TITLE
Feature request: support #network_conditions

### ISSUE THREAD

**Issue by adsteel** [teamcapybara/capybara#1990]
[Selenium Chromedriver now supports toggling things like latency and throughput.](https://github.com/SeleniumHQ/selenium/commit/1103cb7e9e35e8bd22a5aea9b5455445baa6fb85#diff-b1ade8967288d0002579a914345a9f56R37)

Seems like a straightforward addition. If folks are amenable I may open a PR for it.

**Comment by twalpole** [comment]
You can access this already via `page.driver.browser.network_conditions`, but we're not going to add any special Capybara support until it's supported by more than one browser/driver.

**Comment by adsteel** [comment]
Fair enough. Thanks for the quick response!
