### ISSUE TITLE
Running capybara specs causes separate Rails server to hang.

### ISSUE THREAD

**Issue by tobycox** [teamcapybara/capybara#1995]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
2.18.0 
3.0.0.rc2

Driver Information (and browser if relevant):
selenium-webdriver (3.11.0)

## Expected Behavior
I'd expect that I can `rails server` and my system tests in parallel.

## Actual Behavior
When running system specs with a Rails server, as soon as the spec gets to a system spec, the Rails server will report:
`[21121] - Gracefully shutting down workers...` and then hang. 

## Steps to reproduce
Run: `bundle exec rails server`
Run: `bundle exec rspec spec/system/*`

So far I've tried setting a different puma PID file for my development server, but that didn't help.
Have also tried 2.18.0 and 3.0.0.rc2 of capybara. Any ideas how I can debug this further?

Thanks!

**Comment by twalpole** [comment]
Please give your Capybara configuration, and the system spec that causes this.  There is nothing in Capybara that prevents you from running your dev server and system tests at the same time.

**Comment by tobycox** [comment]
@twalpole My capybara config is:
```
Capybara.default_driver = :selenium
Capybara.server = :puma
Capybara.default_max_wait_time = 10
Capybara.server_port = 3001
```

System tests are configured with:
```
  config.before(:each, type: :system, js: true) do
    driven_by :selenium_chrome_headless
   
    Rails.application.routes.default_url_options[:host] = "localhost:#{Capybara.current_session.server.port}"
  end
```

Rails version is `5.1.4`

Thanks for your help! Let me know if there's anything else I can provide or if you can think of any ways to debug this.

**Comment by tobycox** [comment]
Oh and here's a spec that causes it to shut down puma:
```
  it "should return matching stores and categories" do
    visit category_path(category, locale: us.locale)
    if page.has_css?("#main-search-icon")
      find("#main-search-icon").click
    end
    find("#main-search-input").click
    fill_in("main-search-input", with: "OUNT")
    find(".search-store-result", text: store.name)
    find(".search-category-result", text: category.name)
  end
```

**Comment by twalpole** [comment]
What is output in your console when Capybara starts puma ?

**Comment by twalpole** [comment]
Just noticed you're running Rails 5.1.4 - I'm guessing you also have puma config file that is setting 1 or more workers in it.  This would force `puma` to run in clustered mode as mentioned in my previous comment, and won't work properly for testing.  Update to Rails 5.1.6 and your issue will probably go away since it forces a `workers: 0` puma config in test mode.  Your tests then should also work correctly with transactional testing (and no need for database cleaner)
