### ISSUE TITLE
Before each not showing the accurate driver

### ISSUE THREAD

**Issue by Deekor** [teamcapybara/capybara#1999]
## Meta
Capybara Version:
2.11.0

## Issue
In my spec_helper:
` Capybara.javascript_driver = :poltergeist`

I'm also using a before block to check if the test is using the poltergeist driver or not:

```
  config.before(:each, type: :feature) do
    # FIXME: Why isnt this finding poltergeist?
    puts "BEFORE: #{Capybara.current_driver}"
    if Capybara.current_driver == :poltergeist
      DatabaseCleaner.strategy = :truncation
    end
  end
```
When I run this on a set of 4 feature tests wrapped in a describe block: `describe "the signin process", type: :feature, js: true do`

It always prints:
```
BEFORE: rack_test
BEFORE: rack_test
BEFORE: rack_test
BEFORE: poltergeist
```

It's clear based on the test being run it is using the poltergeist driver, just seems the switch hasn't taken place yet in the before block? Is this expected behavior?

**Comment by twalpole** [comment]
The current driver is switched based on the :js metadata by a before block registered when you require 'capybara/rspec' - https://github.com/teamcapybara/capybara/blob/2.18_stable/lib/capybara/rspec.rb#L30 .  What your before block sees would be based on whether it is executed before or after the Capybara provided block, so you need to ensure your block is registered after the Capybara one (RSpec runs before blocks in the order of declaration)

**Comment by Deekor** [comment]
the block is declared after the `require 'capybara/poltergeist'` if that is what you are suggesting?

**Comment by Deekor** [comment]
Got it. I thought they were identical with since poltergeist only says to require theirs. Requiring `capybara/rspec` as well fixed the issue.
