### ISSUE TITLE
using capybara, rspec, selenium, chrome; getting Errno::ECONNREFUSED:

### ISSUE THREAD

**Issue by alosada** [teamcapybara/capybara#2009]
## Meta
Capybara Version: capybara-2.18.0
Driver Information (and browser if relevant):
ChromeDriver 2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85)
selenium-webdriver-3.8.0
Google Chrome 65.0.3325.181 

## Expected Behavior
Trying to run some smoke-tests on my staging server, using capybara to mimic the critical path.

## Actual Behavior
Test run, but I get the following error randomly, but frequently: 

`Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)`

Here's the full trace:
`          Errno::ECONNREFUSED:
            Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
          # ./spec/smoke/staging_basic_auth.rb:11:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "127.0.0.1" port 9515
          #   ./spec/smoke/staging_basic_auth.rb:11:in `block (2 levels) in <top (required)>'

     3.2) Failure/Error:
            raise e, "Failed to open TCP connection to " +
              "#{conn_address}:#{conn_port} (#{e.message})"
          
          Errno::ECONNREFUSED:
            Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/timeout.rb:74:in `timeout'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:878:in `connect'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:852:in `start'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:1398:in `request'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:299:in `delete_all_cookies'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/options.rb:81:in `delete_all_cookies'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:119:in `reset!'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/session.rb:127:in `reset!'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara.rb:314:in `block in reset_sessions!'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara.rb:314:in `reverse_each'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara.rb:314:in `reset_sessions!'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/rspec.rb:22:in `block (2 levels) in <top (required)>'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:357:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `each'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:595:in `block in run_example_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `each'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:594:in `run_example_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:465:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:507:in `run_after_example'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:273:in `block in run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:609:in `run_around_example_hooks_for'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
          # /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
          # /Users/alejandro/.rbenv/versions/2.3.4/bin/rspec:22:in `load'
          # /Users/alejandro/.rbenv/versions/2.3.4/bin/rspec:22:in `<main>'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
          # ------------------
          # --- Caused by: ---
          # Errno::ECONNREFUSED:
          #   Connection refused - connect(2) for "127.0.0.1" port 9515
          #   /Users/alejandro/.rbenv/versions/2.3.4/lib/ruby/2.3.0/net/http.rb:880:in `initialize'`

## Steps to reproduce
just run r-spec

My gems are up to date. I'm also using 'chromedriver-helper'. 

rails_helper contains:
`Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara.configure do |config|
  config.default_max_wait_time = 10
  config.default_driver        = :selenium
end`

and I have a before each: 

before :each do
    Capybara.run_server = false
    Capybara.default_max_wait_time = 15
    Capybara.server_host = 'web'
    Capybara.app_host = 'http://staging.donadora.mx'
    username =  'some_name'
    password = 'some_password'
    visit "http://#{username}:#{password}@staging.donadora.mx"
 end

and an after:

`after :each do
    visit("about:blank")
    Capybara.reset_sessions!
  end`

I've tried adding:
`    options = Selenium::WebDriver::Chrome::Options.new
    options.add_argument(%w[--ignore-certificate-errors ])`
as it was sugested somewhere but it doesn't help. I'm not using headless either, tho I got have the 'poltergeist' gem.

halp :(

**Comment by twalpole** [comment]
From the stack trace it looks like `selenium` is unable to connect to `chromedriver` which is really outside of Capybara.  This could be caused by mismatched versions of Chrome and chromedriver, a bug in either. 

 From a Capybara perspective it is strange that you're visiting 'about:blank' before calling `reset_sessions!` since `reset_sessions!` already does a visit to 'about:blank'.  Also if you've required `capybara/rspec` like recommended when using RSpec then an after block has already been installed to do the session reset..

**Comment by alosada** [comment]
Just in Case anyone lands here with this issue:

ChromeDriver 2.37 doesn't play well with Chrome 65

Downgrading ChromeDriver to version 2.35 fixed the issue for me. 
it can be found here: https://chromedriver.storage.googleapis.com/index.html
