### ISSUE TITLE
Puma startup message showing up in the rspec output 

### ISSUE THREAD

**Issue by jarthod** [teamcapybara/capybara#2017]
Capybara Version: `3.0.2`
Driver Information: `selenium-webdriver 3.11.0`

Hi ! I just upgraded from `2.x` to `3.0.2` and noticed Puma startup messages in the rspec output:
![image](https://user-images.githubusercontent.com/201687/39093896-20569efc-4627-11e8-8017-80553f0c38a0.png)

I guess this is since `3.0.0`:

> Use Puma::Server directly rather than Rack::Handler::Puma so signal handlers don't prevent test quitting

**Comment by jarthod** [comment]
Ok I see, thanks for the quick response. I think the `Silent: true` option should be the default but that's for you to decide ;)

**Comment by twalpole** [comment]
It is specifically not the default because it's useful debugging info when people start trying to get their Capybara JS supporting tests running.

**Comment by jarthod** [comment]
Mm ok ^^
