### ISSUE TITLE
Date format incorrect for selenium-webdriver with :remote as browser

### ISSUE THREAD

**Issue by ianks** [teamcapybara/capybara#2018]
## Meta
Capybara Version: 3.0.2

Driver Information (and browser if relevant): selenium-webdriver (3.11.0) remote using chrome

## Expected Behavior

When using selenium-webdriver, date format should be chosen based on `driver.options[:desired_capabilities][:browser_name]` rather than `driver.options[:browser]` to allow for remote instances to have the correct date formats.

## Actual Behavior

When using `browser: :remote`, the date time formats defaults to the incorrect format when using chrome.

## Steps to reproduce

```ruby
caps = Selenium::WebDriver::Remote::Capabilities.chrome

Capybara::Selenium::Driver.new app,
                               browser: :remote,
                               desired_capabilities: caps

# somewhere in the test
fill_in('my-date-field', with: Date.today)
```

Then, filling out a date field will produce a date in the incorrect format

**Comment by twalpole** [comment]
Capybara tests don't get run against remote selenium instances, but a PR that works for this and local would be accepted

**Comment by ianks** [comment]
Would you guys be willing to support remote (I.e. run on CI?)

**Comment by twalpole** [comment]
Sure, if the PR added a remote chrome run it would be fine

**Comment by twalpole** [comment]
Fixed via PR #2019

**Comment by ianks** [comment]
Yay! When do you think 3.0.3 will be pushed?

**Comment by twalpole** [comment]
Next release will probably be 3.1 in a week or two
