### ISSUE TITLE
Feature Request: Dump browser error logs on failure

### ISSUE THREAD

**Issue by ianks** [teamcapybara/capybara#2023]
We have an app that is fairly JS heavy, and whenever a test fails it's nice to see the browser's console output. This is generally more informative than the default `could not find selector` errors as it gives some clues as to what might have caused the failure.

Currently, we have hacked together a way to accomplish this:

```ruby
  # dump browser console logs when a test fails
  config.after(:each, type: :feature) do |example|
    if example.exception
      logs = console_logs(:severe)

      Rails.logger.tagged('Browser Console Logs') do
        logs.each do |log|
          lines = log.message.split('\n')
          lines.map! { |line| "\t" + line }
          message_in_red = "\e[31m#{lines.join("\n")}\e[0m"
          Rails.logger.error("\n" + message_in_red)
        end
      end
    end
  end
```

Ideally, this could be supported in capybara directly as an option. Would you accept a PR which implemented this? I was thinking the api would be as simple as this:

```ruby
Capybara.configure do |config|
  config.print_browser_logs_on_failure = true
end
```

Thoughts?

**Comment by twalpole** [comment]
This is not currently implementable across drivers, so wont be supported natively by Capybara
