### ISSUE TITLE
Capybara does not work when headless

### ISSUE THREAD

**Issue by davidmoseler** [teamcapybara/capybara#2025]
The test is very simple

@session = Capybara::Session.new(:selenium)
@session.visit("https://youtube.com")
@session.fill_in 'search', :with => "test"

If I run 

ruby youtube.rb

it works. If I run

xvfb-run -a ruby youtube.rb

The error output is:

/home/db/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:314:in `block in synced_resolve': Unable to find visible css "input#search" (Capybara::ElementNotFound)
        from /home/db/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
        from /home/db/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:302:in `synced_resolve'
        from /home/db/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/node/finders.rb:37:in `find'
        from /home/db/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capybara-2.18.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
        from youtube.rb:33:in `method_missing'
        from youtube.rb:57:in `initialize'
        from youtube.rb:79:in `new'
        from youtube.rb:79:in `<main>'

If I change the driver from :selenium to :webkit, and run

ruby youtube.rb

The exact same thing happens.

I think that, for the last one year, I was stuck with watching firefox windows launching when I run capybara because otherwise it would not work on any website. I tried youtube, facebook, google, etc, and nothing works headless, even for such a simple code.

Oddly, if I run Xfvb :1 & and then export DISPLAY=:1 and run the script, it works fine. But the behaviour for webkit on the other hand can not be avoided by this method.

**Comment by twalpole** [comment]
Stop using xvfb, and either use the :selenium_chrome_headless driver, or register your own driver which runs Firefox in headless mode.  In the future ask howto type questions on the mailing list (or on stackoverflow) as requested in the README and mentioned in the new issue template.

**Comment by davidmoseler** [comment]
Twalpole, if you read carefully the reported problems, you will see that it does not only apply to selenium with xvfb, but also applies to the webkit driver. This is what makes it the worse for me: I never could make anything with webkit. I sucefully use capybara in a daily basis with the selenium driver, but webkit never worked on any single page I tried (the example of youtube is above). Why is that?

**Comment by twalpole** [comment]
That’s a question for the capybara-webkit project, not the Capybara project.

**Comment by davidmoseler** [comment]
The page looks fine when I open it's source with firefox. The "missing" elements are there. Since the same error message came from both webkit and selenium with Xvfb, it seemed to me to be a problem coming from a higher level layer than the driver. It is clearly a bug, and "not use xvfb" seems to be a way to circumvent it instead of a solution or explanation. In principle any application should work the same with xvfb.

**Comment by twalpole** [comment]
@davidmoseler The fact that a browser runs differently with/without xvfb is not a Capybara issue, that's either user error, an issue with the browser app, or unsupported functionality by that browser.  Both Chrome and Firefox have implemented headless modes, if you want to run them headless then use their headless modes instead of using xvfb.   Since you seem incapable to "read carefully" the answers you're getting (or accept them) please post any further questions or comments elsewhere.
