### ISSUE TITLE
Slight xhtml rendered difference between drivers rack_test and selenium

### ISSUE THREAD

**Issue by cyrilchampier** [teamcapybara/capybara#2029]
Hi,
I am not totally sure it's a valid problem, because I did not found anything saying that all drivers should have the same behavior, but in case of, here is a report:

## Meta
Capybara Version:
2.18.0 and 3.0.3, same behavior

Driver Information (and browser if relevant):
selenium-webdriver (3.7.0) with chrome 66 headless

## Expected Behavior
Same render for all drivers

## Actual Behavior

RackTest driver:
```
(byebug) page.driver.class
Capybara::RackTest::Driver

(byebug) page.html
"<?xml version=\"1.0\" encoding=\"utf-8\" ?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.doctolib.fr</loc><xhtml:link href=\"https://www.doctolib.fr\" hreflang=\"fr\" rel=\"alternate\"></xhtml:link><xhtml:link href=\"https://www.doctolib.de\" hreflang=\"de\" rel=\"alternate\"></xhtml:link></url></urlset>"

(byebug) page.body
"<?xml version=\"1.0\" encoding=\"utf-8\" ?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.doctolib.fr</loc><xhtml:link href=\"https://www.doctolib.fr\" hreflang=\"fr\" rel=\"alternate\"></xhtml:link><xhtml:link href=\"https://www.doctolib.de\" hreflang=\"de\" rel=\"alternate\"></xhtml:link></url></urlset>"

(byebug) page.document.text
"https://www.doctolib.fr"
```

* Selenium driver:
```
(byebug) page.driver.class
Capybara::Selenium::Driver

(byebug) page.html
"<?xml version=\"1.0\" encoding=\"utf-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.doctolib.fr</loc><xhtml:link href=\"https://www.doctolib.fr\" hreflang=\"fr\" rel=\"alternate\" /><xhtml:link href=\"https://www.doctolib.de\" hreflang=\"de\" rel=\"alternate\" /></url></urlset>"

(byebug) page.body
"<?xml version=\"1.0\" encoding=\"utf-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.doctolib.fr</loc><xhtml:link href=\"https://www.doctolib.fr\" hreflang=\"fr\" rel=\"alternate\" /><xhtml:link href=\"https://www.doctolib.de\" hreflang=\"de\" rel=\"alternate\" /></url></urlset>"

(byebug) page.document.text
*** Capybara::ElementNotFound Exception: Unable to find visible xpath "/html"
```

## Steps to reproduce

simply make a visit on a route rendering xml

**Comment by cyrilchampier** [comment]
I observed another difference on empty pages:
* empty page: 
visit '/something' => head :not_found
* page.body
driver rack_test: ''
driver selenium: '<html><head></head><body></body></html>'
* page.document.text 
empty in both cases

**Comment by twalpole** [comment]
RackTest attempts to emulate very simple parts of a browser, but assumes everything passed to it is HTML.  Chrome on the other hand will render XHTML as well as XML (what you're showing here appears to be XML, not XHTML as the question specifies).  So once you move off dealing with a web app (which Capybara is designed for) and start dealing with random documents being rendered in browsers all bets are off.  Basically you should never be visiting a page that returns raw XML with Capybara because it's not something a user would be doing - that's more appropriate for API testing/request specs.

**Comment by twalpole** [comment]
As for the empty page - real browsers often insert human readable error pages, so no you can't assume all browsers will behave the same (just like they don't all behave the same in other things JS/CSS support/etc)

**Comment by cyrilchampier** [comment]
Hi Thomas,
indeed, in understand it just after creating the ticket, sorry for the bothering.
would not a quick mention of that in the doc would be a good idea ?

Here:
https://github.com/teamcapybara/capybara#drivers
> Capybara uses the same DSL to drive a variety of browser and headless drivers.
> Beware, like for human browser GUIs (IE, Chrome...), there is slight rendering differences between each of these drivers (empty or 404 pages for exemple).

?

**Comment by twalpole** [comment]
I thought it was pretty clear there would be differences (otherwise why support more than 1 driver/browser), but If you want to submit a PR with wording like above I'll include it.

**Comment by cyrilchampier** [comment]
Ok, let's leave it like this for now, you are right, it's clear.
The problem was probably very specific to my case where the driver changed because of a bug on our side and an xhtml page started to render "<truc />" instead of "<truc></truc>".
