### ISSUE TITLE
fill_in "field_id", with => "" does not trigger keyUp event

### ISSUE THREAD

**Issue by medihack** [teamcapybara/capybara#203]
I am using jQuery to bind a text field to the keyUp event. A `fill_in "field_id", with => "test"` works as expected (keyUp is triggered), but clearing the field with `fill_in "field_id", with => ""` does not trigger that event.

**Comment by DougMaisells** [comment]
@BMorearty  When I use your suggestion, I get undefined method `send_keys' for #<Object:0x007fc979f730d8> (NoMethodError)    
Using this
page.find(:xpath, "//input[@placeholder = 'Prefix']").set ""
      send_keys [:control, "a"]

since the Prefix field does not have an id (it's React) so I am trying to access a field with its placeholder text.  It works fine to set it to a value but even though I see the set command above clear the field, the original value is still in the field once I save the form.

**Comment by twalpole** [comment]
@DougMaisells send_keys needs to be called on an element - you probably want something like

    prefix = page.find(:field, 'Prefix')
    prefix.set ""
    prefix.send_keys [:control, "a"]

**Comment by DougMaisells** [comment]
@twalpole Unfortunately this field doesn't have an id, it's react and I had to access with page.find(:xpath) method

**Comment by DougMaisells** [comment]
@nickstreet Thanks but doesn't work.   I can see the field clear when the script runs but when as the script runs and focus travels to other fields, the former value is restored....
fill_in 'person-form-title', with: ""
      trigger_event_for('person-form-title', :keyup)
      #send_keys [:control, "a"]

      sleep 1

**Comment by twalpole** [comment]
@DougMaisells  find_field finds by id, name or placeholder text - so `find_field('Prefix')` should find the element rather than needing xpath.

**Comment by DougMaisells** [comment]
@twalpole  so do I replace the page.find up above with find_field?

**Comment by DougMaisells** [comment]
person_title = page.find(:field, 'person-form-title')
      person_title.set ""
      person_title.send_keys[:control, "a"]

gives error:   no implicit conversion of Symbol into Integer (TypeError)

**Comment by twalpole** [comment]
@DougMaisells  try

    person_title = page.find_field('person-form-title')
    person_title.set ""
    person_title.send_keys([:control, "a"])

If that still errors - tell me which line it's erring on

**Comment by DougMaisells** [comment]
@twalpole Thanks, got by run-time error but still does not persist with the zapped value.  It zaps the field as I run the scripts but the value is restored as the script travels through other fields on the form.  It must be a React thing; I'll have to get with my developer.  (I am QA)

**Comment by twalpole** [comment]
@DougMaisells  Ok -- it all depends on which event React is looking for to trigger it's model updates.  You might want to try just doing the single line - rather than separately setting and then trying to trigger the needed events

    find_field('person-form-title').send_keys([:control, "a"], :backspace)

and see if that triggers the needed events - since that should trigger key events and the change event

**Comment by DougMaisells** [comment]
@twalpole Tom, you are talking over my head now.  My extent of understanding of React is it's a javascript framework which my app and others like Facebook is written in.  I'll get with my dev.  BTW, what you suggested above didn't work either.  This time, it doesn't even render the field as zapped and it stays with its value where the other tries at least zapped the field in real-time but then it restored a moment later as it went through other fields.

**Comment by twalpole** [comment]
@DougMaisells - As I stated above my example assumed ctrl-a was selecting the contents of the field on your platform -- if howeever you're on OS X it would be cmd-a  - so then your test would be

find_field('person-form-title').send_keys([:command, "a"], :backspace)  

ie - send cmd-a to select everything then hit backspace to delete it all - anyway it may be best if you did talk with a developer about what events are required to complete the action with React

**Comment by DougMaisells** [comment]
@twalpole Ooh, I missed that connection.  Yes, I am on OSX and yes that works.   I glanced over that detail above because I wasn't sure what was being talked about.
