### ISSUE TITLE
Crash during "fill_in" with selenium webdriver and firefox

### ISSUE THREAD

**Issue by janas-sebastien** [teamcapybara/capybara#2031]
## Meta
Capybara Version: 3.0.3 and 3.1.0
Driver Information (and browser if relevant): selenium 3.11 and Firefox 59.0.3

## Expected Behavior
- When executing the code, Firefox should open, navigate to www.github.com, then type "test" in the search bar

## Actual Behavior
- crash when the code arrives at the step "fill_in", with the following stack trace

C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms.rb:8:in `read': No such file or directory @ rb_sysopen - C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms/getAttribute.js (Errno::ENOENT)
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms.rb:8:in `read_atom'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/atoms.rb:12:in `execute_atom'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/w3c/bridge.rb:445:in `element_attribute'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/element.rb:114:in `attribute'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/selenium/node.rb:31:in `[]'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/selenium/node.rb:158:in `readonly?'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/node/element.rb:301:in `block in rea
donly?'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/node/base.rb:83:in `synchronize'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/node/element.rb:301:in `readonly?'
        from C:/Ruby24-x86/lib/ruby/gems/2.4.0/gems/capybara-3.1.0.dev/lib/capybara/node/element.rb:97:in `set'
        from ./bug.rb:9:in `<main>'

## Steps to reproduce
Execute that code

require 'capybara/dsl'
require 'selenium-webdriver'

include Capybara::DSL
Capybara.default_driver = :selenium 
Capybara.javascript_driver = :selenium

visit('https://github.com/')
find("input[name$='q']").set "test"

I tried to find back the actual selenium webdriver commands that causes the bug, but did not succeed. The following webdriver code works for example

require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:firefox)
driver.navigate.to "https://github.com/"
element = driver.find_element(:name, 'q')
element.send_keys "Selenium"
element.submit
puts driver.title
driver.quit

**Comment by twalpole** [comment]
That error is coming from inside selenium-webdriver when it attempts to load `getAttribute.js` in order to check for whether or not the element is readonly.  Looking at the 3.11.0 gem that file is definitely included in it which would tend to imply your install of the gem is broken - uninstall and reinstall selenium-webdriver.
