### ISSUE TITLE
Performance issues with `all` finder

### ISSUE THREAD

**Issue by viraptor** [teamcapybara/capybara#2033]
## Meta
Capybara Version: 3.0.3, upgraded from 2.18.0

Driver Information (and browser if relevant): selenium-webdriver 3.11.0; chromedriver

## Expected Behavior

`Capybara::Session#all#(".translation_missing")` takes around the same amount of time in 3.0.3 and in 2.18.0. 

## Actual Behavior

Over multiple executions, 3.0.3 takes a much longer time on the same codebase. From log files:
```
Capybara::Session#all#(".translation_missing")
Total time: 420.56
Count: 31
Avg: 13.57
```
Compared to 2.18.0: (different test distribution between workers, so the count doesn't match exactly)
```
Capybara::Session#all#(".translation_missing")
Total time: 0.16
Count: 14
Avg: 0.01
```

## Steps to reproduce

Early report, no simple reproducer known yet. I'll update if I figure it out.

**Comment by viraptor** [comment]
Confirmed the same regression happens already in 3.0.0.rc1

**Comment by twalpole** [comment]
@viraptor Could you explain how/why you’re using `all` In situations when you expect it not to return any results?

**Comment by viraptor** [comment]
@twalpole It's used in a hook running after each cucumber test. The elements found are used to produce a nice list describing all not translated elements. The standard matcher doesn't provide the same kind of information.

**Comment by twalpole** [comment]
@viraptor - Ok, that makes sense - it's not an assertion they don't exist, you want to know if any do exist and if so report on them - so `wait: false`or `minimum: 0` options to `all` will give what you want.
