### ISSUE TITLE
Unable to find input element nested within label.

### ISSUE THREAD

**Issue by StevenXL** [teamcapybara/capybara#2036]
## Meta
Capybara Version: 2.13.0
Driver Information: selenium-webdriver 3.10.0 with ChromeDriver 2.36.540469

## Expected Behavior

When I search for an `input` element that is a descendant of a `label` element, I expect to be able to find that element via `find` / `find_all`.

## Actual Behavior
An input element nested inside  of a label element is not found by `capybara`'s finders, even though the page's source code contains the `input` element.

## Steps to reproduce

Create a page with the following source code:

```
<label>
  <span>
    <input value="false" name="authorization" type="checkbox">
  </span>
</label>
```

Then try to find the element using `find('input[name="authorization"]')`. The element will not be found.

According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), `label` elements are allowed to contain `Phrasing Content`. [Phrasing Content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) includes `input` and `span` elements.

**Comment by twalpole** [comment]
What is the exact error message you're getting because that definitely works.

**Comment by twalpole** [comment]
Heres a gist - https://gist.github.com/twalpole/fddb639fd928ee60cb6f76497127a00d - showing that it works.
