### ISSUE TITLE
Default Selenium::Node#set(clear: :option)

### ISSUE THREAD

**Issue by cyrilchampier** [teamcapybara/capybara#2038]
## Meta
Capybara Version:
(2.18.0)
Driver Information (and browser if relevant):
selenium-webdriver 3.7.0 / chrome headless

## Expected Behavior
In our app, we make a global use of the `clear: :backspace` behavior implemented here:
`Capybara::Selenium::Node#set('', clear: :backspace)`
https://github.com/teamcapybara/capybara/commit/339bebf55ec45b427970419f02e19a9b2be687f6

Is there any way currently to set this clear behavior by default ?
If not, would you accept a PR to add a `default_clear_option` in `SessionConfig::OPTIONS` ?

**Comment by twalpole** [comment]
Since the options `set` accepts are driver specific I wouldn't accept a PR for `default_clear_option`, I would however accept a PR implmenting `default_set_options` which would be a Hash.

**Comment by cyrilchampier** [comment]
perfect, I'll do that in the next days, thanks :)

**Comment by twalpole** [comment]
Closing this - will wait for PR submission.
