### ISSUE TITLE
fill_in fails against Edge

### ISSUE THREAD

**Issue by johnko27** [teamcapybara/capybara#2040]
## Meta
Capybara Version:
<all>
Driver Information (and browser if relevant):

## Expected Behavior
fill_in to enter text

## Actual Behavior
Selenium::WebDriver::Error::StaleElementReferenceError:
       Stale element reference (WARNING: The server did not provide any stacktrace information)
       Command duration or timeout: 32 milliseconds
       For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
       Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
       System info: host: 'sauce-win10', ip: '172.20.50.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
       Driver info: org.openqa.selenium.edge.EdgeDriver
       Capabilities [{applicationCacheEnabled=true, InPrivate=false, pageLoadStrategy=normal, platform=ANY, acceptSslCerts=true, browserVersion=42.17134.1.0, platformVersion=10, locationContextEnabled=true, webStorageEnabled=true, browserName=MicrosoftEdge, takesScreenshot=true, takesElementScreenshot=true, platformName=windows}]
       Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXEB3EAA7A (org.openqa.selenium.StaleElementReferenceException)

## Steps to reproduce

it look like this line in set_text fails on Edge
driver.execute_script "arguments[0].value = ''", self
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/node.rb

**Comment by twalpole** [comment]
We don't test with Edge and don't really support it since its WebDriver support is severely lacking (at last check).  That being said, StaleElementReferenceError generally means the element has left the page when you're trying to use it -- What is your test code that is generating this error?

**Comment by twalpole** [comment]
Also, what version of Capybara are you using? and if `2.52.0` is the Selenium version being used, it's obsolete and we no longer support anything below `3.x`.  Closing this until enough info to diagnose is provided.

**Comment by johnko27** [comment]
The issue is with 'capybara', '3.1.0' &  .set calls.

fill_in(@@email_textbox_locator, with: email)

work around is 

find(:fillable_field, @@email_textbox_locator).native.send_keys(email)

**Comment by twalpole** [comment]
@johnko27 First, 99.999999% of the time if you're using `native` you've gone wrong, so try `find(:fillable_field, @@email_textbox_locator).send_keys(email)`.  Second, `fill_in` is implemented as `find(:fillable_field, ...).set(...)` while `set` just clears the field and then calls `send_keys` - so if you really want it to work without a clear you can just do

    fill_in(@@email_textbox_locator, with: email, fill_options: { clear: :none }

or if you want a different type of clear you could do something like

    fill_in(@@email_textbox_locator, with: email, fill_options: { clear: :backspace }

however none of this narrows down why you're receiving the error in the first place.   Is 2.52.0 actually the version of Selenium you are using?

**Comment by johnko27** [comment]
i tried this last night.  It fails with the same error.

fill_in(@@email_textbox_locator, with: email, fill_options: {clear: :backspace})

**Comment by twalpole** [comment]
@johnko27 I don't see how that's possible, and it definitely wouldn't be coming from the same line of code.  Is there a reason you're not answering the question about what version of Selenium you are using?

**Comment by johnko27** [comment]
'selenium-webdriver', '3.7.0'

**Comment by twalpole** [comment]
@johnko27 So what is the "Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'"  you originally pasted?

**Comment by johnko27** [comment]
I am not sure.  3.7 is what is in the current gemfile.

**Comment by twalpole** [comment]
@johnko27 Are you running against a remote Selenium server? (i.e. you've specified the `url` parameter in your driver registration)

**Comment by johnko27** [comment]
Yes, for Edge the Selenium server is in Sauce Labs

**Comment by twalpole** [comment]
Ok - 2.52 is pretty much obsolete - You may want to configure Sauce Labs to use a newer version of selenium  - https://wiki.saucelabs.com/display/DOCS/_selenium_version
