### ISSUE TITLE
CSS attribute selector including comma does not match to the element in 3.2.0

### ISSUE THREAD

**Issue by yhatt** [teamcapybara/capybara#2044]
## Meta
Capybara Version: 3.2.0
Driver Information (and browser if relevant): rack-test 1.0.0 / selenium-webdriver 3.12.0 with Chrome 67.0.3396.62

## Expected Behavior

CSS attribute selector including comma should match to the element correctly in 3.2.0

## Actual Behavior

The comma included selector was working in v3.1.1, but it does not work in 3.2.0 (Raise `Capybara::ExpectationNotMet`).

```
$ ruby ./template.rb
Traceback (most recent call last):
        5: from ./template.rb:14:in `<main>'
        4: from /Users/yuki.hattori/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.2.0/lib/capybara/session.rb:734:in `block (2 levels) in <class:Session>'
        3: from /Users/yuki.hattori/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.2.0/lib/capybara/node/finders.rb:279:in `first'
        2: from /Users/yuki.hattori/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.2.0/lib/capybara/node/finders.rb:251:in `all'
        1: from /Users/yuki.hattori/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.2.0/lib/capybara/node/base.rb:83:in `synchronize'
/Users/yuki.hattori/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.2.0/lib/capybara/node/finders.rb:253:in `block in all': expected to find visible css "img[src=\"data:image/gif;base64,R0lGODdhAQABAPAAAMLCwgAAACwAAAAAAQABAAACAkQBADs=\"]" at least 1 time but there were no matches (Capybara::ExpectationNotMet)
```

The data URI scheme should include comma, so its assertion will not work.

## Steps to reproduce

```ruby
# Try in `3.1.1` and `3.2.0` to confirm an issue.
gem 'capybara', '3.2.0'

require 'capybara'

html = DATA.read
app = proc { |env| [200, { 'Content-Type' => 'text/html' }, [html] ] }

# Reproduce in rack_test and selenium_chrome(_headless) driver
sess = Capybara::Session.new(:rack_test, app)
sess.visit('/')

# CSS attribute selector including comma does not match to the element in Capybara 3.2.0.
p sess.first('img[src="data:image/gif;base64,R0lGODdhAQABAPAAAMLCwgAAACwAAAAAAQABAAACAkQBADs="]')
p sess.first('img[src*=","]')

# The other special chars like `:`, `/`, `;`, and `=` would match.
p sess.first('img[src^="data:image/gif;base64"]')
p sess.first('img[src$="R0lGODdhAQABAPAAAMLCwgAAACwAAAAAAQABAAACAkQBADs="]')

__END__

<!doctype html>
<html>
  <body>
    <img src="data:image/gif;base64,R0lGODdhAQABAPAAAMLCwgAAACwAAAAAAQABAAACAkQBADs=" />
  </body>
</html>
```

In 3.1.1, all matcher return `img` element correctly.

```
# In Capybara 3.1.1
$ ruby ./template.rb
#<Capybara::Node::Element tag="img" path="/html/body/img">
#<Capybara::Node::Element tag="img" path="/html/body/img">
#<Capybara::Node::Element tag="img" path="/html/body/img">
#<Capybara::Node::Element tag="img" path="/html/body/img">
```

**Comment by twalpole** [comment]
@yhatt I'm looking into this, although my gut reaction is that the fact it worked in < 3.2.0 was actually a bug since the comma is a special character in CSS and needs to be escaped if you want it to be a literal in a CSS selector.

**Comment by twalpole** [comment]
3.2.1 should restore the previous functionality (and fix this current issue) but there is a larger issue that needs to be fixed - I'll create a new issue for that.  Thanks for the useful issue report, and especially for including a reproducible example.

**Comment by yhatt** [comment]
@twalpole Thank you too for your swift actions. I could understand an outline of the problem well. I'll continue to subscribe a new issue.

**Comment by twalpole** [comment]
@yhatt If you have time could you please check whether the `3.2_css_parser` branch also works for you?

**Comment by yhatt** [comment]
@twalpole Thanks. We have tried `3.2_css_parser` branch in our Rails project. It has some RSpec + capybara tests using CSS attribute selector included commas, and they seem to work well. I also confirmed the other tests with capybara never fail by this updating.

**Comment by twalpole** [comment]
@yhatt Thanks -- I'll probably release a 3.2.2 in a few days with the full fix if no other issues come up in the next couple of days
