### ISSUE TITLE
find "svg" raises an error

### ISSUE THREAD

**Issue by matti** [teamcapybara/capybara#2050]
with fix #2048 

```
find "svg"
```

raises

```
Selenium::WebDriver::Error::UnknownError: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
```

but `all("svg").first` works

**Comment by twalpole** [comment]
@Matti Doing `find "svg"` where raises that error??  Replacing the `find "div svg"`  with it in the code from #2048 doesn't produce that error for me - can you provide a way to replicate?

**Comment by matti** [comment]
Sorry it might be something local, have to dig deeper ~tomorrow.

While at it I think #2051 is valid today
