### ISSUE TITLE
warning: instance variable @matcher not initialized

### ISSUE THREAD

**Issue by shaicoleman** [teamcapybara/capybara#2054]
## Meta
Capybara Version: `3.2.1`
Driver Information (and browser if relevant): `selenium-webdriver 3.12.0`

## Expected Behavior
When upgrading from Capybara 3.1.1 to 3.2.1, there shouldn't be a warning.

## Actual Behavior
I'm getting the following warning
`.../gems/capybara-3.2.1/lib/capybara/selector/filters/base.rb:28: warning: instance variable @matcher not initialized`

## Steps to reproduce
* Download sample app from https://github.com/shaicoleman/forecast
* Check out the `capybara-warning` branch
* Run `bundle exec rspec`

**Comment by twalpole** [comment]
Already fixed in 01305380e8373b916f1b794ada65c2e64ec98274
