### ISSUE TITLE
The .disabled? method does not work correctly on fieldsets

### ISSUE THREAD

**Issue by Jack12816** [teamcapybara/capybara#2059]
## Meta
Capybara Version: 3.3.0

Driver Information (and browser if relevant): selenium-webdriver 3.10.0 and Chrome Headless 67.0.3396.87

## Expected Behavior
```ruby
find('fieldset')[:disabled]
# => true
find('fieldset').disabled?
# => true
```

## Actual Behavior
```ruby
find('fieldset')[:disabled]
# => true
find('fieldset').disabled?
# => false
```

## Additional information
https://github.com/teamcapybara/capybara/issues/1925#issuecomment-336933569
https://www.w3.org/TR/html51/disabled-elements.html#disabled-elements

**Comment by twalpole** [comment]
This is because the WebDriver spec only defines disabled for form controls, but when reading the HTML spec it doesn't make any sense not to define it for fieldset elements as well.  Please try the `disable_fieldset` branch and let me know if it fixes your issue.

**Comment by Jack12816** [comment]
Solves the issue perfectly. Thanks mate! And thank you for the quick fix! :)

**Comment by Jack12816** [comment]
Could you make a patch release for this? This would be really awesome.

**Comment by twalpole** [comment]
Will probably go out in a 3.3.1 release later today, waiting for tests to complete.

**Comment by twalpole** [comment]
Released
