### ISSUE TITLE
Headless Chrome actually opens Chrome browser

### ISSUE THREAD

**Issue by fabersky** [teamcapybara/capybara#2065]
## Meta
Capybara Version: 3.3.1
Driver Information (and browser if relevant): selenium-webdriver 3.13.0, capybara-selenium 0.0.6, chromedriver-helper 1.2.0, chromedriver 2.40, Google Chrome 67.0.3396.99

## Expected Behavior

Running rspec with headless_chrome won't open a Google Chrome browser window

## Actual Behavior
Running rspec with headless_chrome opens a Google Chrome browser window

## Steps to reproduce
```
require 'rspec'
require 'capybara'
require 'capybara/rspec'
require 'selenium/webdriver'

Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[ headless
                               disable-gpu
                               mute-audio
                               disable-extensions
                               disable-password-generation
                               disable-password-manager-reauthentication
                               disable-save-password-bubble
                               window-size=1280,800)
                             ]
                    }
  )
  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    desired_capabilities: capabilities
  )
end

Capybara.default_driver = :headless_chrome
```

When running `rspec test_spec.rb`, it opens a new Chrome Window. It wasn't happening until last week and the last `bundle update`.

**Comment by twalpole** [comment]
This is because chromedriver doesn't accept a `chromeOptions` parameter and really isn't anything to do with Capybara. See https://github.com/teamcapybara/capybara/blob/master/lib/capybara.rb#L500 and https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/chrome/options.rb#L28

**Comment by fabersky** [comment]
Thank you very much @twalpole!
