### ISSUE TITLE
Misspelled method name in matchers.rb

### ISSUE THREAD

**Issue by Zajn** [teamcapybara/capybara#2081]
## Meta
Capybara Version:
3.5.0

I hope this is the correct place to make note of this, but in reviewing capybara updates from 3.4.2 --> 3.5.0 at work, I noticed that a misspelled method name slipped through:

https://github.com/teamcapybara/capybara/blob/4642424530dd4d6b5939b252e63aef1cdea26b5c/lib/capybara/node/matchers.rb#L543

https://github.com/teamcapybara/capybara/commit/919e4df2a87d70f7c387e04375cc2b5dc12ea777#diff-5b48908a3d2bd3374aaef7b6394f1912R544

It looks like the method is deprecated, so it might not be that big of a deal, but anyone who had been using that method anyway might get bitten.

Sorry if this isn't the right space for this!

**Comment by twalpole** [comment]
Thanks for catching this --  Fixed via f13f1244bcac1b01b6c8e4ed79c8f2c409d68c70 - I will release 3.5.1 later today or tomorrow.

**Comment by twalpole** [comment]
Released 3.5.1
