### ISSUE TITLE
click_on / click_link_or_button does not support custom filters for buttons

### ISSUE THREAD

**Issue by shepmaster** [teamcapybara/capybara#2084]
## Meta
Capybara Version: 3.6.0
Driver Information: selenium-webdriver 3.14.0 with Firefox 61.0.2 

## Expected Behavior

The extra filter would be allowed as if we called `click_button` directly.

## Actual Behavior

```
     Failure/Error: click_on(build_button: "Build")

     ArgumentError:
       invalid keys :build_button, should be one of :count, :minimum, :maximum, :between, :text, :id, :class, :visible, :exact, :exact_text, :match, :wait, :filter_set, :disabled
     # .../gems/capybara-3.6.0/lib/capybara/queries/selector_query.rb:213:in `assert_valid_keys'
     # .../gems/capybara-3.6.0/lib/capybara/queries/selector_query.rb:32:in `initialize'
     # .../gems/capybara-3.6.0/lib/capybara/node/finders.rb:33:in `new'
     # .../gems/capybara-3.6.0/lib/capybara/node/finders.rb:33:in `find'
     # .../gems/capybara-3.6.0/lib/capybara/node/actions.rb:24:in `click_link_or_button'
     # .../gems/capybara-3.6.0/lib/capybara/session.rb:736:in `block (2 levels) in <class:Session>'
     # .../gems/capybara-3.6.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/compilation_targets_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/support/playground_actions.rb:32:in `block in in_menu'
     # .../gems/capybara-3.6.0/lib/capybara/session.rb:336:in `within'
     # .../gems/capybara-3.6.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # .../gems/capybara-3.6.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/support/playground_actions.rb:32:in `in_menu'
     # ./spec/support/playground_actions.rb:5:in `in_build_menu'
     # ./spec/features/compilation_targets_spec.rb:32:in `block (3 levels) in <top (required)>'
```
## Steps to reproduce

Modify the `:button` selector with a new filter:

```ruby
Capybara.modify_selector(:button) do
  node_filter(:build_button) {|node, name| node.has_selector?('.button-menu-item__name', text: name) }
end
```

Use the new filter with `click_on`:

```ruby
click_on(build_button: "Build")
```

**Comment by twalpole** [comment]
`click_on` is an alias for `click_link_or_button` and uses the `:link_or_button` selector type  - If you want a 'build_button' option available in `click_on` you need to modify the `:link_or_button` selector rather than the `:button` selector

**Comment by twalpole** [comment]
Also note that your :build_button filter would be more efficient as an expression filter rather than a node filter - something like (untested)

    Capybara.modify_selector(:link_or_button) do
        expression_filter(:build_button) do |expr, name|
          expr[XPath.css('.button-menu-item__name').contains(name)]
        end
    end

**Comment by shepmaster** [comment]
This doesn't seem to be a *bug* and I've solved my specific problem so I'll close this.

I do think it would be *nice* if `:link_or_button` was just a transparent union of `:link` and `:button`. If you agree, feel free to use this as your issue 😉 .

**Comment by twalpole** [comment]
Technically you can use `filter_set` to import filters from one selector type into another, however in your case just creating one Proc and using on both would probably be simpler clearer. 

`expression_filter` is always going to be more efficient because it limits the number of elements returned by modifying the XPath/CSS used for the initial query.  When using a `node_filter` it gets all the matching elements and then applies the node_filter to each one - which usually involves more calls back to the browser to get the attributes/properties being queried (or in your case performing another query).  The downside to `expression_filter` is they can only query on the HTML - not on dynamic properties of elements.

**Comment by twalpole** [comment]
`:link_or_button` isn't a transparent union because it's really more of a least common denominator join since not everything for a link makes sense for a button (`href` for instance)

**Comment by shepmaster** [comment]
As always, thank you for your help, advice, and work on great tools like Capybara!
