### ISSUE TITLE
Capybara::Node::Actions#select is triggering a click event on the selected element

### ISSUE THREAD

**Issue by gabynr** [teamcapybara/capybara#2111]
## Meta
Capybara Version: 3.4.2
Driver Information: ChromeDriver 2.36.540469

## Expected Behavior
Using `Capybara::Node::Actions#select` should not trigger a click event on the element changing value, because browsers don't trigger the click event.

## Actual Behavior
Using `Capybara::Node::Actions#select` is triggering a click event on the element.

## Steps to reproduce
Testing code:
```
page.select 'mysql', from: 'connection[driver]'
```

Javascript:
```
$(document).on "turbolinks:load", ->
  $('#connection_driver').on "click", ->
    console.log 'clicked'
```

HTML:
```
<select class="form-control" name="connection[driver]" id="connection_driver"><option value=""> Please select  a driver</option>
<option value="mysql">mysql</option></select>
```

**Comment by twalpole** [comment]
A user clicking on the select element to open it and select one of the options does generate a click event, so I'm not sure what you're trying to show here?

**Comment by gabynr** [comment]
Hi @twalpole  the click event behaviour on select fields is not consistent between browsers:

- In Safari: is very hard to get the click event triggering, you'll have to double or triple click really fast on the select to get it happening.
- In Firefox: the click event is not triggered until you change the value of the select, if you don't change the value then it isn't triggered.
- In Chrome: the click event is triggered as soon as the select box is clicked.

In all 3 browsers the click is not triggered when changing the select value using tab navigation and just the keyboard.

Therefore, given the inconsistencies between browsers and the fact that select can be used without the mouse, then I think the click event shouldn't be triggered by capybara on doing a select action.

**Comment by twalpole** [comment]
@gabynr Considering that most user interaction with select fields is via a mouse and the example you show when using Chrome behaves exactly like Chrome (the most used browser and the one you're using) using a mouse I'm not sure why you believe this should be changed. This behavior is also explicitly defined in the WebDriver spec.  We're not going to be changing this behavior without a much better reason.
