### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2120]
Capybara 3.10.0, Selenium 3.14.1 used via JRuby.

```
     NoMethodError:
       undefined method `+' for nil:NilClass
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/selenium/node.rb:184:in `path'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/element.rb:442:in `inspect'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/queries/selector_query.rb:52:in `description'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/queries/selector_query.rb:57:in `applied_description'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/queries/selector_query.rb:115:in `failure_message'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/result.rb:105:in `failure_message'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/matchers.rb:104:in `block in assert_selector'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/matchers.rb:740:in `block in _verify_selector_result'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/base.rb:82:in `synchronize'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/matchers.rb:739:in `_verify_selector_result'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/node/matchers.rb:102:in `assert_selector'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/rspec/matchers.rb:67:in `element_matches?'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.10.0/lib/capybara/rspec/matchers.rb:51:in `matches?'
     ...
```

This is very sporadic in our test suite and I'm not sure what's causing it but in any case Capybara should give an error message and not blow up with a `NoMethodError`. Please tell me how I can help more.

**Comment by twalpole** [comment]
What type of element is the scoping element you are searching within ?

**Comment by boris-petrov** [comment]
This is the code that causes this exception:

```ruby
dropdown = find('.navbar a', text: 'Some text').find(:xpath, './following-sibling::*[1]', visible: :all)
expect(dropdown).to have_css('a', visible: :all, exact_text: name)
```

The second line is followed by the stacktrace that I pasted earlier.

**Comment by twalpole** [comment]
The following-sibling is creating an issue when trying to generate the path of the scoping element if no matching ‘a’ element is found. I’ll try and have a fix out later today (California time)

**Comment by twalpole** [comment]
Hmmm -- this might not actually have anything to do with the `sibling` portion of it -- is it possible the dropdown element is going away while `have_css` is running?

**Comment by twalpole** [comment]
I have not been able to reproduce this - but have put in a fix at the current point of failure - Please try branch `issue_2120` and see if that fixes things for you.

**Comment by boris-petrov** [comment]
Thanks for the support! This code is not run in an `within` block, however it is possible that the dropdown is rerendered, yes. Which means that it disappears and is redrawn. We expect that in this case Capybara would just retry the `have_css` check. Is that wrong as an assumption? We use a single-page-application framework (Ember.js) which redraws stuff all the time and such race-conditions are ubiquitous.

**Comment by twalpole** [comment]
@boris-petrov Yes it should retry (if the `undefined method` error hadn't raised), I was just trying to narrow down how the error came about so I could generate a test case for it.

**Comment by twalpole** [comment]
I've merged this in to master branch now -- I'm going to close this issue, we can reopen if the problem still occurs.
