### ISSUE TITLE
iframe method no longer finds elements inside the frame

### ISSUE THREAD

**Issue by souljadev** [teamcapybara/capybara#2127]
I am updating a broken test because the test I had written initially no longer works. I am trying to find elements inside an IFrame, but the method I wrote cannot find any.  I can only find elements outside of the Iframe. Is this because of a version change? or do I need to update a gem? 

## Meta

  gem 'activesupport', '>= 4.0.0'
  gem 'gauge-ruby', '~>0.4'
  gem 'pry'
  gem 'rubocop', '~> 0.48.0'
  gem 'selenium-webdriver', '~> 3.8.0'
  gem 'site_prism', '~> 2.9'
  gem 'test-unit', '~> 3.2.3'
  gem 'chromedriver-helper', '1.1.0'
  gem 'capybara', '2.15.1'

## Expected Behavior
To be able to find(elements) within the frame.

## Actual Behavior
Error Message: Unable to find visible css

I can find elements outside of the frame but I cannot find any css elements inside the frame. 

## Steps to reproduce
I tried both methods

          page.driver.browser.switch_to.frame('IFrameHolder')
          find('div.example')
or
```
          within_frame('IFrameHolder') do
                find('div.example')
           end
```
Any insight on this will be helpful. Thanks in advance!

**Comment by twalpole** [comment]
Show the code you're trying to run - also you're running really old versions of Capybara and selenium-webdriver

**Comment by souljadev** [comment]
Do you think the old versions have a problem? It worked prior like a month ago.  Nothing's change in my code. 

       
` def verify_on_login(account_name)
          page.driver.browser.switch_to.frame('IFrameHolder')
          find('span#lblContentServiceDisplayName', text: account_name)
          page.driver.browser.switch_to.default_content
        end`

**Comment by twalpole** [comment]
Whenever someone says "Nothing has changed" - something has always changed.  Either you updated the browser, or you updated chromedriver, or your site changed.  If nothing had changed then it would still be working the same way it was.  Also you code is calling driver specific methods (`page.driver.browser....)  which is terrible practice when there are Capybara methods that wrap the same behavior but allow Capybara to actually know what is being done.

**Comment by souljadev** [comment]
I agree, so if the site has changed, what would prevent me from targeting the Iframe elements?

How do I go about finding what exactly changed? There was another method I was using to resize the window. This method also does not work anymore, do you think it's a related issue?

```
page.driver.maximize_window(windows[0].handle)
```


Would this method be better, instead of calling driver specific method? 

```
       within_frame('IFrameHolder') do
                find('div.example')
           end
```

**Comment by twalpole** [comment]
If the site changed, nothing would prevent you from targeting the iframe elements unless they changed the iframe elements, or the names/ids of the elements in the iframes, etc.  

As for the code - yes, that would be better (depending on exactly what `IFrameHolder` refers to.  I have no idea why `page.driver.maximize_window` would stop working, but again it's driver specific so not really to do with Capybara.  

Closing this issue since none of it appears to be an actual Capybara issue.

**Comment by souljadev** [comment]
Thanks for your help
