### ISSUE TITLE
When Click on link return a different URL

### ISSUE THREAD

**Issue by luizlohn** [teamcapybara/capybara#2148]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

Driver Information (and browser if relevant):
All browsers

## Expected Behavior
When I click on link to change Language(its just a /en link) on normal browser its work and change for language

## Actual Behavior
When I click on link to change Language the driver put a page error between base URL and Link
If you enter here: https://ferique-cd.azurewebsites.net/fr-FR/ and click on English to change its OK, will change, but when I do that through Capybara do not work

## Steps to reproduce
If you enter here: https://ferique-cd.azurewebsites.net/fr-FR/ and click on English to change its OK, will change, but when I do that through Capybara do not work.
If necessary I have a video

**Comment by twalpole** [comment]
Show the code you're using - and identify what driver/browser you're using

**Comment by twalpole** [comment]
The following code works fine for this, so I'm going to close this issue until a way to reproduce, and details of what you're using are provided.

    require 'capybara/dsl'
    require 'selenium-webdriver'

    session = Capybara::Session.new(:selenium_chrome)

    session.visit('https://ferique-cd.azurewebsites.net/fr-FR/')
    session.within('#nav') do
      session.click_link('English')
    end
    session.assert_text('Already a client?')

**Comment by luizlohn** [comment]
I`m using site_prism, 
PageObect:
`
# Elements from Login Page
class LoginFormSection < SitePrism::Section
  element :user_field, '#loginEmail'
  element :pass_field, '#loginPassword'
  element :user_title, '.signin-form__form > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)'
  element :pass_title, 'div.form-element:nth-child(2) > div:nth-child(1) > div:nth-child(1) > label:nth-child(1)'
  element :submit_button, 'button.btn'
  element :show_password, '.visibility'
  element :forgot_credential, 'div.signin-form__form--helper:nth-child(4)'
  element :forgot_user, 'div.signin-form__form--helper:nth-child(4) > a:nth-child(1)'
  element :forgot_pass, 'div.signin-form__form--helper:nth-child(4) > a:nth-child(2)'
  element :remember_me_text, 'div.signin-form__placeholder > div > form > div.signin-form__form--rememberme > div > div > label > span.input-label'
  element :remember_me, 'div.signin-form__placeholder > div > form > div.signin-form__form--rememberme'
  element :login_error, '#signin-form > div.signin-form__placeholder > div > form > div.input-group.show > span'
  element :blocked_account_message, 'div.signin-form__placeholder > div > form > div.input-group.show > span'
  element :recaptcha, '#recaptcha-anchor > div.recaptcha-checkbox-checkmark'
end

class RecoveryCredentialSection < SitePrism::Section
  element :forgot_user, 'a:nth-child(1)'
  element :forgot_pass, 'a:nth-child(2)'
end

class HeaderSection < SitePrism::Section
  element :logo_image, 'img.nav__logo--image:nth-child(1)'
  element :page_title, '.nav__plotline'
  element :language, '#nav > ul > li.nav__lang'
end

class FooterSection < SitePrism::Section
  element :footer, '#footer > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)'
  element :footer_title, '.footer__plotline > span:nth-child(1)'
  element :footer_week, '.footer__directions--workweek > span:nth-child(2)'
  element :help_button, 'a.btn:nth-child(1)'
  element :ferique_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(2) > a:nth-child(1)'
  element :security_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(3) > a:nth-child(1)'
  element :privacy_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(4) > a:nth-child(1)'
  element :legal_notice_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(5) > a:nth-child(1)'
  element :language_link, '.footer__hotlinks > ul:nth-child(1) > li:nth-child(6) > a:nth-child(1)'
  element :montreal_phone, 'li.footer__directions--sectiontitle:nth-child(2)'
  element :toll_free_phone, 'li.footer__directions--sectiontitle:nth-child(3)'
  element :send_message, 'li.footer__directions--sectiontitle:nth-child(4)'
end

class RequestAccessLink <SitePrism::Section
  element :request_access_text, '.signin-component__footer'
  element :request_access_button, '.signin-component__footer > a:nth-child(1)'
end

class SecurityPrivate <SitePrism::Section
  element :request_access_text, '.signin-component__footer'
  element :request_access_button, '.signin-component__footer > a:nth-child(1)'
end


class LoginPage < SitePrism::Page
  set_url "/{language}"

  section :login_form, LoginFormSection, '#signin-form'
  section :recovery_section, RecoveryCredentialSection, 'div.signin-form__form--helper:nth-child(4)'
  section :header_section, HeaderSection, '#nav'
  section :footer_section, FooterSection, '#footer'
  section :request_access, RequestAccessLink, '.signin-wrapper > div:nth-child(2)'
  section :security_private, SecurityPrivate, '#secure-private'

end

`

To load
`login_page = LoginPage.new
  login_page.load(language: ENV['LANGUAGE'])
  $header = login_page.header_section
`
And I click

`$header.language.click`

But when I click driver get the link and put  set_url "/{language}" again together link and this broken

**Comment by twalpole** [comment]
@luizlohn You might want to ask somewhere that supports site_prism.  I've provided code that shows Capybara works just fine.  

One thing you might want to check is that your `language` element is defined starting with `#nav` but you have it inside a HeaderSection already defined as `#nav` - Without looking into site_prism I would assume it will take those and when you do `login_page.header_section.language` look for an element matching the CSS `#nav #nav > ul > li.nav__lang` which would obviously be wrong (and I would imagine be shown in any error message returned).  That, however, is nothing to do with Capybara and I could be interpreting what site_prism would do incorrectly.
