### ISSUE TITLE
Attach file fails in Firefox and Windows 10

### ISSUE THREAD

**Issue by papitoio** [teamcapybara/capybara#2155]
## Meta
Capybara Version: 3.13.2
Driver Information (and browser if relevant): Selenium Driver with Firefox 65 on Windows 10

Capybara.configure do |config|
  config.default_driver = :selenium
end

## Expected Behavior
Upload with success

## Actual Behavior
     Failure/Error: attach_file('file-upload', @arquivo)

     Selenium::WebDriver::Error::InvalidArgumentError:
       File not found: C:/project/spec/fixtures/arquivo.txt
     # WebDriverError@chrome://marionette/content/error.js:179:5
     # InvalidArgumentError@chrome://marionette/content/error.js:306:5
     # interaction.uploadFiles@chrome://marionette/content/interaction.js:502:13
     # ./spec/upload_spec.rb:11:in `block (2 levels) in <top (required)>'

## Steps to reproduce
       @arquivo = Dir.pwd + '/spec/fixtures/arquivo.txt'
        attach_file('file-upload', @arquivo)
        click_button 'Upload'

        div_arquivo = find('#uploaded-file')
        expect(div_arquivo.text).to eql 'arquivo.txt'

**Comment by twalpole** [comment]
You need to translate / to \ in the filename string since you're on windows

**Comment by lflucasferreira** [comment]
I am facing the same issue. And I am translating / to \ if "OS.windows?" as you can see below.

It works in Chrome but not in Firefox 68.0 (64-bits).

def attach_doc_file(id, file)
    path = File.join(Dir.pwd, "features/support/public/doc/#{file}")
    path = path.tr('/', '\\') if OS.windows?
    attach_file(id, path)
  end

**Comment by twalpole** [comment]
@lflucasferreira What is the actual error you get?

**Comment by lflucasferreira** [comment]
This is the actual error:

File not found: C:/Project/cnb/features/support/public/doc/CEP_Upload.xml (Selenium::WebDriver::Error::InvalidArgumentError)
      WebDriverError@chrome://marionette/content/error.js:179:5
      InvalidArgumentError@chrome://marionette/content/error.js:306:5
      interaction.uploadFiles@chrome://marionette/content/interaction.js:501:13

**Comment by twalpole** [comment]
@lflucasferreira Are you working with a remote driver by any chance?

**Comment by twalpole** [comment]
@lflucasferreira If you're not but you're using Capybara >= 3.24, could you please try 3.23 and see if the issue goes away.

**Comment by lflucasferreira** [comment]
You are right. I downgraded the version to 3.23 and it worked. I was using 3.25. Do you know if this is gonna be fixed soon? Thank you!

**Comment by twalpole** [comment]
@lflucasferreira https://github.com/teamcapybara/capybara/commit/c059bfe0ce510fd60e5518fd185e9ffffc301de7 is the change that broke this -- I'm make a quick fix that only expands if the path is relative but then I need to think about a better way to handle this.

**Comment by twalpole** [comment]
@lflucasferreira Please see https://github.com/teamcapybara/capybara/issues/2228 and provide feedback
