### ISSUE TITLE
Multiple issues with Capybara 3.13.0+

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2162]
Using Chromium. After updating to 3.13.0 a bunch of our tests started failing. This also continued with 3.13.1 and 3.13.2. I waited hoping this would get fixed in 3.14.0 but it didn't so I opened the issue.

I'm seeing at least 2 different types of issues:

1) `.set` on an Element doesn't set the full text any more. For example I do `.set('main project')` but only `m` get's typed or any other substring of what I've written. This doesn't happen in 3.12.0. I think I've seen similar things before so I want to ask - is there any part of the code concerning writing text in fields in Capybara changed between 3.12.0 and 3.13.0? Do you have any idea what might be wrong?

2) Having code like:

```ruby
expect(page).to have_css('.fc-event', text: 'Test the calendars')
```

Fails with `expected to find css ".fc-event" but there were no matches` - which is obviously wrong as in the screenshot saved there are `.fc-event` elements just not with the correct text (the text is wrong due to issue number 1 above - it's something like `Test th`). The error is definitely wrong. Capybara does note when it finds elements when only the filters are not matched but it doesn't do it in this case which I guess is a bug.

There may be more problems, not sure yet. I would like to fix the first one and then see if everything is fine after that.

**Comment by twalpole** [comment]
@boris-petrov Nothing changed in the setting of elements between 3.12 and 3.13. A few other things that could possibly have changed are 
  1. you updated Chrome, but don't have the latest chromedriver that supports it
  2. you updated chromedriver and there's a bug in it. 

However the most likely cause of this is that you have recently added/changed/upgraded React behaviors on the page.  If you had listed a longer string than just `m` I would put this guess at about a 98% chance of being correct, with just `m` being set it's probably around 85%.  Did you make React changes at around the same time as you updated to Capybara 3.13?

**Comment by boris-petrov** [comment]
Thank you for the answer.

I'm using the latest Chromium (72.0.3626.119) and chromedriver (2.46.628388). I haven't updated anything besides Capybara. Also, I reproduce the problems consistently by just going from 3.12.0 to 3.13.0.

I'm not sure whether by `React` you mean the frontend framework. If so, we're actually using Ember.js. I haven't updated it. As I said, I just change Capybara's version and tests start failing consistently.

`DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS=true` seems to fix all of the issues that I've written in the original post. All our tests pass on Capybara 3.14.0 with `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS=true`. Does that give any clues? Can I help with debugging in any way?

**Comment by twalpole** [comment]
@boris-petrov `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS` shouldn't affect the filling in of elements at all -- It would only affect the finding of elements. Also - https://dependabot.com/compatibility-score/?dependency-name=capybara&package-manager=bundler&previous-version=3.12.0&new-version=3.13.0 shows that this isn't a common issue.  Can you show some code that fails? Also what do you have `Capybara.default_max_wait_time` set to?

**Comment by boris-petrov** [comment]
I've set `Capybara.default_max_wait_time` to `10`. `Capybara.disable_animation` is `true`. `Capybara.run_server` is `false`. I don't think these have anything to do with the problem though.

The code that breaks is this one:

```ruby
  def find_element_following_label(label, element_type, options = {})
    following_element = find('.some-class', exact_text: label).find(:xpath, './following-sibling::*[1]')
    return following_element if following_element.matches_css?(element_type, options.merge(wait: 0))
    following_element.first(element_type, options)
  end

  def fill_in_form_field(label, value)
    find_element_following_label(label, 'input, textarea').set(value)
  end

  ...

  fill_in_form_field('Name', 'Test the calendars')
```

And, again, 3.13.0+ without `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS=true` writes less text than `Test the calendars` which causes the test to fail after that. This particular case happens in a Bootstrap modal dialog... not sure if it matters. I'll run all tests and check the failures if it has anything to do with that.

I can try printing stuff for you in Capybara's code so we can debug it easier?

**Comment by boris-petrov** [comment]
OK, a bit more information. As I said in the first post, I thought I've seen a similar problem before. I searched in our tests for `.modal` and I saw that in a number of places where we input text in fields in modals - before that we do `sleep 1 if Capybara.current_driver == :chrome`. I remember that this fixes the same problem in other places. Obviously now it started appearing in the places where we don't sleep too for some reason (and again - this is 100% consistent - I update 3.12.0 to 3.13.0 and these tests start failing). I tried putting the same code in the places that fail and this seems to fix it. Does that make any sense? Is that a bug in chromedriver maybe?

There are a few more failing tests even with these "fixes" and they seem to be because Capybara is clicking on the wrong place - but I'll have to get back to you about those on Thursday.

**Comment by twalpole** [comment]
@boris-petrov Well without disabling the optimizations it would return the element quicker -- If it finds the element, starts to fill it, and then the page replaces/iinitializes the element being filled that could be the issue.  With the optimization disabled it would find the elements quicker so that might be putting it into that race condition.  What exactly does your code do when opening the modal?

**Comment by boris-petrov** [comment]
Aha, I see what you're saying. This optimization with finding elements quicker - was it introduced in 3.13.0?

If our code redraws the elements in the modal, then this is our bug and not Capybara's. I'll get back to you on this one.

**Comment by twalpole** [comment]
@boris-petrov Also, is there any reason you've written `find_element_following_label` the way you have? It would be more efficient to just do it in the XPath using the descendant-or-self axis

**Comment by boris-petrov** [comment]
No reason, I just don't know XPath. :) Thanks for pointing that out!

So, I'll research a bit more what our application does and why it (most likely) redraws modals and I'll get back to you on Thursday and I'll close the issue then if this is the case and you're fine with that.

Thank you very much for the support!

**Comment by twalpole** [comment]
That's fine -- Hopefully that is what happening.  If it is redrawing stuff on the modal see if there is a class change or something you can expect on since that would obviously be better than adding sleeps.

**Comment by twalpole** [comment]
@boris-petrov On the XPath I think it would be something like

    ....find(:xpath, './following-sibling::*[1]/*[descendant-or-self::input or descendant-or-self::textarea]')

Obviously you'd have to build the last part by splitting the `element_type` argument.  Note: I haven't actually tried that XPath so it might not be fully correct - but it should be along those lines.

**Comment by boris-petrov** [comment]
@twalpole - I spent some time with this issue and yes, for some reason some of our modal dialogs are being redrawn and I guess that causes this issue here. Thank you very much for the great support and sorry for the confusion I caused by errors in our own code!
