### ISSUE TITLE
:link selector with test_id configured generates incorrect xpath

### ISSUE THREAD

**Issue by bingjyang** [teamcapybara/capybara#2166]
## Meta
Capybara Version: 3.14.4
Driver Information (and browser if relevant): N/A

## Expected Behavior

Assume, `Capybara.test_id == 'data-test-id'`

`page.find_all(:link, 'unique-value')` should return a single link with `[data-test-id=unique-value]`

## Actual Behavior

`page.find_all(:link, 'unique-value')` returns all links with a `data-test-id` attribute regardless of value

## Steps to reproduce

See above

## Notes

https://github.com/teamcapybara/capybara/blob/a61790eac20fc60ce014eda02956ce84d74b9159/lib/capybara/selector.rb#L104

This line should be changed to `matchers << (XPath.attr(test_id) == locator) if test_id`. 

Because the `<<` takes precedence over the `==`, what's actually happening is essentially `(matchers << XPath.attr(test_id)) == locator if test_id`.

**Comment by twalpole** [comment]
Thanks for catching and reporting this -- great issue report!  https://github.com/teamcapybara/capybara/pull/2167 should fix this, will merge into master once tests have passed.

**Comment by twalpole** [comment]
Closed via PR #2167

**Comment by bingjyang** [comment]
Wow, appreciate the quick turnaround. Thanks for all the good work!
