### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by guilhermecgs** [teamcapybara/capybara#2175]
**Documentation** 

![image](https://user-images.githubusercontent.com/8465337/55507998-53bf2c00-562f-11e9-9be0-52922b4f2611.png)

**Real World**

![image](https://user-images.githubusercontent.com/8465337/55507925-31c5a980-562f-11e9-94fe-f978fd138c25.png)

**Comment by twalpole** [comment]
Thanks for catching this -- I obviously missed it when doing the 3.16 release - fixed

**Comment by twalpole** [comment]
btw. Ruby 2.3 was scheduled for EOL on 3/31 - so it's not getting security updates anymore.  If you are actually still running it, it would be a good time to update

**Comment by guilhermecgs** [comment]
Could not install MSYS2... not sure why...  I am staying in the 2.3 ... for now...

**Comment by twalpole** [comment]
That's your prerogative, although I wouldn't want to be running anything that's not getting security updates on publicly accessible machines.
