### ISSUE TITLE
Can't silent custom webserver

### ISSUE THREAD

**Issue by SomeWhereSomeHow** [teamcapybara/capybara#2176]
## Meta
Capybara Version: 3.14.0
Thin Version: 1.7.2

## Expected Behavior

Giving the "silent=true" flag when assigning a custom webserver, supresses the console output.

## Actual Behavior

I registered thin as webserver which works just fine, sadly I cannot suppress it's console output, which is messing up my test result output. As the 'silent' option, which works for webrick, doesn't work for thin (I guess any other custom webserver).

## Steps to reproduce

  Capybara.register_server :thin do |app, port, host|
    require 'rack/handler/thin'
    Rack::Handler::Thin.run(app, :Port => port, :Host => host)
  end

  Capybara.server = :webrick, { Silent: true } <- Works
  Capybara.server = :thin, { Silent: true } <- silent flag does nothing for thin?

**Comment by twalpole** [comment]
Passing options to the registered server can only do anything if you write your custom server block to accept the options and do something with them.  To do that your server block would need to accept an options hash as the last parameter and do with them whatever would be necessary for the behavior you want.  See - https://github.com/teamcapybara/capybara/blob/master/lib/capybara.rb#L479

**Comment by SomeWhereSomeHow** [comment]
Thanks for the hint @twalpole, works like a charm.
