### ISSUE TITLE
Rack driver renders template tag

### ISSUE THREAD

**Issue by aadityataparia** [teamcapybara/capybara#2189]
## Meta
Capybara Version: 3.18.0
Driver Information (and browser if relevant): Rack

## Expected Behavior
`template` tag shouldn't be rendered, i.e. you should be able to select anything, or do anything with elements inside

## Actual Behavior
`template` tag is rendered, and you can select/change elements inside. This is a problem since I don't want `find` or similar methods to look inside template.

## Steps to reproduce
add `<template></template>` tag in html

**Comment by twalpole** [comment]
Fixed via 8faa557c45cfb8b60643d64fbf76542781af71a6 - Thanks for reporting this!

**Comment by aadityataparia** [comment]
Thank you very much @twalpole !
