### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by VitaliyLazebny** [teamcapybara/capybara#2214]
## Meta
Capybara Version: 3.22.0
Driver Information (and browser if relevant): capybara-webkit

## Expected Behavior
string
`is_expected.to have_xpath("//form[.//input[@value='#{report_type}']]", text: help)`
passes validation

## Actual Behavior
**SystemStackError: stack level too deep**

```
.....................................
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb:33:in `session'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/queries/selector_query.rb:180:in `try_text_match_in_expression?'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/queries/selector_query.rb:117:in `xpath'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/queries/selector_query.rb:218:in `find_nodes_by_selector_format'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/queries/selector_query.rb:131:in `block in resolve_for'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/node/simple.rb:150:in `synchronize'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/queries/selector_query.rb:130:in `resolve_for'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/node/matchers.rb:832:in `block in _verify_selector_result'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/node/simple.rb:150:in `synchronize'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/node/matchers.rb:831:in `_verify_selector_result'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/node/matchers.rb:109:in `assert_selector'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/rspec/matchers/have_selector.rb:13:in `element_matches?'
     # /usr/local/bundle/gems/capybara-3.22.0/lib/capybara/rspec/matchers/base.rb:43:in `matches?'
     # ./spec/views/admin/company_reports/index_spec.rb:38:in `block (3 levels) in <top (required)>'
```

## Steps to reproduce
Code from test:
`is_expected.to have_xpath("//form[.//input[@value='#{report_type}']]", text: help)`

the issue is reproduced only if there's parameter "text". If I remove it: the issue is not reproduced.
I tried to reproduce it with different capybara versions. It's not reproduced with 3.12.0 and can be reproduced with versions starting 3.13.0 and later.

**Comment by twalpole** [comment]
Hmm - from the stacktrace that would appear to be an issue in actionpack-5.0.7/lib/action_dispatch/testing/test_process.rb where the `session` method just keeps calling itself.

**Comment by twalpole** [comment]
What is the subject of your test?

**Comment by VitaliyLazebny** [comment]
> subject.class
ActiveSupport::SafeBuffer

> subject
"<div aria-multiselectable=\"true\" class=\"panel-group\" id=\"accordion\" role=\"tablist\"><div class=\"panel panel-default\">...</div></div>"

**Comment by twalpole** [comment]
Have you done something like include Capybara::DSL into the global Object ??  There's no way `ActiveSupport::SafeBuffer` should be responding to `#has_selector?` or `#session`  which (I think)  it would have to be for this to happen.

**Comment by twalpole** [comment]
Closing due to lack of response
