### ISSUE TITLE
My test suite is printing a lot of deprecation warnings "selector :link must be an instance of String or Symbol", but I can't find the source

### ISSUE THREAD

**Issue by ndbroadbent** [teamcapybara/capybara#2216]
I upgraded to Capybara `3.22.0`, and I'm now seeing this deprecation warning many times in my test suite:

```
Locator Integer:3 for selector :link must be an instance of String or Symbol. This will raise an error in a future version of Capybara.
```

I run my tests in a random order, so I've been having some trouble narrowing this down to a single Capybara spec that shows the error, and then trying to somehow step through all of my tests (and dependencies) to try to figure out the source.

Could you please add an option to crash on these warnings and show a full stack trace? I think the easiest way forward is for me to fork capybara and change these warnings to raise errors, but it would be nice if this option was already available in the original gem.

## Meta

Capybara Version: `3.22.0`

Driver Information (and browser if relevant): `selenium-webdriver 3.142.3`

**Comment by ndbroadbent** [comment]
I've forked the gem and changed this line to raise an error instead of printing to stderr. You can get this behaviour by adding this to your Gemfile:

```
gem 'capybara', github: 'DocSpring/capybara', branch: :crash_on_deprecations
```

Then I was able to look at the stack trace to which line of code was causing the warning:

```
expect(page).to have_link(model.id, href: show_path)
```

(I was testing some admin CRUD views where it shows a link with the model ID)

Hope that helps someone else!

**Comment by twalpole** [comment]
Closing this since it's not really an issue with Capybara - If you want to submit a PR that shows the line the deprecation is coming from in the deprecation notice I'm willing to consider that -- crashing on deprecations is not something Capybara will be supporting though.
