### ISSUE TITLE
Date typo in History.md

### ISSUE THREAD

**Issue by tarragon** [teamcapybara/capybara#2220]
Unless someone invented a time machine, I'm pretty sure the 3.24.0 wasn't released on 2079-06-13. ;)

![image](https://user-images.githubusercontent.com/7235/59482931-54d1cc80-8eae-11e9-8999-ec2b14ff2020.png)

**Comment by twalpole** [comment]
Whoops -- fixed via ea8f81d682e97e6596c32b1336ac2d8130c39da3

Thanks!
