### ISSUE TITLE
AnimationDisabler does not disable animations on :before or :after

### ISSUE THREAD

**Issue by DanielHeath** [teamcapybara/capybara#2221]
In https://github.com/teamcapybara/capybara/blob/master/lib/capybara/server/animation_disabler.rb#L11 the selector is `*`, which misses some animations. 

`*, *:after, *:before` would catch more, as `:after` is not matched by `*`, but can be animated.

**Comment by twalpole** [comment]
PRs accepted

**Comment by DanielHeath** [comment]
awesome, will take a look in a bit.

**Comment by DanielHeath** [comment]
so, this is very hard to add tests for, because webdriver doesn't expose pseudoelement content as document content.
