### ISSUE TITLE
Capybara doesn't take screenshot if there is an alert window displayed

### ISSUE THREAD

**Issue by lflucasferreira** [teamcapybara/capybara#2225]
## Meta
Capybara Version: **3.25.0**
Driver Information (and browser if relevant): **3.142.3 with Chrome 75.0.3770.100**

## Expected Behavior
The expected behavior is to take a screenshot of a page even if there is or not a javascript alert.

## Actual Behavior
The following message is stored within the generated report file.

unexpected alert open: {Alert text : Data de Nascimento inválida.}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18362 x86_64) (Selenium::WebDriver::Error::UnexpectedAlertOpenError)
./features/support/hooks.rb:20:in `After'

## Steps to reproduce
This is the code I put in the hooks.rb file.

After do |scenario|
  if scenario.failed?
  temp_shot = page.save_screenshot('screenshots/temp_shot.png', full: true)
  screenshot = Base64.encode64(File.open(temp_shot, 'rb').read)
  embed(screenshot, 'image/png', 'Screenshot')
end

**Comment by twalpole** [comment]
There's nothing Capybara can do about this - it's a limitation of the WebDriver spec - https://w3c.github.io/webdriver/#user-prompts - Once an alert shows no commands other than the ones that handle alerts can be sent.
