### ISSUE TITLE
Expansion of file paths removes / to \ translation when using the Firefox driver

### ISSUE THREAD

**Issue by twalpole** [teamcapybara/capybara#2228]
For windows with Firefox the user needs to translate / to \ when file names are sent - this is because the webdriver spec doesn't really specify what file separators should be, and we don't know what platform any final browser is actually running on.  Unfortunately expanding the path (added in 3.24) removes any translation of the name a user has done.

**Comment by twalpole** [comment]
@lflucasferreira I'll update here when I have things to try/fixed

**Comment by twalpole** [comment]
Original report :

> I am facing the same issue. And I am translating / to \ if "OS.windows?" as you can see below.
> 
> It works in Chrome but not in Firefox 68.0 (64-bits).
> 
> def attach_doc_file(id, file)
> path = File.join(Dir.pwd, "features/support/public/doc/#{file}")
> path = path.tr('/', '\') if OS.windows?
> attach_file(id, path)
> end

Original Error:

> File not found: C:/Project/cnb/features/support/public/doc/CEP_Upload.xml (Selenium::WebDriver::Error::InvalidArgumentError)
> WebDriverError@chrome://marionette/content/error.js:179:5
> InvalidArgumentError@chrome://marionette/content/error.js:306:5
> interaction.uploadFiles@chrome://marionette/content/interaction.js:501:13

**Comment by twalpole** [comment]
@lflucasferreira I don't have a windows box to test this on currently. Could you please try using the `relative_path` branch and see if it fixes the issue.

**Comment by twalpole** [comment]
Fixed via 482dfb35e3e4044be1ddd48648195aef89026187

**Comment by lflucasferreira** [comment]
> Fixed via [482dfb3](https://github.com/teamcapybara/capybara/commit/482dfb35e3e4044be1ddd48648195aef89026187)

In this case, can I already update Capybara to the newest version?
