### ISSUE TITLE
FrozenError when enable javascript

### ISSUE THREAD

**Issue by fattahmuhyiddeen** [teamcapybara/capybara#2229]
## Meta
Capybara Version:
3.25.0
Driver Information (and browser if relevant):
geckodriver

## Expected Behavior
can test perfectly when enabling javascript

## Actual Behavior
Cause error:
    FrozenError:
       can't modify frozen String

## Steps to reproduce
set ` js: true` inside `describe`. the error will occur at `visit` method

My code:
```
# frozen_string_literal: true

require 'rails_helper'
require 'features/shared_auth'
require 'features/shared_examples'

describe 'new initiative', type: :feature, js: true do
  context 'user initiate feedback' do
    before do
      visit user_google_oauth2_omniauth_authorize_path
    end

    context 'fill all required input' do
      it 'successfully create initiative' do
        visit new_initiative_path
      end
    end
  end
end
```

**Comment by twalpole** [comment]
I'll need the stacktrace that goes along with the error to see where this is actually coming from. I'm 99% sure this isn't coming from Capybara since all of its tests are run with frozen strings and this gist - 
 https://gist.github.com/twalpole/3a9bf7c959b557ac3b710f247d20cd1f - works fine.

**Comment by twalpole** [comment]
Closing due to lack of response - Will reopen if/when a stacktrace or self-conatined example is  provided showing this to be an issue in Capybara.

**Comment by twalpole** [comment]
Note: this could be caused by a bug in selenium-webdriver 3.142.x if you don't have the browser you're trying to use installed in a standard location.  The default browser for selenium is Firefox.

**Comment by fattahmuhyiddeen** [comment]
yeah, just realized that i need to install firefox. now it works. maybe need to mention clearly that this gem requires firefox to be installed?

**Comment by twalpole** [comment]
The gem doesn't need Firefox to be installed - unless the user chooses to run their tests with the :selenium driver which is already mentioned to use Firefox - https://github.com/teamcapybara/capybara#selenium .  Also, if there wasn't a bug in `selenium-webdriver` it would have clearly told you it couldn't find Firefox.
