### ISSUE TITLE
`ancestor` returning no nodes since 3.27

### ISSUE THREAD

**Issue by cyrilchampier** [teamcapybara/capybara#2234]
## Meta
Capybara Version:
3.27.0
Driver Information (and browser if relevant):
selenium-webdriver (3.142.3)

## Expected Behavior
`ancestor` method keep the same behavior as in `3.26.0`

## Actual Behavior
Most of our call to ancestors now fails.
From what I understand, [here](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/queries/ancestor_query.rb#L14), we compare ancestors nodes with all nodes matching the selector, and select only intersection.

Problem seems to be the type, `match_results` contains types `Capybara::Node::Simple` while elements in the other array are `Capybara::Node::Element`.

## Steps to reproduce
I did not fully understood, but here is our "call".
`find('.dc-multi-level-selector-item-label', text: 'something').ancestor('.dc-multi-level-selector-item')`
Tell me if you need more investigations on my side

**Comment by twalpole** [comment]
What driver are you using and what is the relevant HTML?

**Comment by cyrilchampier** [comment]
Here are the versions of our drivers:
```
chrome-driver: 75.0.3770.140
chrome: 75.0.3770.142
```

The command:
```
(byebug) find('.dc-multi-level-selector-item-label', text: 'Urgence').ancestor('.dc-multi-level-selector-item')
*** Capybara::ElementNotFound Exception: Unable to find visible css ".dc-multi-level-selector-item" that is an ancestor of visible css ".dc-multi-level-selector-item-label" with text "Urgence"
```


And the full html corresponding:
```
<div class="dc-multi-level-selector-item cursor-pointer">
  <span class="dc-checkbox dc-multi-level-selector-item-checkbox"></span>
  <div class="dc-multi-level-selector-item-content">
    <span class="dc-multi-level-selector-item-label">Urgence</span>
  </div>
</div>
```

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/4084690d90cc4beac28fcebf887cb6c1 is a self-contained example with that HTML showing the ancestor call working.  What is it doing differently than your code?

**Comment by cyrilchampier** [comment]
Thanks for the nice sample, i will keep it :)
I finally found the culprit, it's [this appium_capybara gem](https://github.com/appium/appium_capybara) that [override `Capybara::Queries::SelectorQuery#resolve_for`](https://github.com/appium/appium_capybara/blob/master/lib/appium_capybara/ext/selector_query_ext.rb#L4) and is incompatible with the new version.
Sorry for bothering you :(

**Comment by twalpole** [comment]
@cyrilchampier Ok -  I'm willing to provide a guaranteed stable API for them if there's something specific they need - overriding `resolve_for` isn't a great idea.
