### ISSUE TITLE
Browser windows are left open after a test completes

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2237]
Capybara 3.28. We are using `Capybara.using_session` which opens a new window. However, after a test completes, the browser window is not closed. I think it is useless to preserve it because cookies/state has been cleared (due to Capybara doing `reset_sessions!` after each test) so the user cannot do anything in it - this just wastes memory. Especially if the user doesn't call `Capybara.using_session` with the same session name again.

Am I wrong somewhere with what I said and do I make sense?

**Comment by twalpole** [comment]
By "a test completes" do you mean a single test out of the test suite - or do you mean when the whole test suite has completed?  

If you mean after a single test, Capybara has no way of knowing whether or not you will be calling `Capybara.using_session` with the same session name again in later tests, so it keeps the session open in case (It would be unusual to have a test suite where only one test requires an extra session). If you really do only use the session once and your memory usage is that critical you can call `quit` on the session.

**Comment by boris-petrov** [comment]
@twalpole - ah, so you're saying that browser windows are closed after a whole test suite finishes? But I don't understand - isn't `reset_session!` called after each test (which clears local and session storages for example)? If so, won't `Capybara.using_session` create a brand new session anyway because all the previous ones have been removed?

**Comment by twalpole** [comment]
You're confusing a Capybara session with a session in your app.  A Capybara session is an instance of a driver/browser/app under test combination.  The things that are reset in a browser after every test are to do with the session in your app.  So - if you do `using_session "other user" do ...` that will start up a new driver instance, which will start a new browser instance and any other time you do `using_session "other_user" do ...` It will use the same driver/browser instance  (assuming you don't change the driver, etc).  The name passed to `using_session` has nothing to do with a session in your app.

**Comment by boris-petrov** [comment]
When I do `using_session "other user" do ...` in a test, Capybara will create a new browser for that. Then the test finishes and this browser (as well as the "main" one, of course) will have their cookies and storages cleared, correct? If I do the same `using_session "other user" do ...` in the second test, how is that different than NOT having done it in the first test, besides Capybara not opening a new browser this time? I, as a user, have no access to stuff from the previous test because it was cleared. So why would I care if it is the same driver/browser under the hood?

**Comment by twalpole** [comment]
Because the time to open a new browser instance can be significant

**Comment by boris-petrov** [comment]
OK, thanks for the information. What about the original issue? We have a number of different files which are like so:

```ruby
require_relative './spec_helper'

RSpec.feature 'chat' do
  scenario 'exchange a few chat messages' do
    ...
  end
end
```

And we use `using_session` in a few of them - and the browsers are not closed before *all* tests are finished. You're saying that they should close between "files"? Or am I misunderstanding again?
```

**Comment by twalpole** [comment]
It shouldn't close them until the entire test suite has finished (not one file in the suite).  If you're using a different name each time you call `using_session` then you're going to have a new browser instance open for each of those until all the tests finish. Most people reuse the names to reuse the browser instance without having to pay the time penalty of opening another browser instance.

**Comment by boris-petrov** [comment]
Thanks. Well, I actually wanted to do exactly that in a generic way (by having an after-test handler that goes through all sessions and quits them (apart from the "main" one)) but there is no public API for getting the sessions and hence this issue. Anyway, I'll probably just reuse the same name, that makes sense. Thanks for your time and support!

**Comment by twalpole** [comment]
Another option you can use is to create your own session instance(s) (Capybara::Session.new), of course then you're responsible for resetting them, quitting them, etc when necessary.
