### ISSUE TITLE
Errno::EMFILE: Failed to open TCP connection to 127.0.0.1:9*** (Too many open files - socket(2) for "127.0.0.1" port 9***)

### ISSUE THREAD

**Issue by melostbr** [teamcapybara/capybara#2238]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
3.22.0
Driver Information (and browser if relevant):
selenium-webdriver (3.142.3)
chromedriver (76.0.3809.68)
pry (0.12.2)
pry-byebug (3.6.0)
pry-rails (0.3.9)

## Expected Behavior
When calling `session.has_select?('#id_selector_field', selected: 'selected_option')` it should be able to return 'true' or 'false'

## Actual Behavior
```
expect(page).to have_field("What's your name?", with: 'Jhon Doe')
binding.pry
expect(page.has_select?('#id_selector_field', selected: 'selected_option')).to be_true
2.6.3 (#<RSpec::ExampleGroups::NewSignupFlow::ACampaignOwnerSigningUp::ForAReferralCampaign::AndAShopifyCampaign:0x00007ff5e7402150>):0 > page.has_select?('#id_selector_field', selected: 'selected_option')
Errno::EMFILE: Failed to open TCP connection to 127.0.0.1:9524 (Too many open files - socket(2) for "127.0.0.1" port 9524)
from /Users/stefanie.melo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
Caused by Errno::EMFILE: Too many open files - socket(2) for "127.0.0.1" port 9524
from /Users/stefanie.melo/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
```

## Steps to reproduce
Try to call the matcher `has_select?` from inside a `binding.pry` session.

**Comment by twalpole** [comment]
Do you have a full stacktrace that shows more about where the error is coming from because the error would imply your system is running out of resources.  Also is there a reason you're asserting `has_select?` is true - rather than just using `expect(page).to have_select('id_selector_field', selected: 'selected_option')`?

**Comment by twalpole** [comment]
I can't replicate this - the code I am using is  https://gist.github.com/twalpole/c42334f9bfeee30b3f7248b414e3d55a
which runs fine, and also works fine with the binding.pry uncommented and then manually calling `has_select?`

**Comment by twalpole** [comment]
Closing due to lack of response. If/when a response is provided regarding how to replicate this I will reopen.
