### ISSUE TITLE
Error save_sreenshot - only in Google Chrome

### ISSUE THREAD

**Issue by TiuCadu** [teamcapybara/capybara#2240]
Capybara Version:
 3.28.0

Driver Information (and browser if relevant):
ChromeDriver 76.0.3809.68 

Expected Behavior

Take a printscreen, but i receive an error error, only in Google Chrome 76.0.3809.100

Actual Behavior

 timeout: Timed out receiving message from renderer: 9,998
        (Session info: chrome=76.0.3809.100) (Selenium::WebDriver::Error::TimeoutError)
      #0 0x5597a3470749 <unknown>

Steps to reproduce
=========================
GemFile

source "https://rubygems.org"

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'rspec'
  gem 'selenium-webdriver'
end

=========================
env.rb

require "capybara"
require "capybara/cucumber"
require "selenium-webdriver"

Capybara.configure do |config|
    config.default_driver = :selenium_chrome
end

=========================
specs.rb

Given("i open google site") do
    visit 'https://www.google.com'
    page.save_screenshot("log/screenshot.png")
end

**Comment by twalpole** [comment]
What version of chromedriver are you using?

**Comment by twalpole** [comment]
Please try on the latest 76.x.x.x chromedriver

**Comment by twalpole** [comment]
Does the following code run without errors for you?  If so it would imply the issue isn't in Capybara but somewhere in your code.  Are you configuring your own driver? If so please show the configuration.
 
```
# test_screenshot.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'selenium-webdriver', '3.142.3'
  gem 'webdrivers'
  gem 'capybara', '3.28.0'
end

require "capybara/dsl"

sess = Capybara::Session.new(:selenium_chrome)
sess.visit("https://www.google.com")
sess.save_screenshot("log/screenshot.png")
```

**Comment by TiuCadu** [comment]
> Please try on the latest 76.x.x.x chromedriver (76.0.3809.126 as of now)
Dont work with 76.0.3809.126

**Comment by TiuCadu** [comment]
> Does the following code run without errors for you? If so it would imply the issue isn't in Capybara but somewhere in your code. Are you configuring your own driver? If so please show the configuration.
> 
> ```
> # test_screenshot.rb
> require 'bundler/inline'
> 
> gemfile do
>   source 'https://rubygems.org'
>   gem 'selenium-webdriver', '3.142.3'
>   gem 'webdrivers'
>   gem 'capybara', '3.28.0'
> end
> 
> require "capybara/dsl"
> 
> sess = Capybara::Session.new(:selenium_chrome)
> sess.visit("https://www.google.com")
> sess.save_screenshot("log/screenshot.png")
> ```

My code work very well, but only with Firefox, I have two lines of code, very simple.
Does it wrong with you?

**Comment by twalpole** [comment]
You don’t only have 2 lines of code - since your code is running inside a whole test framework with a lot of extra code. Does the code I provided work for you when just run as a single file?

**Comment by twalpole** [comment]
Closing due to lack of response
