### ISSUE TITLE
rubydoc.info does not display documentation for Capybara 2.13

### ISSUE THREAD

**Issue by vasiliy-pdk** [teamcapybara/capybara#2251]
## Meta

This is the issue with documentation site for Capybara Version: 2.13 https://www.rubydoc.info/gems/capybara/2.13.0/Capybara/ 

Sorry, was not sure where to raise the issue, appears like documentation is displayed for other libraries and even for the fresher versions of Capybara itself. So I assume it's something specific to 2.13

## Expected Behavior

I expect to see the documentation for Capybara 2.13 when I visit the URL https://www.rubydoc.info/gems/capybara/2.13.0/Capybara/ 

## Actual Behavior

The info message is shown:

```
Processing capybara
capybara (2.13.0) is being processed. You'll be redirected when the pages are built, it shouldn't take much longer.
```

Despite trying several times during a day or even in one-week interval the message is still there.

## Steps to reproduce

1. Visit the URL https://www.rubydoc.info/gems/capybara/2.13.0/Capybara/  
2. Try again in a couple of hours - the message is still there

**Comment by luke-hill** [comment]
Given anything after 3.3.0 works fine and most of the 2.x series doesn't. I would hasten to say this is an archiving / indexing issue at rubydoc.info

This is also an issue for other big gems such as rails and rspec. So I would probably say the website / db of rubydoc is experiencing some issues.

**Comment by vasiliy-pdk** [comment]
Thanks for sharing your observation. I've dropped them a message https://rubydoc.tenderapp.com/discussions/problems/697-documentation-is-not-generated-for-a-library

**Comment by twalpole** [comment]
Closing this since it's not an issue with Capybara. Additionally 2.13 is obsolete at this point in time. Note, you can always build the docs locally if you really need them.
