### ISSUE TITLE
Can't find/click buttons by name or ID with selenium_chrome_headless

### ISSUE THREAD

**Issue by henrik** [teamcapybara/capybara#2256]
Capybara Version:
3.29.0
Driver Information (and browser if relevant):
selenium_chrome_headless

This spec fails for me with selenium_chrome_headless:

```
it "reproduces the issue", :js do
  visit about_path
  click_button "myfoo"
end
```

It runs on a page that includes:

```
<form method="GET" action="">
  <button id="myfoo">Foo</button>
</form>
```

It fails with:

```
Capybara::ElementNotFound:
  Unable to find button "myfoo" that is not disabled
```

If I replace `click_button("myfoo")` with `find("#myfoo").click`, it works.

Or if I remove the `:js` flag, making it no longer use selenium_chrome_headless, it also works.

Finding by button text (`click_button "Foo"`)  also doesn't work with selenium_chrome_headless.

Clicking a link by its text works fine, though (`click_link "Bar"`).

**Comment by henrik** [comment]
Curiously, if I modify  lib/capybara/selenium/extensions/find.rb `find_by` to output what it's doing, I get an xpath selector which seems to work fine.

So if I put this in the test:

```
    p results: find(:xpath, ".//input[((((./@type = 'submit') or (./@type = 'reset')) or (./@type = 'image')) or (./@type = 'button'))][((((./@id = 'myfoo') or (./@name = 'myfoo')) or (./@value = 'myfoo')) or (./@title = 'myfoo'))] | .//input[(./@type = 'image')][(./@alt = 'myfoo')] | .//button[((((((./@id = 'myfoo') or (./@name = 'myfoo')) or (./@value = 'myfoo')) or (./@title = 'myfoo')) or (normalize-space(string(.)) = 'myfoo')) or .//img[(./@alt = 'myfoo')])] | .//input[(./@type = 'image')][(./@alt = 'myfoo
')]")

    find(:button, "myfoo")
```

I get results from the xpath expression, but the `find_button` (or a corresponding `click_button`) fails to find the button.

**Comment by henrik** [comment]
We're also seeing this with e.g. `choose` (for radio buttons) and `fill_in` (for text fields).

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/a23d11af2f747f4a0d906fc58129e5b2 Shows it working -- If you can modify that so it fails (or provide access to your own failing example) then I have somewhere to start from.

**Comment by henrik** [comment]
Thank you, @twalpole! Will try to take the time to do that. Will close the issue for now so you don't have to see it until we get you a repro :)
