### ISSUE TITLE
ArgumentError missing keyword session_options (with Money)

### ISSUE THREAD

**Issue by sfcgeorge** [teamcapybara/capybara#2261]
## Meta
Capybara Version:
3.29.0

## Expected Behavior

The following used to work:

```ruby    
expect(page).to have_text @first_offer.price * 2 + @optional_extra.price * 5
```

But after updating gems it started failing with

```
     Failure/Error: expect(page).to have_text @first_offer.price * 2 + @optional_extra.price * 5
     
     ArgumentError:
       missing keyword: session_options
```

The error is confusing.

## Actual Behavior

I got it to work by adding `to_s`:

```ruby
expect(page).to have_text (@first_offer.price * 2 + @optional_extra.price * 5).to_s
```

So at first I thought Capybara doesn't support finding integers in text, but there is a `to_s` built in in the [relevant place](https://github.com/teamcapybara/capybara/blob/120714984f31d896ec35ff1c99606902734f7b79/lib/capybara/queries/text_query.rb#L18)... 

## Steps to reproduce

Through a lot of putsing I tracked the issue down to interplay between [_verify_text](https://github.com/teamcapybara/capybara/blob/120714984f31d896ec35ff1c99606902734f7b79/lib/capybara/node/matchers.rb#L852) and [_set_query_session_options](https://github.com/teamcapybara/capybara/blob/120714984f31d896ec35ff1c99606902734f7b79/lib/capybara/node/matchers.rb#L861).

Basically one takes an `*query_args` splat, the other takes an `*query_args` splat and an `**query_options` double-splat. Turns out the value I was expecting was a Money object not an integer, and Money responds to `to_hash`. Due to quirkiness in Ruby named arguments for historical reasons, the Money object ends up in the double-splat not the splat as expected.

I've demonstrated the issue with a simpler example:

```ruby
m = Money.new(42)
puts m
# 0.42
p m.to_hash
# {:cents=>42, :currency_iso=>"GBP"}

def mangle_arg_opts(*args, **opts)
  puts "mangle_arg_opts(#{args}, #{opts})"
end
def pass_on_args(*args)
  mangle_arg_opts(*args)
end

pass_on_args(m)
# mangle_arg_opts([], {:cents=>42, :currency_iso=>"GBP"})

m = 42
pass_on_args(m)
# mangle_arg_opts([42], {})
```

There is a [deprecation in Ruby 2.7](https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html) and by Ruby 3 this behaviour might change. I'm not sure whether is would fix this particular case or not though.

I think you could argue for just closing the issue. Effectively you can't pass anything to a Capybara matcher that responds to `to_hash`, that just becomes a rule. The current error makes that hard to find out though.

Alternatively I think the code could be fixed by only using `*args` or always using `*args` and `**opts` consistently. Either way some care would be needed to make sure that something that can be converted to a hash isn't, so it can get converted to a string by the actual matcher down the line.

**Comment by twalpole** [comment]
Are you running with Ruby 2.7 ?  The deprecation and behavior change is breaking around keyword params, so it's going to cause a lot of issues.  Capybara doesn't yet support, and not really sure yet when it will since it's going to require writing a lot of ugly code to work across multiple versions of ruby.

**Comment by twalpole** [comment]
What version of the money gem are you using?  The latest doesn't appear to support `to_hash` on money instances.

**Comment by twalpole** [comment]
Technically this is working as designed since `have_text` is documented to take a String or Regexp, however since it does currently call `#to_s` on parameters I'll see if I can't make it work again, or at least make the error message clearer by validating the parameter.

**Comment by sfcgeorge** [comment]
Sorry I was confusing there, no we're on Ruby 2.6.5 I just share your suspicion that this kind of thing will change in 2.7 but I haven't thought through whether it would fix this case or make it worse.

We're on the latest Money 6.13.4. We upgraded a bunch of things in upgrading to Rails 6 so I'm not certain which thing changed.

Yeah, I don't think this is a bug exactly, more a quirk 😄

**Comment by twalpole** [comment]
I can fix the missing session_options issue relatively easily, however using objects that implement `to_hash` is still going to be a bit quirky with the `have_text` api.  The reason for this is the API is 

    have_text(type=nil, text, **options)

as long as you just pass the object you want to be converted to string things work

    have_text(some_object) # some_object will have #to_s called on it

however if you pass the type and the object responds to #to_hash ruby will default to making the object the options

    have_text(:all, some_object) # text = :all, options = some_object.to_hash

so you'd have to call to_s or pass an empty options object for it to work

    have_text(:all, some_object.to_s)
    have_text(:all, some_object, {})

Not much that can be done about that

**Comment by twalpole** [comment]
Fixed as much as I think it can given the way ruby will automatically call `to_hash` if it is implemented.  I believe better practice would be to implement `to_h` and explicitly call it rather than relying on implicit calling of `to_hash`

**Comment by sfcgeorge** [comment]
That's awesome, thank you!
