### ISSUE TITLE
Expectations in new Tab freeze execution

### ISSUE THREAD

**Issue by florianroesler** [teamcapybara/capybara#2266]
## Meta
Capybara Version:
**3.29.0**
Driver Information (and browser if relevant):
selenium-webdriver gem (3.142.6)
Google Chrome 74.0.3729.169

## Expected Behavior
After opening a new browser tab that leads to a specific URL, I want to verify that the current path is equal to the expected URL.
## Actual Behavior
The code does not respond anymore as soon as I try to make a call to the `current_url`. I verified this by placing a `binding.pry` breakpoint inside the block and executing the given command seen in the reproduction. There is no error. Nothing happens and the terminal never returns anything. I can only exit the execution through SIGINT.

## Steps to reproduce
      new_tab = window_opened_by { click_on('Link') }
      within_window new_tab do
        expect(page.current_url).to include('localhost:3000')
      end

I would be glad to provide more info.

**Comment by twalpole** [comment]
Firstly, you should never write expectations against urls like that - instead write

    expect(page).to have_current_path(/localhost:3000/, url: true)

so Capybaras retrying behavior is used.  Beyond that If it's hanging it's going to be a bug in chromedriver.

**Comment by twalpole** [comment]
@florianroesler FYI - https://bugs.chromium.org/p/chromedriver/issues/detail?id=2650&can=1&q=hang&colspec=ID%20Status%20Pri%20Owner%20Summary is the chromedriver issue I remembered - apparently was fixed in 75.  I notice you're actually using Chrome 74 so you may want to update.

**Comment by florianroesler** [comment]
Thanks for the hint about the expectation!

I remember I specifically downgraded Chrome to version 74 as I had other issues on one of the newer versions. That was a while ago though so I will try to upgrade again. Thank you!
