### ISSUE TITLE
require 'capybara/rails'   Throws 'unitialized constant Rails' error, and seems unecessary 

### ISSUE THREAD

**Issue by Randall-Coding** [teamcapybara/capybara#2269]
## Meta
Capybara Version:3.29
Driver Informatio: selenium-webdriver 3.142  Rails 5.2  Ruby 2.5.1  RackTest

## Expected Behavior
To run a feature spec successfully

## Actual Behavior
Throws 'unitialized constant Rails' error

## Steps to reproducev
Add require 'capybara/rails' to spec_helper or rails_helper file.  Then try to run a feature spec with `rspec spec/features/`  

## Question
Do you still want the directions to add `require 'capybara/rails'` to the spec helper to be on the readme?  It seems wrong.  It isn't necessary for my set up, and it produces an error.

The instructions later on the page to readme `require 'capybara/rspec'` worked fine.

**Comment by twalpole** [comment]
What else are you requiring and in what order?

**Comment by Randall-Coding** [comment]
I had the require statements like this 
![require_1](https://user-images.githubusercontent.com/39175191/68771549-7b26a000-05e5-11ea-8d1a-1d6e3078297e.png)

Looks like it works when I move it underneath this line `require File.expand_path('../config/environment', __dir__)`

![require_2](https://user-images.githubusercontent.com/39175191/68771685-b3c67980-05e5-11ea-913d-d7f8044237fa.png)

So it is fixed now

**Comment by twalpole** [comment]
@Randall-Coding Yes - normally when you generate the initial rails_helper file it has a comment in it stating to only add things after the environment loading line - maybe you removed it?

**Comment by Randall-Coding** [comment]
Good point. Previous times I've used Capybara I just went with the flow of the page instead of trying to put all the requires at the top.  Thanks for the help.
