### ISSUE TITLE
Upgrading from Capybara 3.23.0 to 3.24.0 breaks a JQuery-using feature test

### ISSUE THREAD

**Issue by Arepo** [teamcapybara/capybara#2273]
## Meta
Capybara Version:
3.24.0

Driver Information (and browser if relevant):
Chrome 78.0.3904.108 (Official Build) (64-bit)
webdrivers 4.1.3
selenium-webdriver 3.142.4

## Expected Behavior
The feature test that worked in 3.23.0 should pass

## Actual Behavior
A button that JQuery should have undisabled is left disabled, and the test fails with the following message:

    Unable to find visible button "Increase" that is not disabled (Capybara::ElementNotFound)
    ./features/step_definitions/increasing_pledge_steps.rb:23:in `"I increase my pledge percentage"'
    features/increasing_pledge.feature:9:in `When I increase my pledge percentage' 

## Steps to reproduce
There's quite a few moving parts here, so apologies if this is an overload, but these are the sections:

The setup step of the test:

    Given(/^something like I have successfully pledged$/) do
      # Mimics: step 'I submit a valid pledge'
      # ... step 'an admin countersigns my pledge' (doesn't exist at time of writing)
      @user = FactoryBot.create(:user, :pledged)
      login_as(@user, scope: :user)
    end

The next (failing) step:

    When("I increase my pledge percentage") do
      visit user_path

      within('#pledge-a030Q0000031EdNQAU') do
        # Would like to properly step through this, but Capybara/JS can't click on this link:
        expect(page).to have_link('Increase %')
      end

      visit increase_pledge_path(sf_pledge_id: 'a030Q0000031EdNQAU')

      find('#amended_pledge_percentage').set(56) # As elsewhere, for some reason all changes lead to 56

      trigger_change_on('#amended_pledge_percentage') # definition below

      # The failing line:
      click_button('Increase')
      expect(UserMailer).to receive_message_chain(:increased_pledge, :deliver_later)
      visit amendment_confirmation_path(amendment_id: User.last.amended_pledges.first.id)
    end

    def trigger_change_on(selector)
      script = "$('#{selector}').trigger('change');"
      page.execute_script(script);
    end

The driver config in our features/support/chromedriver.rb:

    require "selenium/webdriver"

    Capybara.register_driver :chrome do |app|
      Capybara::Selenium::Driver.new(app, browser: :chrome)
    end

    Capybara.register_driver :headless_chrome do |app|
      # Disable W3C because it was causing an error with JS cukes. Not sure if it will have other implications
      capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
        chromeOptions: { args: %w(headless disable-gpu), w3c: false }
      )

      Capybara::Selenium::Driver.new app,
        browser: :chrome,
        desired_capabilities: capabilities
    end

    Capybara.javascript_driver = :headless_chrome

The relevant part of the form in question (erb):

    <%= form_with(model: AmendedPledge.new, url: amend_signature_path(sf_pledge_id: @pledge.Id, user_id: current_user.id), class: 'standard-form | standard-form-base', local: true, id: 'amend-pledge-form') do |f| %>
      <%= f.submit content.update_button_text, class: "btn -disabled | js-submit-increase", disabled: true %>
    <% end %>

and the relevant JS listener, defined in app/javascript/components/EnableSubmitButton.js:

    export default function() {
      window.addEventListener("load", function() {
        $("#amended_pledge_percentage").change(function() {
          // Disable submit iff percentage hasn't increased
          if ( Number($(this).attr('min')) < Number($(this).val()) ) {
            $('.js-submit-increase').removeClass('-disabled').prop('disabled', false);
          } else {
            $('.js-submit-increase').addClass('-disabled').prop('disabled', true);
          }
        });
      })
    }

Plausibly relevant, for historical reasons, we use both Sprockets and Webpacker, the latter of which loads the script above, but the former of which loads JQuery. Our assets/app/application.js file just consists of this:

    //= require jquery
    //= require jquery_ujs
    //= require jquery.Jcrop.min

Our custom Javascript is included in these lines of the app/javascript/packs/application.js file: 

    import enable_submit_buttom from "../components/EnableSubmitButton.js";
    // ...
    enable_submit_buttom();

I think that's all the relevant interactions, but I'll keep an eye on this thread in case there's anything I missed.

(it's worth confirming that if I `save_and_open_page` on the line before the test failure, I can confirm that we're in the right place, with the 'Increase' button visible but still disabled.

I also tried throwing in a `sleep 10` on the same line, to ensure it isn't a race condition)

**Comment by twalpole** [comment]
Are you sure you didn't change anything except the version of Capybara because there is nothing between 3.23 and 3.24 that would affect this.

I think the main issue here is you are working around things that have no need to be worked around.
Text inputs don't fire the `change` event until the element loses focus (which you shouldn't be doing via JS - just remove your `trigger_change_on` method completely).  You could generate the event by clicking on something else on the page (so the input loses focus and fires its change event) or potentially by appending `\t` to the string being sent (driver dependent), but a better fix (from a UX perspective) would be to trigger your JS on the `input` event instead of `change` which will fire every time a key is pressed in the field.

Additionally the comment - 

    # Would like to properly step through this, but Capybara/JS can't click on this link:
    expect(page).to have_link('Increase %')

doesn't make any sense, unless your window during testing is too small and you have other elements overlaying the link (or you've done something silly like set `Capybara.ignore_hidden_elements = false`).

**Comment by twalpole** [comment]
Closing due to lack of response
