### ISSUE TITLE
Provide a `closest` finder (or change `ancestor`) to return closest ancestor

### ISSUE THREAD

**Issue by TylerRick** [teamcapybara/capybara#2276]
I'd like to propose adding a `closest` finder, which would be to `ancestor` what `first` is to `all`.

## Motivation

[This question](https://stackoverflow.com/questions/7017530/closest-in-capybara) asks how to find the closest matching ancestor.

That question is...
- ... the top search result when searching for _capybara find closest element_  (using DuckDuckGo)
- ... the 3rd search result when searching for _capybara find closest ancestor_

The way to do that with both the [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) and the [jQuery API](https://api.jquery.com/closest/) is with `closest`. It's a useful search to be able to do. So it would be natural to expect Capybara to at least _have_ an equivalent finder. And one could even _hope_ that it would be named the same too. :) (Though I realize — and am glad — that the equivalent to `querySelector` and `querySelectorAll` in Capybara is `first` and `all` rather than those long names, so name parity isn't _everything_. But it is _something_.)

Alas, my search for such a method in Capybara has been in vain so far.

I keep running into this same question/need myself (and I'm obviously not the only one). In fact, I was surprised when I found this question and then found my own answer explaining that `.ancestor` is currently the best way to do this with the Capybara API currently.

But existing `ancestor` is not semantically the same as [`closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest): `closest` automatically returns the single, _closest_ match, whereas our a `ancestor` method expects to only ever find *one* match or it raises an error. I guess that works okay if you can be very specific with your query (locating by `#id`, for example), but that seems less useful than `closest` (which you could probably replace most `ancestor` queries with and your tests would still pass).

## Expected Behavior

```
  it 'should find closest ancestor (even if there are multiple matches)' do
    el = @session.find(:css, '#child')
    expect(el.closest(:css, 'div')[:id]).to eq 'ancestor1'
    expect(el.closest(:css, 'div', text: 'Ancestor')[:id]).to eq 'ancestor1'
    expect(el.all_ancestors(:css, 'div').map {|x| x[:id] }).to eq ['ancestor1', 'ancestor2', 'ancestor3']
  end
```

# Implementation

Assuming it's okay to change the order of elements returned by `AncestorQuery` so that `match: :first` works as expected (#2275), this weould be easy to build as a wrapper for `ancestor(match: :first`).

But if #2275 can't be released yet because it's a breaking change, we could implement `closest` without introducing that breaking change yet...

# Meta (not relevant)
Capybara Version: capybara-3.29.0
Driver Information (and browser if relevant): selenium-webdriver-3.141.0

**Comment by twalpole** [comment]
I think https://github.com/teamcapybara/capybara/commit/98feb06e3b7a41c81a8140bc7740ccb4cd57cb2d in the ancestor work branch may provide more flexibility/functionality and allow you define your own helper method for `closest` or whatever.  There's also some work to be done around this on performance optimization if people are going to actually be using ancestor for more than just assertions because it's currently pretty inefficient if you're specifying generic requirements on the ancestor (in order to implement scoping restrictions)

**Comment by twalpole** [comment]
The :order option should make it possible for anyone to add their own `closest` (I dislike that name because it really doesn't tell you anything) helper, and I don't really understand what anyone would use `ancestors` for when testing.
