### ISSUE TITLE
have_table raised error when have empty selector and have `with_cols` argument

### ISSUE THREAD

**Issue by bekicot** [teamcapybara/capybara#2279]
## Meta
Capybara Version: 3.29

I have a page with 1 table where i want to check each cols value.

## Expected Behavior
Allow empty first argument of `have_table` with `with_cols` keyword argument to not raised:

```sh
expected to find table nil but there were no matches
```
## Actual Behavior
```ruby
expected to find table nil but there were no matches
```
## Steps to reproduce
```ruby
expect(page).to have_table(with_cols: [ %w[ col1 col2 ] ])
```

The behavior of
```ruby
expect(page).to have_table # Without argument
```
is passed on the same page.

**Comment by twalpole** [comment]
What is the HTML of the page, because that error indicates their isn’t a table with those columns on the page

**Comment by bekicot** [comment]
> What is the HTML of the page, because that error indicates their isn’t a table with those columns on the page

There is a table, but there isn't a table with these cols.

**Comment by twalpole** [comment]
If there isn’t a table with matching columns then the expectation is failing correctly - what is the actual issue her?

**Comment by bekicot** [comment]
> If there isn’t a table with matching columns then the expectation is failing correctly - what is the actual issue here?

@twalpole Shouldn't the error show `Cant find table without id with col1, col2`. Instead of `expected to find table nil but there were no matches`. 

As mentioned above,
```ruby
expect(page).to have_table # Without argument
```
is passed, hence, `expected to find table nil` is not valid.

**Comment by twalpole** [comment]
So your issue is with the message, not that the assertion doesn’t pass? If so, please provide a self contained example and what you think the message should be - or PRs are considered

**Comment by twalpole** [comment]
If you want to do a PR the change would need to be in https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector/definition/table.rb#L60
