### ISSUE TITLE
Proposal: Capybara.fragment

### ISSUE THREAD

**Issue by franzliedke** [teamcapybara/capybara#2286]
## Meta
Capybara Version: 3.12.0

---

`Capybara.string(some_html_string)` apparently expects its input to be just one HTML element (with children). Fragments (multiple HTML elements at the top level) are not supported - in my case, a string along the lines of `<script /> <script /> <my-element />` was automatically wrapped in a `head` tag, which meant the `<my-element>` tag was not visible.

What do you think about adding a `Capybara.fragment` method that can deal with fragments as well? We monkey-patched this locally and it seems to work well:

~~~rb
module Capybara
  def self.fragment(html_string)
    Capybara.string(Nokogiri::HTML.fragment(html_string))
  end
end
~~~

Feel free to close this quickly, whether you agree with the proposal or not. If it is approved, I will happily follow up with a pull request. :smile:

**Comment by twalpole** [comment]
What type of tests are you doing where you're dealing with HTML fragments?

**Comment by franzliedke** [comment]
We have a small component system (a la React etc., but for server-side HTML generation) - Capybara offers nice matchers for testing the HTML output of these components, which can be fragments.

**Comment by twalpole** [comment]
I don't think this belongs in Capybara, and is easy enough for anyone to implement themselves if wanted.

**Comment by franzliedke** [comment]
Thanks for the feedback, and this project!!! :heart_eyes:
