### ISSUE TITLE
Feature request: has_select? assert, allow check disabled options

### ISSUE THREAD

**Issue by kinnrot** [teamcapybara/capybara#2289]
## Meta
Capybara Version:

Driver Information (and browser if relevant):

## Expected Behavior
When asserting for select input type, allow assert for disabled options, for example:

`assert_select('select_input_name', { options:['a', 'b', 'c'], disabled_options:['a'])`

Or to keep it standard when asserting for options, do not include disabled ones.

## Actual Behavior

Select options assertion include disabled options, not allowing any way to distinguish between enabled and disabled options.

**Comment by twalpole** [comment]
a PR that adds `enabled_options` and `disabled_options` filters to the `select` selector type - see https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector/definition/select.rb#L13 - would be acceptable

**Comment by twalpole** [comment]
Implements via https://github.com/teamcapybara/capybara/commit/c8bceae5ac95b607b58acd723d647deb98e49cc3
