### ISSUE TITLE
warning in ruby 2.7.0

### ISSUE THREAD

**Issue by huobazi** [teamcapybara/capybara#2290]
## Meta
Capybara Version:
capybara-3.29.0

## Steps to reproduce

when rails app start 

```bash
bundle exec rails s
```
output:
```bash
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filter_set.rb:117: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filters/node_filter.rb:9: warning: The called method `initialize' is defined here
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filter_set.rb:20: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filter_set.rb:113: warning: The called method `add_filter' is defined here
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filter_set.rb:117: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filters/base.rb:7: warning: The called method `initialize' is defined here
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/definition.rb:169: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filters/locator_filter.rb:9: warning: The called method `initialize' is defined here
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filters/locator_filter.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/xxx/.gem/ruby/2.7.0/gems/capybara-3.29.0/lib/capybara/selector/filters/node_filter.rb:9: warning: The called method `initialize' is defined here
```

**Comment by misdoro** [comment]
@huobazi have you tried updating capybara version to 3.30.0 ? They've just released it, and it addresses ruby 2.7 warnings.

**Comment by twalpole** [comment]
3.30.0 only addresses some of the warnings. You’re going to find these warnings coming from a lot of gems because Ruby 2.7 changes have made it complicated to do method delegation/forwarding in a way that will work cleanly across multiple versions of Ruby. I would recommend staying on 2.6 for a few months if you want warning free logs

**Comment by twalpole** [comment]
If you really do need to use Ruby 2.7 for some reason you can disable those warnings by doing

    RUBYOPT=-W:no-deprecated bundle exec rails s

instead

**Comment by connorshea** [comment]
@twalpole maybe you've already ruled this out, but one option for method delegation/forwarding might be to do something like Rails has here?:
https://github.com/rails/rails/commit/04f94394b35a98b49daf9d7740bb60f6bf81aa97#diff-4150e8175b9a99c0e92bfdcaabf8455dR223-R230

**Comment by twalpole** [comment]
I have a branch where I’m working on all the warnings - it’s just a pain because there are 3 different behaviors <2.7, 2.7, 3  to consider and I don’t actually think it’s possible to implement without breaking current user code in some of the cases. I get why the change is being made but IMHO, the impact wasn’t considered early enough in the 2.7 cycle and 2.7 should have provided better features for transitioning this (leading parameter support with `...`, etc)

**Comment by twalpole** [comment]
@connorshea - Yep -- unfortunately there isn't one clean way to fix all the warnings, and in some cases may be no way to fix them without breaking user code - it's a mess.

**Comment by connorshea** [comment]
@twalpole I happened to check the repo right after you pushed the most recent commits, it looks like all the deprecation warnings have been resolved for me, and there aren't any breaking changes that effect my test suite (though it's admittedly not the largest test suite ever). :) Nice work!
