### ISSUE TITLE
Dubious order of operations in getAttribute atom

### ISSUE THREAD

**Issue by rodovich** [teamcapybara/capybara#2300]
## Meta
Capybara Version:
3.30.0
Driver Information (and browser if relevant):
n/a

## Expected Behavior

Every `if` block can possibly be executed and can possibly not be executed.

## Actual Behavior

The `getAttribute` atom contains the following `if` statement:

https://github.com/teamcapybara/capybara/blob/7a410b52565b4855ac59cc9f2aa1f997902a1ef0/lib/capybara/selenium/atoms/src/getAttribute.js#L120-L126

This condition is equivalent to `(!value) === null` and evaluates to `false` no matter what `value` is, never executing the code on lines 121–125. I suspect this was meant to be:

```js
if (!(value === null)) {
```

which would mirror this usage a bit later in the function:

https://github.com/teamcapybara/capybara/blob/7a410b52565b4855ac59cc9f2aa1f997902a1ef0/lib/capybara/selenium/atoms/src/getAttribute.js#L133

## Steps to reproduce

Unknown—I'm not sure what impact this has. I noticed this when reading the code trying to understand behavior I was observing, but I don't understand this code well enough yet to reverse-engineer a meaningful test case.

**Comment by twalpole** [comment]
Nice catch! Doesn't really have any affect in modern browsers, I think this was probably there originally for IE - but worth fixing anyway.  Waiting on travis to run the tests.

**Comment by twalpole** [comment]
Fixed via 8658b39d1c27956b2c85a3e6755d58fc99317537
