### ISSUE TITLE
How to disable W3C mode in Edge

### ISSUE THREAD

**Issue by kishorekumartbm** [teamcapybara/capybara#2306]
[Edge-Selenium-Ruby.zip](https://github.com/teamcapybara/capybara/files/4164033/Edge-Selenium-Ruby.zip)
When I trigger selenium execution for Edge browser, it is failing after launching the application.

## Meta
Capybara Version: 3.30.0
Ruby :  2.5.7
Selenium: 3.141.0
Edge : 79.0.309.71

## Expected Behavior
It has to do the user actions like click and send keys
## Actual Behavior
It is not performing any user actions

Traceback (most recent call last):
        40: from Selenium-edge-capybara-1.rb:1:in `each'
        39: from Selenium-edge-capybara-1.rb:1:in `each'
        38: from Selenium-edge-capybara-1.rb:1:in `each'
        37: from Selenium-edge-capybara-1.rb:1:in `each'
        36: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/result.rb:32:in `block in initialize'
        35: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/queries/selector_query.rb:109:in `matches_filters?'
        34: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/queries/selector_query.rb:429:in `matches_system_filters?'
        33: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/queries/selector_query.rb:528:in `matches_visibility_filters?'
        32: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/node/element.rb:302:in `visible?'
        31: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/node/base.rb:77:in `synchronize'
        30: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/node/element.rb:302:in `block in visible?'
        29: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/selenium/nodes/edge_node.rb:69:in `visible?'
        28: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.30.0/lib/capybara/selenium/node.rb:152:in `visible?'
        27: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/element.rb:199:in `displayed?'
        26: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:509:in `element_displayed?'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/atoms.rb:13:in `execute_atom'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
        23: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
        22: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
        15: from        RtlUserThreadStart [0x00007FF8562ECED1+33]
        14: from        BaseThreadInitThunk [0x00007FF8545A7BD4+20]
        13: from        Ordinal0 [0x00007FF6A5C3CE9D+1429149]
        12: from        Ordinal0 [0x00007FF6A5C3E026+1433638]
        11: from        Ordinal0 [0x00007FF6A5C31B8E+1383310]
        10: from        GetHandleVerifier [0x00007FF6A5D7A723+657939]
         9: from        GetHandleVerifier [0x00007FF6A5D81DAC+688284]
         8: from        GetHandleVerifier [0x00007FF6A5D79CE1+655313]
         7: from        GetHandleVerifier [0x00007FF6A5D79F49+655929]
         6: from        Ordinal0 [0x00007FF6A5C3BB91+1424273]
         5: from        Ordinal0 [0x00007FF6A5AF813E+98622]
         4: from        Ordinal0 [0x00007FF6A5AF6D7B+93563]
         3: from        Ordinal0 [0x00007FF6A5B80C41+658497]
         2: from        Ordinal0 [0x00007FF6A5C1D122+1298722]
         1: from        Ordinal0 [0x00007FF6A5CB8C82+1936514]
Backtrace:: unknown command: Cannot call non W3C standard command while in W3C mode (Selenium::WebDriver::Error::UnknownCommandError)

## Steps to reproduce
Used the below code to trigger against the Edge 79 browser and it throws the above errror.
But When I run the code excluding Capybara (Only Ruby+Selenium) it is performing all the user actions.

require 'selenium/webdriver'

require 'capybara/rspec'

include Capybara::DSL

Capybara.default_driver = :selenium
Capybara.register_driver :selenium do |app|
	caps=Selenium::WebDriver::Remote::Capabilities.edge(edgeOptions: {'w3c' => false})
	Capybara::Selenium::Driver.new(app, browser: :edge, desired_capabilities: caps)
end

capabilities = Capybara.current_session.driver.browser.capabilities
puts "running the tests with capabilities #{capabilities.inspect}"

$driver = Capybara.current_session.driver.browser

$driver.visit("https://www.aaaaabbbbvvvvv.com")

sleep 10

element=$driver.find(:xpath,"//button[@id='search']")

element.click

sleep 3

$driver.find(:xpath,"//input[@id='input-search']").send_keys "mobile"
[Edge-Selenium-Ruby.txt](https://github.com/teamcapybara/capybara/files/4164026/Edge-Selenium-Ruby.txt)

**Comment by twalpole** [comment]
Selenium 3.141.0 doesn't support Chrome based edge

**Comment by kishorekumartbm** [comment]
Hi Thomas,
 I have attached zip file while opening this issue.
It has two different files.
1. Program with Ruby+Selenium - Runs Edge without any issue
2. Program with Ruby+Selenium + Capybara - Here it is throwing the W3c mode error.

So it is not a problem with Selenium 3.141.0.
I believe Capybara is not supporting the New Edge Chromium execution

**Comment by twalpole** [comment]
Your Ruby+Selenium example doesn’t check the elements visibility so it doesn’t exhibit the issue ( just  look at the stack trace from the error ), selenium-webdriver 3.141.0 does not support chrome based edge - you need to upgrade

**Comment by kishorekumartbm** [comment]
My point is both are doing the same user action of 
1. Finding the element
2. Clicking the found above
3. Entering the text into a new element

When the above is performed using 3.141.0 ver of selenium but why Capybara is not doing the same.

Also do you have any recommendation for the selenium driver?

**Comment by twalpole** [comment]
They aren’t doing the same thing - Capybara finds visible elements, your Ruby+Selenium example doesn’t do that. I’ve now told you multiple times that the version of selenium you’re using doesn’t support Chrome based Edge. If you don’t want to upgrade selenium that’s up to you, but this is not a capybara issue
