### ISSUE TITLE
Not able to attach file remotely in sauce

### ISSUE THREAD

**Issue by vidhijain24** [teamcapybara/capybara#2307]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

Driver Information (and browser if relevant):

I am executing my code at sauce. There I trying to upload my file.
Below is the code:

`visit "http://xndev.com/display-image/"`
`element = find(:xpath, "//*[@id='post-2554']/div/input")`
`specific_filename = "C:\\Users\\vidhi.jain\\Pictures\\qa.JPG"`
`element.send_keys specific_filename`

My configurations are:
`RSpec.configure do |config|`
`	config.include Capybara::DSL, :type => :request`
`	config.include Capybara::DSL, :type => :acceptance`
`	config.include Capybara::RSpecMatchers, :type => :request`
`	config.include Capybara::RSpecMatchers, :type => :acceptance	`
`	caps = {`
`			url: 'https://app.saucelabs.com/login',`
`			browser_version: '79',`
`			browser_name: 'chrome',`
`			platform_name: 'Windows 10',`
`			"goog:chromeOptions" => {w3c: true},`
`			"sauce:options" => {`
`					name: 'Demo',`
`					seleniumVersion: '3.141.59',`
`					username: 'vidhijain24',`
`					accessKey: '**************',`
`					# tags to filter test reporting.`
`					tags: ['instant-sauce', 'ruby-rspec', 'module4'],`
`					maxDuration: 10800,`
`					commandTimeout: 300,`
`					idleTimeout: 1000`
`			}`
`	}`
`		Capybara.default_driver = :chrome`
`		Capybara.register_driver :chrome do |app|`
`		Capybara::Selenium::Driver.new(app, browser: :remote,url: "https://ondemand.saucelabs.com:443/wd/hub",desired_capabilities: caps).tap do |driver|`
`		driver.browser.file_detector = lambda do |args|`
`			str = args.first.to_s`
`			str if File.exist?(str)`
`		end`
`   end`
`  end`
`end`
Below is the error:
![image](https://user-images.githubusercontent.com/60422141/73926593-e25aa480-48f5-11ea-9611-d9dba7a3f83b.png)

**Comment by twalpole** [comment]
You need to talk to saucelabs about that

**Comment by vidhijain24** [comment]
When I searched over the internet about this error message. I found a solution ([link](https://github.com/SeleniumHQ/selenium/issues/7666)). I opened a file C:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\selenium-webdriver-3.141.0\lib\selenium\webdriver\remote\w3c\commands.rb and update the command upload of class Bridge.
original: upload_file: [:post, 'session/:session_id/se/file'.freeze]
To update: upload_file: [:post, 'session/:session_id/file'.freeze]

It works for me. I don't know why this works. And what is the issue.

Can you please help to explain what is the issue with session here?

**Comment by twalpole** [comment]
You need to contact SauceLabs and tell them they need to support the new selenium endpoints.  This is NOT a capybara issue.

**Comment by vidhijain24** [comment]
Hi @twalpole , Thanks for guiding me. But I am not understanding why I should not use selenium-webdriver 3.141.0?

**Comment by twalpole** [comment]
https://rubygems.org/gems/selenium-webdriver
