### ISSUE TITLE
How to clear out local storage for Internet Explorer using Selenium-Ruby-Capybara Framework

### ISSUE THREAD

**Issue by hari1690** [teamcapybara/capybara#2308]
Session storage is not getting cleared out in Internet Explorer

## Meta

Capybara Version: 3.10.0
Ruby : 2.5.6
Cucumber: 3.1.2
Rspec: 3.9.0
Selenium: 3.141.0
IE : 11.592

**Complete scenario and Steps to reproduce**

Run the below testcases using Selenium - Ruby - Cucumber - Capybara Framework 

1st Test case steps:
- Login User will be created using API
- By using login details created in the first step, Application will be logged in
- Application must be logged out using logout button

2nd Test case steps:
- Login User will be created using API
- By using login details created in the first step, Application will be logged in
- Application must be logged out using logout button

## Expected Behavior

Session Storage must be cleared out after 1st test case execution.

After executing 1st Testcase, Registered user session must be cleared out. For 2nd testcase, it should not withhold the 1st testcase user details.

## Actual Behavior

1st Test case steps:
- Login User will be created using API - **Login Details created - Pass**
- By using login details created in the first step, Application will be logged in - **Pass**
- Application must be logged out using logout button - **Pass**

2nd Test case steps:
- Login User will be created using API - **Login Details created - Pass**
- By using login details created in the first step, Application will be logged in - **Fail - As session is not cleared out, it shows the 1st testcase registered user**
- Application must be logged out using logout button - **Fail - due to the above step**

Main thing to observe - Our Application will hold the session details. Even after logging out, session will be stored as expected. This is the main reason why we need to clear the local storage after every testcase execution. This works in chrome and firefox browser, but not in IE.

**Tried methods:**

First Method:
$driver.execute_script("window.localStorage.clear()")
$driver.execute_script("window.sessionStorage.clear()")

Second Method:
$driver.manage.delete_all_cookies

Third Method:
caps = Selenium::WebDriver::Remote::Capabilities.ie ({clear_local_storage:true})
Capybara::Selenium::Driver.new(app, browser::ie, desired_capabilities:caps)

Fourth Method:
Capybara::Selenium::Driver.new(app, browser::ie)
Capybara.execute_script 'localStorage.clear()'

Fifth Method:
caps = Selenium::WebDriver::Remote::Capabilities.ie ({IE_ENSURE_CLEAN_SESSION:true})
Capybara::Selenium::Driver.new(app, browser::ie, desired_capabilities:caps)

**Comment by twalpole** [comment]
Capybara 3.10.0 is outdated - 3.31 is the latest - and beyond that https://rubydoc.info/github/teamcapybara/capybara/Capybara/Session#reset!-instance_method

**Comment by hari1690** [comment]
Hello @twalpole  Upgraded capybara to latest version (3.31) and used reset method as suggested. Still the clear storage method is not working. Do you recommend any other methods

$driver.reset!

**Comment by twalpole** [comment]
I didn’t recommend you to use `reset!` - I hoped you would read the documentation of `reset!`. As stated in the new issue template, this is for Capybara issues, it is not a location for how-to questions
