### ISSUE TITLE
Error When Uploading Multiple Files on Selenium 3.141

### ISSUE THREAD

**Issue by tubbo** [teamcapybara/capybara#2323]
## Meta
Capybara Version:
3.31.0

Driver Information (and browser if relevant):
selenium-webdriver 3.142.7
Using the "selenium/standalone-chrome:3.141" Docker image to run Chrome in a container

## Expected Behavior

When running the following code in a system test:

```ruby
      front = Rails.root.join('test', 'fixtures', 'files', 'front.jpg')
      back = Rails.root.join('test', 'fixtures', 'files', 'back.jpg')

      attach_file 'Front', front
      attach_file 'Back', back
```

I expect that the files will be uploading successfully, since I'm using a supposedly higher version of Selenium than is required for the upload to succeed.

## Actual Behavior

I get this error when trying to attach the second file:

```
ArgumentError: Selenium < 3.14 with remote Chrome doesn't support multiple file upload
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/selenium/nodes/chrome_node.rb:29:in `rescue in set_file'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/selenium/nodes/chrome_node.rb:17:in `set_file'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/selenium/node.rb:72:in `set'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/node/element.rb:123:in `block in set'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/node/base.rb:83:in `synchronize'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/node/element.rb:123:in `set'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/node/actions.rb:303:in `attach_file'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
    /usr/local/bundle/gems/capybara-3.31.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
    /usr/src/app/test/system/accounts_test.rb:75:in `block (2 levels) in <class:AccountsTest>'
    /usr/local/bundle/gems/vcr-5.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
    /usr/local/bundle/gems/vcr-5.1.0/lib/vcr.rb:188:in `use_cassette'
    /usr/src/app/test/system/accounts_test.rb:51:in `block in <class:AccountsTest>
```

## Steps to Reproduce

Write a test with two `attach_file` calls using standalone Chrome in a remote container, driven by Selenium.

**Comment by twalpole** [comment]
That error is raised when attaching the file raises an error message matching /File not found : .+\n.+/m .
It's possible that matcher is too liberal.  Since you're getting the error message when communicating with a remote Chrome I'm assuming the file is not available on the remote machine at Rails.root.join('test', 'fixtures', 'files', 'back.jpg'), and you haven't set up a FileDetector which Selenium requires if you want to send the file from the machine running the tests to a remote machine.

**Comment by tubbo** [comment]
That makes sense. I don't believe I've set up any kind of `file_detector`, and looking in the Selenium::WebDriver docs it would seem that none is specified by default. This is how I'm setting up my driver, by the way:

```ruby
Capybara.register_server :puma do |app, port, _host|
  require 'rack/handler/puma'

  Rack::Handler::Puma.run(
    app,
    Host: '0.0.0.0',
    Port: port,
    Threads: '0:4',
    Silent: true
  )
end

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    loggingPrefs: {
      browser: 'ALL'
    }
  )
  driven_by :selenium,
            using: :chrome,
            screen_size: [1400, 1400],
            options: {
              url: 'http://chrome:4444/wd/hub',
              desired_capabilities: capabilities
            }

  setup do
    host! "http://#{IPSocket.getaddress(Socket.gethostname)}"
  end

  # ...
```

This has worked so far in running the actual tests on the `selenium/standalone-chrome` container, but yeah I guess it can't find the file because it doesn't exist on that filesystem :)

**Comment by tubbo** [comment]
I tried changing my configuration to `using: :remote`, and that seemed to solve the file loader problem I was experiencing before. However, I'm noticing something very strange when my app actually tries to process the form. In my controller tests, I was getting an `ActionDispatch::Http::UploadedFile`, but in my system tests it's just the `String` filename (in this case, "front.jpg"). Not really sure why this is so different...
