### ISSUE TITLE
Add a delay option to click

### ISSUE THREAD

**Issue by Ecco** [teamcapybara/capybara#2324]
Hi there!

I'm testing a webpage which is sensitive to the *speed* at which a button is clicked. Weird, I know, but well, it's kinda simple actually : we just listen for "mouseup" and "mousedown" events, and act accordingly.

It would be awesome if we could do something like:

```ruby
find("button").click(delay: 0.5)
```

One a side note, it's currently possible to achieve this behavior by abusing drag_to. But it's obviously a dirty hack:

```ruby
button = find("button")
button.drag_to(button, delay: 0.5)
```

**Comment by twalpole** [comment]
Fixed via PR #2325

**Comment by Ecco** [comment]
Wow, that was quick!!! Thank you so much!!!

**Comment by twalpole** [comment]
You’re welcome, it’ll go into a release tonight or tomorrow

**Comment by Ecco** [comment]
Awesome. Thanks!
