### ISSUE TITLE
ActionController::UnknownFormat error even though manual test is successful

### ISSUE THREAD

**Issue by angarc** [teamcapybara/capybara#2328]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 

capybara (3.31.0, 3.29.0)

Driver Information (and browser if relevant):

selenium-webdriver (3.142.7, 3.142.6)

## Expected Behavior

A successful test. I know it's supposed to be successful because when I manually test it, it works as expected.

## Actual Behavior

```
Failures:

  1) Blogs create new blog should be successful with all values filled
     Failure/Error:
       respond_to do |format|
         format.js
       end

     ActionController::UnknownFormat:
       ActionController::UnknownFormat
     # ./app/controllers/dashboard/blogs_controller.rb:15:in `create'
     # ./spec/features/blogs_spec.rb:17:in `block (3 levels) in <main>'
```

## Steps to reproduce

Here is my test:
```
RSpec.feature 'Blogs', type: :feature do
  setup do 
    user = create(:user)
    login_as user
  end

  context 'create new blog' do
    it 'should be successful with all values filled' do 
      visit dashboard_blogs_path
      expect(page).to have_content('Blogs Overview') 
      find('#newBlogModalButton').click
      within('#newBlogModalForm') do 
        fill_in 'Name', with: 'My Blog'
      end
      find('#create_blog_modal_button').click
      expect(page).to have_content('My Blog')
    end
  end
end
```

Here is my html code:
```
<%= simple_form_for @blog, html: { id: 'newBlogModalForm' }, url: dashboard_blogs_path, remote: true do |f| %>
  <div class="modal-body">
    <div class="form-group row">
      <%= f.label :name, class: 'col-sm-2 col-form-label' %>
      <%= f.input :name, 
        label: false, 
        placeholder: 'John Doe\'s Blog', 
        input_html: { class: 'form-control' },
        wrapper_html: { class: 'col-sm-10' },
        hint: 'required' %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit class: 'btn btn-primary', id: :create_blog_modal_button %>
  </div>
<% end %>
```

And my controller action:
```
    def create
      @blog = Blog.new blog_params
      @blog.users << current_user

      if @blog.save
        @blogs = current_user.blogs
        respond_to do |format|
          format.js
        end
      else
        flash[:danger] = @blog.errors.full_messages.to_sentence
      end
    end
```

I'm a bit new to testing, so my tests probably aren't best practice. Also, I saw this same error on a stackoverflow post posted in 2014, but it had no solution.

Hopefully you all can help!

**Comment by twalpole** [comment]
The error is telling you what the problem is - `ActionController::UnknownFormat:` and the only format your code is supporting is `js` - so you're running Capybara with a driver that isn't making a js request.  This most likely means you're running Capybara with the default rack_test driver - see https://github.com/teamcapybara/capybara#drivers and then configure Capybara to use a JS capable driver, or write your app to support non-JS requests too.
