### ISSUE TITLE
capybara wrong element is clicked somehow

### ISSUE THREAD

**Issue by yanshney** [teamcapybara/capybara#2339]
Capybara Version:
3.14.0
Driver Information (and browser if relevant):
selenium-webdriver 3.141.0 with Firefox

## Expected Behavior
I have this capybara test:

 private_session_span_save = private_session_2.find("span", text: "Save this property", wait: 6)
 puts private_session_span_save.inspect
 private_session_span_save.click

Locally it clicks on the span element successfully. On codeship the second line has the same output as locally:

#<Capybara::Node::Element tag="span" path="/HTML/BODY[1]/DIV[4]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/DIV[1]/FORM[1]/BUTTON[1]/SPAN[1]">

But the third line causes this error: 

Selenium::WebDriver::Error::ElementClickInterceptedError:         Selenium::WebDriver::Error::ElementClickInterceptedError: Element <button name="button" type="submit"> is not clickable at point (133,119) because another element <img class="property-tour-carousel-image"> obscures it.

The button mentioned in this error is the parent of the span element that I am trying to find, but I am trying to click the span, not its parent. Or should the parent of the element also be clickable?

Thank you,
Yan

**Comment by twalpole** [comment]
I don't see a button in the error in your post, but most likely your window size on codeship is set differently than locally and the layout of the page is preventing the span from being interacted with.

**Comment by yanshney** [comment]
Oh sorry it got edited out somehow when I pasted 
Here is the full error: 
Hi twalpole! Thank you for your response!

Here is the full error, sorry
Selenium::WebDriver::Error::ElementClickInterceptedError:         Selenium::WebDriver::Error::ElementClickInterceptedError: Element 'button name="button" type="submit"' is not clickable at point (133,119) because another element obscures it.

I understand that the setup could be different, but it is being told it should click on span and instead the error message is about the button that is a parent of this span. Or this could still be caused by the the window size difference?

**Comment by twalpole** [comment]
That error is returned by Selenium - and the text may actually be coming from firefox or selenium.  Either way it's still most likely due to window size.  Note also that Capybara 3.14 is obsolete at this point in time as is selenium 3.141.0 - you really should be upgrading.

**Comment by yanshney** [comment]
Okay, will do, thank you!
