### ISSUE TITLE
Click on submit skipping randomly

### ISSUE THREAD

**Issue by fabriciofreitag** [teamcapybara/capybara#2343]
## Meta
Capybara Version:
3.32.1
Driver Information (and browser if relevant):
selenium-webdriver 3.142.7

## Expected Behavior
`find('input[name="commit"]').click`, `click_on 'Save'` and `click_button 'Save', exact: true` should submit the form.

## Actual Behavior
Form submission fails randomly (from 1 to 3 times out of 200 times with the same seed number).
If I manually trigger the same `click` again it works as expected:

```
     97: 
     98:           find('input[name="commit"]').click
 =>  99:           binding.pry unless page.has_content?("Due date can't be blank")
    100: 
    101:           expect(page).to have_content("Due date can't be blank")
    102:           expect(page).to have_content("Scheduled time can't be blank")
    103:           expect(current_path).to eq(admin_task_path(task))

[1] pry(#<RSpec::ExampleGroups::Tasks::WhenALoggedUserIsCRUDingTasks::Edit::WhenTryingToUpdateATaskWithoutDueDateOrScheduledTime>)> find('input[name="commit"]')
=> #<Capybara::Node::Element tag="input" path="/HTML/BODY[1]/DIV[1]/DIV[1]/DIV[1]/FORM[1]/DIV[9]/INPUT[1]">
[2] pry(#<RSpec::ExampleGroups::Tasks::WhenALoggedUserIsCRUDingTasks::Edit::WhenTryingToUpdateATaskWithoutDueDateOrScheduledTime>)> page.has_content?("Due date can't be blank")
=> false
[3] pry(#<RSpec::ExampleGroups::Tasks::WhenALoggedUserIsCRUDingTasks::Edit::WhenTryingToUpdateATaskWithoutDueDateOrScheduledTime>)> find('input[name="commit"]').click
=> Obsolete #<Capybara::Node::Element>
[4] pry(#<RSpec::ExampleGroups::Tasks::WhenALoggedUserIsCRUDingTasks::Edit::WhenTryingToUpdateATaskWithoutDueDateOrScheduledTime>)> page.has_content?("Due date can't be blank")
=> true
```

## Steps to reproduce
[Full page HTML](https://pastebin.com/ANySCUVG) at the time of the `submit`

The same happens using:
`click_on 'Save'`
`click_button 'Save', exact: true`

Also tried enabling:
`Capybara.default_max_wait_time = 5`

Thanks for considering this issue and do let me know if I'm missing any information.

**Comment by twalpole** [comment]
These types of issues generally boil down to one of two things (assuming not an actual bug in your app)

1. Animation on the page (panels sliding/fading up/down/left/right/in/out) which can cause clicks to miss the actual element if it moves between when the driver gets its position and actually sends the click event. The solution for that is to disable animation in the test environment or use an assertion for something that indicates the page is stable

2. JS behavior that is enabling/disabling the button. If the form has JS driven validation that is enabling/disabling the button in some way other than by adding a `disabled` attribute then Capybara has no way of knowing the button is disabled and will just click it. If it was disabled by use of the `disabled` attribute `click_button` would check for the attribute and wait for it to become enabled (your `find(...).click` would not). If this is the case then you need to change the selector for your button to be aware of whatever method is being used to enable/disable the button

**Comment by fabriciofreitag** [comment]
Hi Thomas.

Thanks for looking at this.
The first thing asserted was the lack of submission.
I'm using bootstrap, but no animations and no custom javascript, everything is pure rails forms with activerecord validations.
I thought maybe the element finding could be failing silently, hence the test with `default_max_wait_time`.
Any other ideas of what to investigate are very welcome.

**Comment by twalpole** [comment]
You say you use bootstrap but have no animations - Is this because you've disabled the animations? Bootstrap by default uses animations on many of its components when displaying them.  

Try setting `Capybara.disable_animation = true` in your global test config - It will attempt to disable animation via page injection.  If that fixes your issue then you'll want to actually work out how to more surgically disable animation only for the libraries you're using instead, or use an assertion to make sure the page is actually stable before clicking.  `Capybara.disable_animation` unfortunately can't always disable all animation, so even if it doesn't fix the issue it doesn't rule out animation being the issue.

**Comment by twalpole** [comment]
Closing due to lack of response
