### ISSUE TITLE
Doc for `server_port` says "see configure" but it's not mentioned there

### ISSUE THREAD

**Issue by avdi** [teamcapybara/capybara#2348]
https://github.com/teamcapybara/capybara/blob/d6a3e18f5c605236ae41ec90e872ae6a554c12fc/lib/capybara/session/config.rb#L65

**Comment by twalpole** [comment]
Fixed via b4dbf6473a40b2b7ac4ef2a5067af38977a4ddf4

**Comment by avdi** [comment]
Thanks @twalpole! 🙏
