### ISSUE TITLE
Using lazy enumarators on JRuby causes issues since version 3.29.0

### ISSUE THREAD

**Issue by Unknown-Guy** [teamcapybara/capybara#2349]
First of all to link with issue on JRuby side here https://github.com/jruby/jruby/issues/6004 but also as it impacts Capybara directly then maybe something should be done on Capybara side.

With this change https://github.com/teamcapybara/capybara/commit/2e052792a59d0c183ff42009cc73bf7e9eae43c6 we started to see issues with JRuby threads to the point it just runs out of them. Reverting the change fixed the issue for us.

**Comment by headius** [comment]
FWIW we do want to fix this Lazy fiber leak but it's a very tricky thing to do.

No alternative Ruby has perfected thread-based fibers yet, though I believe we're the closest. If it's possible to patch the laziness back out of Capybara, that would be a big help to our users.

The short explanation is that when using `Lazy` + `Enumerator#next`, the Fiber used to drive the `next` logic ends up getting referenced on its own native thread stack. As a result, the JVM GC does not see the fiber ever get dereferenced, so it ends up in memory and alive forever.

The workarounds are:

* Don't use `Lazy` and `Enumerator#next` together.
* Make sure you consume everything from `next` so the fiber comes to an end.

**Comment by headius** [comment]
I believe doing an `Enumerator#rewind` will also reset the fiber and may avoid this issue.

**Comment by headius** [comment]
Oh to clarify one other point... this issue mostly affects **incomplete** enumerators, i.e. enumerators that do not finish iterating over all elements before they are abandoned. We spin up a thread for the fiber that drives `next`, which will run to completion if you use all elements (i.e. we won't have a dangling fiber waiting for the next call to `next`). When an enumerator is abandoned without finishing that iteration, the thread stays alive and will take a while to clean up.

Best practice to avoid dangling fibers (on any implementation) would be to either `rewind` or consume all elements via `next`.

**Comment by twalpole** [comment]
@headius Since the point of using a lazy enumerator was to not need to evaluate every element if not necessary - consuming all elements pretty much defeats the purpose.  From the discussion it sounds like lazy enumerator support in JRuby is fundamentally flawed and might be better to just disable it completely rather than let people write code which quietly leaks resources.

**Comment by twalpole** [comment]
@Unknown-Guy @boris-petrov Please try the jruby_lazy_enumerator branch and let me know if it fixes the issue

**Comment by boris-petrov** [comment]
@twalpole - yep, this fixes the problem. No more hanging threads. Thanks!

**Comment by twalpole** [comment]
Closing via PR #2351
