### ISSUE TITLE
Maybe not the best way to support HTTPS?

### ISSUE THREAD

**Issue by ioquatix** [teamcapybara/capybara#2355]
Hi, I'm the maintainer of falcon-capybara, and I want to use HTTPS and HTTP/2 by default. It became more important recently because things like secure cookies needed by default and don't work across HTTP (insecure).

We have a special code path when dealing with `localhost` (skip verification) so it would be great if we can use `localhost` rather than `127.0.0.1` by default.

Next, I don't feel the [`Checker` approach](https://github.com/teamcapybara/capybara/blob/bfe0a72c39bf6bbdc9e885a3dc8e968f9416c4fc/lib/capybara/server/checker.rb#L5) is a good one because not only is it slow, it's better for user to be explicit about it.

I suggest you have some configuration option like:

```
Capybara.configure do |config|
  config.host = "https://localhost"
end
```

Also, rather than generating a port the adaptor should bind to port 0 and that return the address.

Anyway, not quite sure if this is useful feedback, I'll keep on pushing my way forward and see how I go.

**Comment by ioquatix** [comment]
Okay, the other part of this is ensuring the browser allows insecure "localhost":

```
Capybara.register_driver :selenium_chrome do |app|
	Capybara::Selenium::Driver.load_selenium
	browser_options = ::Selenium::WebDriver::Chrome::Options.new.tap do |opts|
		opts.args << '--disable-site-isolation-trials'
		opts.args << '--allow-insecure-localhost'
	end
	Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options)
end
```

Adding `opts.args << '--allow-insecure-localhost'` is good enough.

So:

Can we make the `https` support "opt-in" by the user, which is passed through to the server and selenium appropriately?

**Comment by ioquatix** [comment]
Okay so to follow up, here is what I ended up doing:

```
Capybara.configure do |config|
	config.app = Rack::Builder.parse_file(
		File.expand_path('../config.ru', __dir__)
	).first
	
	config.threadsafe = false
	
	config.server = :falcon_https
	config.default_driver = :selenium_chrome_headless_https
	config.javascript_driver = :selenium_chrome_headless_https
end
```

I added `falcon_http` and `falcon_https` as servers.

I added patched versions of `selenium_chrome_headless_https` and `selenium_chrome_https`.

I feel like these concerns should probably be solved by the core library, but understand if it's out of scope.

The implementation is here: https://github.com/socketry/falcon-capybara/commit/84f86d117ca330715fd22dc95daa08f2a5c35e10

I do feel like feeding the host through to the driver and server would make this process a lot easier.

**Comment by twalpole** [comment]
server_host : Capybara has gone back and forth over the years between 127.0.0.1 and localhost as the default for server_host, but 127.0.0.1 has had the least problems for the most people (you can search Capybaras issue and source history) so that's what we'll be sticking with.  If you feel you need localhost you're free to see it via `Capybara.server_host`.  

allow_insecure_localhost: For anything more than basic cases it's up to users to configure their driver they way they need.  If someone wants to use https in an insecure manner that's up to them, Capybara will not be supporting that as a default position.

port 0: last time I checked this didn't work across all varieties of ruby, so we'll be sticking with with what we have for now

checker: It's a one time cost at test startup, that amounts for a tiny percentage of any test run, and makes things simpler for most users.  We could add a mode that only tries https, but we would still default to using the checker if that wasn't specified so don't really see the point.

**Comment by ioquatix** [comment]
> Capybaras issue and source history) so that's what we'll be sticking with. If you feel you need localhost you're free to see it via Capybara.server_host.

Great, I didn't see this option in the documentation, I must have missed it.

> Not sure what I was thinking about here, we do get a random port by requesting port 0, unless the user specifies a port, so not really sure what this is about

Can you point me at the code that does this?

> checker: It's a one time cost at test startup, that amounts for a tiny percentage of any test run, and makes things simpler for most users. We could add a mode that only tries https, but we would still default to using the checker if that wasn't specified so don't really see the point.

It's more about being predictable. Maybe someone has a server capable of both on the same port but the user wants https.

**Comment by ioquatix** [comment]
I can't see how you set `server_host` in the configure block. Is that a thing?

**Comment by ioquatix** [comment]
Okay, so reporting back on this issue:

```
 0.82s    error: Async::Task [oid=0x2b20463debb8] [pid=2946] [2020-06-05 13:33:51 +0000]
               |   OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: http request
               |   → /home/runner/work/socketry.io/socketry.io/vendor/bundle/ruby/2.6.0/gems/async-io-1.30.0/lib/async/io/generic.rb:216 in `accept_nonblock'
               |     /home/runner/work/socketry.io/socketry.io/vendor/bundle/ruby/2.6.0/gems/async-io-1.30.0/lib/async/io/generic.rb:216 in `async_send'
               |     /home/runner/work/socketry.io/socketry.io/vendor/bundle/ruby/2.6.0/gems/async-io-1.30.0/lib/async/io/generic.rb:62 in `block in wrap_blocking_method'
               |     /home/runner/work/socketry.io/socketry.io/vendor/bundle/ruby/2.6.0/gems/async-io-1.30.0/lib/async/io/ssl_socket.rb:145 in `block in accept'
               |     /home/runner/work/socketry.io/socketry.io/vendor/bundle/ruby/2.6.0/gems/async-1.26.1/lib/async/task.rb:258 in `block in make_fiber'
```

Is logged for every spec since OpenSSL fails for the incoming request.

So, it seems like it would make sense to at least have a way of specifying this and bypassing the checker implementation.

What do you think?

**Comment by twalpole** [comment]
@ioquatix I don't know what you're doing. The Capybara ssl Checker behavior is only done when initially contacting a server while waiting for it to be responsive (up).  If you're seeing errors with every spec either that's not coming from capybara (don't see capybara in the stacktrace of the log you're showing, or you're somehow creating a new server instance for every spec which is not normal.  Maybe Capybara isn't the best tool for whatever you're trying to do??

**Comment by ioquatix** [comment]
> The Capybara ssl Checker behavior is only done when initially contacting a server while waiting for it to be responsive (up).

Sorry, I misunderstood the output I was getting, it looks like the checker is hitting the server once with the HTTP request... the followup requests are from Chromium and is apparently a known issue when dealing with self-signed certificates.

![image](https://user-images.githubusercontent.com/30030/83933042-5308c380-a7f9-11ea-8e04-5b40686978f6.png)

Overriding `@ssl` in a monkey patch forces the first request to be HTTP which then doesn't print out the failed OpenSSL negotiation.

```
module Capybara
  class Server
    class Checker
      def initialize(host, port)
        @host, @port = host, port
        @ssl = true
      end
    end
  end
end
```

Sorry for the previous confusion.

So, some way for the server to report what protocol it's using could be great. Probably the server implementation itself should expose this, e.g. `https?` or something similar.
