### ISSUE TITLE
Bug? within_frame affects all frames?

### ISSUE THREAD

**Issue by benlieb** [teamcapybara/capybara#2357]
## Meta
Capybara Version:

Driver Information (and browser if relevant):

## Code

```ruby
      within_frame(find_all('.panel#marketing iframe')[0]) do
        # warning there seems to be a bug in capybara that sends this to all capybara frames (weird)
        # the block below still works, but will also have this text as well
        find('.mce-content-body').send_keys 'foo_bio'
      end

      within_frame(find_all('.panel#marketing iframe')[1]) do
        find('.mce-content-body').send_keys 'foo_short_bio'
      end
```

## Expected Behavior
I would expect that the ` find('.mce-content-body').send_keys 'foo_bio'` would only affect the first frame, but both are affected, and then contain `foo_bio`.

Interestingly inside the block `find_all('.mce-content-body').count` is `1`.  So perhaps this is something internal to `tinymce-react` ?

## Actual Behavior
As I say above both are affected. But strangely inside the next block, only the second one is affected. So I end up with a state that looks like this:

![image](https://user-images.githubusercontent.com/634562/83070398-47124a00-a020-11ea-9a58-9682c22da744.png)

**Comment by twalpole** [comment]
Interesting, if there is an actual bug here it's going to be in whichever driver you're using (assume selenium?).  I'm going to need to try and replicate the issue to investigate any further which I don't have time to do right now.

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/6a886efd78fe0e6fcc3e3d6cd7c4ca4d is code that creates two frames with content editable elements inside and sends keys to them. They behave as expected, which would indicate either your code is doing more than shown, tinymce editor is somehow in the parent window when editing, or the multiple tinymce widgets are communicating between each other somehow.  If you can update the gist to reproduce the issue I'll look further, but as of now I'm not convinced this is actually a Capybara issue.

**Comment by twalpole** [comment]
Closing due to lack of response.  If/when a reproduction case is provided I will reopen.
