### ISSUE TITLE
 Capybara::Node::Element set() stripping off everything after newline character

### ISSUE THREAD

**Issue by ucguy** [teamcapybara/capybara#2362]
Capybara Version: 3.29.0 

Driver Information:
selenium-webdriver (3.142.7)
with Chrome Version 83.0.4103.61

## Expected Behavior
When we use the `Capybara::Node::Element` `set()` method for a textbox input element like so:

```
textbox.set("multiple\nlines\nof\ninput")
```

We expect the value of the text to be "multiple\nlines\nof\ninput"

## Actual Behavior
What we actually get is the value of the textbox becomes just "multiple"

I am beginning to write a spec to expose this behavior. Let me know if that would be helpful.
In the meaning time, our workaround for the issue is by doing: 

```
page.execute_script %{$('.textbox-class').val("multiple\nlines\nof\ninput").trigger('change')}
```

**Comment by twalpole** [comment]
Yes a spec that shows the behavior would be helpful.  When you say "textbox" do you mean an `<input type="text">...` element, or a `<textarea>...` element?

**Comment by twalpole** [comment]
If you do actually mean an `<input type="text">...` element - it's not legal to have multiple lines in one - https://html.spec.whatwg.org/multipage/input.html#text-(type=text)-state-and-search-state-(type=search) - `User agents must not allow users to insert U+000A LINE FEED (LF) or U+000D CARRIAGE RETURN (CR) characters into the element's value.`

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/6a3b090ee1f71161fc0188f472898b02 is a gist showing the behaviors of the three different types of text inputs.  The text input should definitely not be returning a value including the `\n` since the browser doesn't allow you to type that in there. Whether it should be set to the full string with the `\n`s removed or just part of the string is debateable.

**Comment by twalpole** [comment]
Closing due to lack of response - Will reopen if there is more to discuss
