### ISSUE TITLE
Calling 'has_key?' on the drivers/servers container is deprecated without replacement

### ISSUE THREAD

**Issue by thoraxe** [teamcapybara/capybara#2371]
## Meta
Capybara Version:
3.33.0

Driver Information (and browser if relevant):
selenium-webdriver (3.142.7)
webdrivers (4.4.1)
websocket-driver (0.7.1)
turnip (4.1.0)
cucumber-gherkin (10.0.0)
cucumber-messages (10.0.3)
protobuf-cucumber (3.10.8)

Mozilla Firefox 68.10.0esr

## Expected Behavior
More information about deprecation warnings or what is actually wrong

## Actual Behavior
`DEPRECATED: Calling 'has_key?' on the drivers/servers container is deprecated without replacement`

## Steps to reproduce
I'm not entirely sure. I upgraded to Capybara 3.33.0 and, when running my test, got this warning.

3.32.2 does not produce this warning.

I'm not sure if this is related to turnip/cucumber, or something else. The message tells me nothing about which code invoked `has_key?` so I don't know how to troubleshoot further.

Is there a way to get more verbosity out of the warning?

**Comment by twalpole** [comment]
Treating the driver registrations as a Hash is deprecated. Something in your code/included libraries is calling `Capybara.drivers.has_key?` and that won't be supported in Capybara 4.x.  As of now no further information is output although PRs to add that would be accepted.

**Comment by thoraxe** [comment]
@twalpole How the heck can I figure out what's calling that? I have... dozens of gems?

It's not in my code:

```
app/api/result_wrapper.rb:        if parsed_body.has_key?(COLLECTION_KEY)
node_modules/node-sass/src/libsass/src/sass_util.hpp:        if not grouped.has_key?(key) then
```
The above is from a grep on the entire codebase. So, the only thing I can think is that it's in one of the gems related to Capybara?

**Comment by luke-hill** [comment]
@thoraxe If those gems are doing proper semver, then when capybara 4.0 is released they will do fixes their end, or they will fix this up beforehand.
