### ISSUE TITLE
Can't run selenium on AWS Windows Server

### ISSUE THREAD

**Issue by 1660623** [teamcapybara/capybara#2372]
Although I have successfully run selenium on my Windows laptop, I couldn't run  it  on AWS Windows server. It returned below error:

<div id="content">
       <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:4444/session">http://127.0.0.1:4444/session</a></p>

       <blockquote id="error">
       <p><b>Connection to 127.0.0.1 failed.</b></p>
       </blockquote>

       <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

       <p>The remote host or network may be down. Please try the request again.</p>

       <p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=.............

Can you help me to run it. Thank you very much.

This is my sample project:
https://github.com/trinhcanhphuc/rails-capybara-example

**Comment by twalpole** [comment]
The error seems to be something trying to connect to a selenium instance that isn’t running (or is blocked by a firewall)  beyond that I can’t really help you - this is for Capybara issues not Selenium issues

**Comment by trinhcanhphuc** [comment]
Your connect has trouble, check with proxy. My code use to resolve your trouble:
sample-selenium.rb

`require 'capybara'
require 'capybara/dsl'
include Capybara::DSL

ENV['NO_PROXY'] = ENV['no_proxy'] = '127.0.0.1'

Capybara.app_host = 'http://127.0.0.1:3000'
Capybara.server_port = 3000
Capybara.default_driver = :selenium_chrome
Capybara.default_selector = :css
Capybara.default_max_wait_time = 10

Capybara.register_driver :selenium do |app|
  profile['network.proxy.type'] = 1
  profile['network.proxy.http'] = 'localhost'
  profile['network.proxy.http_port'] = 3128

  Capybara::Selenium::Driver.new(app, browser: :chrome, profile: profile)
end

visit 'http://www.google.com'
`
