### ISSUE TITLE
DEPRECATED: Directly setting drivers/servers is deprecated, please use Capybara.register_driver/register_server instead

### ISSUE THREAD

**Issue by ioquatix** [teamcapybara/capybara#2376]
Thanks for your effort with the latest release.

It looks like directly adding records to `servers` is deprecated. Do you mind explaining why that is?

https://github.com/socketry/falcon-capybara/issues/2

`falcon-capybara` uses a wrapper instance of a block because the server instance exposes a work queue for executing jobs within the server's reactor. It implements `#call` as expected. This allows the following:

```
Capybara.server.remote do
	# This will run on the server thread.
end
```

The `register_server` interface is not sufficient since it's not possible to pass an instance, only a proc/block is accepted.

I am happy to try and rework this on my end, but I'm afraid it will break `Capybara.server` usage.

**Comment by ioquatix** [comment]
Regarding the change here:

https://github.com/teamcapybara/capybara/commit/6fcd43aec8db49184a28f05ab6fbc20670911dee

What about introducing:

```ruby
def register_server(name, instance = nil, &block)
  servers.send(:register, name.to_sym, instance || block)
end
```

**Comment by ioquatix** [comment]
Here is a hack which works but I don't really like:

``` ruby
class Wrapper < Proc
	def self.new(*arguments)
		super{}
	end
end
```

``` ruby
Capybara.register_server(:falcon, &Falcon::Capybara::Wrapper.new)
Capybara.register_server(:falcon_http, &Falcon::Capybara::Wrapper.new("http"))
Capybara.register_server(:falcon_https, &Falcon::Capybara::Wrapper.new("https"))
```

**Comment by ioquatix** [comment]
Here is a more realistic fix: https://github.com/socketry/falcon-capybara/pull/3

However, it would be nice to have some way to access the return value of `#call` so that we can implement a job queue.

**Comment by twalpole** [comment]
This was done because I have thoughts of updating the server/driver requirements/functionality in the future and that can't happen if people are sticking random things in drivers/servers - so I'm enforcing the original intent of the server and driver registries.  Current support won't go away before 4.0 which doesn't have any date yet but 99% sure it won't be this year.

**Comment by ioquatix** [comment]
@twalpole What are your thoughts about updating the driver requirements/functionality?
