### ISSUE TITLE
click_link_or_button with :title option

### ISSUE THREAD

**Issue by sj26** [teamcapybara/capybara#2386]
Hi there! Thanks, I love capybara. But I found an oddity which I can't quite figure out.

[click_link_or_button](https://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions#click_link_or_button-instance_method) claims to work like [click_button](https://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions#click_button-instance_method) or [click_link](https://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions#click_link-instance_method), and they claim to accept the same arguments as [find_button](https://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Finders#find_button-instance_method) and [find_link](https://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Finders#find_link-instance_method), both of which accept a `title: ...` option without a locator. But instead it raises an exception.

I think it's something to do with the `link_or_button` locator, but I don't understand the class composition well enough to identify and solve the error in order to provide a pull request, sorry!

## Meta
Capybara Version: 3.33.1
Driver Information (and browser if relevant):
selenium-webdriver 3.142.3

## Expected Behavior

```ruby
page.click_link_or_button title: "Some Button"
# clicks a link or button with the given title
```

## Actual Behavior

```
     ArgumentError:
       Invalid option(s) :title, should be one of :above, :below, :left_of, :right_of, :near, :count, :minimum, :maximum, :between, :text, :id, :class, :style, :visible, :obscured, :exact, :exact_text, :normalize_ws, :match, :wait, :filter_set, :disabled
     # capybara-3.33.0/lib/capybara/queries/selector_query.rb:352:in `assert_valid_keys'
     # capybara-3.33.0/lib/capybara/queries/selector_query.rb:52:in `initialize'
     # capybara-3.33.0/lib/capybara/node/finders.rb:52:in `new'
     # capybara-3.33.0/lib/capybara/node/finders.rb:52:in `find'
     # capybara-3.33.0/lib/capybara/node/actions.rb:26:in `click_link_or_button'
     # capybara-3.33.0/lib/capybara/session.rb:759:in `block (2 levels) in <class:Session>'
     # capybara-3.33.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # ./spec/features/my_feature_spec.rb:155:in `block (5 levels) in <top (required)>'
```

**Comment by twalpole** [comment]
Click_link_or_button claims that the `locator` works the same as click_link or click_button - The locator is the string that can be passed in which will be attempted to match against multiple properties of the elements.  It does not accept the same options that click_link or click_button accept.  If you want to specify exactly what should be matched against then you should also be specifying whether it's a link or a button and calling the appropriate method.

    click_link_or_button 'Some Button'    #  'Some Button' is the locator and would attempt to be matched against the title and other attributes

**Comment by sj26** [comment]
Never mind, I just realised that I don't need the "title:" at all, specifying the title as a locator works just fine. Sorry!
