### ISSUE TITLE
Unable to find css when find element with Internet Explorer

### ISSUE THREAD

**Issue by trinhcanhphuc** [teamcapybara/capybara#2387]
I got Capybara::ElementNotFound: Unable to find css when I use Capybara with Internet Explorer. However, Chrome work normally.
Can you help me.
Thanks

**Comment by twalpole** [comment]
You need to provide details of exactly what you’re doing, and the exact error messages. Better yet, provide a stand alone example that demonstrates the issue you’re having

**Comment by trinhcanhphuc** [comment]
Thanks. I fixed this bug by adding Capybara.ignore_hidden_elements = false to init
