### ISSUE TITLE
Capybara fails to recognize Vue-Fragments

### ISSUE THREAD

**Issue by Mattwhooo** [teamcapybara/capybara#2390]
## Meta
Capybara Version: 
3.33.0

Driver Information (and browser if relevant):
Selenium Chrome. Chrome 85

## Actual Behavior
Capybara is unable to recognize elements created with Vuejs and Vue-Fragments

## Steps to reproduce
I've created a repo with a reproducible example.   https://gitlab.com/mattwhooo/capybara_vue_fragment 
In this repo it's serving a static site with VueJS.  The site contains a table with several rows and cells containing text generated by VueJS and Vue-Fragment.  In one of the rows the text can not be found by Capybara.

I don't know enough about Capybara internals to know where to start looking for this but if someone would point me in the right direction I would be happy to dig in to it.  Thanks!!

**Comment by Mattwhooo** [comment]
Investigating a little more I see that if the HTML generated by Vue-Fragment is 
```
<td>
    <!--fragment#dced76579b#head-->
    <div fragment="dced76579b">
         Fragment-Text
    </div>
    <!--fragment#dced76579b#tail-->
</td>
```
it fails, but if there is no div wrapper
```
<td>
    <!--fragment#143bd7c5159#head-->
    Fragment-Text<!--fragment#143bd7c5159#tail-->
</td>
```
It works.

**Comment by twalpole** [comment]
Since this works fine with Firefox - it is most likely a bug in the current version of chromedriver

**Comment by Mattwhooo** [comment]
Thanks. I've opened an issue with chrome driver project!
