### ISSUE TITLE
Unable to change browser language with intl.accept_languages

### ISSUE THREAD

**Issue by woto** [teamcapybara/capybara#2391]
## Meta
Capybara Version: 3.33.0
Driver Information (and browser if relevant): selenium-webdriver 3.142.7 with Chrome 85.0.4183.102 47.0.1

## Expected Behavior

Changing `request.headers['Accept-Language']`

## Actual Behavior

Do not changes

## Steps to reproduce
Hello!

Nor add_option, neither add_preferences do not change Accept-Language header

```ruby
    driven_by :selenium, using: :chrome do |driver_option|
      # driver_option.add_option('prefs', 'intl.accept_languages' => 'en-US')
      driver_option.add_preference('intl.accept_languages' => 'en-US')
    end
```

I found that this way does work

```ruby
Capybara.register_driver :browser do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_option('prefs', 'intl.accept_languages' => 'en-US')

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    options: options
  )

RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :browser, using: :chrome
  end
end
```

And seems the reason is that `options` passed in `Capybara::Selenium::Driver` constructor

I also tried

```ruby
options = Selenium::WebDriver::Chrome::Options.new
options.add_option('prefs', 'intl.accept_languages' => 'en-US')

driven_by :selenium, using: :chrome, options: options do |driver_option|
```

And this could be work if there is not merge method https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/driver.rb#L43
which leads to this error

```ruby
          NoMethodError:
            undefined method `merge' for #<Selenium::WebDriver::Chrome::Options:0x00007fb860ff1818>
```

for example like this it works fine

```ruby
        def browser_options
          { options: @options }
          # @options.merge(options: @browser.options).compact
        end
```

What do you think? Is it a Capybara bug? Selenium? ActionPack?

Thank you!

**Comment by twalpole** [comment]
Considering that every object/method you appear to be having an issue with is from Selenium or Rails, I would guess you're having an issue with one of them - doesn't appear to be a bug in Capybara

**Comment by woto** [comment]
Ok, thank you will try to bug report there with link here
