### ISSUE TITLE
Still able to download files with Capybara selenium and chrome headless?

### ISSUE THREAD

**Issue by nerrante** [teamcapybara/capybara#2393]
Hi Thomas,

I am trying to be able to download files with chrome headless using capybara and selenium. I know there have been issues in the past but apparently they have been resolved.  When googling, I found this StackOverflow response from you: https://stackoverflow.com/questions/52640691/chrome-headless-download-pdf-using-capybara-and-selenium

You gave a link to the configuration you use for testing capybara with selenium and chrome headless, and mentioned that you are able to download files with that config.  I just wanted to check to make sure if that is still true?  I copied your config but still can't get any file to download (tried one that downloads directly from page and one that opens a new tab).  Any thoughts?

For reference, this is the driver config I used based on what you had:

browser_options = ::Selenium::WebDriver::Chrome::Options.new
browser_options.headless!
browser_options.add_option(:w3c, ENV['W3C'] != 'false')
 Chromedriver 77 requires setting this for headless mode on linux
 Different versions of Chrome/selenium-webdriver require setting differently - jus set them all
browser_options.add_preference('download.default_directory', 'C:/Users/nerrante/Downloads')
browser_options.add_preference(:download, default_directory: 'C:/Users/nerrante/Downloads')

browser_options.add_preference('plugins.always_open_pdf_externally', true)

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options).tap { |d| d.browser.download_path = 'C:/Users/nerrante/Downloads' }
end
Capybara.default_driver = :selenium
Capybara.javascript_driver = :selenium

## Meta
Capybara Version: 3.29
selenium-webdriver 3.142.7
Chrome Version 85.0.4183.121 (Official Build) (64-bit)
chromedriver  85.0.4183.87

Let me know if there's any other info you need.  The code to download the file is just normal navigating through browser code to run a report and download.  The only "special" thing I did was above in the driver config.  I'm hoping maybe there is a new trick you know of to get it to work.

**Comment by twalpole** [comment]
I just ran the Capybara tests with Chrome  85.0.4183.121 and the latest matching chromedriver (use webdrivers gems) and the download test passed in both headless and headed modes.

**Comment by nerrante** [comment]
Thanks - I'll do some more troubleshooting on my end.
