### ISSUE TITLE
have_css matcher failing on Heroku (but not locally, or on CircleCi)

### ISSUE THREAD

**Issue by yoshie902a** [teamcapybara/capybara#2401]
My matcher rspec test seems to fail when pushed to Heroku, but passes when run locally, or on CircleCi. What could be the cause? Is this a bug? Version issue?

## Version
    rails (6.0.3.3)
    capybara (3.33.0)
    rspec-rails (4.0.1)

## Error
     Failure/Error: expect(rendered).to have_css("a[href='/teachers/#{@teacher.id}'][data-method='delete']", text: "Delete")

       expected to find css "a[href='/teachers/999'][data-method='delete']" but there were no matches

     # ./spec/views/teachers/show.html.erb_spec.rb:55:in `block (4 levels) in <main>'

**Comment by twalpole** [comment]
It could be any number of things - you'd need to look at `rendered` and see what it actually is.  However this isn't an issue with Capybara, so as asked in the issue template please post it in one of the locations designed for user support.
