### ISSUE TITLE
`fill_in` fills in wrong input

### ISSUE THREAD

**Issue by mockdeep** [teamcapybara/capybara#2412]
## Meta
Capybara Version: 3.29.0
Driver Information (and browser if relevant):
selenium-webdriver: 3.142.7
chromedriver: 85.0.4183.87

## Expected Behavior

Capybara fills in the correct inputs.

## Actual Behavior

We have a flaky test where Capybara sometimes fills in the wrong input:

```rb
fill_in 'Title or Name', with: 'Bloop Blap'
fill_in 'Email', with: 'bloop'
```

result:

![approver](https://user-images.githubusercontent.com/80543/96378558-9842e780-1141-11eb-8c05-de3c3355e001.png)

## Steps to reproduce

This page is built out in React and it has change handlers on the inputs, which I suspect causes the issue based on [this comment](https://github.com/teamcapybara/capybara/issues/2280#issuecomment-559296846). I'm not familiar with how React and Capybara handle focus under the hood, but I imagine it's something like:

1. Capybara focuses first input
2. Capybara fills in first input
3. Capybara focuses second input
4. React handles first input change event
5. React focuses first input again
6. Capybara fills in first input

I know this may not technically be considered an issue with Capybara, but I wonder if there's anything that can be done within Capybara to mitigate these sorts of issues. Is there anything Capybara can do to ensure it has the correct field focused before inputting? Otherwise, we'll have to test super defensively around React pages or (*gasp!*) start introducing some `sleep` calls.

**Comment by twalpole** [comment]
Capybara clicks in the field, which focuses it, then sends keyboard events which will go the focused input.  This imitates what a user would do.  If you have JS code that will change the focus at any moment in time there is nothing Capybara can do about it, since even if Capybara used JS to check the field is focused at a point in time it could still be changed before/while the keyboard events are sent.  

I would hope this doesn't happen on every field in your site (if it does imho you've done something very wrong in your react component design) - and this only affect a handful of fields.  In that case you'd need to check for whatever changes react is making to the handful of fields before filling in the next field.  If this really is affecting every field in your site then I don't really have anything to suggest.

**Comment by mockdeep** [comment]
@twalpole We're not changing the focus ourselves. I'm not sure what React is doing under the hood. But it's the sort of flakiness that we can see any time we have [controlled components](https://reactjs.org/docs/forms.html#controlled-components). Our `onChange` handler is only recording the value of the input:

```js
handleChange(event) {
  const element = event.target;

  this.setState({ [element.name]: element.value });
}
```

Either way, though, this isn't actually addressing the user experience, because our users don't run into this issue. It seems like it's more that Capybara runs so quickly that it triggers surprising edge cases with front end libraries.

**Comment by twalpole** [comment]
With that, my guess is that react is rerendering the form on every change

**Comment by twalpole** [comment]
If you can provide a minimal example of this behavior I’ll investigate, but I’ve used Capybara with many redact projects and not had this issue

**Comment by mockdeep** [comment]
@twalpole I missed something on our end that we may need to poke around with. It turns out we have a `componentDidMount` callback that focuses the first field. Could it be that Capybara has managed to fill in the first field and focus the second before this callback has fired?

**Comment by twalpole** [comment]
Definitely could, an expectation for that field being focused might be worthwhile. Also with the on change you might want to look at whether that component remounts after it’s filled in

**Comment by mockdeep** [comment]
No, [`componentDidMount`](https://reactjs.org/docs/react-component.html#componentdidmount) only gets triggered once when the entire component first renders. React is re-rendering the input as it changes, so I think under the hood it's technically a different input getting rendered after each change. If that's true, then React might be doing some magic under the hood to manage focus state as well. But if the issue we're seeing isn't that common then it probably has something to do with the way we're initially focusing it. I want to also see if we can use `autofocus` to sidestep it.
