### ISSUE TITLE
Ambiguous match when checking the checkbox with allow_label_click

### ISSUE THREAD

**Issue by dreyks** [teamcapybara/capybara#2421]
When a checkbox is visually hidden and has two labels (a valid situation according to the spec) `check "Label text"` does not work because it's getting an ambiguous match. This happens because https://github.com/teamcapybara/capybara/blob/22252382421f3126d6e10fa90a63237ff817436a/lib/capybara/node/actions.rb#L375 does not propagate the locator that was initially passed to `check`

## Meta
Capybara Version: 3.33.0

Driver Information (and browser if relevant):
ChromeDriver 85.0.4183.87
Chome Version 86.0.4240.183

## Expected Behavior
The checkbox is checked

## Actual Behavior
```
Selenium::WebDriver::Error::ElementClickInterceptedError:
element click intercepted: Element <input type"checkbox" /> is not clickable at point (891, 513). 
Other element would receive the click: <div>...</div>
```

## Steps to reproduce
```html
<label for="my-checkbox">
  The label we want to click
</label>
<div>Non-related markup elements that justify the usage of a separate label</div>
<label>
  <div> <!-- <- this div is what receives the click when you try clicking at checkbox's coordinates -->
    <input type="checkbox" id="my-checkbox" /> <!-- <- this is visually hidden -->
    <div>This is the visual representation of the checkbox</div>
  </div>
</label>
```
```rb
  page.check 'The label we want to click'
```

This happens because [_check_with_label](https://github.com/teamcapybara/capybara/blob/22252382421f3126d6e10fa90a63237ff817436a/lib/capybara/node/actions.rb#L363) does not expect more than one label to be present and does not pass the locator to the `find`

If this is something you agree on fixing I can make a PR

**Comment by twalpole** [comment]
Not supporting multiple labels is an issue that needs fixing, but I don't think the solution is passing the locator through.  Calling `check "Label text"` is saying to check the checkbox associated with the "Label text" selector - which can be done by clicking any of the labels.  Also passing the selector through to a label finder won't work because `check 'my-checkbox'` should do the same thing - and the 'my-checkbox' locator wouldn't find a label.  

IF you want a specific label clicked then you should find that label element directly and click on it

**Comment by dreyks** [comment]
yeah, as soon as i've posted the issue i've encountered this exact case you're talking about: check 'field_name' which failed with my monkey-patch

so do you think we still need to provide a method to distinguish between labels or do you think `check` should not be used for such cases?

**Comment by twalpole** [comment]
Should be fixed by https://github.com/teamcapybara/capybara/pull/2423

**Comment by twalpole** [comment]
@dreyks My fix for this just goes with the first label found, which I think is acceptable for the `check` method.  As stated earlier if you are testing a specific label you should be finding that label directly and then clicking on it

**Comment by dreyks** [comment]
nice! thanks!

**Comment by AxelTheGerman** [comment]
Hi, glad I found this issue it was driving me up the walls that capybara wasn't able to check my checkbox.

@twalpole first, thanks for all the work! Second, now I see `allow_label_click` and `automatic_label_click` in the docs - are there any reasons for `automatic_label_click` not being `true` by default?

My understanding is that it's quite common for the actual checkbox to be hidden - but either way, most actual users (which capybara is mimicking) are clicking on the label (or maybe that's just me).

Not a big deal, I just need to remember to enable that option. Just wondering if you have a list for the next major release of things you wanna do and if this would maybe be one.

**Comment by twalpole** [comment]
@AxelTheGerman It's not true by default because it would have been a breaking change.  Also you would be surprised at how many people write HTML that doesn't actually associate the label elements with the input elements they refer to... ...

**Comment by AxelTheGerman** [comment]
Thank you for that detailed explanation! I don't want to take too much more of your time for this, but I think it's a good candidate to add on the breaking changes list for 4.x

**Re Rails holding back a major release:**
I checked the `Gemfile.lock` from on of my Rails apps - `capybara` not being a Rails dependency or any other inferred dependency but a direct project dependency. Same seems to be true for Rails too https://github.com/rails/rails/blob/bad93fe2a127fbc623c00fe52ca02638ba3e9b90/Gemfile#L12

**Re people's bad HTML:**
Great opportunity to teach people proper HTML (or have them disable the option). It's literally one of the easier ways to make the web more accessible 🙂 

However, no rush on a major release. Seems like you got it going in the right direction so all good there

**Comment by Ahmed-toast** [comment]
> Thank you for that detailed explanation! I don't want to take too much more of your time for this, but I think it's a good candidate to add on the breaking changes list for 4.x
> 
> **Re Rails holding back a major release:** I checked the `Gemfile.lock` from on of my Rails apps - `capybara` not being a Rails dependency or any other inferred dependency but a direct project dependency. Same seems to be true for Rails too https://github.com/rails/rails/blob/bad93fe2a127fbc623c00fe52ca02638ba3e9b90/Gemfile#L12
> 
> **Re people's bad HTML:** Great opportunity to teach people proper HTML (or have them disable the option). It's literally one of the easier ways to make the web more accessible 🙂
> 
> However, no rush on a major release. Seems like you got it going in the right direction so all good there





https://stackdev.space/questions/step-by-step-guide-on-choosing-a-checkbox-using-seleniumwebdriver-by-passing-the-name-of-the-checkbox
