### ISSUE TITLE
Capybara 3.34.0 is incompatible with selenium-webdriver 4.0.0.alpha7

### ISSUE THREAD

**Issue by jcoyne** [teamcapybara/capybara#2431]
```
     NoMethodError:
       undefined method `<<' for nil:NilClass
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara/registrations/drivers.rb:14:in `block in <top (required)>'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara/session.rb:104:in `driver'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara/session.rb:90:in `initialize'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara.rb:424:in `new'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara.rb:424:in `block in session_pool'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara.rb:315:in `current_session'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara/dsl.rb:46:in `page'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/capybara-3.34.0/lib/capybara/dsl.rb:53:in `visit'
 ```
 
 It seems like there should be a guard clause if `options.args` is nil? https://github.com/teamcapybara/capybara/blob/master/lib/capybara/registrations/drivers.rb#L14

**Comment by twalpole** [comment]
This seems like a bug in Selenium where args should be initialized to an empty array.  Fix would be to either use `add_argument` or `headless!` rather than shifting into the array if the Firefox::Options instance responds to the method

**Comment by twalpole** [comment]
Working around in PR #2439

**Comment by twalpole** [comment]
Fixed via a760f1775efe115d65aea9eaee194f6b62607ce1

**Comment by jcoyne** [comment]
Thank you @twalpole .  You make Capybara the best part of the Ruby ecosystem.

**Comment by twalpole** [comment]
@jcoyne Thanks for the kind words,  I'll try and get an updated release out this weekend

**Comment by boris-petrov** [comment]
@twalpole - unfortunately this broke Selenium 3.142.7:

```
ArgumentError:
  wrong number of arguments (given 3, expected 1..2)
# ./features/build/.gems/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/logger.rb:12:in `deprecate'
# ./features/build/.gems/gems/capybara-3.35.1/lib/capybara/selenium/logger_suppressor.rb:12:in `deprecate'
# ./features/build/.gems/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/legacy/driver.rb:34:in `initialize'
# ./features/build/.gems/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/firefox/driver.rb:35:in `new'
# ./features/build/.gems/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:54:in `for'
# ./features/build/.gems/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
# ./features/build/.gems/gems/capybara-3.35.1/lib/capybara/selenium/driver.rb:83:in `browser'
# ./features/build/.gems/gems/capybara-3.35.1/lib/capybara/selenium/driver.rb:210:in `current_window_handle'
# ./features/build/.gems/gems/capybara-3.35.1/lib/capybara/session.rb:448:in `current_window'
# ./features/spec_helper.rb:97:in `block in <main>'
```

We have to go back to `3.34.0` because of that.

**Comment by twalpole** [comment]
@boris-petrov What is your `features/spec_helper.rb` line 97 doing?

**Comment by twalpole** [comment]
Umm - and it looks like you're using the legacy firefox integration? We haven't officially supported that in over a year, so I'm surprised it still works in 3.34 actually.

**Comment by twalpole** [comment]
@boris-petrov Also, what version of Ruby are you using?

**Comment by twalpole** [comment]
@boris-petrov Should be fixed in 3.35.3 - but it really is time to get off the legacy firefox driver and move to using the W3C compliant driver with modern firefox

**Comment by boris-petrov** [comment]
@twalpole - yes, this is using the legacy Firefox integration. It still works like a charm even now so thank you for (involuntarily) supporting it! :smile: This is using JRuby.

Thanks for the quick fix - it works great! As for the legacy driver - you're right, we're using the latest Chrome for our tests but we also want to test an "old" browser on Linux - this is the only thing that is available as a choice. If you have better ideas...?

**Comment by twalpole** [comment]
Don’t really have a suggestion for testing “old” browsers (other than don’t) but the first Firefox browser that supported the w3c mode is pretty old now too (though it was buggy).. You would need to look at what percentage of your customers are really using and old Firefox...  I can say that Selenium 4 drops the legacy driver so you’re going to be forced to update if you want to stay up to date with Selenium

**Comment by catmando** [comment]
Isn't this a cleaner way to fix this?

```ruby
      def deprecate(*args, **opts, &block)
        super(*args, **opts, &block) unless @suppress_for_capybara
      end
```

**Comment by twalpole** [comment]
@catmando It may be - have you tried it with all Ruby versions from 2.5 -3.0 .  There are issues between different Ruby versions where opts may be sent as an empty hash even though it shouldn't, etc.  If it works it's good for me right now. The way the Ruby 2.6 => 2.7 => 3.0 transition was handled created a whole bunch of issues for libraries that need to support all of them and I'm pretty much of the mind to release a Capybara 4.0 soon that is Ruby 3.0+ only just to allow cleaning all of this stuff up - which will also mean going selenium 4.0+ only and getting rid of the need to monkey patch the logger anyway.
