### ISSUE TITLE
Incorrect browser with :selenium_chrome and :selenium_chrome_headless

### ISSUE THREAD

**Issue by robinetmiller** [teamcapybara/capybara#2442]
Looks like version 3.35.0 broke the builtin browser configurations a bit. `:selenium_chrome` and `:selenium_chrome_headless` now produce a non-headless Firefox selenium instance.

The changes to `lib/capybara/registrations/drivers.rb`, lines 28 and 41 in commit https://github.com/teamcapybara/capybara/commit/0ad261ad0a9771d2f3ee45555c34caf7e79c563e  appear to be the culprit.

**Comment by twalpole** [comment]
Fixed in 3.35.1
