### ISSUE TITLE
Remaining ruby2.7 deprecation warning

### ISSUE THREAD

**Issue by strviola** [teamcapybara/capybara#2446]
Capybara Version: 3.35.1
Driver Information:
selenium-webdriver (3.142.7) with Google Chrome (headless) 88.0.4324.96
Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Ruby on Rails version: 6.1.1

```
vendor/bundle/ruby/2.7.0/gems/capybara-3.35.1/lib/capybara/session.rb:762: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
vendor/bundle/ruby/2.7.0/gems/capybara-3.35.1/lib/capybara/node/actions.rb:149: warning: The called method `check' is defined here

# 2 another called methods:
vendor/bundle/ruby/2.7.0/gems/capybara-3.35.1/lib/capybara/node/actions.rb:177: warning: The called method `uncheck' is defined here
vendor/bundle/ruby/2.7.0/gems/capybara-3.35.1/lib/capybara/node/actions.rb:88: warning: The called method `fill_in' is defined here
```

**Comment by twalpole** [comment]
Considering the fact the session.rb line 762 is using (...) and actions.rb 149 is defined as `def check(locator = nil, **options)` - I'm really not sure this is a valid warning -   Or it's from your code calls...

**Comment by strviola** [comment]
@twalpole Sure, I'll try to fix it in my repository
