### ISSUE TITLE
Minitest::UnexpectedError: NoMethodError: undefined method `call' for nil:NilClass (server.rb:77:in `block in boot')

### ISSUE THREAD

**Issue by aximuseng** [teamcapybara/capybara#2448]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.35.1
Rails v 5.x / Ruby 2.6.3 / Minitest
MacOSX (BigSir 11.1)
selenium-webdriver (3.142.7)
webdrivers (4.5.0)

## Expected Behavior

Simple visit index page test...

Background SE question here: https://stackoverflow.com/questions/65974423/minitest-webdrivers-unable-to-connect-to-chromedriver

## Actual Behavior

```
#<Thread:0x00007ffcdf082530@/Users/aximus/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.35.1/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
/Users/aximus/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.35.1/lib/capybara/server.rb:77:in `block in boot': undefined method `call' for nil:NilClass (NoMethodError)
#<Thread:0x00007ffcdf093498@/Users/aximus/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.35.1/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
/Users/aximus/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.35.1/lib/capybara/server.rb:77:in `block in boot': undefined method `call' for nil:NilClass (NoMethodError)
ERROR["test_visiting_the_index", #<Minitest::Reporters::Suite:0x00007ffcdf098c90 @name="WellsTest">, 13.165569999953732]
 test_visiting_the_index#WellsTest (13.17s)
Minitest::UnexpectedError:         NoMethodError: undefined method `call' for nil:NilClass
            /Users/aximus/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/capybara-3.35.1/lib/capybara/server.rb:77:in `block in boot'
```

## Steps to reproduce

All system integrations fail like this.  These error messages are not hitting on any specific searches on related issues.  Not sure where to start.

**Comment by twalpole** [comment]
You've specified a server which doesn't have builtin support in Capybara.  Is there a particular reason you're specifying :thin ?  Capybara defaults to using :puma, and has support for using :webrick (but you're better off sticking with puma).  If you really need/want to use thin, you'll need to register your own server block - see `Capybara.register_server`

**Comment by aximuseng** [comment]
That would be my inexperience with Capybara - Puma did the trick... sort of.  I just need to now figure out how to get Capybara to look for the right port:

```
12:31:39 - INFO - Running: test/system/work_breakdown_structures_test.rb
Started with run options --seed 43168

Capybara starting Puma...--=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=] 0% Time: 00:00:00,  ETA: ??:??:??
* Version 5.2.0 , codename: Fettisdagsbulle
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:60707
ERROR["test_visiting_the_index", #<Minitest::Reporters::Suite:0x00007fcafb268068 @name="WorkBreakdownStructuresTest">, 73.58754300000146]
 test_visiting_the_index#WorkBreakdownStructuresTest (73.59s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
            test/system/work_breakdown_structures_test.rb:9:in `block in <class:WorkBreakdownStructuresTest>'

  1/1: [==============================================================================================================] 100% Time: 00:01:13, Time: 00:01:13

Finished in 73.58843s
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by twalpole** [comment]
If you require webdrivers and tell capybara to use chrome it will “just work”. You don’t need to manually run chromedriver, chrome, or the app under test - Capybara will do all that for you. If you’re using rails system tests read the rails testing guide, otherwise read the Capybara readme, and don’t follow tutorials from 3+ years ago

**Comment by aximuseng** [comment]
@twalpole thanks for the feedback.  The docs on Capybara are a bit thin for a newcomer like me.  I feel I have followed all the set-up guidelines and not following and old tutorials - my Gemfile:

```
  gem 'capybara'
  gem 'webdrivers'
```
my test_helper.rb (have tried iterations of removing these settings etc):

```
module ActionDispatch
  class IntegrationTest

    include Devise::Test::IntegrationHelpers

    include Capybara::DSL
    include Capybara::Minitest::Assertions

    teardown do
      Capybara.reset_sessions!
      Capybara.use_default_driver
    end

    setup do
      Capybara.current_driver = :selenium_chrome ## is this not telling Capybara to user chrome??
    end
  end
end
```
As for my actual tests - I commented out all the auto generated ones and only have a single simple `visit my_url` etc.  I can't even get to that point so far.  Any guidance on how to "tell capybara to use chrome" would be appreciated.

**Comment by twalpole** [comment]
Maybe you shouldn’t have commented out all of the auto-generated stuff since Rails sets up system tests by default to work. Read the rails system testing guide - https://guides.rubyonrails.org/testing.html#system-testing and make sure you have required webdrivers

**Comment by aximuseng** [comment]
That comment was directed towards my actual test content.  I have not touched the previous settings.  I forgot about this one - my application_system_test_case.rb:

```
require 'test_helper'

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome
end
```

The test I am running looks like this:

```
require "application_system_test_case"

class WorkBreakdownStructuresTest < ApplicationSystemTestCase

  test "visiting the index" do
    visit work_breakdown_structures_url
    assert_selector "h1", text: "Work Breakdown Structures"
  end

end

```

Unless I am reading the problem wrong Capybara is starting Puma on random ports and the webdriver is looking for port 9195 each time.

**Comment by twalpole** [comment]
You're reading the problem wrong - Puma is started on a random port and so is chromedriver (which I assume is what you mean by "webdriver") Capybara talks to chromedriver via Selenium to control the browser which makes its requests against Puma.  If you just go with the Rails defaults rather than trying to change things it will work out of the box.  ie - Follow the rails guide and don't start by trying to configure Capybara directly. Also check the example tests that were generated by Rails are they really visiting xxxx_url ?

**Comment by aximuseng** [comment]
Well that was quite the lightbulb moment - after some searching and coming across this post:

https://stackoverflow.com/questions/19978577/unable-to-connect-to-chromedriver

I moved my gems to the test group (I had them in the dev group).  My tests now run (failing but running lol).  Need to get the sign-in working etc. but that seems a small hurdle now.  Perhaps note that in the docs to prevent endless future headaches for newbies like me.

Thanks again for your help 👍
