### ISSUE TITLE
Screenshots not rendering text (renders as weird glyphs)

### ISSUE THREAD

**Issue by AxelTheGerman** [teamcapybara/capybara#2451]
Hi,

I am not sure this is a capybara issue but I have to start somewhere.

I have a failing test (in my CI) and Rails (w capybara) automatically takes screenshots. They used to render just fine but not anymore. I recently switched my CI docker image from ruby debian to ruby alpine to be able to install a non-ESR FF version.

Any hints will be much appreciated. *Note: I was able to figure out the actual issue for the test as the expected elements is off screen due to poor layout from my side - but I do prefer my screenshots to be working to be able to troubleshoot when needed.*

Thank you very much :bow: 

## Meta
Capybara Version: 3.35.1
Driver Information (and browser if relevant):
selenium-webdriver (3.142.7)
Mozilla Firefox 84.0.2
geckodriver 0.29.0 (cf6956a5ec8e 2021-01-14 10:31 +0200)

## Expected Behavior
Screenshots should render text properly.

## Actual Behavior
Somehow all characters are rendered as glyphs.

![failures_test_user_can_resend_email_verification](https://user-images.githubusercontent.com/5974020/107855670-911ea400-6dd8-11eb-8ba1-3c37fb2bfbfe.png)

## Steps to reproduce
Sorry, I don't really have any besides making a test fail and download resulting failure screenshot from CI.

**Comment by twalpole** [comment]
Capybara doesn’t control page rendering, that’s handled by the browser. Since you’ve changed the OS and browser recently it’s likely your docker image doesn’t contain the necessary fonts for the browser to render correctly

**Comment by AxelTheGerman** [comment]
Thanks for the quick response and sorry for taking your time. Not surprised that that's not capybara's doing. It's just weird since I'm just using default fonts (besides for icons). Will bring this question to a community such as stackoverflow instead
