### ISSUE TITLE
Capybara::Node::Simple#sibling raises NoMethodError

### ISSUE THREAD

**Issue by jaredbeck** [teamcapybara/capybara#2452]
## Meta

Capybara 3.35.3
Driver/browser: N/A

## Example

```ruby
require 'capybara'
html = '<p>Fruit:</p><table />'
node = Capybara::Node::Simple.new(html)
node.find('p', text: 'Fruit:').sibling('table')
```

## Expected Behavior

I expected Node::Simple to support `#sibling`.

## Actual Behavior

```plain
ruby issue.rb
Traceback (most recent call last):
	7: from issue.rb:4:in `<main>'
	6: from .../capybara-3.35.3/lib/capybara/node/finders.rb:99:in `sibling'
	5: from .../capybara-3.35.3/lib/capybara/node/finders.rb:292:in `synced_resolve'
	4: from .../capybara-3.35.3/lib/capybara/node/simple.rb:156:in `synchronize'
	3: from .../capybara-3.35.3/lib/capybara/node/finders.rb:294:in `block in synced_resolve'
	2: from .../capybara-3.35.3/lib/capybara/queries/sibling_query.rb:9:in `resolve_for'
	1: from .../capybara-3.35.3/lib/capybara/node/simple.rb:156:in `synchronize'
.../capybara-3.35.3/lib/capybara/queries/sibling_query.rb:10:in `block in resolve_for': 
undefined method `session' for #<Capybara::Node::Simple tag="p" path="/html/body/p"> (NoMethodError)
```

## Steps to reproduce

Please see above

## Thoughts

If Node::Simple _intentionally_ does not support `#sibling`, an error message to that effect would be helpful.

Thank you for this great gem. I use it all the time for general-purpose parsing and traversal of document fragments, not necessarily only in tests. I could use Nokogiri directly, but I like the `Finders` API.

**Comment by twalpole** [comment]
Looking at this currently,

**Comment by twalpole** [comment]
Should be fixed via https://github.com/teamcapybara/capybara/commit/3780800f337241160936b427e58f0e10a150b04c - sorry for the delay, work has been really busy for a while

**Comment by jaredbeck** [comment]
Thanks :heart:
