### ISSUE TITLE
Webpacker + Rspec + Capybara + Rails Engine fails loading compiled assets

### ISSUE THREAD

**Issue by DiegoOrejuela** [teamcapybara/capybara#2455]
## Meta
Capybara Version: 3.35.3
Driver Information (and browser if relevant): selenium-webdriver 3.142.7 with Chrome 89.0.4389.114

## Expected Behavior
Successfully load compiled assets produced by webpacker from a Rails engine in Test environment.

## Actual Behavior
In summary, the problem is that the compiled assets of the Rails engine, the result of the Webpacker compilation, are not found in the test environment, as opposed to the development and production environment, where it works according to the documentation.

![image](https://user-images.githubusercontent.com/34580380/113500768-5686dd00-94e6-11eb-97c1-e315b439986d.png)

## Steps to reproduce
I have made the repository [engine_with_webpacker](https://github.com/DiegoOrejuela-issue-reporting/engine_with_webpacker) to reproduce the error. You can find in the Readme a description of the problem and screenshots, the requirements you need to install the application and the steps to follow.

There are some configurations that maybe are too many because I have used a template that I have because installing webpacker in an engine is very tedious and other configs, but they should not affect the correct operation at all.

Thank you, and I am very attentive.

**Comment by twalpole** [comment]
I will try to find time to look at your repo, but my initial reaction is that there’s no way this is a Capybara issue, What assets get compiled in any environment is purely up to your apps configuration, Capybara has nothing to do with that v

**Comment by DiegoOrejuela** [comment]
It seems to me that the problem is in the test server that is used for tests in Capybara, because it does not route to the webpacker assets in the Rails engine, as if it does in development through this code https://github.com/DiegoOrejuela-issue-reporting/engine_with_webpacker/blob/34f5ea56ff1eb5c96377a33098737d61180ce1d7/lib/engine_with_webpacker/engine.rb#L19

**Comment by twalpole** [comment]
It shouldn’t be running anything like development though - tests should run more like production otherwise they don’t really have value

**Comment by DiegoOrejuela** [comment]
I understand. However, in production it also works as in development. The only environment where it does not work is in test, and even more with your comment you reaffirm that it should work.

**Comment by twalpole** [comment]
Don’t take my comment to mean it should work - I write Capybara, not Rails, rspec, rspec-rails, we packer, etc. All Capybara does is start the  config.ru - if that’s not setup to get everything going the app needs then it’s up to you to set Capybara.app to something that does

**Comment by DiegoOrejuela** [comment]
Thanks @twalpole.

The reference to that file helped me to contemplate other possibilities. Indeed to solve it I inserted the middleware to serve static files in test mode. [Here](https://github.com/DiegoOrejuela-issue-reporting/engine_with_webpacker/commit/90687f18578e0a1e428f5ace1d862ed60cadb4fa#diff-7712a26ff640a799bf6a92cc945d02a36dcd893b5583bcfabd59fddc4238c632) the commit in the test repo.
