### ISSUE TITLE
Feature request:  Provide a file/line number for Locator :link must be an instance ... message

### ISSUE THREAD

**Issue by vanboom** [teamcapybara/capybara#2456]
## Meta
Capybara Version: `3.35.3`

## Expected Behavior
The message identifying a bad Locator for :link  should include a file/line number reference. 

## Actual Behavior
The message includes no clue as to where the message is happening

## Steps to reproduce
Induce the message by passing an object reference to :link
```
expect(rendered).to have_link user, href: user_path(user)
```

**Comment by twalpole** [comment]
better late than never - 72b70fa0581764a31a30f3a7f62cf7ed822a1008
