### ISSUE TITLE
Error when using `all` rspec matcher

### ISSUE THREAD

**Issue by Valentyna** [teamcapybara/capybara#2457]
When running next line (where as you see Capybara is not involved at all)
`expect([1, 3, 5]).to all( be_odd )`

I'm getting next error
> Locator RSpec::Matchers::BuiltIn::BePredicate:#<RSpec::Matchers::BuiltIn::BePredicate:0x00007f96271a0800 @method_name=:be_odd, @args=[], @block=nil> for selector :css must be an instance of String or Symbol. This will raise an error in a future version of Capybara.
> Selenium::WebDriver::Error::InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
>   (Session info: chrome=89.0.4389.114)
> from 0   chromedriver                        0x000000010bb29909 chromedriver + 2533641

## Meta
Capybara Version: 3.32.1
standalone-chrome:3.141.59-20210128  (https://github.com/SeleniumHQ/docker-selenium)
cucumber 4.0.0
ruby 2.7.0
rspec 3.10

**Comment by twalpole** [comment]
Please read https://github.com/teamcapybara/capybara#using-capybara-with-rspec , especially the note at the end of the section
