### ISSUE TITLE
Capybara.current_session.server is nil after the first test

### ISSUE THREAD

**Issue by henrahmagix** [teamcapybara/capybara#2459]
## Meta
Capybara Version:
3.32.2, then updated and seeing the same issue in 3.35.3.

Driver Information (and browser if relevant):
selenium-webdriver 3.142.7 with the following:
```rb
Capybara.register_driver :chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    'goog:chromeOptions': { args: %w[window-size=1280,800 headless disable-gpu] }
  )
  Capybara::Selenium::Driver.new(app, browser: :chrome, desired_capabilities: capabilities)
end

Capybara.javascript_driver = :chrome
Capybara.current_driver    = Capybara.javascript_driver

Capybara.configure do |config|
  config.always_include_port = true
  config.reuse_server = true
end
```

Also rspec-rails 4.0.2.

## Expected Behavior

`Capybara.current_session.server` is always available, so it can be used to get the dynamically-assigned `port`.

 E.g. if I want to alter the host to add a subdomain just for one test, then I'd like to get the current host (or ip) and port that Capybara has setup itself.

## Actual Behavior

A new Capybara server is started on the first `visit`, a port is dynamically assigned, and the port is stored in `Capybara::Server.ports` keyed by the server's `object_id`. Subsequent `visit`s in the same test (RSpec Example) use the same host and dynamically-assigned port.

In all subsequent tests, `Capybara.current_session.server` is nil and the default host is used. The tests still pass though, so Capybara is running the app in one way or another, or is still communicating with the server from the first test but is just not accessible through `Capybara.current_session.server`.

The port continues to stay open until rspec is finished (seen in `sudo lsof -PiTCP -sTCP:LISTEN`).

## Steps to reproduce
```rb
# spec/features/server_port_spec.rb
require 'rails_helper'

RSpec.describe 'Server port testing', type: :feature do
  before do
    puts "Test start! current_url=#{current_url} \"#{page.title}\""
    visit '/'
    puts "visited #{current_url} \"#{page.title}\""

    puts "default_url_options:                  #{default_url_options}"
    puts "Capybara.reuse_server:                #{Capybara.reuse_server.inspect}"
    puts "Capybara.app_host:                    #{Capybara.app_host.inspect}"
    puts "Capybara.default_host        :        #{Capybara.default_host.inspect}"
    puts "Capybara.app        :                 #{Capybara.app}"
    puts "Capybara.server_host:                 #{Capybara.server_host.inspect}"
    puts "Capybara.server_port:                 #{Capybara.server_port.inspect}"
    puts "Capybara::Server.ports :              #{Capybara::Server.ports.inspect}"
    puts "Capybara.current_session.app:         #{Capybara.current_session.app}"
    puts "Capybara.current_session.server:      #{Capybara.current_session.server || 'nil'} (object_id: #{Capybara.current_session.server.object_id})"
    puts "Capybara.current_session.server.host: #{Capybara.current_session.server&.host.inspect}"
    puts "Capybara.current_session.server.port: #{Capybara.current_session.server&.port.inspect}"
    puts "Capybara.current_session.server_url:  #{Capybara.current_session.server_url.inspect}"
  end

  describe 'repeat visits' do
    3.times.each do |n|
      it "visit #{n + 1}" do
        visit '/'
        puts "visited #{current_url} \"#{page.title}\""
      end
    end
  end

end
```
```
bundle exec rspec --format documentation spec/features/server_port_spec.rb

Randomized with seed 53688

Server port testing
  repeat visits
Capybara starting Puma...
* Version 5.1.1 , codename: At Your Service
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:52617
Test start! current_url=data:, ""
visited http://lvh.me:52617/ "My Test App"
default_url_options:                  {:host=>"www.example.com"}
Capybara.reuse_server:                true
Capybara.app_host:                    nil
Capybara.default_host        :        "http://www.example.com"
Capybara.app        :                 #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.server_host:                 "lvh.me"
Capybara.server_port:                 nil
Capybara::Server.ports :              {70338283890620=>52617}
Capybara.current_session.app:         #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.current_session.server:      #<Capybara::Server:0x00007ff1c96ce428> (object_id: 70338221601300)
Capybara.current_session.server.host: "lvh.me"
Capybara.current_session.server.port: 52617
Capybara.current_session.server_url:  "http://lvh.me:52617"
visited http://lvh.me:52617/ "My Test App"
    visit 3
Test start! current_url= ""
visited http://example.com/ "My Test App"
default_url_options:                  {:host=>"www.example.com"}
Capybara.reuse_server:                true
Capybara.app_host:                    nil
Capybara.default_host        :        "http://www.example.com"
Capybara.app        :                 #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.server_host:                 "lvh.me"
Capybara.server_port:                 nil
Capybara::Server.ports :              {70338283890620=>52617}
Capybara.current_session.app:         #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.current_session.server:      nil (object_id: 8)
Capybara.current_session.server.host: nil
Capybara.current_session.server.port: nil
Capybara.current_session.server_url:  nil
visited http://example.com/ "My Test App"
    visit 2
Test start! current_url= ""
visited http://example.com/ "My Test App"
default_url_options:                  {:host=>"www.example.com"}
Capybara.reuse_server:                true
Capybara.app_host:                    nil
Capybara.default_host        :        "http://www.example.com"
Capybara.app        :                 #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.server_host:                 "lvh.me"
Capybara.server_port:                 nil
Capybara::Server.ports :              {70338283890620=>52617}
Capybara.current_session.app:         #<Rack::URLMap:0x00007ff1d0d9cf78>
Capybara.current_session.server:      nil (object_id: 8)
Capybara.current_session.server.host: nil
Capybara.current_session.server.port: nil
Capybara.current_session.server_url:  nil
visited http://example.com/ "My Test App"
    visit 1

Finished in 2.98 seconds (files took 1.08 seconds to load)
3 examples, 0 failures

Randomized with seed 53688
```

**Comment by twalpole** [comment]
What `before`/`after` blocks do you have setup?  The default session reset is

def reset!
      if @touched
        driver.reset!
        @touched = false
      end
      @server&.wait_for_pending_requests
      raise_server_error!
end

which wouldn't be clearing `server`

**Comment by henrahmagix** [comment]
@twalpole None that I can find. I've replicated it with a barebones new rails project: see https://github.com/henrahmagix/test-capybara-server/tree/97e7bfaa447107190ad73fa5be1abd8b46523596

**Comment by henrahmagix** [comment]
I think this barebones replica shows that the puma server started in the first test _isn't_ accessed in the subsequent tests, because without `config.hosts.clear`, trying to visit `/` results in an action controller error because `www.example.com` isn't an allowed host.

**Comment by twalpole** [comment]
I haven't had time to test your reproduction repo yet - but I'm guessing your first test is running with the selenium driver, but the two after that are running with the rack_test driver which doesn't use a server.  This because current_driver is reset to `Capybara.default_driver` after each spec.

**Comment by twalpole** [comment]
Yep, that's exactly whats happening -- tag your specs as :js or set Capybara.default_driver if you always want to use the selenium driver

**Comment by henrahmagix** [comment]
Aha perfect, thanks @twalpole!

So I fixed it by replacing `Capybara.current_driver=` with `Capybara.default_driver=`, and then to ensure the port is always used if I set a `Capybara.server_host` and need to add a subdomain, this is my full config:
```rb
Capybara.javascript_driver = :chrome # defined above
Capybara.default_driver    = Capybara.javascript_driver

Capybara.configure do |config|
  config.server = :puma # just to be sure, even though it's the default
end

RSpec.configure do |config|
  config.around do |example|
    Capybara.server_host ||= Capybara.current_session.server&.host
    Capybara.server_port ||= Capybara.current_session.server&.port
    example.run
  end
end
```

**Comment by twalpole** [comment]
@henrahmagix I'm glad it's working for you, but I'm really not clear why you're setting Capybara.server_host and Capybara.server_port like that.  They are values used to customize how Capybara runs the app under test server. The only time they are used is when the app server is being started - so setting them after you already the have the server started really doesn't make sense - and could cause you issues if the side-effect of setting them change in the future.

**Comment by henrahmagix** [comment]
Ah yeah, you're right: I just commented them out and it all works fine. I thought I needed `Capybara.server_port` to be the dynamically-assigned port, but it doesn't need to be because I can see it's always added to `Capybara.app_host` in `visit` calls =)

Thanks for your help!

**Comment by henrahmagix** [comment]
<details><summary>This is why I was doing that: I have a need to add a subdomain to the current host/server/whatever, in one or two tests, regardless of how it's setup globally.</summary><p>

```rb
module SetCapybaraSubdomain

  def set_capybara_subdomain(subdom_code)
    around do |example|
      if Capybara.server_host.blank? || ['localhost', '127.0.0.1'].include?(Capybara.server_host)
        raise "cannot set a subdomain on #{Capybara.server_host.inspect}"
      end

      host_with_subdomain = "#{subdom_code}.#{Capybara.server_host}"
      host_with_subdomain += ":#{Capybara.server_port}" if Capybara.server_port.present?

      original_app_host = Capybara.app_host
      Capybara.app_host = "http://#{host_with_subdomain}"

      example.run

      Capybara.app_host = original_app_host
    end
  end
end

RSpec.configure do |config|
  config.extend SetCapybaraSubdomain, type: :feature
end
```

</p></details>
