### ISSUE TITLE
Server responsive checker sends http request to an https server

### ISSUE THREAD

**Issue by brendon** [teamcapybara/capybara#2460]
With regards to:

https://github.com/teamcapybara/capybara/blob/2c4538823dcfda00ed95b95a1d266a9cfb7ae2cc/lib/capybara/server.rb#L56

This causes the following output when the server is an `ssl` Puma server:

```
* Listening on ssl://127.0.0.1:64971?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem
2021-04-22 23:11:56 +1200 SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: HTTP connection?>
```

I raised the original error message here: https://github.com/puma/puma/issues/2603

I was wondering if it is possible to have the request be over `https`? Perhaps as a configuration option?

**Comment by nateberkopec** [comment]
The `Checker` object [certainly looks like it can handle](https://github.com/teamcapybara/capybara/blob/2c4538823dcfda00ed95b95a1d266a9cfb7ae2cc/lib/capybara/server/checker.rb#L14) `https`, but I don't know where it gets configured.

**Comment by brendon** [comment]
It looks like it can't be configured off the bat, but has to fail into ssl after trying unencrypted and failing.

**Comment by twalpole** [comment]
It "autodetects" whether the server is running http or https by trying http, then https -- If you don't want to see the message  you should be able to pass `Silent: true` in the puma options

Capybara.server = :puma, {
  Host: "ssl://#{Capybara.server_host}?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem",
  Silent: true
}

**Comment by brendon** [comment]
Well would ya look at that :)

Thanks @twalpole, that certainly sorts it for me.
