### ISSUE TITLE
Click on source element again after drag it to destination

### ISSUE THREAD

**Issue by vidhijain24** [teamcapybara/capybara#2461]
Capybara Version: capybara-3.35.3
Driver Information (and browser if relevant): selenium-webdriver 4.0.0.beta2 with Chrome 89 

```
sourceLocation = page.find(:xpath, source)
destinationLocation = page.find(:xpath, destination)
sleep 10
sourceLocation.drag_to(destinationLocation)

```
## Expected Behavior
The above code works properly at my system but when I execute the same code at Saucelabs then it drags the element to destination and then click again to the sourceLocation. And unfortunately my element is link, so when it clicks back on sourceLocation it opens a popup window.

Note: It was working fine with capybara version -3.7.2 at Local and Sauce both. After capybara upgrade I am getting such issue.
Thanks

**Comment by twalpole** [comment]
The beauty of OSS is you look at exactly what it's doing - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/extensions/html5_drag.rb#L7.

From that you can see that Capybara does two different code flows depending on whether or not it detects you doing html5 style dragging or legacy style dragging, but in both of those all it's doing is holding down the left mouse button, moving to the target element, and releasing the left mouse button - there is no `click` being issued by Capybara.  In the case of HTML5 dragging it does issue some extra events (dragOver, etc) that are necessary for that style of dragging, but again no clicks.  If Sauce is interpreting a click at the end then it sounds like an issue with Sauce.   One possibility is that Sauce is breaking the HTML5 dragging detection - you can try working around that by passing `html5: true` (or false depending on which style your app is using) to `drag_to` - Beyond that I think you'll need to take it up with Saucelabs
