### ISSUE TITLE
I just had a same issue, I resolved it by requiring `addressable/uri` in /lib/capybara/queries/current_path_query.rb:1

### ISSUE THREAD

**Issue by EtnaStar** [teamcapybara/capybara#2467]
I just had a same issue, I resolved it by requiring `addressable/uri` in /lib/capybara/queries/current_path_query.rb:1

this is because the addressable is not a file

_Originally posted by @rezadehganpour in https://github.com/teamcapybara/capybara/issues/1644#issuecomment-175909273_

**Comment by EtnaStar** [comment]
Please, I can not resolve this error: C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll.rb:33:in `require': cannot load such file -- addressable/uri (LoadError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll.rb:33:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
        from C:/Ruby30-x64/bin/jekyll:23:in `load'
        from C:/Ruby30-x64/bin/jekyll:23:in `<main>'

**Comment by twalpole** [comment]
The error posted here is in jekyll -- I'm not really sure why you've posted it in Capybara?
