### ISSUE TITLE
Rspec matchers `not_to have_css` is not equivalent to  `to have_no_css`

### ISSUE THREAD

**Issue by lvonk** [teamcapybara/capybara#2472]
## Meta
Capybara Version:
3.35.3
Driver Information (and browser if relevant):
Chromedriver '91.0.4472.19'

## Expected Behavior
According to the README in section https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends:

> Capybara's RSpec matchers, however, are smart enough to handle either form. The two following statements are functionally equivalent:
```ruby
expect(page).not_to have_xpath('a')
expect(page).to have_no_xpath('a')
```

## Actual Behavior

Rspec matcher `not_to have_css` does not respect `default_max_wait_time` but `to have_no_css` does.

## Steps to reproduce
The following code will wait until css is no longer there:

```ruby
start = Time.now
begin
  expect(page).to have_no_css('li#organization-data')
ensure
  end_time = Time.now
  puts "Took: #{end_time - start} ms with wait time #{Capybara.default_max_wait_time}"
end
```

and produces `Took: 0.153024 ms with wait time 10`

But this code doesn't

```ruby
start = Time.now
begin
  expect(page).to_not have_css('li#organization-data')
ensure
  end_time = Time.now
  puts "Took: #{end_time - start} ms with wait time #{Capybara.default_max_wait_time}s"
end
```

And produces `Took: 0.054761 ms with wait time 10s`

**Comment by twalpole** [comment]
With a correctly installed Capybara those two will be equivalent.  It's unclear from your example exactly what it's showing (other than two runs taking different times) but I'm assuming the second example actually errors while the first succeeds?  If that's the case please look at the exception message generated by the second run.  My guess is that it will indicate it's using RSpecs general `have_xxx` matcher rather than Capybaras which would indicate either you haven't included Capybaras matchers or you've included them in the wrong order.

**Comment by lvonk** [comment]
Hi @twalpole ,

Thanks for replying. The second one is indeed the one not waiting and produces the following error:

```ruby
 Failure/Error: expect(page).to_not have_css('li#organization-data')
       expected `#<Capybara::Session>.has_css?("li#organization-data")` to be falsey, got true
```

> which would indicate either you haven't included Capybaras matchers or you've included them in the wrong order.

This could indeed also be the case. Our setup is as follows, which seems like how it is described in the README:

```ruby
require 'capybara/rspec'

RSpec.configure do |config|
  config.define_derived_metadata(file_path: %r{/spec/.*feature_spec}) do |metadata|
    metadata[:features] = true
  end
  config.include Capybara::DSL, :features
end
```

> My guess is that it will indicate it's using RSpecs general have_xxx matcher rather than Capybaras

I will do some more investigation to see if this is indeed the case (would make sense, since otherwise I would have expected an older issue about this...)

**Comment by twalpole** [comment]
@lvonk Yep - from the message `expected `#<Capybara::Session>.has_css?("li#organization-data")` to be falsey, got true` you can see that it's using using the RSpec `have_xxx` matcher which just calls the has_xxx? predicate.  If it was using the Capybara provided have_css matcher any error message would provide a lot more useful info that just true vs false.    From `capybara/rspec` - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec.rb - you can see that Capybara includes its matchers into tests with type `feature` and `system` - from your `metadata[:features]` setting it would appear you're doing something non-standard and may need to include them into those.

**Comment by lvonk** [comment]
The problem was indeed that the `include Capybara::RSpecMatchers` was missing. But this was because we delegate the
`has_***` to a separate driver class that handles the navigating to the app which is not rspec aware. So after adding `include Capybara::RSpecMatchers` it worked like a charm. Thanks for taking the time to help out and give pointers. Much appreciated.
