### ISSUE TITLE
Undefined local variable el in have_selector.rb line 68

### ISSUE THREAD

**Issue by hennikul** [teamcapybara/capybara#2473]
I got this error when I tried to do a expect(element).not_to have_any_of_selectors('selector1', 'selector2) : 
     NameError:
       undefined local variable or method `el' for #<Capybara::RSpecMatchers::Matchers::HaveAnySelectors:0x000055e756f33200 @args=["selector1", "selector2"], @kw_args={}, @filter_block=nil>

Too mee it looks like the _actual-parameter should be renamed to el here: 
https://github.com/teamcapybara/capybara/blob/98787a9c6922ca4486735e1791153a2c4a011001/lib/capybara/rspec/matchers/have_selector.rb#L68

**Comment by twalpole** [comment]
Thank you - fixed via 60f117c4af3d88744536206b7233a90baaba4653
