### ISSUE TITLE
set for checkbox not consistently working in Chrome 91

### ISSUE THREAD

**Issue by maciek-ys** [teamcapybara/capybara#2474]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 2.6.2
Driver Information (and browser if relevant): Chrome 91, semaphoreci

## Expected Behavior
calling `find(:checkbox, "…").set(false)` should consistently set the checkbox to the unclicked state

## Actual Behavior
we are not consistently seeing this work; in our test suite, a particular checkbox fails to uncheck on the first attempt. Subsequent attempts do work. It appears the `find(…)` method returns an object for which `value` is `nil`, although in every other way it appears to be the checkbox element.

## Steps to reproduce
see above.

## Discussion, proposed approach
Would there be any downside to modifying `Capybara::Selenium::Node#set` such that this clause executes unconditionally? Or, if `value` is `nil` (which is the behaviour we are observing), call `click` in addition to the xor?

```
      when 'checkbox'
        #click if value ^ checked?
        click if value.nil? || value ^ checked?
```

There may be some other regression with Chrome 91 that should be addressed, but we have not identified it as yet if it exists.

**Comment by twalpole** [comment]
Do you happen to be setting w3c: false in your driver config? If so, stop

**Comment by twalpole** [comment]
Also, I assume you don't really mean you're running Capybara 2.6.2 since that's over 5 years old

**Comment by twalpole** [comment]
@maciek-ys The `w3c: false` option is not a Capybara option, it's a driver option that some browser drivers were supporting - Chrome 91 stopped supporting it - and iirc was the default in older versions of selenium.  I'm actually a lot surprised that modern browsers work at all with a Capybara so old, and whatever version of selenium you're using.   Closing this due to the versions used being obsolete
