### ISSUE TITLE
drag_to method raises a non_implemented error

### ISSUE THREAD

**Issue by RalphNgassa** [teamcapybara/capybara#2478]
Hello guys, I've been using capybara with Cuprite as driver on headless for a system I am working on.
![image](https://user-images.githubusercontent.com/71353825/123325363-efd1f800-d505-11eb-89e0-75ca4c9cb7dd.png)

As you can see on the capture above, a non-implemented error for the following line of code:

`capybara_element.drag_to(find(:css, "#tempPositionMarker"))`

where capybara_element is the source html element and #tempPositionMarker the target one.

**Comment by twalpole** [comment]
The error is in cuprite, sounds like it hasn't implemented all the base driver methods, nothing Capybara can do about that

**Comment by RalphNgassa** [comment]
Please I need help do you think selenium might help this work?

**Comment by twalpole** [comment]
Yes drag works with Selenium, I don't know if you're using any cuprite specific functionality that wouldn't be supported by Selenium though

**Comment by RalphNgassa** [comment]
Thanks I switched drivers and it seems to work flawlessly. I am kinda new to this technology, sorry if I raised the issue, just wanted to raise your attention.
