### ISSUE TITLE
Cannot interact with external server: rack-test requires a rack application, but none was given (ArgumentError)

### ISSUE THREAD

**Issue by maca** [teamcapybara/capybara#2480]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
capybara (3.35.3)
Driver Information (and browser if relevant):
selenium driver
Chromium 91.0.4472.114 Arch Linux

## Expected Behavior

I am using cucumber without any ruby framework.
And according to the documentation configuring capybara as such should allow me to visit external sites:

https://github.com/teamcapybara/capybara#calling-remote-servers

```
# features/env.rb
require 'capybara/cucumber'
require 'capybara'
require 'selenium-webdriver'


Capybara.current_driver = :selenium
Capybara.app_host = 'https://example.com'
Capybara.run_server = false

```
Should allow me to visit an external site.

## Actual Behavior

I've tried with this steps:

```
Given('I visit the request handling bot with locale {string}') do |locale|
  visit "https://example.com/#{locale}/contact/assistant"
end
```

```
Given('I visit the request handling bot with locale {string}') do |locale|
  visit "/#{locale}/contact/assistant"
end
```

But either way I get this error:

```
    Given I visit the request handling bot with locale "en-gb"                                                                      # features/step
_definitions/web_steps.rb:1
      rack-test requires a rack application, but none was given (ArgumentError)
      ./features/step_definitions/web_steps.rb:4:in `nil'
      features/en-tier-2.feature:4:in `I visit the request handling bot with locale "en-gb"'
```

**Comment by twalpole** [comment]
The error message is letting you know that you're using the rack-test driver which doesn't support external sites.  Even though you appear to be setting :selenium for current_driver you have code somewhere else that's setting that back.

**Comment by maca** [comment]
@twalpole Thank you, I don't have any other code than that and the Cucumber steps

**Comment by maca** [comment]
For reference I've removed  `require 'cucumber/capybara'` which seems to override whatever capybara specific config for the driver.

This worked:

```

**Comment by twalpole** [comment]
Ah yes, that provides the ability to specify a different driver per test, as documented in the readme - https://github.com/teamcapybara/capybara#using-capybara-with-cucumber - and in between it resets the driver to `Capybara.default_driver' - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/cucumber.rb
