### ISSUE TITLE
Capybara requires attached file to exist in local filesystem

### ISSUE THREAD

**Issue by ktimothy** [teamcapybara/capybara#2484]
Having an issue with capybara and browserless chrome in a docker container. The file I am trying to attach does not exist on local filesystem, since chrome runs as a service in a docker container with its own filesystem. 

IMO this requirement does not respect modern approaches with chrome run in cloud and controlled via CDP. I think we can remove this check, or add an option to remove it. What do you think?

https://github.com/teamcapybara/capybara/blob/f2113294deb04c08383779674b8868a599a4ad60/lib/capybara/node/actions.rb#L285

**Comment by twalpole** [comment]
What driver are you using? Files you need for your tests should be included with your tests and transferred to the required system when needed

**Comment by ktimothy** [comment]
I am using Cuprite, which connects to Chrome via url.

**Comment by YusukeIwaki** [comment]
@ktimothy Hi, I encountered the same issue using browserless.io. It seems we have to upload files in advance with workspace API. https://docs.browserless.io/docs/workspace.html

Similar issue: https://github.com/hardkoded/puppeteer-sharp/issues/1363 
(puppeteer-sharp uses the same CDP method for file uploading (DOM.setFileInputFiles), as Cuprite and Apparition does.)

**Comment by twalpole** [comment]
I don't see this as a current issue, drivers should be updated to support transferring the file to the target system (like the selenium driver does)
