### ISSUE TITLE
Use listener for after hooks?

### ISSUE THREAD

**Issue by ngan** [teamcapybara/capybara#2499]
We were cleaning up some of our `after` hooks based on this comment: https://github.com/rspec/rspec-core/issues/2289#issuecomment-231540385

And realized, should Capybara hooks be moved to a listener as well? We're using `rspec-retry` and have to manually reset the capybara session because of this issue: https://github.com/NoRedInk/rspec-retry/issues/72

**Comment by twalpole** [comment]
IMO, you shouldn't be using rspec-retry - and there's no current reason to move the Capybara hooks to a listener.
