### ISSUE TITLE
Unable to target contents of a `template` element

### ISSUE THREAD

**Issue by boardfish** [teamcapybara/capybara#2510]
I couldn't submit this to the mailing list due to errors, but I wonder whether it could be a bug.

## Meta
Capybara Version:

3.35.3

---

Hey folks. I'm working with HTML that's a little like this:

```html
<turbo-stream action="update" target="upcoming">
  <template></template>
</turbo-stream>
<turbo-stream action="update" target="active">
  <template></template>
</turbo-stream>
<turbo-stream action="update" target="history">
  <template>
    <div id="event_da2527c5-4ae0-4c1f-af8e-92c5196ded36"></div>
  </template>
</turbo-stream>
```

I'm trying to query for that div that's in the last template tag. But here's what I get:

```rb
foobar.has_css? 'template'
false
foobar.has_css? 'template', visible: :all
true
foobar.has_css? 'template > *', visible: :all
false
```

`foobar` in this case is the given HTML passed to `Capybara#string`.

I've also tried diving in by calling `foobar.all('template').map(&:native).map(&:children)` to see what Nokogiri makes of it, and no children are returned.

How can I test for the presence of that `div` in the template element? I'd expect Capybara to be able to find the element.

**Comment by pythonandchips** [comment]
I have encountered the exact same issue. This is the minimal test i've been able to recreate the issue with

```
  describe "internal template" do
    it "find the tag internal to template" do
      html = Capybara.string("<template><form></form></template>")

      html.find("form", visible: :all) # this will throw an exception
    end

    it "find the tag internal to template with xpath" do
      html = Capybara.string("<template><form></form></template>")

      html.find(:xpath, "//form") # this will throw an exception
    end
  end
```

Interestingly it fails if you revert to using xpath when trying to find the form in this case.

**Comment by pythonandchips** [comment]
@boardfish I've tracked down to why forms are coming back as empty. In this commit https://github.com/teamcapybara/capybara/commit/f23274e84a44cfe2b51607147dba4c151f735dee code was added to remove the content of template tags.

So not a bug its a feature :smile:

**Comment by boardfish** [comment]
That's interesting. It would make sense that in a lot of cases, folks might not want to be able to target `template` elements. However, I think it'd be better to make this a feature of Capybara that can be enabled or disabled on the fly, e.g.:

```rb
describe ExampleComponent do
  subject { render component; rendered_component }

  around do |example|
    Capybara.remove_template_elements = false
    example.run
    Capybara.remove_template_elements = true
  end

  let(:component) { ExampleComponent.new }

  it { is_expected.to have_css 'template > *', visible: :all }
end
```

I'm happy to tackle it myself.

**Comment by twalpole** [comment]
Real browsers remove the inner elements from the document tree and build a document fragment which is then accessible on the content property of the template element.  This means in real browsers the template contents are not accessible via CSS or XPath.  To emulate that as much as makes sense in the rack_test driver the inner elements are removed.  If you're using templates you should be feature/system testing the behaviors that use them rather than checking for the contents of the template in the page.

**Comment by jcoyne** [comment]
I'm working around this problem by doing:
```ruby
      template = Nokogiri(response.body).css('template').first.inner_html
      parsed = Capybara.string(template)
```

**Comment by adrianthedev** [comment]
Thanks @jcoyne for your solution. I used it to check inside `template` tags.
Cheers!

**Comment by kylefox** [comment]
This seemed to work for me:

```ruby
subject { component.css("template").children }

it { is_expected.to have_link("Logout", href: logout_path) }
```
