### ISSUE TITLE
Capybara::Helpers::Timer.expired? being evaluated too quickly evaluates to true

### ISSUE THREAD

**Issue by fbeaudoin-shopify** [teamcapybara/capybara#2512]
## Issue
The apparition driver [uses](https://github.com/twalpole/apparition/blob/11aca464b38b77585191b7e302be2e062bdd369d/lib/capybara/apparition/driver/chrome_client.rb#L110 ) `Capybara::Helpers.Timer().expired?` to raise a `TimeoutError` while waiting on a page to load.

The issue is that `expired?` evaluates to `true` intermittently if it is being evaluated too quickly after being initialized.

For example, running the following locally:

```ruby
100.times do
  Capybara::Helpers::Timer.new(9999).expired?
end
```

Results in:
```
Capybara::FrozenInTime: Time appears to be frozen. Capybara does not work with libraries which freeze time, consider using time travelling instead
from /capybara-3.36.0/lib/capybara/helpers.rb:106:in `expired?'
```

This is systematically reproducible on a Mac OS with the following specs:
```
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 32 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5300M 4 GB
          Intel UHD Graphics 630 1536 MB
```

**Comment by twalpole** [comment]
Does your build of ruby support Process::CLOCK_MONOTONIC ?

**Comment by fbeaudoin-shopify** [comment]
Yes it uses `Process::CLOCK_MONOTONIC`.

**Comment by twalpole** [comment]
Should be helped by a2b8793747c50f6235e2fead50142c2faa6a36a4
