### ISSUE TITLE
find with count: N should not be graceful

### ISSUE THREAD

**Issue by kwerle** [teamcapybara/capybara#2513]
## Meta
Capybara Version:
    capybara (3.29.0)

## Expected Behavior

`find('a', count: 44)`  should maybe blow up (raise).  I'm pretty sure that the old behavior was to do what 
`all('a', count: 44)` now does (makes sure that the page has 44 links).  I understand the behavior change (at least I think it's a change).  But it would be really nice for it to raise and complain about not supporting count.

## Actual Behavior
It returns the first one.

**Comment by twalpole** [comment]
I don't believe this is a change in behavior, although it probably does make sense to warn if any of the count options are specified

**Comment by twalpole** [comment]
Implemented as a warning in  f973c9f1f4cff4eda8320f5dd6459cb76307aa97
