### ISSUE TITLE
Is there a way to get Capybara.server to use Spring?

### ISSUE THREAD

**Issue by maxwell** [teamcapybara/capybara#2514]
Hi,

First thanks for all the teams hard work on Capybara!

This is more of a question to understand if there is a way I might be able to get Capybara server to use Spring. I asked over here https://github.com/rails/spring/issues/657#issuecomment-979475806 and was wondering if there might be a way forward here. My main reason for this that when I run my JS enabled feature tests, the first request to my server is always super slow, but subsequent tests are fast. When I am TDDing, since I am running one test at the time, it's extra annoying. 

If this is something that you think could be possible, I'd welcome any thoughts or hints.

**Comment by donv** [comment]
We are doing this :)
