### ISSUE TITLE
Can teamcapybara become the home for ports of capybara to other languages?

### ISSUE THREAD

**Issue by dwt** [teamcapybara/capybara#2515]
I'm sorry if this is the wrong place to ask this, but I don't know a better one. Pointers welcome. :-)

So here's the deal, there exists a pretty much one to one port of capybara to python [on GitHub here](https://github.com/elliterate/capybara.py/).

It is very usable, very complete - but sadly the maintainer is not very responsive anymore and seems to have moved on to other things.

I [have asked for more maintainers and an organisation on their bugtracker](https://github.com/elliterate/capybara.py/issues/24) - but haven't been able to get ahold of the maintainer yet (I guess next is sending him direct emails and then trying to call him).

BUT: That leaves the problem off where to put that library? Would you guys be willing to welcome that sister project into the `teamcapybara` fold? It is a one to one api port, so I think that from a technical standpoint it would be a really good match.

I am perfectly willing to help maintain it, fix some bugs and start a regular release train again - but of course I need to get ahold of the original maintainer @elliterate first.

**Comment by twalpole** [comment]
If the original maintainer is ok with it I would consider it

**Comment by dwt** [comment]
I have been able to get in touch with him now - I'll try to pull him into this conversation to get his input.

**Comment by twalpole** [comment]
Closing as out of date, we can reopen if this comes back alive

**Comment by dwt** [comment]
Yes, the original creator came back just enough to answer some bugs. He didn't really answer to a merge of organizations - but did enough that I don't want to just fork his stuff to here. He's sadly not really maintaining it though. :-/
