### ISSUE TITLE
expect() is giving error -> Error Message: TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by adalberto02** [teamcapybara/capybara#2517]
Using Gauge-UI
 capybara (3.36.0)

I Use **expect(this).to eq(that)** and if they do not match, the test throws an error **Error Message: TypeError: no implicit conversion of nil into String**

I checked that "this" and "that" are not empty.

expect behavior:
Test Should Fail and message should be **expected this to eq that** 

Thank you

**Comment by twalpole** [comment]
If neither `this` nor `that` are Capybara objects then your issue is with RSpec not Capybara (and you really shouldn’t be using Capybara objects with the rspec native marchers eq, etc since they don’t have waiting behavior)

**Comment by adalberto02** [comment]
OK. Thank you for the Advice.
