### ISSUE TITLE
Text rapid set can be flaky 

### ISSUE THREAD

**Issue by chadlwilson** [teamcapybara/capybara#2521]
## Meta
Capybara Version: `3.36.0`

Driver Information (and browser if relevant):

- Tried both selenium-webdriver `3.142.7` and `4.1.0`
- Firefox 95 on both Linux and Mac

## Expected Behavior
Reliable text setting in inputs for longer strings

## Actual Behavior

Since upgrading from `3.29.0` (ya, old) to `3.36.0`, reasonably often we are seeing tests flake due to problems setting text in inputs. Every time they fail I have seen the middle portion of the string missing entirely, i.e the entire portion executed by `driver.execute_script RAPID_APPEND_TEXT, self, value[4...-3]` is missing from the string, as included in

https://github.com/teamcapybara/capybara/blob/a958240ef44b44ca90be8e7b8fbcba8511a6e262/lib/capybara/selenium/node.rb#L277-L284

The prefix and suffix chars are all there.

We have not seen an issue with earlier versions or with the "slow" approach. Any ideas what could be causing this particular issue with the "rapid set" approach? 

It's possible it could be something like #2331 and we just need to disable rapid set in all these places, however it seems a bit strange that it's flaky.

## Steps to reproduce

I can't find a reproducer at this point :-(

**Comment by twalpole** [comment]
If you can provide a reproducible example I can look into it, but this is most likely going to boil down to JS behavior attached to your inputs being incompatible with the value being set directly.  Additionally, looking at your tests you might want to look at the `Capybara.test_id` setting so you can use the smarter Capybara selectors and actions rather than all the find(...).click, etc
 
ie. 

    click_button('add-secure-variables-btn')

rather than

    find('button[data-test-id="add-secure-variables-btn"]').click

**Comment by chadlwilson** [comment]
Thanks for the reply @twalpole . You're probably right however it might be a good idea to somehow document this feature/behaviour specifically as currently it seems to require a bit of digging to figure out the 'opt-out' and the types of JS interaction which might cause it to break or become flaky (debouncing validations?).

I'm not deeply familiar with either the JS involved in the inputs on our side or the Capybara/site_prism test implementation unfortunately so it's probably difficult for me to get to a simple reprod. I'm mainly trying to maintain/tend to the existing test suite and keep it running on modern rubys/browsers so lack some of the depth possibly necessary.

Appreciate the tips on using Capybara better though!

**Comment by twalpole** [comment]
@chadlwilson After a quick look I would guess, that rather than debouncing validations, it's something to do with Angular and your app setting the default change event  data sync handler to be called on input events instead. I haven't looked far enough to find out what the default change handler is actually doing though

**Comment by chadlwilson** [comment]
Right, that makes sense. GoCD is still, unfortunately, a hybrid app with some older screens using Rails/angular/raw-js and newer screens using smaller mithril/typescript SPAs and I think I have seen both new and old suffer from the same challenges, but they are possibly following the same approach.

I'm happy (enough...) with the workaround for now, but if you're open to it I can possibly find appropriate place to document the options for `.set` and submit a PR to Capybara?

**Comment by twalpole** [comment]
For large strings sending key by key was REALLY slow with selenium and chrome.  Not sure if that's still the case or not, but that's why rapid mode was added.  PRs are always considered.
