### ISSUE TITLE
Does the browser back button run Javascript?

### ISSUE THREAD

**Issue by knathan-10** [teamcapybara/capybara#2522]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.32.0

Driver Information (and browser if relevant): Selenium-webdriver 

## Expected Behavior
When I click on the browser back button via page.go_back, I expect the turbolinks to kick and render the page differently than what I see. When I save the html after clicking the back button, viewing it on my browser renders the expected view, not sure why this is inconsistent.

I wanted to clarify if the browser back button use turbolinks in capybara

**Comment by twalpole** [comment]
Assuming you're running with a JS capable driver - Chrome via Selenium? The browser button calls the webdriver `back` method which  is supposed to behave just like clicking the browsers back button.  If that isn't happening then it would be a bug in whichever driver you're using (chromedriver, etc)
