### ISSUE TITLE
Capybara appears to leak login state between scenarios in chrome

### ISSUE THREAD

**Issue by luke-hill** [teamcapybara/capybara#2523]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
3.36
Driver Information (and browser if relevant):
selenium 4.0.3 / 4.1.0

## Expected Behavior
No state leak
## Actual Behavior
State leak (Logged in state leaking)

## Steps to reproduce
The rspec test is fairly simple.
Test 1 - Login (Remain logged in)
Test 2 - Login again (Fails because you are already logged in).

https://github.com/luke-hill/automation_playground/tree/24ea0609718199a155f23fd362445fe8fab1bfd7/chromedriver-scope-issue/spec is the repo state whereby we fully use capybara. Spec 1 passes Spec 2 fails

I then use this commit: https://github.com/luke-hill/automation_playground/commit/22c679ba590c3b517053e926e6bd2fc62ae85374#diff-d451650cc819bbf5922e84141856ba9c9fd65531da450d990c2fd1ff139631a1 to switch from capybara to selenium. The 2nd spec now passes.

Any other questions feel free to ask. I also popped a message in slack. Can triage / debug with you accordingly.

**Comment by luke-hill** [comment]
EDIT: Looking through the docs, specifically around the `#reset!` method, it seems via code comments that maybe this clearing I am expected isn't likely to happen (Although I was sure it was happening before).

Adding a verbose kill command to my after hook **does seem** to remedy the situation. So I'm a little confused why this wasn't needed before.

But given the code comments in the file: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/session.rb#L114-L118 which probably hints at login information being retained, I am just going to add an extra `Capybara.current_session.quit` to the end of my after hook and then close this as not-actionable.

**Comment by twalpole** [comment]
@luke-hill That comment is outdated -- local and session storage will be cleared by default when using Chrome.  IndexedDB will not, although you can add code to do so.  Quitting sessions like that, will significantly increase the time and memory usage of your tests

**Comment by luke-hill** [comment]
@twalpole would you expect by default with the current capybara code to clear a login session? (Without doing `current_session.quit`)
