### ISSUE TITLE
A symbol is added to a textarea when pressing CTRL+END on Chrome 98+

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2528]
## Meta
Capybara Version:
3.36.0
Driver Information (and browser if relevant):
selenium-webdriver 4.1.0 with Chromium 98

## Expected Behavior

Running the code below to not modify the textarea.

## Actual Behavior

There is a strange symbol that appears in the textarea. Happens only with Chrome 98+. 97 and below work fine.

## Steps to reproduce
```rb
require 'capybara/dsl'
require 'selenium/webdriver'

html = DATA.read
app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
sess.find(:field, class: 'edit-titles', with: 'asd').send_keys(%i[control end])
sleep 100000

__END__
<!DOCTYPE html>
<html>
<head>
<title>title</title>
</head>
<body>
  <textarea class="edit-titles" rows="3">asd</textarea>
</body>
</html>
```

**Comment by twalpole** [comment]
Capybara just sends the keys through to be set to selenium => chromedriver.  Since this has changed with Chrome 98 it's going to be a bug in the latest chromedriver or chrome (most likely chromedriver).

**Comment by eliotsykes** [comment]
For anyone landing here looking for a workaround. If your HTML allows, try using the `fill_in(locator, with:)` method instead of `some_field.send_keys`. Worked for me but your mileage may vary.

(Another workaround found elsewhere is to downgrade to chromedriver 97. I've not tried this.)

**Comment by boris-petrov** [comment]
@eliotsykes - does `fill_in` work with CTRL+END as in my example?
