### ISSUE TITLE
Default driver issues a warning, selenium-driver deprecation

### ISSUE THREAD

**Issue by yonta** [teamcapybara/capybara#2531]
## Meta
Capybara Version: 3.36.0
Driver Information (and browser if relevant): selenium-webdriver 4.1.0 with Firefox 97.0

## Expected Behavior

No warnings.

## Actual Behavior

It issues a warning when running the tests, like this.

```console
$ rspec
.................................2022-03-01 01:13:59 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
....
```

## Steps to reproduce

1. Install latest capybara and selenium-webdriver
2. Use default selenium_headless driver as javascript driver
3. Test with `js: true`
4. Issue the warning

## I think

Capybara switches hash key by checking Selenium Driver Version.
I think that this checking return false with version 4.1.0.

https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/registrations/drivers.rb#L13

https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/selenium/driver.rb#L15

```ruby
 Gem::Requirement.new("~> 4.0.0.alpha6").satisfied_by?(Gem::Version.new("4.0.0"))
#=> true
Gem::Requirement.new("~> 4.0.0.alpha6").satisfied_by?(Gem::Version.new("4.1.0"))
#=> false
```

**Comment by twalpole** [comment]
This is already fixed in the master branch - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L15 - and will be in the next release.  Either use master, or ignore the warning until the next release.

**Comment by yonta** [comment]
OK, thx!
I am looking forward to the next release :)
