### ISSUE TITLE
Support access to console exceptions through `selenium-webdriver` 4.x and `on_log_event`

### ISSUE THREAD

**Issue by brodock** [teamcapybara/capybara#2532]
In `selenium-webdriver` 4.x they've introduced a new capability to receive console events through Console API messages via DevTools.

You can check the commit that introduces that here: https://github.com/SeleniumHQ/selenium/commit/a640141d2441571abb579082e4b144f0ef4c4078

and an example usage here: https://github.com/SeleniumHQ/selenium/blob/c9a2ef6a880338f87017bbb983b0531dd5161455/rb/spec/integration/selenium/webdriver/devtools_spec.rb#L73-L95

While DevTools may suggest this is a chromium only, Firefox does support CDP (see: https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#firefox-capabilities) and so does support the same `driver.on_log_event` implementation.

**Comment by twalpole** [comment]
What exactly are you asking from Capybara here? You already have the ability to access the driver register a handler

**Comment by twalpole** [comment]
Closing because it's unclear what is being asked for that can't already be done by calling the driver directly.  Will consider reopening if more details are provided
