### ISSUE TITLE
Inconsistency between `has_css?` and `find_link`

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2533]
## Meta
Capybara Version:
3.36.0
Driver Information (and browser if relevant):
selenium-webdriver 4.1.0 with Chrome

## Expected Behavior
`has_css?` in the example below prints `true` (which is correct). However, the `find_link` line blows up because a link cannot be found. But the conditions are **exactly** the same as in `has_css?` so I would expect that to work also.

## Actual Behavior
`find_link` fails even though `has_css?` returned `true`.

## Steps to reproduce
```rb
require 'capybara/dsl'
require 'selenium/webdriver'

html = DATA.read
app = proc { [200, { 'Content-Type' => 'text/html' }, [html]] }

sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
puts sess.has_css?('a', exact_text: "foo\nbar")
sess.find_link(exact_text: "foo\nbar")

__END__
<html>
  <body>
    <a>
      foo
      <div class="vr"></div>
      bar
    </a>
  </body>
</html>
```

**Comment by twalpole** [comment]
A `a` element technically requires an href attribute to be a link, without one it's a placeholder.  If you want `find_link` to match a placeholder you need to explicitly specify that you are looking for that by passing `href: nil` as an option

**Comment by boris-petrov** [comment]
@twalpole - OK, fair enough. It would be nice to point that in the documentation.

What about this:

```rb
require 'capybara/dsl'
require 'selenium/webdriver'

html = DATA.read
app = proc { [200, { 'Content-Type' => 'text/html' }, [html]] }

Capybara.exact = true
sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
puts sess.has_css?('a', exact_text: "foo\nbar")
sess.find_link("foo\nbar")

__END__
<html>
  <body>
    <a href="asd">
      foo
      <div class="vr"></div>
      bar
    </a>
  </body>
</html>
```

Note `Capybara.exact = true`. This example fails but both `sess.find_link(exact_text: "foo\nbar")` and `sess.find_link(text: "foo\nbar")` do work. Why is that?

**Comment by twalpole** [comment]
The reason that example doesn't work is because selector locators are implemented via XPath for performance reasons.  The string you are passing does not actually exist in the document in the element from an XPath perspective so it fails.  The text/exact_text options use the DOM interpreted text which allows it to match (with a performance penalty)
