### ISSUE TITLE
Race-condition with `click_on` without a selector

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2534]
## Meta
Capybara Version:
3.36.0
Driver Information (and browser if relevant):
selenium-webdriver 4.1.0 and Chrome 99

## Expected Behavior
I have in a test `click_on(exact_text: /\w{48}\.txt/)`. Before that I do a "search" in my app which returns one result (the one that must be clicked). But Capybara tells me `Ambiguous match, found 38 elements matching visible link or button nil`. This is definitely not correct. There is only one link that has that exact text. If I get the HTML that is produced by the failure and put it in a simple test case, it passes. Capybara does something strange.

If I change it to `click_on(text: /\w{48}\.txt/)` it works fine. As do both `click_on(text: /^\w{48}\.txt$/)` and `click_on(text: /\w{48}\.txt/, exact_text: true)`. Putting a `sleep 1` before the check also seems to resolve the issue.

## Steps to reproduce
I tried really hard to create a reproduction, even with JavaScript dynamically creating/updating links but I can't. :(

A little bit more information can be found in [Gitter](https://gitter.im/jnicklas/capybara?at=6225ea858db2b95f0a56b54a).

**Comment by twalpole** [comment]
Without reproduction steps there's not a lot that can be done here

**Comment by boris-petrov** [comment]
I know. :( But, unfortunately, as with any race-condition, it's pretty difficult/impossible to reproduce consistently. If you have absolutely no clue what the issue might be, you could close the issue. Otherwise you can leave it open until you've taken a closer look. Sorry I cannot help more here.

**Comment by twalpole** [comment]
@boris-petrov I just looked a little deeper into the code, and should have realized this sooner.  `exact_text` is documented to take only a boolean, or a string -- it doesn't accept a regex because that doesn't make sense for exact text - If you want a regexp just use the `text` option.

**Comment by twalpole** [comment]
@boris-petrov FTI - 3.37.0 should now support Regexp for the `exact_text` option, and warn for Regexp passed for `text` with exact_text Boolean value passed
