### ISSUE TITLE
Headless Browser ignores `required` HTML tags

### ISSUE THREAD

**Issue by hamolicious** [teamcapybara/capybara#2539]
## Meta
Capybara Version: 3.36
Driver Information (and browser if relevant): Chrome Driver: 99.0.4844.51

## Expected Behavior
Upon using `click_on('<button>')` in a `from` with `required` input tags the browser should not execute the method and instead should notify the user to input the missing data (if any)

## Actual Behavior
Capybara Headless in RSpec executes the action form instead of "nothing".

## Steps to reproduce

The browser **has** to be headless as a non-headless browser exhibits the expected behaviour

HTML Code
```html
<form class="form-container border" action="/spaces" method="post">
  <input required type="text" name="name" placeholder="Name" />
  <input required type="text" name="description" placeholder="Description" />
  <input required type="number" min="0" max="100000000" name="pricepernight" placeholder="Price per night (£)" />
  <input required type="date" name="availablefrom" placeholder="Available from" />
  <input required type="date" name="availableto" placeholder="Available to" />
  <button type="submit" > List my Space </button>
</form>
```
RSpec Scenario
```ruby
scenario 'A user did not specify name of listing' do 
  visit('/spaces/new')
  # notice the `name` is missing
  fill_in('description', with: 'its a seven story mansion bro, what more do you want?')
  fill_in('pricepernight', with: '1000')
  fill_in('availablefrom', with: '07-04-2022')
  fill_in('availableto', with: '10-10-2023')

  click_on('List my Space') # <-- redirects despite missing the name input field

  expect(page).to have_content('List a Space')
end
```

**Comment by twalpole** [comment]
What exactly do you mean by 'a headless browser' - If you mean running Chrome/Firefox/Safari in headless mode then there's nothing we can do about this, that behavior is all controlled by the browser itself, and should be reported as a bug to the browser vendor.  If you mean the racktest driver - then yes - it's a best attempt simulation of a browser without JS support - PRs are welcome (if accompanied by tests) if you want to add missing functionality
