### ISSUE TITLE
3.37.0 regression: second request in test marked as https

### ISSUE THREAD

**Issue by HoneyryderChuck** [teamcapybara/capybara#2548]
## Meta
Capybara Version:
3.37.0
Driver Information (and browser if relevant):
html driver (nokogiri)

## Expected Behavior

That capybara-driven requests are still recognized as coming from "http://example.com".

## Actual Behavior

The second request within an example comes marked as "https". This [broke rodauth-oauth tests](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/jobs/2427834114) (reverting to 3.36.0 fixes the issue).

## Steps to reproduce

Running the individual `rodauth-oauth` failing tests can reproduce it (ex: ` bundle exec ruby -Itest test/jwt/authorize_test.rb --name /jwks_request_object_signing_alg/`). The reason is a bit "buried", but it all comes down to calling `request.scheme`, where `request` is a `Rack::Request` (rack 2.2.3 in my runs).

**Comment by twalpole** [comment]
Thanks, looks like the addition of support for <base> elements changed behavior so that the previous pages url is being used as the base for new visits....  looking into how to fix

**Comment by twalpole** [comment]
Fixed via b21c2383d35186c210f287269a6c5a4903c21176

**Comment by HoneyryderChuck** [comment]
thx for the quick turnaround!
