### ISSUE TITLE
Default driver issues a warning, selenium-driver deprecation

### ISSUE THREAD

**Issue by seandilda** [teamcapybara/capybara#2551]
**NOTE**: This is effectively a reopen of #2531.  I'm experiencing the same issue with versions released since that issue was closed.

## Meta
Capybara Version: 3.37.1
Driver Information: selenium-webdriver 4.1.0

## Expected Behavior

No deprecation warnings when running a test

## Actual Behavior
When running a test, I see the following warning:

```
2022-05-19 11:36:24 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
```

## Steps to reproduce
My config looks like:
```ruby
  driven_by(
    :selenium,
    using: :chrome,
    screen_size: [1400, 2400],
    options: {
      browser: :remote,
      url: 'http://chromedriver:9515'
    }
  )
```

**Comment by twalpole** [comment]
You're calling `driven_by` that's a Rails method, and Rails (or possibly rspec-rails depending on what you're using) is defining the driver being used not Capybara.
