### ISSUE TITLE
Wrong handling of form inputs with the same name

### ISSUE THREAD

**Issue by HoneyryderChuck** [teamcapybara/capybara#2552]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.36.0
Driver Information (and browser if relevant): `rack-test`

## Expected Behavior

Given the following inputs within a form:

```html
<input type="hidden" name="resource" value="res1" />
<input type="hidden" name="resource" value="res2" />
```

Wen using the rack-test driver, I'd expect both values to be encoded in the POST payload sent to the server: `resource=res1&resource=res2`.

## Actual Behavior

Instead, only the last `resource` gets sent. The reason seems to be that the form input parser [return an hash](https://github.com/teamcapybara/capybara/blob/1c164b608fa6452418ec13795b293655f8a0102a/lib/capybara/rack_test/form.rb#L37), instead of an array of tuples.

**Comment by twalpole** [comment]
I believe this is a rack limitation in not supporting multiple fields with the same name unless they're specified as an array (name ending in [])

**Comment by HoneyryderChuck** [comment]
Should capybara be limited by it then? AFAIK it's not really a limitation in the rack spec, it's just that APIs such as .params can't deal with it. 

For context, the requirement to support this from my side is imposed by the protocol RFC, so I'm already working around that limitation. Would be great to test it though.

**Comment by twalpole** [comment]
It’s the ‘rack-test’ driver and Capybara supports starting/running rack based apps - Racks parameters parsing doesn’t support multiple scaler parameters with the same name so I really don’t see a massive value in supporting more in Capybara currently. If rack updates it’s parameter parsing then I’d look at it. Other options would be to extend the rack-test driver, write your own custom driver, or use one of other real browser drivers
