### ISSUE TITLE
xpath guessing is considered css syntax

### ISSUE THREAD

**Issue by akicho8** [teamcapybara/capybara#2554]
## Meta

```
public_suffix 4.0.7
bundler 2.3.13
matrix 0.4.2
racc 1.6.0
mini_mime 1.1.2
regexp_parser 2.4.0
childprocess 4.1.0
rexml 3.2.5
rubyzip 2.3.2
rack 2.2.3
addressable 2.8.0
nokogiri 1.13.6 (x86_64-darwin)
selenium-webdriver 4.1.0
rack-test 1.1.0
xpath 3.2.0
webdrivers 5.0.0
capybara 3.37.1
```

## Expected Behavior

```ruby
node.has_selector?("//a[contains(text(), 'x')]") # => true
```

## Actual Behavior

```ruby
node.has_selector?("//a[contains(text(), 'x')]") rescue $! # => #<Nokogiri::CSS::SyntaxError: unexpected 'text(' after 'contains('>
```

## Steps to reproduce

```ruby
require "bundler/inline"

gemfile(false) do
  source "https://rubygems.org"
  gem "webdrivers"
  gem "capybara", require: "capybara/dsl"
end

Capybara.default_selector       # => :css

# It is presumed to be xpath because it starts with //
# However, if write contains(text()), it will not work.
node = Capybara.string("<a>xxx</a>")
node.has_selector?("//a[text()='xxx']")                    # => true
node.has_selector?("//a[contains(text(), 'x')]") rescue $! # => #<Nokogiri::CSS::SyntaxError: unexpected 'text(' after 'contains('>

# It works when specify :xpath
node.has_selector?(:xpath, "//a[contains(text(), 'x')]")   # => true

# It works in nokogiri.
node = Nokogiri.XML("<a>xxx</a>")
node.at("//a[text()='xxx']")          # => #<Nokogiri::XML::Element:0x884 name="a" children=[#<Nokogiri::XML::Text:0x870 "xxx">]>
node.at("//a[contains(text(), 'x')]") # => #<Nokogiri::XML::Element:0x884 name="a" children=[#<Nokogiri::XML::Text:0x870 "xxx">]>

Nokogiri::XML::Searchable::LOOKS_LIKE_XPATH # => /^(\.\/|\/|\.\.|\.$)/
```

**Comment by twalpole** [comment]
Capybara doesn't guess whether the input is CSS or XPath, you have to tell it - either by setting the default type (defaults to :css) or by passing as the first parameter - The fact that nokogiri MIGHT do some type of guessing is irrelevant to Capybara behavior and should not be depended on. Additionally most of the time you don't want to be starting XPath with `//` when using Capybara since it defeats scoping - see https://github.com/teamcapybara/capybara#beware-the-xpath--trap

**Comment by twalpole** [comment]
Note also that Nokogiri isn't actually guessing that it's XPath -- Nokogiris  CSS#xpath_for is being called to convert the "CSS" to XPath -- it's just that Nokogiris conversion is VERY lenient, and supports a number of extensions to CSS as mentioned in https://github.com/sparklemotion/nokogiri/blob/main/lib/nokogiri/xml/searchable.rb#L92 - In this case it's converting from "//a[text()='xxx']" => "////a[child::text()='xxx']". which happens to still work with what you're doing

    Nokogiri::CSS.xpath_for("//a[text()='xxx']")
    => ["////a[child::text()='xxx']"]

LOOKS_LIKE_XPATH is never actually used in the Capybara code flow (doesn't call Nokogiri::XML::Searchable#search)

**Comment by akicho8** [comment]
@twalpole I see.
The input of the XPath was converted as XPATH, and some happened to work.
Thank you for the detailed explanation.
