### ISSUE TITLE
Capybara drag_to method works on Windows machine but doesnot works on Linux one

### ISSUE THREAD

**Issue by galogen** [teamcapybara/capybara#2555]
Hello

I posted the question: [Capybara drag_to method works on Windows machine but doesnot works on Linux one](https://stackoverflow.com/questions/72369314/capybara-drag-to-method-works-on-windows-machine-but-doesnot-works-on-linux-one) but want to duplicate here

**Comment by twalpole** [comment]
Sorry, but I'm not going to look at random videos from a russian website.  I'd say verify the versions of Chrome and chromedriver you're using are the same and that your default window sizes are set the same. If those are all the same then it pretty much has to be a bug in the linux build of chromedriver or chrome.
