### ISSUE TITLE
`switch_to_window` is not supposed to be invoked from `within` or `within_frame` blocks

### ISSUE THREAD

**Issue by galogen** [teamcapybara/capybara#2560]
Hello!

Сapybara-3.35.3

Previously I used code like this
```
Given(/^Switch to window$/) do 
   window_last = page.driver.browser.window_handles.last
   page.driver.browser.switch_to.window(window_last)
end
```
On the advice of Thomas, I changed the code to 
```
Given(/^Switch to window$/) do 
    window_last = page.windows.last
    log window_last.handle
    page.switch_to_window(window_last)
end
```

There is a pair of tests where the error "`switch_to_window` is not supposed to be invoked from `within` or `within_frame` blocks" occurs.

The first of them opens a new window that has a frame (under angular control)
The second opens a new window that has a frame (under angular control) from the frame (under angular control) 

Could you suggest how to solve this problem?

Sincerely, Edward.

**Comment by twalpole** [comment]
This isn't a place for howto questions, however the error explains the issue.  You have to backed out of frames before switching windows.  That would generally mean putting your frame changing within a `window_opened_by and then using the result to change windows

    new_window = window_opened_by do
       within_frame ... do
          ...
       end
    end 
    within_window new_window do
      ...
    end

**Comment by galogen** [comment]
Thank you. Sorry for choosing the wrong place for the question.
