### ISSUE TITLE
How can I configure Capybara to re-use the same server and browser session between test runs?

### ISSUE THREAD

**Issue by ndbroadbent** [teamcapybara/capybara#2571]
This is an issue I've been having with Capybara for many years. Sorry to post on GitHub issues, but I also posted on the Google mailing list a few years ago: https://groups.google.com/g/ruby-capybara/c/Zc6jrzFVyjA

I'm working on some RSpec integration tests that use Capybara and Selenium WebDriver. Each time I run a test with rspec, it has to call `chromedriver` and open a new Chrome browser. This takes a lot of time to set up and tear down the browser very frequently. I would like to find a way to keep `chromedriver` and the browser session running in the background, and reconnect to it next time I run `rspec`.

Is there an easy way to set this up in my Capybara driver / RSpec configuration?

I use Spring to preload my Rails application and keep it running in the background, so perhaps I could also keep the Capybara session running in this Spring process. Or maybe I could save / reload the session details to a YAML file in my `tmp` directory?

Thanks!

## Meta
Capybara Version: 3.35.3
Driver Information (and browser if relevant):
* selenium-webdriver (3.142.7)
* ChromeDriver 102.0.5005.61

## Expected Behavior

There should be an easy way to re-use a browser session between test suite runs when developing on a local machine.

## Actual Behavior

It seems to be very difficult to find a solution (I've been scouring the GitHub issues, StackOverflow, etc.)

**Comment by ndbroadbent** [comment]
This is surprisingly difficult. I played around and tried to hack something together on a branch: https://github.com/teamcapybara/capybara/compare/master...DocSpring:capybara:reuse_session_with_spring

I put this `config.to_prepare` block in `config/environments/test.rb`:

```
  config.to_prepare do
    require_relative '../../spec/support/capybara'
    Capybara.threadsafe = false
    Capybara.current_driver = Capybara.javascript_driver
    # Start Capybara server and browser
    Capybara.current_session.driver.browser
  end
```

This sets up the Capybara server and browser while Spring is preloading the application. Then I needed to call `ActiveRecord::Base.establish_connection` as a quick hack in the server middleware, so that the forked Puma server re-established the database connection. It turns out that starting the Puma server was actually taking the most time, and starting the browser wasn't too slow. Would it be possible to use Spring for the Puma server?

It's mostly working now and I'm able to re-use the same browser and server between `rspec` calls. The only issue is that there's a 60 second delay before the test suite exits, even if the test is passing. I couldn't figure out where that delay is happening. (It's not waiting for any pending requests, etc.)

**Comment by twalpole** [comment]
This is going to add all sorts of complexity, overhead and concurrency issues for, imo, very little gain.  If you  really want this just run your application externally and have Capybara hit the external app.  This functionality isn't something I'm currently interested in building into Capybara.
