### ISSUE TITLE
Consumes much CPU while synchronizing

### ISSUE THREAD

**Issue by masa-nomoto** [teamcapybara/capybara#2574]
Capybara consumes much CPU while waiting for elements.  It sometimes stresses my CI environment.

I think that `Capybara::Node::Base#synchronize` retries checking too frequently.  If I replace `sleep(0.01)` with `sleep(0.25)` in the code, CPU usage is noticeably reduced.

Is it possible to provide configurations for tuning the intervals, or is there another way to reduce CPU usage effectively?

## Meta
Capybara Version: 3.37.1
Driver Information: selenium-webdriver 4.4.0 with Firefox 103.0

## Expected Behavior
Capybara saves CPU usage while synchronizing.

## Actual Behavior
Capybara consumes more CPU than expected.

I have no way to improve the problem other than changing the installed script directly. (See the next section.)

## Steps to reproduce

Gemfile:

```ruby
source 'https://rubygems.org'

# ruby '3.1.2'

gem 'capybara', '3.37.1'
gem 'selenium-webdriver'
```

Sample code:

```ruby
require 'capybara/dsl'
require 'selenium-webdriver'

#--- configure ---#
Capybara.register_driver :selenium do |app|
  options = Selenium::WebDriver::Firefox::Options.new
  options.headless!
  Capybara::Selenium::Driver.new(app, browser: :firefox, options: options)
end
Capybara.default_driver = :selenium
Capybara.javascript_driver = :selenium

#--- main ---#
include Capybara::DSL

visit 'http://example.com/'
find '#dummy-id', wait: 60
```

Commands:

```bash
bundle install --path=vendor/bundle

# Replace `sleep(0.01)` with `sleep(0.25)` .
# sed -i.bk -e '/sleep/s/0\.[0-9]*/0.25/' $(bundle show capybara)/lib/capybara/node/base.rb

# Measure CPU usages while executing the `#find` method.
bundle exec ruby sample.rb & \
sleep 10 && pidstat -C 'ruby|geckodriver|firefox' 5 10
```

---

Examples of output:

```
#--- Original: sleep(0.01) ---#
Average:      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
Average:     1000   1778721    7.55    1.60    0.00    3.56    9.15     -  ruby
Average:     1000   1778735    1.76    1.30    0.00    0.00    3.06     -  geckodriver
Average:     1000   1778741    9.21    2.84    0.00    3.96   12.05     -  firefox

#--- Custom: sleep(0.25) ---#
Average:      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
Average:     1000   1779497    0.56    0.08    0.00    0.12    0.64     -  ruby
Average:     1000   1779511    0.10    0.12    0.00    0.00    0.22     -  geckodriver
Average:     1000   1779517    2.12    1.12    0.00    0.32    3.24     -  firefox
```

**Comment by twalpole** [comment]
I would accept a PR that makes it configurable, but realize that by setting to 0.25 any test suite for a dynamic app is going to become painfully slow.  The whole point of 0.01 is to keep the app checking as quickly as possible so the tests can move on as fast as possible, a quarter second is a LONG time compared to what any reasonable machine can make DOM changes in nowadays.  Also, modifying the installed library using `sed` is a terrible idea.  Just monkeypatch the method

**Comment by apc-nomoto** [comment]
Thanks for your comments.  I try to make it configurable.

Is there any other advice or suggestion on how to design and implement the configurations?  I believe that users want to set the new parameter `interval` together with `wait`.  So I'm thinking interfaces like below:

```ruby
# global
Capybara.default_max_wait_time = 2
Capybara.default_wait_interval = 0.01

# scoped
Capybara.using_wait_time(5, interval: 0.05) do; end

# each method
find('selector', wait: 60, interval: 0.25)
```

**Comment by twalpole** [comment]
I don’t think there’s a lot of value in having it configurable in a scoped way with using_wait_time, and find. Judging by the fact you’re the first person to worry about this I’d say it will rarely be used. Just do  Capybara.default_retry_interval
