### ISSUE TITLE
`visit` doesn't return until script tags have been loaded

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2582]
## Meta
Capybara Version:
3.37.1
Driver Information (and browser if relevant):
Selenium 4.2.1 on Chrome 105

## Expected Behavior
`visit` to "end" immediately

## Actual Behavior
`visit` seems to wait for the page to "finish loading" or something.

## Steps to reproduce
```rb
require 'capybara/dsl'
require 'selenium/webdriver'

require 'socket'

server = TCPServer.open 2000

Thread.new do
  loop {
    client = server.accept()
    sleep 3
    resp = 'document.getElementById("foo").remove();'
    headers = ['HTTP/1.1 200 OK',
               'Date: Tue, 14 Dec 2010 10:48:45 GMT',
               'Server: Ruby',
               'Content-Type: application/javascript; charset=utf-8',
               "Content-Length: #{resp.length}\r\n\r\n"].join("\r\n")
    client.puts headers
    client.puts resp
    client.close
  }
end

html = DATA.read
app = proc { [200, { 'Content-Type' => 'text/html' }, [html]] }

sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
puts sess.has_css?('#foo')

__END__
<html>
  <body>
    <div id="foo">aaaaa</div>
    <script src="http://localhost:2000/foo.js" async></script>
  </body>
</html>
```

Running this leads to a browser showing and `aaaaa` being displayed in it. However, `visit` doesn't return until the `script` tag hasn't completed (and it has a 3-second delay to make things visible). Because of that the `puts` will display `false` because it will only be run after the script has been executed (which removes the `div`).

I found this because I want to test literally the same code in my app - that a "loading" screen is shown until the JavaScript has loaded. Any ideas how to do that and why `visit` behaves like it does?

**Comment by twalpole** [comment]
This is driver specific behavior not Capybara. If the driver you’re using supports other definitions of “page loaded” then you can configure them to return earlier

**Comment by boris-petrov** [comment]
Any ideas if Selenium supports that? How can I test such a functionality (loading spinner before JS is loaded)?

**Comment by twalpole** [comment]
I believe there is a chrome setting with selenium that will but I don’t know what it is currently. Depending on how your JS is setup/partitioned you could also mark the script tag as defer or async

**Comment by boris-petrov** [comment]
For future readers - I added a new driver (copying the options from my main driver):

```rb
Capybara.register_driver :chrome_no_load_waiting do |app|
  options = Capybara.drivers[:chrome].call(nil).options[:capabilities]
  options.page_load_strategy = 'none'
  Capybara::Selenium::Driver.new(app, browser: :chrome, capabilities: options)
end
```

And then I use that driver in my test and then `visit` doesn't wait for the page to be fully loaded.
