### ISSUE TITLE
Headless mode spawns a browser window

### ISSUE THREAD

**Issue by gdonald** [teamcapybara/capybara#2583]
Capybara Version:

```shell
> gem list capybara

capybara (3.37.1)
```

Driver Information (and browser if relevant):

```shell
> gem list selenium-webdriver

selenium-webdriver (4.4.0)
```

```shell
> chromedriver --version

ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853})
```

```shell
> /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version

Google Chrome 105.0.5195.125
```

My config in my spec_helper.rb:

```ruby
require 'capybara/rspec'
Capybara.javascript_driver = :selenium_chrome_headless
Capybara.default_driver = :selenium_chrome_headless
```

## Expected Behavior

When I run a system spec I expect Chrome to observe headless mode and not spawn a visible window.

## Actual Behavior

Chrome spawns a visible window.

## Steps to reproduce

The above config and a spec like:

```ruby
RSpec.describe 'Test', type: :system do
  it 'visits the test page' do
    visit root_path
    expect(page).to have_content 'Test'
  end
end
```

**Comment by twalpole** [comment]
What is capybara-selenium?

**Comment by gdonald** [comment]
> What is capybara-selenium?

Oops.  It's a gem I was trying while trying to fix my issue.  I no longer have it installed or in my Gemfile.  Sorry about that.

**Comment by twalpole** [comment]
You're using rails `system` tests which I assume means you are using rspec-rails -- Since you're using rails system tests the driver used during system specs is controlled by `driven_by` as documented in https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec, not by the Capybara default_driver and javascript_driver settings.
