### ISSUE TITLE
`hover` doesn't hover the center of a link

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2587]
## Meta
Capybara Version:
3.37.1
Driver Information (and browser if relevant):
Selenium 4.4.0 on Chrome 106

## Expected Behavior
The element to be hovered in the center.

## Actual Behavior
The element is hovered near the beginning.

## Steps to reproduce
```rb
require 'capybara/dsl'
require 'selenium/webdriver'

html = DATA.read
app = proc { [200, { 'Content-Type' => 'text/html' }, [html]] }

sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
sess.find_link.hover
puts sess.find('div').text

__END__
<html>
  <body>
    <a href="#">&nbsp;<span>some long content</span></a>
    <div></div>
    <script>
      document.querySelector('a').addEventListener('mouseover', function (event) {
        document.querySelector('div').innerHTML = event.clientX + ' - ' + event.clientY;
      });
    </script>
  </body>
</html>
```

If you run this, you'll see in the console something like `10 - 16`. If you remove either `&nbsp;` or the `span` element (leaving the text), then the log will be something like `65 - 16` (which is the correct position near the center of the link).

Not sure if this is a Capybara bug or a Selenium one?

**Comment by twalpole** [comment]
This is likely a change caused by Seleniums changing `move_to` from the center to the top left corner, although I don't see anywhere in the docs where Capybara claims it will be over the center of the element

**Comment by twalpole** [comment]
Looking deeper I think the root cause for the difference in behavior her is actually chromedriver.  Selenium isn't doing anything other than sending the action to chromedriver which is behaving differently based on whether or not the nbsp and span are in the a element or not.
