### ISSUE TITLE
Capybara is broken in combination with puma 6.0.0

### ISSUE THREAD

**Issue by jorg-vr** [teamcapybara/capybara#2594]
After the [new puma update](https://github.com/puma/puma/blob/master/History.md), capybare fails to setup a puma server.

The code makes use of no longer available classes. Eg. in `registrations/servers.rb` line 32:
```ruby
  events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
```
should be

```ruby
events = conf.options[:Silent] ? ::Puma::LogWriter.strings : ::Puma::LogWriter.stdio
```
Due to the changes in https://github.com/puma/puma/pull/2798

Changing this results in a new error, which I did not explore further:
```
#<Thread:0x00007f412cd1ab18 <path>/capybara-3.37.1/lib/capybara/server.rb:76 run> terminated with exception (report_on_exception is true):
<path>/capybara-3.37.1/lib/capybara/registrations/servers.rb:43:in `block (2 levels) in <main>': NoMethodError
        from <internal:kernel>:90:in `tap'
        from<path>/capybara-3.37.1/lib/capybara/registrations/servers.rb:41:in `block in <main>'
        from <path>capybara-3.37.1/lib/capybara/config.rb:64:in `block in server='
        from <path>/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
```

## Meta
Capybara Version: 3.37.1

## Steps to reproduce
Install capybara
Install puma 6.0.0
Try to run a system test that uses capybara with puma

**Comment by twalpole** [comment]
Use the master branch until I have time to finish up the next release, or  just use puma 5.x
