### ISSUE TITLE
Incompatible with Puma 6.0.0

### ISSUE THREAD

**Issue by rakshassa** [teamcapybara/capybara#2603]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
3.37.1

## Expected Behavior
Success running existing rspec tests using Puma 6.0.0.
Reverting to Puma 5.6.5 fixes the issue.

## Actual Behavior
09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-3.37.1/lib/capybara.rb:377:in `ensure in using_session'

09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-3.37.1/lib/capybara.rb:378:in `using_session'

09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-screenshot-1.0.26/lib/capybara-screenshot/capybara.rb:7:in `using_session'

09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-screenshot-1.0.26/lib/capybara-screenshot/rspec.rb:55:in `after_failed_example'

09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-screenshot-1.0.26/lib/capybara-screenshot/rspec.rb:105:in `block (2 levels) in <top (required)>'

09:30:08            # /home/jenkins/.rvm/gems/ruby-3.1.2/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

09:30:08            # ------------------

09:30:08            # --- Caused by: ---

09:30:08            # NoMethodError:

09:30:08            #   undefined method `strings' for Puma::Events:Class

09:30:08            #  

09:30:08            #     events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio

09:30:08            #                                                    ^^^^^^^^

09:30:08            #   /home/jenkins/.rvm/gems/ruby-3.1.2/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>'

**Comment by simi** [comment]
You would be able to find out on your own by searching in issues first.

![image](https://user-images.githubusercontent.com/193936/196748463-a42ccec3-fc83-460a-b540-8539debcd1ca.png)

**Comment by zspencer** [comment]
Closing issues once merged, but haven't been released makes them much less discoverable through Github's search interface.  I was lucky to see this one still open, but if I hadn't; I would have searched and found no open Puma issues. This would lead me to believe it is unreported; rather than fixed-but-unreleased. 

For those who find this issue later, there is [a recommended set of solutions on the patch that fixes the incompatibility](https://github.com/teamcapybara/capybara/pull/2530#issuecomment-1283130450)

**Comment by simi** [comment]
@zspencer the solution is to let maintainer prepare capybara release and don't rush on Puma upgrade.
