### ISSUE TITLE
Puma 6.0.0 incompatibility

### ISSUE THREAD

**Issue by MattBudz** [teamcapybara/capybara#2605]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
3.37.1

Driver Information (and browser if relevant):
selenium-webdriver (4.5.0)

## Expected Behavior
Tests run

## Actual Behavior
```bash
/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <main>': undefined method `strings' for Puma::Events:Class (NoMethodError)

  events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                 ^^^^^^^^
```

## Steps to reproduce
Use current Puma 6.0.0 and attempt to run tests.

**Comment by simi** [comment]
![image](https://user-images.githubusercontent.com/193936/197390913-4858e48f-7a54-4b9c-a192-85348c37a32d.png)

**Comment by MattBudz** [comment]
@twalpole @simi sorry guys! I totally missed checking closed issues. I was actually surprised no one submitted an issue yet so I created one 🤦‍♂️ (lesson learned).
