### ISSUE TITLE
New release of puma `6.0.0` breaks current capybara version

### ISSUE THREAD

**Issue by sordu** [teamcapybara/capybara#2610]
## Meta
Capybara Version:
`3.37.1`
Driver Information (and browser if relevant):
`capybara-angular (0.2.5)` & `poltergeist (1.18.1)`

## Expected Behavior

Capybara works without errors

## Actual Behavior
```
     1.1) Failure/Error: events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio

          NoMethodError:
            undefined method `stdio' for Puma::Events:Class
          # ../2.7.6/lib/ruby/gems/2.7.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <main>'
          # ../2.7.6/lib/ruby/gems/2.7.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
          #
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

## The problem
It seems to be an error in https://github.com/teamcapybara/capybara/blob/master/lib/capybara/registrations/servers.rb on line 32. Internal for `puma` were changed in version 6.0.0 https://github.com/puma/puma/releases/tag/v6.0.0. Probably something along this PR https://github.com/puma/puma/pull/2798

**Comment by simi** [comment]
Please search issues next time before opening new one. :pray: 

![image](https://user-images.githubusercontent.com/193936/199491749-8dfe668e-a900-463a-9f2f-0fb418a26dfc.png)
