### ISSUE TITLE
Different behavior between {..} and do..end block with filter block of rspec matchers

### ISSUE THREAD

**Issue by cbliard** [teamcapybara/capybara#2616]
## Meta
Capybara Version: 3.38.0

Driver Information: selenium-webdriver 4.6.1

## Expected Behavior

These two expectations should behave identically as only the block notation differs:

```ruby
# will fail
expect(page).to have_selector("input") { false }

# will pass
expect(page).to have_selector("input") do
  false
end
```

Currently they behave differently: first one is failing, second one is passing. I think second one should fail too.

Why does it pass in the second case: as `do..end` block having lower precedence than `{..}` block, the block in the first expectation is attached to the `have_selector` matcher while the block in the second expectation is attached to the `#to` method.

Adding parens can make the second expectation fail as expected:
```ruby
# will fail
expect(page).to(have_selector("input") do
  false
end)
```

## Actual Behavior
```ruby
expect(page).to have_selector("input") do |input|
  input.value == "42"
end
```

This expectation will pass regardless of the actual value in the input element, as the filter block is never evaluated.

## Steps to reproduce

Something like this should fail:
```ruby
expect(page).to have_selector("input") do
  false
end
```

I'll submit a PR for this.

**Comment by mvz** [comment]
@cbliard just to be clear, the problem you're seeing is that the behavior is different due to Ruby's block precedence rules, and you'd like the behavior to be the same?

**Comment by cbliard** [comment]
@mvz yes exactly.

[We use the do block notation](https://github.com/opf/openproject/blob/93a4878dea1f1c3ed992109290dde8ca5552cee8/spec/features/wysiwyg/non_breaking_spaces_spec.rb#L58-L60) to run additional check when using `have_selector` matcher, and we just noticed recently that the block was never evaluated.

**Comment by cbliard** [comment]
Is there anything I can do to help and get this issue and the associated PR reviewed?

**Comment by twalpole** [comment]
The fact the blocks aren't getting evaluated is down to ruby binding precedence, and I'm guessing `rubocop` would have warned of such and suggested putting ()s around things to make unambiguous.  Due to that I'm closing this issue as not really a Capybara issue.  The change in https://github.com/teamcapybara/capybara/pull/2617/files is being considered but currently the tests added are not acceptable as implemented.
