### ISSUE TITLE
uninitialized constant Selenium::WebDriver::Error::ExpectedError

### ISSUE THREAD

**Issue by ronnqvistandreas** [teamcapybara/capybara#2621]
## Meta
Capybara Version: 3.37.1

Driver Information (and browser if relevant): selenium-webdriver 4.5.0 with Chrome 107.0.5304.110

## Expected Behavior
The actual error to be raised

## Actual Behavior
NameError: uninitialized constant Selenium::WebDriver::Error::ExpectedError
[::Selenium::WebDriver::Error::ExpectedError]

/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/nodes/chrome_node.rb:109:in `block in file_errors'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/logger_suppressor.rb:23:in `suppress_deprecations'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/nodes/chrome_node.rb:108:in `file_errors'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/nodes/chrome_node.rb:27:in `rescue in set_file'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/nodes/chrome_node.rb:17:in `set_file'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/selenium/node.rb:77:in `set'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/node/element.rb:123:in `block in set'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/node/base.rb:83:in `synchronize'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/node/element.rb:123:in `set'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/node/actions.rb:304:in `attach_file'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/session.rb:771:in `attach_file'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/dsl.rb:52:in `attach_file'

## Steps to reproduce

We are having sporadic issues when using `attach_file`, which might be related to timeouts. Thing is, we don't get the actual error, as the above error is raised instead when setting the file.

![image](https://user-images.githubusercontent.com/3678847/204266639-e7af889d-105b-42c7-9dcb-ca390573fe34.png)

![image](https://user-images.githubusercontent.com/3678847/204266688-eea8575f-d90b-46fc-8d9b-487a3d248b18.png)

As far as I can tell, there is no class ExpectedError defined since selenium-webdriver 4.0.0.alpha1: 
https://github.com/SeleniumHQ/selenium/commit/75d235f681fd2c3d5a93f423a1f8b2f0205b80b9
https://github.com/SeleniumHQ/selenium/blob/trunk/rb/CHANGES#L461

**Comment by twalpole** [comment]
Fixed via PR#2632
