### ISSUE TITLE
`execute_cdp` is a private method

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2622]
I tried calling `page.driver.execute_cdp` and pass some arguments. That leads to `private method execute_cdp called...`. Indeed it [is a private method](https://github.com/teamcapybara/capybara/blob/3.38.0/lib/capybara/selenium/driver_specializations/chrome_driver.rb#L95).

## Meta
Capybara Version:
3.38.0
Driver Information (and browser if relevant):
Chromium 108 with chromedriver 108

## Expected Behavior
To be able to call `execute_cdp` directly on the driver.

## Actual Behavior
`private method called`.

**Comment by twalpole** [comment]
Yes, it's a private method, has been since it was added, what made you think it wasn't a private method?

**Comment by boris-petrov** [comment]
Nothing made me think it wasn’t private. My point is that it *mustn’t* be private because I want to call the driver’s “execute_cdp” method. I want to use some functionality that isn’t exposed by Selenium.

**Comment by twalpole** [comment]
If you want to use the selenium `execute_cdp` method call it on the Selenium::WebDriver instance `page.driver.browser.execute_cdp` - the method you are trying to call currently is there for internal use to deal with older versions of selenium and will not be made public
