### ISSUE TITLE
CSS text transform with apostrophe leads to erroneous results

### ISSUE THREAD

**Issue by jeremyatenovis** [teamcapybara/capybara#2625]
## Meta
Capybara Version: 3.38.0 (and many previous versions)
Driver Information (and browser if relevant): selenium-webdriver (4.7.1) with Chrome 108.0.5359.124 (Official Build) (arm64)

## Expected Behavior
The letter immediately after an apostrophe is not capitalized with a style: `text-transformation: capitalize`.

## Actual Behavior
The letter immediately after an apostrophe is capitalized

## Steps to reproduce
I have created a new Rails project that demonstrates this problem: https://github.com/jeremyatenovis/capybara-text-transform-bug

**Comment by jeremyatenovis** [comment]
Just to be extra clear. Here's the test: 

```ruby
RSpec.describe "Statics", type: :system do
  describe 'Index page' do
    it 'shows proper capitalization' do
      visit root_path
      expect(page).to have_content("This Is My Dog's Page!")
    end
  end
end
```

And here is the HTML: 

```html
<p style="text-transform: capitalize;">This is my dog's page!</p>
```

This test fails due to the S being capitalized.

**Comment by twalpole** [comment]
Capybara doesn’t apply the CSS itself it just uses what the driver/browser return as the displayed text  therefore this is an issue in either the driver or browser versions you’re using

**Comment by jeremyatenovis** [comment]
@twalpole Are you sure? When I inspect the `body` method of page the text is not transformed and I saw this old ticket that says this used to be intentional:  https://github.com/teamcapybara/capybara/issues/890

**Comment by jeremyatenovis** [comment]
I have just confirmed that this behavior also exists on selenium with node. Thanks for the quick response! I'll take it up with them.
