### ISSUE TITLE
Syntax Error when update capybara to 3.38.0

### ISSUE THREAD

**Issue by uday708** [teamcapybara/capybara#2626]
## Meta
Capybara Version:

Driver Information (and browser if relevant):

## Actual Behavior
gems/capybara-3.38.0/lib/capybara/session.rb:771: syntax error, unexpected ...
  def all(...)
          ^~~

Facing this issue.

Using Puma 6.0.0

## Steps to reproduce
While running test cases getting this issue.

**Comment by twalpole** [comment]
What version of ruby are you using? Capybara 3.38.0 has been out for quite some time, nobody else has reported this, and Capybaras own tests pass.  This is unlikely to be a Capybara issue, and more likely to be something in your system/setup

**Comment by uday708** [comment]
> What version of ruby are you using? Capybara 3.38.0 has been out for quite some time, nobody else has reported this, and Capybaras own tests pass. This is unlikely to be a Capybara issue, and more likely to be something in your system/setup

jruby 9.3.9

**Comment by ahorek** [comment]
capybara 3.38.0 requires ruby 2.7+ syntax, You shouldn't be able to install it on jruby 9.3.9. https://github.com/teamcapybara/capybara/blob/master/capybara.gemspec#L11

jruby 9.3.x is ruby 2.6.x compatible.
jruby 9.4.x is ruby 3.1.x compatible.

these combinations should work
jruby 9.3.9 + capybara 3.36.0
jruby 9.4.0 + capybara 3.38.0

please double check which versions you have.

**Comment by twalpole** [comment]
As indicated by `ahorek` this is a ruby version issue.  Why jruby let you install Capybara 3.38 when it states a minimum ruby version of 2.7+ is a question for the jruby team
