### ISSUE TITLE
Ruby 2.7 deprecation warning for has_no_text?

### ISSUE THREAD

**Issue by mltsy** [teamcapybara/capybara#2631]
## Meta
Capybara Version:
3.38.0

## Warning text:
DEPRECATION WARNING: [...]/capybara-3.38.0/lib/capybara/node/matchers.rb:726: warning: Passing the keyword argument as the last hash parameter is deprecated
[...]/capybara-3.38.0/lib/capybara/node/matchers.rb:691: warning: The called method `assert_no_text' is defined here
 (called from block (4 levels) in <top (required)> at [...]/spec/components/zip_coi/profile_banner_component_spec.rb:48)

## Steps to reproduce

I am simply calling `expect(subject).to have_no_content` with no arguments (and with deprecation warnings enabled using `RUBYOPTS="-W:deprecated"`).  I believe calling this on any element would produce this deprecation warning... 

In this case, the arguments being passed are: `args => []` and `options => {}`, and they're both being explicitly "splatted"...

It looks as though `assert_no_text` actually takes 3 arguments though, so I think what's happening is that `options` is being gobbled up by the `type_or_text` argument of `assert_no_text`, leaving the actual `opts` argument empty (regardless of what "options" are passed into `has_no_text?`).  In Ruby 3, this should fail because the `**options` argument being passed to `assert_no_text` would no longer be sufficient to fill the required positional argument `type_or_text`.

I'm guessing if nobody has complained, this maybe still works fine in Ruby 3, but I don't understand how, since it would be missing the required first argument.

**Comment by mltsy** [comment]
I *think* what we need to do is just pass `nil` as the first argument to `assert_no_text` here: https://github.com/teamcapybara/capybara/blob/e1547f0fda17b811993548a07fabe6d5a5eba993/lib/capybara/node/matchers.rb#L726

But I'm not too familiar with the innards of this gem, so I could be wrong.

**Comment by twalpole** [comment]
have_no_text/have_no_content are not meant to be called with no parameters, they are designed to be called with the text which is not supposed to exist in the element.

**Comment by twalpole** [comment]
If what you're actually trying to check for is that the element has empty text contents then you'd do either

    have_text("", exact: true)

or

    have_text(/^$/)

**Comment by mltsy** [comment]
Oh, so they are!  Well that works out nicely that it actually raises an exception in ruby 3 then doesn't it 😜  (Unless you're calling it wrong all along like us, and have to find out the hard way).  Thank you! 🙏
