### ISSUE TITLE
`all_text` performance characteristics and proposal

### ISSUE THREAD

**Issue by baweaver** [teamcapybara/capybara#2634]
## Overview

While benchmarking against Capybara specs I had noticed that flamegraphs were showing a significant amount of time on `gsub`, corresponding to the following code:

```ruby
def all_text
  text = driver.evaluate_script('arguments[0].textContent', self) || ''
  text.gsub(/[\u200b\u200e\u200f]/, '')
      .gsub(/[\ \n\f\t\v\u2028\u2029]+/, ' ')
      .gsub(/\A[[:space:]&&[^\u00a0]]+/, '')
      .gsub(/[[:space:]&&[^\u00a0]]+\z/, '')
      .tr("\u00a0", ' ')
end
```

...which can be found in either `Capybara::Selenium::Node` or `Capybara::RackTest::Node`.

## Areas of Interest

There were a few potential areas of interest with this code:

1. **Inline Regex construction** - Every call of `all_text` creates 4 regex objects which could be solved with hoisting constants
2. **`gsub` slowness** - `gsub` can be slower than methods like `squeeze` or `tr`, and for lead/trailing removals `sub` could be used instead
3. **Regex slowness** - In some of these cases `tr` and a literal string could be used instead, offering gains on regex usage
4. **Immutable Element** - Some parts of `Capybara::Node::Element` are immutable, or cache invalidation could be used, to not recompute text on every search
5. **Hot Path** - `all_text` is called _a lot_ which means that any improvements to this method will have dramatic performance impacts.

Given that and the flamegraph observations I decided to see how much of a difference this would make, and I believe it may be of interest to the Capybara team.

## Benchmarks

The following benchmarks include both the current variant of the `all_text` method as well as a variant which avoids usage of `gsub` and hoists constants:

```ruby
require "benchmark/ips"

NO_CACHING = true

class Node
  NON_BREAKING_SPACE = "\u00a0"
  LINE_SEPERATOR = "\u2028"
  PARAGRAPH_SEPERATOR = "\u2029"

  BREAKING_SPACES = "[[:space:]&&[^#{NON_BREAKING_SPACE}]]"

  SQUEEZED_SPACES = "\ \n\f\t\v#{LINE_SEPERATOR}#{PARAGRAPH_SEPERATOR}"
  LEADING_SPACES = /\A#{BREAKING_SPACES}+/
  TRAILING_SPACES = /#{BREAKING_SPACES}+\z/

  ZERO_WIDTH_SPACE = "\u200b"
  LEFT_TO_RIGHT_MARK = "\u200e"
  RIGHT_TO_LEFT_MARK = "\u200f"

  REMOVED_CHARACTERS = [ZERO_WIDTH_SPACE, LEFT_TO_RIGHT_MARK, RIGHT_TO_LEFT_MARK].join

  EMPTY_LINES = /[\ \n]*\n[\ \n]*/

  def initialize(text)
    @text = text
  end

  def all_text_original
    @text
      .gsub(/[\u200b\u200e\u200f]/, '')
      .gsub(/[\ \n\f\t\v\u2028\u2029]+/, ' ')
      .gsub(/\A[[:space:]&&[^\u00a0]]+/, '')
      .gsub(/[[:space:]&&[^\u00a0]]+\z/, '')
      .tr("\u00a0", ' ')
  end

  def all_text_optimized
    @text
      .delete(REMOVED_CHARACTERS)
      .tr(SQUEEZED_SPACES, ' ')
      .squeeze(' ')
      .sub(LEADING_SPACES, '')
      .sub(TRAILING_SPACES, '')
      .tr(NON_BREAKING_SPACE, ' ')
  end

  def all_text_cached
    @all_text ||= all_text_optimized
  end
end

HEADER_SEGMENT = <<~HTML
  <h1>And a Header#{Node::REMOVED_CHARACTERS}</h1>

  <p>#{Node::LINE_SEPERATOR}and some paragraph#{Node::PARAGRAPH_SEPERATOR}content</p>
HTML

DEMO_TEXT = <<~HTML



 <html>
  <strong>Here's some#{Node::NON_BREAKING_SPACE * 4}text</strong>


  #{HEADER_SEGMENT * 50}
 </html>
HTML

node = Node.new(DEMO_TEXT)

original_clean = node.all_text_original
new_clean = node.all_text_optimized

puts "Are the same?: #{original_clean == new_clean}", ''

Benchmark.ips do |benchmark|
  benchmark.report("Using `gsub` to clean") do
    node.all_text_original
  end

  benchmark.report("Avoiding `gsub` to clean") do
    node.all_text_optimized
  end

  benchmark.report("Cache the results assuming immutable element") do
    node.all_text_cached
  end unless NO_CACHING

  benchmark.compare!
end
```

Using no caching the results with a decently sized HTML string are:

```
Are the same?: true

Warming up --------------------------------------
Using `gsub` to clean
                       138.000  i/100ms
Avoiding `gsub` to clean
                       652.000  i/100ms
Calculating -------------------------------------
Using `gsub` to clean
                          1.372k (± 4.2%) i/s -      6.900k in   5.040737s
Avoiding `gsub` to clean
                          7.441k (± 3.9%) i/s -     32.600k in   5.069154s

Comparison:
Avoiding `gsub` to clean:     6441.2 i/s
Using `gsub` to clean:     1371.5 i/s - 4.70x  (± 0.00) slower
```

...and with caching, assuming the same element gets hit and does not recompute (yes, spurious assumption, but potentially interesting):

```
Are the same?: true

Warming up --------------------------------------
Using `gsub` to clean
                       142.000  i/100ms
Avoiding `gsub` to clean
                       677.000  i/100ms
Cache the results assuming immutable element
                         1.553M i/100ms
Calculating -------------------------------------
Using `gsub` to clean
                          1.436k (± 3.6%) i/s -      7.242k in   5.049498s
Avoiding `gsub` to clean
                          6.613k (± 3.2%) i/s -     33.173k in   5.021716s
Cache the results assuming immutable element
                         15.889M (± 3.8%) i/s -     80.741M in   5.089371s

Comparison:
Cache the results assuming immutable element: 15888670.0 i/s
Avoiding `gsub` to clean:     6613.1 i/s - 2402.62x  (± 0.00) slower
Using `gsub` to clean:     1436.2 i/s - 11063.06x  (± 0.00) slower
```

## Proposal

I can see an immediate case for hoisting regex constants out of these methods, and for replacing instances of `gsub` with more efficient methods for those usecases. I can get a PR out for this by the end of today.

The caching presents a very very interesting opportunity for performance improvements as not every node recomputes, and the invalidation case does not appear to be difficult to program for. Considering how often `all_text` is hit this could be exceptionally valuable.

I bring this up to get a few thoughts, but I'll see about getting the first case put into a PR as well as some tests to verify the behavior as I did not see explicit tests for `all_text` in the code.

Hot-editing this on our work monorepo via `bundle open` yielded fairly significant performance gains on Capybara tests.

**Comment by twalpole** [comment]
Caching is not an option here, as the whole point is that nodes will change.  I am curious what sort of tests you're test suite is made up of that this optimization makes any significant difference in runtime?  The vast majority of time in most test suites I've ever looked at is made up of waiting for browser interaction/retry rather than Capybaras string matching

**Comment by baweaver** [comment]
Yeah, caching, fair point. Even with invalidation that'd get complicated.

As far as why this makes a significant difference? That one is interesting. It's a React app, and it includes all the CSS and JS inline in `head` meaning that the whitespace cleaners hit all of it, causing it to try and clean up 500k characters. Certainly self-inflicted in that case, and the other patch is to use `find('body')` or `within('body')` instead of `page` on most things considering the content we likely want to test against is in the body.

In a way that makes this a red herring on perf optimization, and you're correct, in most reasonable cases it's probably not going to be an issue. In our case? Well not quite so lucky 😅

Thanks for taking a look! Will get all those changes in later tonight.
