### ISSUE TITLE
Capybara does not start until visiting a page

### ISSUE THREAD

**Issue by georgeu2000** [teamcapybara/capybara#2639]
## Meta
Capybara Version:
capybara (3.38.0)
selenium-webdriver 4.8.0
rspec (3.12.0)

## Expected Behavior
The app uses Chrome headless to save an image of the browser page. This is the feature I am testing.
In the specs, I do not `visit` a page. Just call the #export method of an object.
I expect chrome to load the page and save the image.

## Actual Behavior
This only works if I visit a page in the specs before calling the #export method.
Without visiting a page, the export fails with a blank page. I gather that the server has not started or is not accepting requests.

Config:
```
require 'capybara/rspec'

RSpec.configure do |config|
  Capybara.server = :puma
  Capybara.server_port = 8282
  Capybara.default_driver = :selenium_chrome
  Capybara.run_server = true
```

Is there a way to force Capybara to start running the server without visiting a page? Or is there some other config that is required?

**Comment by simi** [comment]
What about `Capybara.current_session.server.boot`?

**Comment by georgeu2000** [comment]
Yes, that solved the issue. I did not see it referenced in the docs.

Thank you!
