### ISSUE TITLE
Capybara 'webrick' server registration not compatible with rack 3

### ISSUE THREAD

**Issue by jrochkind** [teamcapybara/capybara#2640]
Capybara Version: 3.38.0

The capybara 'webrick' registration tries to require and use: `require 'rack/handler/webrick'`. 

https://github.com/teamcapybara/capybara/blob/48fe7018edbbf46c61f1c7632ff49fb8f1116f6c/lib/capybara/registrations/servers.rb#L8-L10

The file `rack/handler/webrick` is no longer at that location in rack in 3.0.  It looks like they have been removed to a separate `rackup` gem. https://github.com/rack/rack/pull/1937

This means if you try to use capybara with rack 3 and `Capybara.server = :webrick`, you get an error something like:

```
       cannot load such file -- rack/handler/webrick
       capybara-3.38.0/lib/capybara/registrations/servers.rb:8:in `block in <top (required)>
```

I discovered this because I run CI on a project against rails "edge" for early warnings, and Rails edge main branch seems to have recently allowed rack 3?

https://github.com/rails/rails/commit/859b526c5b9f1e516df3fc1b388c949da3fa9c4e

I'm a bit confused about what Rails is doing here. Current edge of `main` definitely allows rack 3, as far as what's in the gemspec.  And this commit saying "Merge PR 46594" seems to be committed: https://github.com/rails/rails/commit/1b44989521fe0ef274d85f24af6c5d6e69ac8463

But actual Rails PR 46594 "Allow rack >= 3 in Rails" is still in an open state? https://github.com/rails/rails/pull/46594. (And I think current Rails edge of `main` actually not only allows but possibly _requires_ rack 3.0.x, or at any rate I'm having trouble getting bundler to create a resolution with rack 2.x... I'm getting confused about what's going on in Rails land)

At any rate, regardless of what's going on in Rails, capybara is not only used with Rails, and rack 3.0 was [released in Nov 2022](https://rubygems.org/gems/rack/versions/3.0.0), and capybara gemspec allows any `rack >= 1.6.0` -- should `Capybara.server = :webrick` be fixed to work with rack 3?

**Comment by simi** [comment]
Per my understanding Rails edge is currently locked to rack 3.0+ and (sadly) not fully compatible yet. There is no easy way to use Rack 2.x+ for now.

If you would like to use rack 3 + webrick I think something like this should work (not tested):

```ruby
# Gemfile
gem 'rackup'
...
# test helper
Capybara.register_server :webrick do |app, port, host, **options|
  require 'rackup/handler/webrick'
  options = { Host: host, Port: port, AccessLog: [], Logger: WEBrick::Log.new(nil, 0) }.merge(options)
  Rackup::Handler::WEBrick.run(app, **options)
end

Capybara.server = :webrick
```

**Comment by jrochkind** [comment]
Ah, so rails edge is actually known to not actually be working properly?  So much for my plan of testing against Rails edge!  I had thought that Rails edge should always be in a working state, i guess I misunderstood!

Thanks for that demo code, i will try it out, super helpful!

But regardless of what Rails is doing or does -- should `Capybara.server = :webrick` already work with rack 3, since rack 3 is long-released, and capybara can be used without Rails too?

**Comment by dentarg** [comment]
Indeed Capybara needs to be updated (to either work with both Rack 2 and 3 or just one of them), the changes are in the Rack 3 upgrade guide: https://github.com/rack/rack/blob/7acfe495c907c4b219125309f97f7309e64a563c/UPGRADE-GUIDE.md#binrackup-rackserver-rackhandlerand--racklobster-were-moved-to-a-separate-gem

**Comment by skipkayhil** [comment]
> In the sense that it requires rack 3, but is known to not yet work with it?

Just wanted to add some clarification here: Rails edge allows either Rack 2.x or 3.x.

3.x was first allowed in rails/rails#47133 so that compatibility could be fixed across multiple PRs since the diff ended up really big in a single PR.

You should be able to prevent a Rack 3.x resolution with something like `gem "rack", "< 3"` in your Gemfile/gemspec. Rails itself does this to test against both major versions of Rack:

https://github.com/rails/rails/blob/c8190750f9d28b831f9b38b4ded8a3ee5b41fd9d/Gemfile#L72

> and capybara gemspec allows any `rack >= 1.6.0` -- should `Capybara.server = :webrick` be fixed to work with rack 3?

probably a good idea to add a `< 4` too once 3.x compatibility is fixed

**Comment by simi** [comment]
@skipkayhil ahh, thanks for clarification. I was a little confused since there was a lot of changes related to actionpack gemspec happening at short time.

**Comment by jrochkind** [comment]
(update: I at first had trouble getting a rack 2 resolution with `"rack", "< 3"` in a rails app -- bundler was refusing to resolve it, claiming conflicts.  But a rack 2 resolution was possible, bundler was just having trouble with it, and eventually after messing with it, adding and removing different restrictions from my gemfile, I got bundler to resolve with rack 2)

**Comment by twalpole** [comment]
Issue here is that Capybaras tests depend on sinatra which doesn't yet have a versions which supports rack 3, so we can't currently add rack 3 to the automated tests.

**Comment by twalpole** [comment]
Trial "fix" merged here - 2db340d184782912d0cd2e0fa3ab68b731c439dd - please give it a try and let me know - we can reopen if anything else is required

**Comment by jrochkind** [comment]
Thank you for the workaround commit for `:webrick` server in capybara!

simi's local workaround at https://github.com/teamcapybara/capybara/issues/2640#issuecomment-1409085067 also works fine for me, and is reasonable. 

The bigger concern is of course the block on capybara running CI for rack 3! Would it be useful to make an open issue here to track that, for people curious to find? And I wonder the most realistic path to resolving that.  The sinatra project does not currently seem to have resources for supporting rack 3. https://github.com/sinatra/sinatra/issues/1797   Swapping sinatra out in capybara CI may or may not be desirable/feasible.  (swapping it out for... roda? The roda gemspec does not specify any rack version requirements, not sure if that actually means it is fully supported for rack 3; I haven't found it's CI to see what it builds with; some posts in Github Discussions and Issues seem to suggest some people are using it with rack 3).

**Comment by dentarg** [comment]
@jrochkind Feel free to try out https://github.com/sinatra/sinatra/pull/1857 :-)

**Comment by twalpole** [comment]
@dentarg Looks like Rack::File was removed, and it needs to be Rack::Files::Iterator at https://github.com/dentarg/sinatra/blob/rack-3/lib/sinatra/base.rb#L294 now -- not sure where else in the code that may affect

**Comment by dentarg** [comment]
@twalpole Yes, but not until Rack 3.1: https://github.com/rack/rack/pull/1811 (will try to address that too)

**Comment by twalpole** [comment]
@dentarg Files is available in Rack 2.x too --- it's just that File was an alias of it --- should be able to just swap to using Files in both 2 and 3

**Comment by dentarg** [comment]
I noticed
