### ISSUE TITLE
JRuby 9.4.0.0 crash

### ISSUE THREAD

**Issue by HoudayerPierre** [teamcapybara/capybara#2645]
I'm not able to run capybara under JRuby 9.4.0.0

## Meta
Capybara Version:
capybara-3.38.0
Driver Information (and browser if relevant):
Windows, java version "17.0.5"
[JRuby 9.4.0.0](https://www.jruby.org/files/downloads/9.4.0.0/index.html)
Installed capybara in JRuby jar like this :
```
java -jar jruby-complete-9.4.0.0.jar -S gem install -i ./allmylibs capybara
jar uf jruby-complete-9.4.0.0.jar -C allmylibs .
```

## Expected Behavior
Run ruby script `require 'capybara'` without crash

## Actual Behavior
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa255f1aa4, pid=25596, tid=8240
#
# JRE version: Java(TM) SE Runtime Environment (17.0.5+9) (build 17.0.5+9-LTS-191)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.5+9-LTS-191, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [racob-x64.dll+0x1aa4]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\sikuli\hs_err_pid25596.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

## Steps to reproduce
Download JRuby 9.4.0.0
Install capybara gem
create and run the ruby script :
`require 'capybara'`

**Comment by twalpole** [comment]
Not really sure how this is a bug in Capybara -- seems more like a bug in jRuby.  Capybara runs fine with Ruby 3.1 which jRuby 9.4.0.0 is claiming compatibility with
