### ISSUE TITLE
find(:link_or_button, text) finds text based on all text (including invisible text)

### ISSUE THREAD

**Issue by timdiggins** [teamcapybara/capybara#2648]
## Meta
Capybara Version:
3.38.0

Driver Information (and browser if relevant):

* selenium-webdriver (4.8.0)
* /usr/bin/google-chrome Google Chrome 110.0.5481.177 
* /usr/local/bin/chromedriver ChromeDriver 110.0.5481.77 `(65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839})`

## Expected Behavior

Sometimes on CI (and very occasionally on my much more powerful laptop), a spec which is testing a rails app which has an angularjs component fails. 

The failure is when it is testing for 

```ruby
    expect(page).not_to have_selector(:link_or_button, "Save and Issue")
```

i would expect it (in this context) to wait (up to the Capybara wait time however defined) until the link or button which is labelled "Save and Issue" is changed (via an angularjs digest) to "Issue" and then be positive.

An alternative is that it for some reason fails (and times out for example) and then says that it did find the link or button with text "Save and Issue"

## Actual Behavior

```
     Failure/Error: expect(page).not_to have_selector(:link_or_button, "Save and Issue")
       expected not to find visible link or button "Save and Issue", found 2 matches: "Issue", "Issue"
```

What I don't understand here is why or how it can generate this error message. It's saying "I'm not expecting to find a match "Save and Issue", but found two matches - neither of which actually match" (likewise the png screenshot shows a button labelled "Issue").  I guess it's theoretically possible that it reaches the max time of wait and **at exactly that time** the angularjs completes its digest and it outputs the text, which by that time has changed? 
Tthis seems so unlikely (and it wouldn't repeat multiple times but not every time)

## Steps to reproduce

I don't think this is easily reproducible (it happens about 50% of the time on CI, but here's the test code:

```ruby
    expect(page).to have_selector(:link_or_button, "Save and Issue")
    click_on "Save and keep editing" # actually I have a new mechanism for doing this, see notes below
    expect(page).not_to have_selector(:link_or_button, "Save and Issue") # < - fails here
    expect(page).to have_selector(:link_or_button, "Issue")
```

Ok here's the haml (i can translate into html if helpful)  just to show that basically it's the same button, but the text should change from Save and Issue to Issue when the form goes from unsaved to saved ($pristine).

```haml
.form-group(ng-show='quote.isDraft() && quote.id')
    %button.btn.btn-primary{"ng-click": 'issue(quoteForm)', "ng-disabled": '!quoteForm.$valid'}
      %span(ng-show="!quoteForm.$pristine")
        Save and
      Issue
```

## Notes

Just FYI - I've changed `click_on "Save and keep editing"` to something like `execute_script("document.querySelector('#save-and-keep-editing-button').click()` because I was having periodic failures of clicking that button (which resulted in a authentic failure of `    expect(page).not_to have_selector(:link_or_button, "Save and Issue")`, because the js behaviour hadn't attached to the html button by the time of too-fast clicking). However I believe that change isn't related to this problem (and have seen this problem occasionally too even with clik_on, it's just become a lot more frequent now I've removed the chance of an authentic failure, if that makes sense)

**Comment by nflorentin** [comment]
I think you should use the negative form of the selector instead of using the negative matcher.

See doc for explanation : https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends

**Comment by timdiggins** [comment]
@nflorentin thanks for the link, but I don't think I agree. It explicitly says:

> Capybara's RSpec matchers, however, are smart enough to handle either form. The two following statements are functionally equivalent:
> 
> expect(page).not_to have_xpath('a')
> expect(page).to have_no_xpath('a')

**Comment by timdiggins** [comment]
I've actually worked out what the problem is using a debug session:

Given this visible output:
<img width="218" alt="Issue_button" src="https://user-images.githubusercontent.com/18395/222717192-d09aa10d-3eb0-4eaa-8720-fcd7c7ff2196.png">

With this html:

```html
<button class="btn btn-primary" ng-click="issue(quoteForm)" ng-disabled="!quoteForm.$valid">
  <span ng-show="!quoteForm.$pristine" class="ng-hide">
    Save and
  </span>
  Issue
</button>
```

and this relevant css: 

```css
[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate) {
    display: none !important;
}
```

With this active in computed classes.

I would expect 

`page.has_selector?(:link_or_button, "Save and Issue")` not to be true, but it is true. 

Meanwhile:

`page.has_content?("Save and")` returns false and
`page.all(:link_or_button, "Save and Issue").map(&:text)` returns `["Issue", "Issue"]

**Comment by timdiggins** [comment]
So I think the issue (for me) is that the `has_selector?(:link_or_button, text)` is matching on all text rather than just visible text.

**Comment by nflorentin** [comment]
Oh I see, you are right, I read a bit to quick.

**Comment by timdiggins** [comment]
Based on this discussion and further tests, I've got a much simpler test case:

Given html

```html
<button name="whatever" value="something">
  Some
  <span style="display:none;">very long</span>
  name
</button>

<a href="#whatever">
  Some
  <span style="display:none;">very long</span>
  link
</a>
```

I would expect the following tests to succeed:

```ruby
    it "can find button by visible text" do
      expect(page).to have_button("Some name")
    end
    it "won't find button by invisible text" do
      expect(page).not_to have_button("Some very long name")
    end
    it "can find link by visible text" do
      expect(page).to have_link("Some link")
    end
    it "won't not find link by invisible text" do
      expect(page).not_to have_link("Some very long link")
    end
```

but they all fail:

```
  1) can find button by visible text
     Failure/Error: expect(page).to have_button("Some name")
       expected to find button "Some name" that is not disabled but there were no matches

  2) won't find button by invisible text
     Failure/Error: expect(page).not_to have_button("Some very long name")
       expected not to find visible button "Some very long name" that is not disabled, found 1 match: "Some name"
  
  3) can find link by visible text
     Failure/Error: expect(page).to have_link("Some link")
       expected to find link "Some link" but there were no matches

  4) won't not find link by invisible text
     Failure/Error: expect(page).not_to have_link("Some very long link")
       expected not to find visible link "Some very long link", found 1 match: "Some link"
```

whereas this succeeds:

```ruby
    it "will correctly find" do
      expect(page).to have_selector(:button, text: "Some name")
      expect(page).to have_selector(:link, text: "Some link")
      expect(page.find("button[name=whatever]").text).to eq("Some name")
      expect(page.find("a[href='#whatever']").text).to eq("Some link")
    end
```

**Comment by twalpole** [comment]
Correct, the `:text` option has CSS/visibility applied to it, the locator does not since it's implemented via XPath.  This is behaving as designed.  If you need visibility of your button text you can do something like

    expect(page.to have_button(text: "Some name"))

**Comment by timdiggins** [comment]
@twalpole thanks for the clarification
