### ISSUE TITLE
Spec folder in gem

### ISSUE THREAD

**Issue by sreid99** [teamcapybara/capybara#2649]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:3.38.0

Driver Information (and browser if relevant):

## Actual Behavior

Found a possible small error when running Trivy on a docker image :
 
  /usr/local/bundle/gems/capybara-3.38.0/spec/fixtures/key.pem (secrets)
  Total: 1 (HIGH: 1, CRITICAL: 0)
  HIGH: AsymmetricPrivateKey (private-key)

Doubt the key itself is a real issue, but should the spec folder be included in the gem ?

**Comment by twalpole** [comment]
Yes, the spec folder is in the gem so 3rd party drivers can run the test suite against them.
