### ISSUE TITLE
Possible race condition issues with turbo causing flaky tests?

### ISSUE THREAD

**Issue by tomekchime** [teamcapybara/capybara#2651]
## Meta
Capybara Version: 3.38.0

Driver Information (and browser if relevant):

**google-chrome version:** Google Chrome 110.0.5481.177
**chromedriver version:** ChromeDriver 110.0.5481.77
**selenium-webdriver:** 4.6.1

## Expected Behavior

Capybara waits for fetch based redirect executed by Turbo

## Actual Behavior

Capybara does not wait and instead will fail the expectation if the redirect doesn't happen fast enough.

## Steps to reproduce

This is unfortunately pretty difficult to reproduce because of the flakiness. However, I've gathered some screenshots and will share the spec and relevant code here.

Below is the screenshot taken from the failed system spec. It shows the blue page loading indicator is ~15% through at the time rspec throws a failure on the spec for the redirect:

![spec_failure_screenshot](https://user-images.githubusercontent.com/95378212/223849501-76ea2a56-aa0f-47a5-bb87-3d8907465cca.png)

As can be seen in the network tools, the redirect is being intercepted by Turbo and made via a JS Fetch:

![Screenshot 2023-03-08 at 2 47 50 PM](https://user-images.githubusercontent.com/95378212/223849780-26533e58-8eb5-452d-bc87-5639021166be.png)

Failing spec line:

```
   Failure/Error: expect(page).to have_current_path(access_request_path(access_request))
    expected "/approvals" to equal "/access_requests/690"
```

from this spec:
```
    it "approver can view details of a pending request" do
      access_request = create(:access_request)
      access_request.okta_group.approval_permissions.create(user: approver)
      login_as(approver)

      visit approvals_path
      click_on "Show details"

      expect(page).to have_current_path(access_request_path(access_request))
    end
```

**Comment by tomekchime** [comment]
Here's another example, this time with `have_content`

```ruby
    it "prompts for a reason before denying the access request" do
      stub_moveworks_send(status: 204)
      access_request = create(:access_request)
      access_request.okta_group.approval_permissions.create(user: approver)

      login_as(approver)
      visit access_request_path(access_request)
      click_on "Deny"
      within "#denial-form" do
        fill_in("reason", with: "a good reason")
        click_on "Deny"
      end

      expect(page).to have_content("Access request was successfully denied")
      expect(page).to have_content("Denied")
    end
```

```
     Failure/Error: expect(page).to have_content("Access request was successfully denied")
       expected to find text "Access request was successfully denied" in ...
```

Note, that putting a `sleep(2)` above `expect(page).to have_content("Access request was successfully denied")` seems to make the issue go away

![Screenshot 2023-03-08 at 3 26 14 PM](https://user-images.githubusercontent.com/95378212/223854425-6a253d00-01c6-41fd-a521-71bc19bd992a.png)

**Comment by twalpole** [comment]
Capybara waits up to Capybara.default_max_wait_time seconds. What is yours set to?  You may need to increase it depending on your app/hardware, or pass the `wait` option to your matchers to extend on a test by test basis
