### ISSUE TITLE
:capabilities driver parameter deprecation warning

### ISSUE THREAD

**Issue by kengallego** [teamcapybara/capybara#2657]
## Meta
Capybara gem Version:
`3.38.0`
Driver Information:
`:selenium_chrome_headless`

## Expected Behavior
No warnings

## Actual Behavior
`
2023-03-29 14:35:26 WARN Selenium [DEPRECATION] [:capabilities] The :capabilities parameter for Selenium::WebDriver::Chrome::Driver is deprecated. Use :options argument with an instance of Selenium::WebDriver::Chrome::Driver instead.
`

## Steps to reproduce
Run `rspec` with Capybara and `:selenium_chrome_headless` as javascript driver. `Capybara.default_driver` is `rack_test`

## Workaround
Looking at [this line in the code](https://github.com/teamcapybara/capybara/blob/5d28453d8fe3d30f5a69ed984a28e9357e55f070/lib/capybara/registrations/drivers.rb#L33) i see where `:capabilities` is being called. If I inverse the `if` clause, WORKS. So it looks like this:

`options_key = Capybara::Selenium::Driver::CAPS_VERSION.satisfied_by?(version) ? :options : :capabilites`

## Question
I imagine that changing that line of code will make something different somewhere so I don't think my workaround is the final solution. But also is strange that it shows a deprecation warning when the `selenium-webdriver` gem version is up to date and it does not show when it is an older one.

**Comment by twalpole** [comment]
This should have been fixed in the master branch on Fed 12 by https://github.com/teamcapybara/capybara/commit/44c595eccf78474fd1472b996b81f51bd519b55d

**Comment by kg-currenxie** [comment]
Still seeing this in 3.39.1

```

group :test do
  gem 'capybara', '3.39.1'
  gem 'database_cleaner', '2.0.2'
  gem 'guard-rspec', '4.7.3', require: false
  gem 'magic_test', git: 'https://github.com/bullet-train-co/magic_test.git', tag: 'v0.1.0'
  gem 'pundit-matchers', '2.3.0'
  gem 'rspec-rails', '6.0.1'
  gem 'webdrivers', '~> 5.0', require: false # Selenium & friends for easy headless testing
  gem 'super_diff', '0.10.0'
end
```

```
be rspec
...........2023-05-30 21:34:03 WARN Selenium [:capabilities] [DEPRECATION] The :capabilities parameter for Selenium::WebDriver::Chrome::Driver is deprecated. Use :options argument with an instance of Selenium::WebDriver::Chrome::Driver instead.
.

Finished in 2.9 seconds (files took 1.89 seconds to load)
12 examples, 0 failures
```

**Comment by twalpole** [comment]
That's not coming from Capybara, you need to check whether you've written your own driver registration, are using the one provided by rails, etc

**Comment by kg-currenxie** [comment]
> That's not coming from Capybara, you need to check whether you've written your own driver registration, are using the one provided by rails, etc

Oh I see. I heard that rails uses capybara under the hood in system tests. 😬

**Comment by twalpole** [comment]
@kg-currenxie If you're just using the standard rails system test configuration then you probably just need to update to rails 7.0.5 - https://github.com/rails/rails/releases/tag/v7.0.5 - for the selenium registration change in Action Pack

**Comment by kg-currenxie** [comment]
Nice! Thanks for that :) I'm on `7.0.4.3`. Will try tonight <3

**Comment by kg-currenxie** [comment]
Confirmed, 7.0.5 fixed it
