### ISSUE TITLE
wrong number of arguments (given 4, expected 3) when submitting RackTest form

### ISSUE THREAD

**Issue by jianbocui** [teamcapybara/capybara#2658]
I've seen this close issue (https://github.com/teamcapybara/capybara/pull/2611), but still confused how does the submit method work, the driver `submit` method takes 3 arguments, but form `submit` caller gives 4 arguments.
Regardless if I pass a submit button, it would fail on wrong number of args. The fix seems necessary.

Capybara::RackTest::Form.new(page.driver, find('form').native).submit(button)

```
# From class
def submit(button)
    action = button&.[]('formaction') || native['action']
    method = button&.[]('formmethod') || request_method
    driver.submit(method, action.to_s, params(button), content_type: native['enctype'])
  end
```
```
# Driver class
  def submit(method, path, attributes)
    browser.submit(method, path, attributes)
  end
```
https://github.com/teamcapybara/capybara/blob/48fe7018edbbf46c61f1c7632ff49fb8f1116f6c/lib/capybara/rack_test/driver.rb#L53

https://github.com/teamcapybara/capybara/blob/a3ff5514f40f3af0ec6655354d3596f6d9ea8964/lib/capybara/rack_test/form.rb#L57

**Comment by twalpole** [comment]
It works because when Capybara uses those classes `driver` is an instance of Capybara::RackTest::Browser, not an instance of Capybara::RackTest::Driver which you're assuming it is

**Comment by jianbocui** [comment]
Thank you @twalpole
