### ISSUE TITLE
`page.driver.go_back` go back to prev url without query params

### ISSUE THREAD

**Issue by malinowskil123** [teamcapybara/capybara#2660]
## Meta
Capybara Version :
3.39.0
Driver Information (and browser if relevant):
selenium-webdriver 4.8.6, webdrivers 5.2.0

## Expected Behavior
```rb
page.driver.go_back # should go back to previous page with query params intact
```

## Actual Behavior
Loses query params just goes back to the pervious urls path

**Comment by twalpole** [comment]
When using the selenium driver Capybara just calls selenium which calls the browsers driver (chromedriver, etc) which tells the browser to go back. There are no parameters to be passed, so if it's not working as you expect that would be a bug in the browser or browser driver. Are you sure you're using selenium for this test? Can you provide an example which shows your issue?

**Comment by twalpole** [comment]
Closing due to lack of response
