### ISSUE TITLE
Bug with `visible`

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2661]
## Meta
Capybara Version:
3.39.0
Driver Information (and browser if relevant):
Selenium 4.8.6 on Chrome 112

## Expected Behavior
The example below prints `false`, `false`, `true`. Which is rather unexpected as the requested `ul` (which is there as seen from the HTML and from the last line) should either be visible or invisible. But the first two lines both return `false`. The third one (which checks `visible: :all`) works fine. I believe that's a bug. The correct output should be `false`, `true`, `true`.

## Actual Behavior
See `Expected Behavior`.

## Steps to reproduce
```rb
require 'capybara/dsl'
require 'selenium/webdriver'

html = DATA.read
app = proc { [200, { 'Content-Type' => 'text/html' }, [html]] }

sess = Capybara::Session.new(:selenium_chrome, app)
sess.visit('/')
puts sess.has_css?('ul', text: /Deutsch.*English/, visible: :hidden)
puts sess.has_css?('ul', text: /Deutsch.*English/, visible: :visible)
puts sess.has_css?('ul', text: /Deutsch.*English/, visible: :all)

__END__
<html>
  <body>
    <ul>
      <li>
        Deutsch
      </li>
      <li>
        English
      </li>
    </ul>
  </body>
</html>
```

**Comment by twalpole** [comment]
@boris-petrov Actually the first two outputs of `false`, `false` are 100% correct, the third one however may have an issue - The first two are correct because your regex doesn't match to the text.  This is because `.` doesn't match a newline unless you enable multiline mode `/Deutsch.*English/m` -- Why the third one matches is the real question

**Comment by twalpole** [comment]
The third one matches because in :all mode the text is normalized to match against hidden and visible elements, so while it may not be 100% correct I don't really know if it's worth attempting to do anything different there, since this seems like a pretty rare edge case

**Comment by twalpole** [comment]
Note that :all is not a combination of `visible` and `hidden`  -- it's `ignore visibility` which is subtly different

**Comment by twalpole** [comment]
A better example of this behavior since it doesn't involve the subtleties of regexp is what should the following element match against in each of your three example modes

 `<div>this <span style="display: none">is </span>text</div>`

**Comment by boris-petrov** [comment]
I see, thanks for the response! You're absolutely correct for everything.
