### ISSUE TITLE
Finding table row

### ISSUE THREAD

**Issue by inkstak** [teamcapybara/capybara#2664]
After digging into Capybara to find a way to select a link in a table row, i've found a `:table_row` selector was implemented in #2168

It works when used in assertions:

```ruby
expect(page).to have_selector(:table_row, "Name" => "Elliot Alderson") do |row|
  expect(row).to have_link("Show page")
  
  within row do
    click_on "Show page"
  end
end
```

But it doesn't work as a locator in `find()` or `within()`:

```ruby
within :table_row, "Name" => "Elliot Alderson" do |row|
  click_on "Show page"
end

# NoMethodError:
#   undefined method `shift' for nil:NilClass
#   [..]/capybara-3.39.0/lib/capybara/selector/definition/table_row.rb:15:in `block (2 levels) in <top (required)>'
#   [..]/capybara-3.39.0/lib/capybara/selector/selector.rb:63:in `instance_exec'
#   [..]/capybara-3.39.0/lib/capybara/selector/selector.rb:63:in `call'
#   [..]/capybara-3.39.0/lib/capybara/queries/selector_query.rb:54:in `initialize'
#   [..]/capybara-3.39.0/lib/capybara/node/finders.rb:60:in `new'
#   [..]/capybara-3.39.0/lib/capybara/node/finders.rb:60:in `find'
#   [..]/capybara-3.39.0/lib/capybara/session.rb:773:in `find'
#   [..]/capybara-3.39.0/lib/capybara/session.rb:362:in `within'
#   [..]/capybara-3.39.0/lib/capybara/dsl.rb:52:in `call'
#   [..]/capybara-3.39.0/lib/capybara/dsl.rb:52:in `within_element'
#   [..]/capybara-3.39.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
```

**Comment by twalpole** [comment]
What version of Capybara are you using -- from that error the selector isn't being correctly passed the locator ("Name" => "Elliot Alderson") as a Hash which could be a ruby v 2/3 issue around parameter passing.  try

    within(:table_row, { "Name" => "Elliot Alderson" }) do ...

to see if that correctly passes the parameter

**Comment by inkstak** [comment]
You're right, using an Hash instead of keyword arguments works.

I will try to find a way to solve this issue and pull a request.
Otherwise I will come back in a few hours.

**Comment by inkstak** [comment]
Not sure I can or should fix this :

* all queries rely on [SelectorQuery](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/queries/selector_query.rb) which expects locators to be present in arguments and not in keyword arguments.

* the `:table_row` selector is the only one using Hash as a locator and is still undocumented.

* the RSpec matcher accepts locators as keyword arguments because of these two lines : [have_selector.rb:13 & have_selector.rb:14](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec/matchers/have_selector.rb#L13). Keyword arguments passed to the matcher are pushed into regular arguments.

The ambiguity is more about the RSpec matcher and not about `find` or `within`.
I'll close this issue now.
