### ISSUE TITLE
Capybara::RackTest::Form.submit throws exception using Capybara::RackTest::Driver

### ISSUE THREAD

**Issue by cschilbe** [teamcapybara/capybara#2670]
## Meta
Capybara Version: 3.39.1
Driver Information (and browser if relevant): rack-test 3.39.1

## Expected Behavior
Calling Capybara::RackTest::Form.new(page.driver, form.native).submit({}) when driver is Capybara::RackTest::Driver should not throw an exception.

## Actual Behavior
Exception is thrown because of change in this commit https://github.com/teamcapybara/capybara/commit/a3ff5514f40f3af0ec6655354d3596f6d9ea8964 where it is assumed that the driver will be a browser.

```
     ArgumentError:
       wrong number of arguments (given 4, expected 3)
     # /bundle/ruby/3.1.0/gems/capybara-3.39.1/lib/capybara/rack_test/driver.rb:53:in `submit'
     # /bundle/ruby/3.1.0/gems/capybara-3.39.1/lib/capybara/rack_test/form.rb:57:in `submit'
```

## Steps to reproduce
Capybara::RackTest::Form.new(page.driver, form.native).submit({}) with Capybara::RackTest::Driver

**Comment by twalpole** [comment]
Please search previous issues - this is as designed. If you are testing behavior that requires JS use a JS capable driver
