### ISSUE TITLE
NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by crespire** [teamcapybara/capybara#2690]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.39.2

Driver Information (and browser if relevant): Selenium Webdriver 4.10.0 with Chrome latest.

## Expected Behavior
Tests can navigate via path helpers

## Actual Behavior

```bash
     Failure/Error: some_path
     
     NoMethodError:
       undefined method `empty?' for nil:NilClass
     # ./app/components/some_component.rb:26:in `back_link'
     # ./app/components/some_component.html.erb:14:in `call'
     # ./spec/components/some_component_spec.rb:13:in `block (2 levels) in <top (required)>'
```

## Steps to reproduce

I am not sure how to reproduce, as the spec was working yesterday. I suspect this has to do with the new Chormium for Testing changes, but I have already updated `selenium-webdriver` and `capybara` (per https://github.com/titusfortner/webdrivers/issues/247) - unsure what next steps to take here. Any path method in my system test is throwing this error. There are a few throwing `NoMethodError: undefined method 'merge' for nil:NilClass` as well. I suspect it's a request level issue.

**Comment by twalpole** [comment]
From the stack trace posted this doesn’t appear to have anything to do with Capybara.

**Comment by crespire** [comment]
Yeah, the stack trace is not really helpful. I think there is an issue with the webdriver/capybara interaction. Let me see if I can do some more digging.

**Comment by twalpole** [comment]
From the new backtrace this still has nothing to do with Capybara,  I would suggest reverting the gems to the previous versions and update one gem at a time until you find out which gems update causes the issue, and then read the upgrade guide for whichever gem it is.
