### ISSUE TITLE
When I'm using click on is not redirecting

### ISSUE THREAD

**Issue by pargara** [teamcapybara/capybara#2692]
## Meta
Capybara Version:
 3.39.2 
Driver Information (and browser if relevant):
selenium/standalone-firefox:114.0

## Expected Behavior

When a specific button is clicked the user should be redirected to a third party page

## Actual Behavior
Is not redirecting to other page

## Steps to reproduce
My app is in a docker container and im using Capybara to fill a form and then clicking on the final button it should redirect to another page but is not working, im using click_on "Enviar Liquidación a mi correo". Any ideas?

**Comment by twalpole** [comment]
If it's not raising an error then it is clicking the button and you have a bug in your app. Check your browsers console when running in test or production mode (not development) for JS errors
