### ISSUE TITLE
Add a has_test_id? matcher

### ISSUE THREAD

**Issue by tmaier** [teamcapybara/capybara#2694]
I want to use the test_id feature more.
I configured `Capybara.test_id = "data-testid"`

I see that there is support for test ids in many matchers.
(In geeneral, it would be great to have support for it in all matchers.)

I want to test, if a certain element with a test id exists.
Currently, I can only test for it with the `has_css` matcher.
like `expect(page).to have_css("[data-testid='my-id']"))`

This is tedious to write and it hardcodes `data-testid`.

I would prefer to have a dedicated matcher for test_id called `has_test_id?`
One could use it like this: `expect(page).to have_test_id('my-id')`

Pseudo code implementation:

```ruby
def has_test_id?(test_id)
  has_css?("[#{Capybara.test_id}='#{test_id}']")
end
```

## Meta
Capybara Version: capybara (3.39.2)
Driver Information (and browser if relevant):
N/A

**Comment by twalpole** [comment]
You can use Capybara.add_selector to define any custom selectors you like in your project

**Comment by tmaier** [comment]
Fair enough.

I solved it with some Rspec matchers. They are called `have_test_id` and `have_test_id_and_css`.
I hope they are helpful for someone. See my blog post introducing them: <https://tobiasmaier.info/posts/2023/06/19/rspec-capybara-data-testid.html>
