### ISSUE TITLE
Feature spec after showing the result it got stuck and never completed.

### ISSUE THREAD

**Issue by uday708** [teamcapybara/capybara#2695]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.36.0

Driver Information (and browser if relevant):

Jruby v 9.4.2.0

Using DatabaseCleaner v 2.0.1

## Expected Behavior
Feature spec should complete  after showing the result.
## Actual Behavior
For some reason only for feature spec after showing the result it got stuck and never completed.

```
3 examples, 0 failures

Randomized with seed 5766
```
**Stuck here**

**Comment by twalpole** [comment]
Not sure how this is a Capybara issue.  There's no way to reproduce, no stack trace, and no other information which would be useful to start debugging. If you can provide some info that shows this is an issue in Capybara rather than Rspec, rack, selenium, chrome driver, etc, etc we can reopen

**Comment by uday708** [comment]
because things working fine with version 3.26.1
