### ISSUE TITLE
`Rack::Handler is deprecated` warning when using Rails 7.1 beta and Rack 3

### ISSUE THREAD

**Issue by mattbrictson** [teamcapybara/capybara#2705]
## Meta

- capybara 3.39.2
- rack 3.0.8
- rails 7.1.0.beta1
- selenium-webdriver 4.12.0
- ChromeDriver 116.0.5845.96
- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]

Using the following system test case config:

```ruby
class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium,
    using: (ENV["SHOW_BROWSER"] ? :chrome : :headless_chrome),
    screen_size: [1400, 1400] do |options|
      options.add_argument("--disable-dev-shm-usage")
      options.add_argument("--no-sandbox")
    end

  setup do
    Capybara.default_max_wait_time = 2
    Capybara.disable_animation = true
    Capybara.server = :puma, {Silent: true}
  end
end
```

## Expected Behavior

Capybara can be used with Rails 7.1 and Rack 3 without warnings.

## Actual Behavior

The following warning is printed to stderr:

```
Rack::Handler is deprecated and replaced by Rackup::Handler
```

## Steps to reproduce

Upgrade a Rails app to Rails 7.1.0.beta1 and run a system test that uses Capybara.

```
$ bin/rails test:system
Running 4 tests in a single process (parallelization threshold is 50)
Run options: --seed 27755

# Running:

Rack::Handler is deprecated and replaced by Rackup::Handler
....

Finished in 4.122453s, 0.9703 runs/s, 12.1287 assertions/s.
4 runs, 50 assertions, 0 failures, 0 errors, 0 skips
```

## Workaround

The warning goes away if Rack is pinned at 2.x. (Rails 7.1 beta works with Rack 2 and Rack 3.)

```ruby
gem "rack", "< 3"
```

**Comment by Fjan** [comment]
Thanks for doing a PR! If you came here by Googling the warning now that Rails 7.1 is released, you could just drop this in `app/config/initializers` to get rid of the deprecation messages while waiting for this PR to get merged:
```ruby
if Rails.env.test?
  require 'rackup'
  module Rack
    Handler = ::Rackup::Handler
  end
end
```

**Comment by gap777** [comment]
This is great! Can we get a release or tag generated to include this?
