### ISSUE TITLE
Capybara Selenium Driver compatible issue chrome browser

### ISSUE THREAD

**Issue by 9211ali** [teamcapybara/capybara#2717]
Capybara selenium driver version issue with chrome browser, I am working on rspec **features** testing. When run feature test cases, chrome browser is opened.
**Problem**
For running feature test cases, I need to downgrade my current chrome browser to compactible with selenium driver. For instance, I need to downgrade my chrome browser version (118.0.5993.70-1) to (104.0.5112.101-1). 

What is other way to run feature test without selenium driver compactible with chrome issue.

**Comment by adam-hampton-sp** [comment]
I believe we are seeing this issue as well:

```
     1.2) Failure/Error: Unable to infer file and line number from backtrace

          Selenium::WebDriver::Error::UnknownError:
            unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
              (Session info: headless chrome=119.0.6045.159)
          # #0 0x55aeb7f99fb3 <unknown>
          ...
```

Related libs/versions:
 - Ruby gem capybara (3.39.2) 
 - Ruby gem capybara-selenium (0.0.6)
 - Ruby gem selenium-webdriver (4.15.0)
 - Environment ubuntu-20.04, amd64

**Comment by twalpole** [comment]
Capybara is not responsible for you having the matching chrome and web driver, that is something selenium does.
