### ISSUE TITLE
Add HTML details click helper

### ISSUE THREAD

**Issue by bkuhlmann** [teamcapybara/capybara#2722]
## Meta
Capybara Version: 3.39.2
Driver Information (and browser if relevant): Cuprite 0.15.0 with Firefox 120.0.1 (64-bit)

## Expected Behavior

Hello. :wave: I would like to suggest adding HTML [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element support via a `click_details` helper which could work in the same fashion as `click_link` and `click_button`. Example:

``` ruby
click_details ".demo"
expect(page).to have_content("Demo")
```

## Actual Behavior

At the moment, to make this work, you can use the following:

``` ruby
# Click (open)
page.execute_script %(document.querySelector(".demo").setAttribute("open", ""))
expect(page).to have_content("Demo")

# Click (close)
page.execute_script %(document.querySelector(".demo").removeAttribute("open"))
expect(page).not_to have_content("Demo")
```

## Steps to reproduce

You can use this DOM snippet to test the above:

``` html
<details class="demo">
  <summary>Test</summary>
  <p>Demo</p>
</details>
```

**Comment by twalpole** [comment]
You can just do `page.find('details.demo').click`, I'm not really sure why you're using `execute_script`

**Comment by bkuhlmann** [comment]
Thanks. I thought I had tried using `page.find` earlier but see that works too. Regardless, my main point was that having `click_details` seemed a like bit of syntactic sugar in terms of making HTML details elements a tad bit  easier to work with. Anyway, that was my initial thought and why I wanted to suggest this feature.
