### ISSUE TITLE
Ruby 3.2.2 and Rails 7.1.2 Issues

### ISSUE THREAD

**Issue by RailsCod3rFuture** [teamcapybara/capybara#2732]
## Meta
Capybara Version:
3.39.2
Driver Information (and browser if relevant):
cuprite/chrome-headless (latest)

## Expected Behavior
Javascript should load alongside CSS when rendering page & elements will be accessible by capybara finders

## Actual Behavior
CSS loads but Javascript doesn't and capybara is failing with the error below

```
Capybara::Ambiguous:
    Ambiguous match, found 2 elements matching visible link or button "Element"
```

## Steps to reproduce
1. Required gems: Latest sprockets-rails, terser, sass-rails, psych < 4, capybara, cuprite, webdrivers, capybara-screenshot
2. Create a test with some javascript/jquery elements
3. View the screenshot and see that no js elements are hidden

**Comment by RailsCod3rFuture** [comment]
I turned on JS errors and I'm getting an error for Jquery not being present.

**Ferrum::JavaScriptError: ReferernceError: $ is not defined**

**Comment by huynghodfords** [comment]
@RailsCod3rFuture Did you solve this problem? I'm facing the same issue.

**Comment by RailsCod3rFuture** [comment]
It was related to jquery not being available for cuprite. Add a reference to your jquery file for the extensions option for cuprite & any other mandatory file for your ui. Most should work after the jquery reference is set.
