### ISSUE TITLE
Full page screenshot not working

### ISSUE THREAD

**Issue by SofiaSousa** [teamcapybara/capybara#2738]
When saving a screenshot using the `driver` method `save_screenshot`, nothing change if you pass or not the option `:full_page`.

Running
`page.driver.save_screenshot('tmp/capybara/full.png')` or 
`page.driver.save_screenshot('tmp/capybara/full.png', full_page: true)`
results in exactly the same: a screenshot of the page viewport only.

This happens because `options` is not being passed when `browser.save_screenshot` is called here:

https://github.com/teamcapybara/capybara/blob/52eaecea6d154b7d664b0032cd1cbcad4788fe65/lib/capybara/selenium/driver.rb#L151-153

To confirm my thesis, running 
`page.driver.browser.save_screenshot('tmp/capybara/full.png', full_page: true)`
 results in a screenshot of the full page, as expected 😸

**Comment by twalpole** [comment]
Updated in master
