### ISSUE TITLE
disable_animation option doesn't work if app uses Rack::Deflater middleware (gzip)

### ISSUE THREAD

**Issue by mattbrictson** [teamcapybara/capybara#2740]
## Meta

Capybara Version: 3.40.0

## Expected Behavior

I would like to use this Capybara configuration option to disable animation:

```ruby
Capybara.configure do |config|
  config.disable_animation = true
end
```

My app is a Rails 7.1.3 app with `Rack::Deflater` enabled to gzip responses:

```ruby
# application.rb

module MyApp
  class Application < Rails::Application
    # ...
    config.middleware.insert_after ActionDispatch::Static, Rack::Deflater
  end
end
```

## Actual Behavior

The `disable_animation` option has no effect when the `Rack::Deflater` middleware is present. This is because `disable_animation` is implemented as a middleware that wraps the Rails app, and this wrapper doesn't understand gzip-compressed responses.

This can be confirmed by viewing the HTML of the page rendered during a Capybara-driven test. The CSS and JS for disabling animation are not injected into the HTML as expected.

## Solutions Considered

An easy workaround is to remove the `Rack::Deflater` middleware, or insert it only in production environments. Although this works, I would like my app being tested to resemble production as much as possible. If `Rack::Deflater` changes the behavior of the system, I would like that to be found by CI and not be an unpleasant surprise in production.

Perhaps `Rack::Deflater` could be inserted _after_ the `Capybara::Server::AnimationDisabler` middleware. Or conversely, the latter could be inserted before. I'm not sure how to do this.

`Capybara::Server::AnimationDisabler` doesn't work because `Rack::Deflater` compresses the response with gzip, and `AnimationDisabler` doesn't know to decompress the response prior to its attempt to modify it. Maybe `AnimationDisabler` could be updated to understand gzipped responses? This seems like a lot of additional complexity to address an edge case.

_Edit: since this bug is an edge case, maybe the most appropriate solution is to just update the Capybara docs with a note explaining that `disable_animation` does not work for app responses encoded with gzip, e.g. if `Rack::Deflater` is present._

**Comment by twalpole** [comment]
As you've stated the easiest solution would just be to not use Rack::Deflater in the test environment, at least in the tests where you're using animation disabler -- another solution would just be to copy the animation disabler into your own middleware which you insert before deflater.  I don't really think this is something Capybara should be dealing with.
