### ISSUE TITLE
Feature request:  click_on should expand details/summary

### ISSUE THREAD

**Issue by jcoyne** [teamcapybara/capybara#2748]
Given HTML like this:
```html
<details>
  <summary>Details</summary>
  Something small enough to escape casual notice.
</details>
```

Then I should be able to write capybara like this:
```ruby
click_on 'Details'
assert page.has_content?('Something small')
```

But currently this will give the error:
```
     Failure/Error: click_on "Details"

     Capybara::ElementNotFound:
       Unable to find link or button "Details"
```

Currently I have to work around by doing:
```ruby
find('details:first-of-type > summary').click
```

This does seem possible in the rack-test driver(0783f95d5460c22cdda2a117b59d72d65ec30fff) but I would like to do the same in selenium.

**Comment by twalpole** [comment]
Pretty sure this is tested for in the node tests. What's the difference between your use case and what's tested there

**Comment by jcoyne** [comment]
@twalpole I'm not sure what tests you are referring to. Can you point me there?

**Comment by twalpole** [comment]
https://github.com/teamcapybara/capybara/blob/edc0397f2cd97c050c77d64f8e4a79bbeba6117a/lib/capybara/spec/session/node_spec.rb#L284

**Comment by twalpole** [comment]
Rereading the initial report, you're calling click_on which is defined to click on links or buttons, a summary element is neither of those. instead find the element and call `click` on it

    find_css('summary', text: 'Details').click

**Comment by twalpole** [comment]
Rereading the initial submission, I realize I completely misread this.  You're asking for 'summary' elements to be treated the same as links/buttons by `click_on`.  I'm not sure changing the current behavior of `click_on` makes sense, and would be a potentially breaking change
