### ISSUE TITLE
Popover attribute is not handled when determining visibility

### ISSUE THREAD

**Issue by toy** [teamcapybara/capybara#2755]
## Meta
Capybara Version: 3.40.0
Driver Information (and browser if relevant): selenium-webdriver 4.18.1 with Chrome 121.0.6167.85

## Expected Behavior

I was testing interaction with buttons that are in an element with [popover attribute](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) which is inside an element with overflow hidden. After making the popover visible, it is still not possible to interact with the button despite it being visible. [isDisplayed](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/atoms/src/isDisplayed.js) doesn't have anything related to popover attribute. Selenium apparently also doesn't handle popover attribute, so even if `isDisplayed` is modified to handle it, trying to click the button gives `Selenium::WebDriver::Error::ElementNotInteractableError`.

HTML to show the problem:
```html
<div style="position: relative; overflow: hidden;">
  <button popovertarget="show">Show popover</button>
  <button style="position: absolute; top: 30px;">Can not be clicked</button>
  <button popover id="show" style="position: absolute; top: 60px;">Should be clickable</button>
</div>
```
After clicking the «Show popover»:
![image](https://github.com/teamcapybara/capybara/assets/18144/054ed283-ab52-4777-b79e-393d6d1525d0)

It should not be possible to click the «Can not be clicked» button, but it should be possible to click the «Should be clickable» button.

## Actual Behavior
It is not possible to click the «Should be clickable» button.

**Comment by toy** [comment]
Maybe the way to handle popover attribute: https://github.com/teamcapybara/capybara/commit/ece5af493f3256020e592230db74dafb8933c799

**Comment by twalpole** [comment]
Visibility handled via https://github.com/teamcapybara/capybara/pull/2759
