### ISSUE TITLE
     ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by NeilAllen** [teamcapybara/capybara#2757]
## Meta
rbenv version: 3.2.2

Capybara Version:
capybara (3.40.0)
    Authors: Thomas Walpole, Jonas Nicklas
    Homepage: https://github.com/teamcapybara/capybara

Driver Information (and browser if relevant):
selenium-webdriver (4.18.1, 4.9.0)
    Authors: Alex Rodionov, Titus Fortner, Thomas Walpole
    Homepage: https://selenium.dev
    License: Apache-2.0

## Actual Behavior
     Failure/Error: visit path
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)

This doesn't fix it:
    module DeprecationSuppressor
      def initialize(...)

**Comment by twalpole** [comment]
There's not enough information here to do anything with - closing
