### ISSUE TITLE
fill_in does not support contenteditable nodes

### ISSUE THREAD

**Issue by infews** [teamcapybara/capybara#310]
I'm not sure what the correct way is to do this, but I want to be able to set the content of a contenteditable node during a spec.

The XPath repo has both a pull request (https://github.com/jnicklas/xpath/pull/9) and an issue (https://github.com/jnicklas/xpath/issues#issue/12) re: this. The pull request says it was merged in but I don't see the code.

What is the right way to do this?

**Comment by david-dcp** [comment]
The problem with the set approach is that it doesn't set off JavaScript events. Which is my issue. Also I have tried `set` to no avail. I know this is old.. but if anyone comes across this and there is an update... Would love to know about it please. 

`<Textarea>` being a valid form element should get the same behaviour as `<input>`  I would think.

**Comment by twalpole** [comment]
@david-dcp You're commenting on an issue closed over 5 years ago, that was referring to contenteditable nodes (i.e. elements with the content editable attribute).

As far as &lt;textarea> and &lt;input> elements - they're basically treated identically and calling `find` and then `#set` on an element is the same as using `#fill_in` and will generate the same events.  

If you have an actual bug please create a new issue, if you just want to know how to do something please post to the mailing list as requested in the README.  In either case make sure you identify what version of Capybara you are using as well as which and which version of driver you are using.
