### ISSUE TITLE
Clicking the label of a hidden field

### ISSUE THREAD

**Issue by jonleighton** [teamcapybara/capybara#316]
I have an app where I have a set of radio buttons with respective `label`s. The actual `input` elements themselves are hidden, but the labels are visible.

If I do `choose 'label text'`, Selenium will throw an error saying "Element is not currently visible and so may not be interacted with". This is because Capybara finds the `input` using the label text or otherwise, and then changes the state of the input itself.

Perhaps it would be possible to simulate a click on the label instead of changing the input, if a label is found. (And then keep the current behaviour in other cases.)

For now I can get around it with `find('label', :text => 'label text').click`.

Thanks

**Comment by waynebontrager** [comment]
Helped me too!

**Comment by Startouf** [comment]
Now what about labels that don't have text ? FOr exemple if I use a label to make a custom checkbox
```
<label>
  <input type=checkbox hidden>
  <span></span> <!-- This one is used to make a custom checkbox via css -->
</label>
```

**Comment by twalpole** [comment]
@Startouf Posting on an issue closed 6 years ago is generally not a great way to get a useful response.  Since you have a question about how to use Capybara post it on the mailing list or gitter as mentioned in the README - or read the docs - http://www.rubydoc.info/gems/capybara/Capybara/Node/Actions#check-instance_method - the available options have changed in the last 6 years.

**Comment by Startouf** [comment]
Sorry I had just looked at the previous message timestamp and not the original OP's ^^" Shame on me.

**Comment by gregblass** [comment]
Found this on Google. Had the same problem as @Startouf. Apologies that it's 2019? Anyway, I'm having the same issue...custom checkbox CSS.

I try to keep it pretty civil on Github, but are you actually telling someone to post to a mailing list??
