### ISSUE TITLE
click_link 'foo' not working on links without href

### ISSUE THREAD

**Issue by nicholasf** [teamcapybara/capybara#379]
Running click_link 'Title View' against 

```
<a id="title-view-link">Title View</a> 

```

results in  Capybara::ElementNotFound: no link with title, id or text 'Title View' found . Adding an empty href -

```
 <a id="title-view-link" href="">Title View</a> 
```

works.

So, is the code testing for links by looking for a elements with href attributes? If so, shouldn't it drop the href attribute as mandatory?

**Comment by terryyin** [comment]
Seems it works on my Mac but failed on my Linux box with Firefox. On Linux it went to '/'.

**Comment by twalpole** [comment]
@terryyin This is an old closed issue - if you have a reproducible example of a problem please create a new issue with enough detail to reproduce
