### ISSUE TITLE
Capybara needs to support nesting like Webrat does

### ISSUE THREAD

**Issue by dmonopoly** [teamcapybara/capybara#384]
Capybara's have_selector matcher does not support nesting.

Example:

<pre>
    require 'spec_helper'
    describe "messages/new.html.erb" do
      let(:message) do
        mock_model("Message").as_new_record.as_null_object
      end
      before do
        assign :message, message
      end
      it "renders a form to create a message" do
        render
        rendered.should have_selector("form",
          :method => "post",
          :action => messages_path
        ) do |form|
          form.should have_selector("input", :type => "submit") # this should fail because no submit button is in the view, but it silently passes
        end
      end
</pre>

This doesn't work with Capybara, but would work correctly if with Webrat. In any case, shouldn't Capybara support nesting just like Webrat does?

This issue becomes more prominent with something like this:

<pre>
    rendered.should have_selector("form") do |form|
        form.should have_selector("input",
            :type => "submit",
            :name => "message[title]",
            :value => "the title"
        )
    end
</pre>

because many of the checks are in the nested area.

**Comment by hisapy** [comment]
Hey guys, I just started "appreciating" view specs and needed some of the scoping of Capybara in there so inspired in this "conversation" and other resources I created 

https://gist.github.com/hisapy/0cbd7898334b386afa84

This appreciation came after finally finding a robust and agile Rails BDD flow from Cucumber to RSpec which I'll try to describe in a future blog/tweet post (https://twitter.com/hisa_py).
 
I hope you enjoy it.
