### ISSUE TITLE
Dropdown selection broken

### ISSUE THREAD

**Issue by dblock** [teamcapybara/capybara#448]
Capybara 1.0 (also tried HEAD). Selenium driver, Firefox 5, Ubuntu Natty. Selecting items in a dropdown with `page.select(value, :from => "id")` is broken. It looks like it selects something, but when the UI posts, the value is not chosen. Calling .select on the option has been seen to work, inconsistently.

As a workaround, a JQuery selection always works, `page.execute_script("$('#widget_size').val('5')")`.

A few more details and screenshot here: http://code.dblock.org/selecting-items-from-a-dropdown-with-capybara-selenium-firefox-jquery

**Comment by fuzzyalej** [comment]
The main problem here is that `val` and `value` are different things.

`val` is a property of the element, accessed with `.val()` and setted with `.val('X')`
`value` is an attribute of the element (in the DOM), accessed with `.attr('value')` and setted with `.attr('value', 'X')`

And we are mixing both here.
