### ISSUE TITLE
Save_and_open_page / "Show me the page" doesn't include CSS from Rails 3.1 asset pipeline

### ISSUE THREAD

**Issue by tracedwax** [teamcapybara/capybara#485]
I worked around it by including the following gist in an initializer, so it only triggers in the cucumber or test environments. 
https://gist.github.com/1144277

Is there an easier or more standard way to get the asset pipeline css to show up?

I have Launchy 2.0.5.

Thanks!

**Comment by daveharris** [comment]
I just wanted to say, that if you can't/don't want to specify `Capybara.asset_host = "http://localhost:3000"`from #958 then you can always have a bookmarklet in your browser's bookmark bar with something like

```js
javascript:(function(){document.getElementsByTagName('link')[0].href='http://localhost:3000/assets/application.css'})();
```

It's a bit hacky, but you can use it any rails app.
