### ISSUE TITLE
Undefined method delete

### ISSUE THREAD

**Issue by ghost** [teamcapybara/capybara#509]
I am testing a rails app, and in one test (Using a rSpec request spec), I am using javascript since the link is a link to delete an object.

When using Selenium (Which is what I am using currently since akephalos does not support the newer Capybara's), I get this error: 

3) SessionsController signing out shows Sign In and Sign Up in user-bar
     Failure/Error: page.driver.delete
     NoMethodError:
       undefined method `delete' for #<Capybara::Selenium::Driver:0xad3d484>
     # ./spec/requests/sessions_spec.rb:19:in`block (4 levels) in <top (required)>'
     # ./spec/requests/sessions_spec.rb:18:in `block (3 levels) in <top (required)>'

The link looks like: rel="nofollow" data-method="delete" href="/sign-out"

Gems are: 

selenium-webdriver 2.7.0
capybara 1.1.1

**Comment by mohsinali** [comment]
@jnicklas Then what we should do, in order to logout a devise user.
