### ISSUE TITLE
Capybara.reset_sessions! doesn't clear cookies.

### ISSUE THREAD

**Issue by uahmed** [teamcapybara/capybara#535]
I am using Capybara with selenium driver, and doing require 'capybara/cucumber' to reset my session after every scenario. I am running tests in FireFox.

If I debug I can trace that after every scenario Capybara calls the _Capybara.reset_sessions!_ in After do hook, which further down calls  @browser.manage.delete_all_cookies in selenium/driver.rb. However it doesn't seem to actually clear the cookies and no exception is thrown as well.

Could this be because Capybara doesn't launch FireFox with Administrator privilege? or there is something else wrong, any ideas?

OS: Windows 7 64 bit.
My gem versions
- capybara (1.1.1)
- cucumber (1.1.0)
- selenium-webdriver (2.8.0)

**Comment by georgeu2000** [comment]
Ran into this issue, after all this time. As @mgogov mentioned, you must visit the site to access the cookie for that site, before calling `reset_session!`

For my use case, it looks like:

    visit '/'
    Capybara.reset_session!

**Comment by wrtsprt** [comment]
@georgeu2000's point seems very important and fixed the problem for us. Could that be documented somewhere?

**Comment by georgeu2000** [comment]
@wrtsprt @twalpole - I would be happy to update the docs, if that is desired.

**Comment by twalpole** [comment]
@georgeu2000 The behavior is driver dependent - selenium only allowa to clear cookies for the current domain, other drivers allow to just clear all cookies IIRC.  Therefore this should not be documented in Capybara.reset_session!, maybe the wiki would be a reasonable place.

**Comment by franzliedke** [comment]
This is part of the [webdriver spec](https://www.w3.org/TR/webdriver/#delete-all-cookies), unfortunately. So this definitely occurs for all drivers using Selenium's W3C bridge.

We might want to consider navigating to Capybara's `app_host` (unless already there) when calling `reset_session!`

Here is a similar discussion on the cypress repo: https://github.com/cypress-io/cypress/issues/408

**Comment by grk** [comment]
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec.rb#L18 this is already done after each spec
