### ISSUE TITLE
fill_in does not trigger a change event

### ISSUE THREAD

**Issue by pbiggar** [teamcapybara/capybara#620]
While I use fill_in on a textarea, a change event is not triggered when the textarea loses focus. However, doing it manually in Firefox always triggers this event.

This is on version 1.1.2 with the firefox driver.

**Comment by Sporky023** [comment]
I'm a little confused as to why this is a capybara issue worth discussing/addressing when the underlying driver is selenium, but not when capybara-webkit is involved.  Can you please help me (and future readers arriving here via google search) understand the technical distinction?

**Comment by twalpole** [comment]
@Sporky023 because the capybara project provides the driver for interfacing to selenium, the capybara-WebKit project is separate - I'm now going to lock this issue
