### ISSUE TITLE
attach_file does not work with Selenium

### ISSUE THREAD

**Issue by duckpond** [teamcapybara/capybara#621]
This method works fine until you add, js: true to your spec at which time it does not upload the file. 

The workaround I used was found here:

http://how.itnig.net/facts/attach-file-in-capybara---selenium-webdriver

Perhaps a similar implementation could be added to capybara?

**Comment by atodorov** [comment]
Similar issue for me here. Does anyone have a copy of the workaround b/c the page has expired ?

**Comment by twalpole** [comment]
@atodorov You're posting on a closed issue from 4 years ago.  Capybara has changed a lot since then so anything to do with this issue is most likely outdated.  If you have an actual issue, that isn't solved by using an absolute path, please open a new issue with enough details to reproduce.
