### ISSUE TITLE
click_link should find visible links only

### ISSUE THREAD

**Issue by rbu** [teamcapybara/capybara#761]
Capybara should only find visible links when using the click_link action.

In a JS-app where a link is added to the DOM and later made visible, capybara will produce a failure when waiting for the element it wants to click:
`Element is not currently visible and so may not be interacted with (Selenium::WebDriver::Error::ElementNotVisibleError)
...
      (eval):2:in `send'
      (eval):2:in `click_link'
`

While it makes sense to `find_link` invisible links, the `find()` construct used by `click_link` should really specify `:visible => True` so Capybara waits until the link is visible before clicking it.

**Comment by asiniy** [comment]
byzg +1
