### ISSUE TITLE
Doing a direct post does not follow redirects

### ISSUE THREAD

**Issue by tomtt** [teamcapybara/capybara#77]
I am writing an app that accepts post requests from flash. Therefore I have to use the page.driver#post method. One of the actions performs a redirect and it is not followed automatically and therefore the cucumber breaks.

My workaround has been to explicitly call the private page.driver#follow_redirects! which is not ideal.

I think the post should follow redirects out of the box, or at least the follow_redirects! method should be available as a public method from my step.

**Comment by grosser** [comment]
FYI could not find it ... using this now :(

```Ruby
Capybara::Rails::TestCase.class_eval do
  def post(url)
    page.driver.post url
    visit page.driver.response.location
  end
end
```
