### ISSUE TITLE
attach_file not working with :js => true

### ISSUE THREAD

**Issue by jackdesert** [teamcapybara/capybara#791]
attach_file is working fine for me--that is, until I enable javascript. With :js => true, the file I attached does not show up in the params at all. I've tried using both relative and absolute paths for the file, with the same result.

Using Capybara 1.1.2 on Ubuntu

**Comment by kay4444** [comment]
I've faced with the problem of uploading file from PC via clicking Browse browser button.
I have following xml
> input id="file_upload_input" class="ng-pristine ng-untouched ng-valid" type="file" ng-model="vid_input_file_field"

And I am trying to upload file in this way:
> attach_file 'file_upload_input', 'C:/Users/Kay/Videos/video_file_three_seconds.mp4'
But it doesn't select the file from defined directory. But I see that "Browse" button is highlighted.
So what I am doing incorrectly?

**Comment by twalpole** [comment]
@kay4444  Please ask howto questions on the mailing list as requested in the README, or if you believe you've found an actual problem with Capybara provide enough info to replicate, including things like the versions of gems used and the actual error messages you're getting, etc.
