### ISSUE TITLE
have_content should match escaped strings

### ISSUE THREAD

**Issue by jfelchner** [teamcapybara/capybara#796]
So, let me run through a quick example.

If I do something like:

```
buffer = 'some input I <em>know</em> is safe'.html_safe
buffer << "#{some_var_from_the_user}"
```

Might produce a string like:

```
some input I <em>know</em> is safe&lt;script&gt;alert(&#x27;fooled you!&#x27)&lt;/script&gt;
```

If it's output on the page and there's text such as:

```
some input I know is safe<script>alert('fooled you!')</script>
```

Neither `have_content` nor `have_text` will match it.  Now of course I _could_ do:

```
page.should have_content CGI.unescape_html buffer
```

But that seems like the typical case considering `have_content` is always matching against unescaped text.

Maybe I'm thinking of this incorrectly, but I couldn't find any old issues pointing to this.

**Comment by budu** [comment]
I've ended up monkey patching the HaveText matcher class with this:

```ruby
module Capybara
  module RSpecMatchers
    module HaveTextWithUnescaping
      def matches?(actual)
        wrap(actual).assert_text(*expected)
      rescue Capybara::ExpectationNotMet => e
        @failure_message = e.message
        return false
      end

      def does_not_match?(actual)
        wrap(actual).assert_no_text(*expected)
      rescue Capybara::ExpectationNotMet => e
        @failure_message_when_negated = e.message
        return false
      end

      def expected
        @args.map do |string|
          CGI.unescape_html string.to_str
        end
      end
    end
  end
end
```

I'll try to find time to send a proper PR next week.

**Comment by twalpole** [comment]
@budu This is an issue that was fixed/closed a long time ago with no one else reporting problems-- if you're having issues with this you may want to ask on the mailing list.
