### ISSUE TITLE
API proposal/discussion for touch platform interactions

### ISSUE THREAD

**Issue by carhartl** [teamcapybara/capybara#803]
Little bit of background: For a touch platform only web app we're building we're using Capybara for acceptance tests, along with a js driver that is touch capable (now poltergeist, before capybara-webkit - basically any recent webkit based driver supporting touch events could be used). We're not using any click interactions at all, thus I needed to make the capybara js driver touch capable.

Here's a pull request I sent to poltergeist
https://github.com/jonleighton/poltergeist/pull/135/files

which contains an initial implementation, so far only for simple, single taps:

```
Element#single_tap
```

e.g.

```
find('.tap-me').single_tap
```

@jonleighton in response asked me to start a discussion here as to (hopefully) agree on an API that could be implemented by any capable driver.  See https://github.com/jonleighton/poltergeist/issues/141

I had further methods in mind to be implement later, just as a proposal:

single_tap
double_tap
long_tap
swipe_left
swipe_right
swipe_up
swipe_down

(The names follow what Zepto.js provides for touch event abstractions.) There are also gesture events I didn't yet think about.

I'd be glad if we could get a discussion going about this and happily help with the implementation whenever required.

[Edit: swipe_bottom -> swipe_down]

**Comment by Ricardonacif** [comment]
Hey, there's this gem I have developed that adds touch gestures support to Capybara. Take a look at https://github.com/Ricardonacif/touch_action .

Thanks,
