### ISSUE TITLE
undefined method `visit' for #<RSpec::Core::ExampleGroup

### ISSUE THREAD

**Issue by aaronpark** [teamcapybara/capybara#814]
ever since the september 7 commit de34c638354c117f20269b4fd129c2657b01ef12 we have been getting these errors in our request specs.

If I set my gem file to the previous commit everything starts to works again. Just an FYI

:gem 'capybara', git: 'https://github.com/jnicklas/capybara', :ref => 'd153635e6546ecc742e2b805390bc42a1e863d7c'

**Comment by srghma** [comment]
re error 

```
undefined method `visit' for #<Page:0x00000005f47f90>
```

I had the same error, it happened that `Page` object was active-record object, not capybara page

I have fixed this error by removing line

```
let!(:page) { create :page }
```
