### ISSUE TITLE
has_text? and invisible content

### ISSUE THREAD

**Issue by jonleighton** [teamcapybara/capybara#844]
Capybara master has a new `has_text?` matcher which excludes invisible content such as `<title>` elements and `display: none` elements.

Its implementation uses the `Node#text` method, so the implication is that the behaviour of `Node#text` has now changed from returning all text to only returning visible text. This presents two problems:
- Users will have trouble upgrading if they are using `Node#text` directly, or `has_content?` (which is now just an alias of `has_text?`)
- There is no API for getting e.g. the text of the `<title>` element. This could be a valid user requirement and was previously supported by the `#text` method.

I propose adding a `#visible_text` method and using that to implement `has_text?`, leaving the implementations of `#text` and `#has_content?` as they are in 1.1. (`#has_content?` can be deprecated but I believe `#text` remains useful for checking e.g. `<title>` text.) WDYT?

Related: #522

cc @mkdynamic

**Comment by andresprogrammer** [comment]
I have one afternoon and half of the morning only with the title problem. Finally I found a solution and I just sign up to write it:

    expect(page.title).to   eq("My title")

Good luck
