### ISSUE TITLE
Capybara stops / hangs unexpectedly and inconsistently

### ISSUE THREAD

**Issue by mattheworiordan** [teamcapybara/capybara#848]
Firstly, I appreciate how hard it is to debug this issue, or even figure out if Capybara is indeed at fault, but I believe Capybara and or the Capybara-Webkit driver is the most likely culprit.  So I appreciate any help if you can help.

I am on OS X 10.8.1 with the latest version of all gems, QT webkit and Ruby 1.9.3 available.  I'll post the info further down for your reference.

I have found that recently when running a few small Cucumber tests using `rake cucumber:wip` everything tends to work fine.  However, when I run the full suite I find the tests just hang for some reason, and never fix themselves.  I have seen this in my CI environment (Mac as well, but OS OX 10.7) as well.  And I only seem to see this when Capybara-Webkit is enabled, however it does seem to hang sometimes before Capybara-Webkit is invoked.

For example, in my most recent run, I ran `rake cucumber` and 34 scenarios across 5 feature files ran OK, and then oddly when I hit the 6th feature file (one of many more), it hung on the first scenario.

Here is the output from the test on that scenario showing, and importantly it does not seem like the @javascript interpretor has yet been invoked (I use capybara-webkit) as it got stuck on the Background portion:

```
Feature: Backlog Other Functionality
  In order to manage a backlog
  A visitor
  Should be able to rely on some necessary functionality

  Background:                                                                                      # features/backlog_other.feature:6
    Given the database has the necessary lookup tables                                             # features/step_definitions/shared_steps.rb:1
    And a user named "John" is registered                                                          # features/step_definitions/authentication_steps.rb:1
```

The @javascript declaration in fact comes later in the scenario declaration, not in the background section, so to be honest I'm not sure if Capybara detects that in advance and switches to the :javascript driver, or if it only switches when the Scenario starts that is tagged with @javascript.

Anyway, clearly it is hanging on the next step in the Background which is `And I am signed in as "John"`
The code for this step is as follows:

```
step %{I am on the home page}
step %{I follow "Log in"}
step %{I fill in "Email" with "#{user_name.gsub(/ /,'')}@acme.com"}
step %{I fill in "Password" with "password"}
step %{I press "Log in"}
step %{I should see the notice "Signed in successfully."}
```

Now I could include all the code for this step if you want, but it's all pretty bog standard Capybara code.  For example, here are two of the steps:

```
Given /^(?:|I )am on (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )follow "([^"]*)"(?: within "([^"]*)")?$/ do |link, selector|
  with_scope(selector_to(selector)) do
    click_link(link)
  end
end
```

So why it should hang on this step confuses me.  There is certainly nothing in those steps that warrants any odd behaviour, and if I run that test individually it works just fine.

Has anyone else experienced this intermittent behaviour?  Is there some way I can start to debug the issue or provide more information?

Here is some info on my environment:

OS X Version: 10.8.1
Ruby: ruby-1.9.3-p194 using RVM
XCode version:  4.5.1

$ gcc --version
    i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

$ bundle list
Gems included by the bundle:
- Ascii85 (1.0.2)
- ZenTest (4.8.2)
- actionmailer (3.2.8)
- actionpack (3.2.8)
- activemodel (3.2.8)
- activerecord (3.2.8)
- activeresource (3.2.8)
- activesupport (3.2.8)
- acts_as_list (0.1.8)
- addressable (2.3.2)
- arel (3.0.2)
- autotest (4.4.6)
- autotest-growl (0.2.16)
- autotest-rails (4.1.2)
- awesome_print (1.1.0)
- bcrypt-ruby (3.0.1)
- builder (3.0.3)
- bundler (1.2.0)
- capybara (1.1.2)
- capybara-screenshot (0.2.2)
- capybara-webkit (0.12.1)
- childprocess (0.3.5)
- chunky_png (1.2.6)
- coderay (1.0.8)
- columnize (0.3.6)
- compass (0.12.2)
- compass-960-plugin (0.10.4)
- compass-rails (1.0.3)
- cucumber (1.2.1)
- cucumber-rails (1.3.0)
- database_cleaner (0.9.1)
- debugger (1.2.0)
- debugger-linecache (1.1.2)
- debugger-ruby_core_source (1.1.3)
- deep_merge (1.0.0)
- devise (2.1.2)
- devise-encryptable (0.1.1)
- diff-lcs (1.1.3)
- ejs (1.1.1)
- email_spec (1.2.1)
- erubis (2.7.0)
- exceptional (2.0.32)
- excon (0.16.4)
- execjs (1.4.0)
- factory_girl (4.1.0)
- factory_girl_rails (4.1.0)
- ffi (1.1.5)
- foreman (0.60.0)
- fssm (0.2.9)
- gherkin (2.11.4)
- growl (1.0.3)
- haml (3.1.7)
- hashery (2.0.1)
- heroku (2.32.11)
- heroku-api (0.3.5)
- heroku_san (3.0.4)
- hike (1.2.1)
- hpricot (0.8.6)
- httparty (0.9.0)
- i18n (0.6.1)
- journey (1.0.4)
- jquery-rails (2.1.3)
- jslint_on_rails (1.1.1)
- json (1.7.5)
- kgio (2.7.4)
- launchy (2.1.2)
- libwebsocket (0.1.5)
- mail (2.4.4)
- method_source (0.8)
- mime-types (1.19)
- multi_json (1.3.6)
- multi_xml (0.5.1)
- netrc (0.7.7)
- newrelic_rpm (3.4.2)
- nokogiri (1.5.5)
- orm_adapter (0.4.0)
- pdf-reader (1.2.0)
- pg (0.14.1)
- polyglot (0.3.3)
- prawn (0.12.0)
- pry (0.9.10)
- pry-rails (0.0.4 6dd39e3)
- quiet_assets (1.0.1)
- rack (1.4.1)
- rack-cache (1.2)
- rack-force_domain (0.2.0 ff16ac9)
- rack-ssl (1.3.2)
- rack-test (0.6.2)
- rails (3.2.8)
- railties (3.2.8)
- raindrops (0.10.0)
- rake (0.9.2.2)
- rdoc (3.12)
- recursive-open-struct (0.2.2 8178fa5)
- redis (2.2.2)
- redis-namespace (1.0.3)
- rest-client (1.6.7)
- rspec (2.11.0)
- rspec-core (2.11.1)
- rspec-expectations (2.11.3)
- rspec-mocks (2.11.3)
- rspec-rails (2.11.0)
- ruby-rc4 (0.1.5)
- ruby_parser (2.3.1)
- rubyzip (0.9.9)
- sass (3.2.1)
- sass-rails (3.2.5)
- selenium-webdriver (2.25.0)
- sequel (3.20.0)
- sexp_processor (3.2.0)
- shortly (0.3.3)
- shoulda-matchers (1.4.0)
- sinatra (1.0)
- slop (3.3.3)
- sprockets (2.1.3)
- taps (0.3.24)
- thor (0.16.0)
- tilt (1.3.3)
- timecop (0.5.2)
- treetop (1.4.11)
- ttfunk (1.0.3)
- turbo-sprockets-rails3 (0.1.15)
- tzinfo (0.3.33)
- uglifier (1.3.0)
- unicorn (4.3.1)
- vanity (1.8.0 dda319f)
- warden (1.2.1)
- watchr (0.7)
- webrat (0.7.3)
- will_paginate (3.0.3)
- xml-object (0.9.93)
- xpath (0.1.4)

$ brew info qt
    qt: stable 4.8.3 (bottled), HEAD
    http://qt.nokia.com/
    /usr/local/Cellar/qt/4.8.2 (2753 files, 195M)
    /usr/local/Cellar/qt/4.8.3 (2779 files, 194M) *
    https://github.com/mxcl/homebrew/commits/master/Library/Formula/qt.rb
    ==> Options
    --developer
      Compile and link Qt with developer options
    --with-qt3support
      Enable deprecated Qt3Support module
    --with-debug-and-release
      Compile Qt in debug and release mode
    --with-qtdbus
      Enable QtDBus module
    --universal
      Build a universal binary
    --with-mysql
      Enable MySQL plugin
    --with-demos-examples
      Enable Qt demos and examples
    ==> Caveats
    We agreed to the Qt opensource license for you.
    If this is unacceptable you should uninstall.

**Comment by Nerian** [comment]
Hi,

I am having this issue too. When I run an individual test, it runs fine. But when I run the whole suite it hangs 33% of the time.

capybara (2.4.4)
capybara-webkit (1.6.0)
qt5: stable 5.5.0

````
Received "Visit(http://127.0.0.1:60817)"                                                                                                                         |  ETA: 00:02:41 
Started "Visit(http://127.0.0.1:60817)"
Started request to "http://127.0.0.1:60817/"
Finished "Visit(http://127.0.0.1:60817)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html)"
"TimeoutCommand" waiting for load to finish
Received 304 from "http://127.0.0.1:60817/"
Page finished with true
````

It hangs on a `visit('')`.

**Comment by twalpole** [comment]
@Nerian since you're using capybara-webkit as your driver you should probably look over in that project
