### ISSUE TITLE
Choosing invisible check boxes / radio buttons

### ISSUE THREAD

**Issue by joliss** [teamcapybara/capybara#856]
In a form, you can hide the `<input>` for a radio button or check box, but still have the label visible, and the form element will be fully functional in the browser. This can be useful if you want to completely hide the browser's check box or radio button styling.

But `choose` and `check` will ignore those elements unless you pass `visible: false`.

Do you think it's hard to change the XPath for `choose` and `check` to work even when only one of `<input>` and `<label>` is visible?

**Comment by kovpack** [comment]
It would be nice to support this. In my case I can not simply click on visible label, cause label contains a few links with `target="_blank" and Capybara clicks on the link, but not simple text within label. So, instead of selecting checkbox, it opens some docs in new windows.

**Comment by twalpole** [comment]
@kovpack - most drivers don't support clicking on invisible elements because a user wouldn't be able to --- can you put the text within a span or something to enable you to click on that specific content?

**Comment by kovpack** [comment]
@twalpole yeap, put extra span looks like good idea
