### ISSUE TITLE
Ambiguous match, found 2 elements matching xpath "/html"

### ISSUE THREAD

**Issue by tonydaly** [teamcapybara/capybara#881]
I'm using `capybara (2.0.1)` and I'm getting this issue whenever I write an expectation such as: 

```
page.has_content?
```

However, everything works if I rewrite this to:

```
find('body').has_content?
```

I'm not sure if this is the intended functionality or if I've misunderstood the new changes.

**Comment by jasonfb** [comment]
having condition IE tags with multiple html-open tags causes this symptom as well 

 In particular this started failing on a Rails 3 -> Rails 4 upgrade. (the version of capybara in both is 2.4.4)

Ambiguous match, found 2 elements matching xpath "/html"

my main application layout looked like this

 <!DOCTYPE html>
-
-
-
- <html class="no-js" lang="en"> 


The fix was to remove the extra html open tags. are there any other work arounds?

**Comment by TStrothjohann** [comment]
Just in case someone hits this problem while debugging a Rails App: The [Rails web console](https://github.com/rails/web-console) was causing it in my case. When I took ```console``` out of my controller, the tests went green again.

**Comment by fishbullet** [comment]
@TStrothjohann thanks buddy, you save my day.

**Comment by mdesjardins** [comment]
Yet another thing that can cause it (if anyone runs into it) - my app was using an offcanvas javascript library that was adding additional html tags to the output. :/

**Comment by mooman** [comment]
@TStrothjohann That was my problem too, upgrading web-console fixes this. See [this web-console issue](https://github.com/rails/web-console/pull/162).

**Comment by ElizabethRamos** [comment]
I had the same problem. Thanks for sharing the solution.

**Comment by jr180180** [comment]
Thanks so much for the discussion here. It helped point me in the right direction. I found that my application.html.slim file was improperly nested. That is there were some elements outside of the html open and closing tags.

**Comment by chabgood** [comment]
> For me it's this one causing the trouble:
> 
> ```
> <!DOCTYPE html>
> 
> 
> <html>
> ...
> </html>
> ```
> 
> As you can see even this parser recognizes that the multiple `<html>` tags are just comments and Capybara maybe shouldn't raise an Exception :) I'm using `2.1.0`

https://html.com/tags/doctype/#HTML5_Documents

**Comment by twalpole** [comment]
@chabgood I have no clue why you're adding a link about doctype to a comment from 6 years ago - I'm locking this issue.  If you have an actual issue please create a new one with enough details to reproduce it.
