### ISSUE TITLE
Consider an optional dependency on selenium-webdriver

### ISSUE THREAD

**Issue by christiannelson** [teamcapybara/capybara#887]
I've been sleuthing how simple rails projects with only a few explicit dependencies end up including many others (transitively) that in some cases aren't being used at all. This bloat is fuel for rails critics and wastes cycles each time Bundle.require is invoked.

We have been using capybara for years on possibly as many as 20 projects, and as far as I know we haven't used it with a selenium driver for at least 2 years. I have to believe we're not the only ones who always pair capybara with something else (e.g. headless-webkit or poltergeist). However, we end up dragging selenium-webkit (and libwebsocket, websocket, and rubyzip) along with us on every project.

Would you consider removing the dependency on selenium-webdriver and leaving that to the user to include, since they know which driver they want to use? Including rack-test provides an out of the box experience (without js support). I can imagine capybara throwing a warning/error if js is required and no driver is set.

If you think this is a bad idea, I would love to understand why. Thanks!

**Comment by zeusintuivo** [comment]
Check:
Capybara.default_driver = :poltergeist
vs 
Capybara.javascript_driver = :poltergeist    

´´´
 Capybara's selenium driver is unable to load `selenium-webdriver`, please install the gem and add `gem 'selenium-webdriver'` to your Gemfile if you are using bundler. (LoadError)
´´´

**Comment by twalpole** [comment]
@zeusintuivo you’re commenting on an issue that was closed over 4 years ago, and I’m not sure what you’re asking for. If you think you have found a bug in Capybara please open a new issue and describe it. If you just have a question about how something works please ask in the mailing list or on gitter as mentioned in the README
