### ISSUE TITLE
Problem adding cookies to current session

### ISSUE THREAD

**Issue by emilianodellacasa** [teamcapybara/capybara#910]
Hi everyone,

i am using capybara gem 2,0.1 and I am having problem adding cookies to current session.

The code giving me problem is the following:

``` ruby
cookies = Capybara.current_session.driver.browser.current_session.instance_variable_get(:@rack_mock_session).cookie_jar
cookies[:stub_user_id] = User.where(:email=>"joe@bloggs.com").first.id
```

It used to work before updating, not it is giving me this error

can't convert nil into String (typeError)

Any suggestion on how to fix this?

Thanks!

**Comment by lessless** [comment]
despite the fact that `allow_any_instance_of` considered is most buggy feature of the RSpec,  it might have sense to prefer it over using internal Capybara API:

```
  def stub_user_id(id)
    if defined?(session)
      session[:user_id] = id
    else
      allow_any_instance_of(ActionDispatch::Request::Session).
        to receive(:[]).with(:user_id).and_return(id)
    end
  end
```
